EXPERIMENTAL/WIP: Added OnClusterLeaderChanged plugin Hook (34)
mattermost/mattermost pull request #21653
Opened 2022-11-12 18:40 UTC by levb

RFC: Expose the existing server mechanism to notify of cluster leader (job server?) changes to plugins.

2022-11-14 18:13 UTC, lieut-data requested changes
(Requesting changes just to remove myself from the review until there's more context I can consume.)

2022-11-22 13:36 UTC, hanzei requested changes
Also blocking on https://github.com/mattermost/mattermost-server/pull/21653#issuecomment-1314180603

2023-01-23 07:03 UTC, iomodo requested changes
blocking on https://github.com/mattermost/mattermost-server/pull/21653#issuecomment-1314180603

2023-03-06 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-06-01 21:03 UTC, closed without merging