[MM-27473] Additional slash command responses appear as replies
mattermost/mattermost pull request #21840
Opened 2022-12-09 07:44 UTC by arendsk

#### Summary
Previously, if the original slash command response is a root post i.e. it's triggered from the center panel, additional responses will not get placed in the same thread but instead open new threads i.e. are root posts themselves. This change presents additional responses as replies to the original response in the same thread.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15174

#### Release Note
```
Changed additional slash command responses from appearing as new posts to appearing as replies to the first response.
```

2022-12-09 07:44 UTC, mattermod commented
Hello @arendsk,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-12-09 07:51 UTC, arendsk commented
Release note wasn't formatted correctly. Fixed now

2022-12-09 11:54 UTC, hanzei requested changes
The changes LGTM.

Is it reasonable to add a test for the changes?

2022-12-09 11:55 UTC, mattermod commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2022-12-12 05:55 UTC, arendsk commented
I started working on a test, but I'm finding it difficult to get information about the posts created by `HandleCommandResponsePost `within `HandleCommandResponse`. The only way I can think of is to separately get all of the posts from the database then use that to verify the behavior. I've tried using `th.App.Srv().Store().Post().GetPosts` which returns a `PostList`, but I haven't had much success getting it to work. Any advice on how to do this?

2022-12-15 22:53 UTC, hanzei commented
You are on the right track. `th.App.Srv().Store().Post().GetPosts()` is the way to go. You could use something like `th.App.Srv().Store().Post().GetPosts(model.GetPostsOptions{ChannelId: th.BasicChannel.Id, Page: 0, PerPage: 100}, false, map[string]bool{})`. What kind of issues are you running into?

2022-12-26 01:03 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-07-29 17:05 UTC, closed without merging

2024-07-29 17:06 UTC, jwilander commented
Closing as stale. Feel free to re-open.