MM-47188 Migrate messageHtmlToComponent to TypeScript
mattermost/mattermost pull request #22665
Opened 2023-03-26 01:16 UTC by Dismated

#### Summary
Migrated file to TS

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-47188

#### Release Note
NONE

2023-03-26 01:16 UTC, mattermost-build commented
Hello @Dismated,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-04-04 01:35 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-04-04 01:36 UTC, M-ZubairAhmed commented
/release-note-none

2023-04-04 21:45 UTC, sinansonmez commented
Thanks for your contribution @Dismated Could you please run`make check-types` and `make check-style` in webapp. I see some type mismatches. After that I will have a second round of look

2023-04-04 21:48 UTC, sinansonmez requested changes

2023-04-04 21:48 UTC, sinansonmez commented on webapp/channels/src/utils/message_html_to_component.tsx
> +                let newAttribs = JSON.parse(JSON.stringify(node.attribs));
Compared to old version, I believe we are changing the behaviour here. If OK for you, we can keep the old version

2023-04-04 21:48 UTC, sinansonmez commented on webapp/channels/src/utils/message_html_to_component.tsx
> +    if (options) {
Do we really need to introduce this if check?

2023-04-15 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-04-15 11:05 UTC, M-ZubairAhmed commented
@Dismated do you need help with this PR

2023-07-12 11:32 UTC, M-ZubairAhmed commented
@Dismated feel free to reopen the PR if you intend to work on it

2023-07-12 11:32 UTC, closed without merging