MM-47280 : Migrate "/ad_ldap/" e2e tests to TypeScript
mattermost/mattermost pull request #22666
Opened 2023-03-26 08:18 UTC by joremysh

#### Summary

Converting following spec files under /integration/ad_ldap to Typescript

1. saml_ldap_sync_id_attrib_spec.js
2. saml_ldap_sync_remove_spec.js
3. saml_ldap_sync_spec.js

Original pull request: https://github.com/mattermost/mattermost-webapp/pull/11419

#### Ticket Link

Fixes mattermost/mattermost-server#21302

#### Release Note

```release-note
NONE
```

2023-03-26 08:18 UTC, mattermost-build commented
Hello @joremysh,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-03-28 09:11 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-03-29 19:10 UTC, furqanmlk commented
/update-branch

2023-03-29 19:10 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.

2023-03-29 19:17 UTC, furqanmlk commented
@joremysh can you please take updates as we have changed the name `e2e` folder  to `e2e-tests`

2023-04-04 14:49 UTC, joremysh commented
> @joremysh can you please fix the conflict and take updates as we have changed the name `e2e` folder to `e2e-tests`

updated

2023-04-06 20:42 UTC, furqanmlk reviewed
@joremysh 
Thanks for your patience.
Unfortunately, I still get an error at `keycloak_commands.js:50:36` for all test cases.
However, all tests are passing in `Master.`


<img width="735" alt="image" src="https://user-images.githubusercontent.com/6909890/230489419-496191f4-5075-4cf1-bc40-3757101d2510.png">

Please let me know If you want; we can have session Zoom session to debug.

2023-04-07 15:16 UTC, joremysh commented
how do I get a license to run it on local environment?
<img width="379" alt="image" src="https://user-images.githubusercontent.com/7455516/230633169-9284dace-95b2-4fd0-a993-7d9ce0ef5485.png">

2023-04-11 04:01 UTC, saturninoabril requested changes
Thanks @joremysh for your contribution! I've left few comments.

For running the tests locally, since it requires enterprise build, one option is not to run by source but via docker using [mattermost/mattermost-enterprise-edition:master](https://hub.docker.com/r/mattermost/mattermost-enterprise-edition) then use license in trial mode. For this test to work, it also requires LDAP and keycloak services which you may have using openldap and keycloak. Let me know if you got it working.

Since this is TS migration, maybe correcting the migration should be fine and then we could run it on our side if it makes it hard for you to run locally.

2023-04-22 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-02-19 11:11 UTC, saturninoabril commented
@joremysh Closing now. Feel free to reopen or open new PR to address the coments.

2024-02-19 11:11 UTC, closed without merging