[MM-50460]  - Fixed textarea focus
mattermost/mattermost pull request #22744
Opened 2023-03-30 17:38 UTC by masif2002

#### Summary

This PR fixes the bug of not being able to focus on the textbox when clicked anywhere above the “Aa”, attachment, emoji, or send buttons. Right now, if you click anywhere in the textbox, the focus goes to it. (As expected)

* #### Before
    <img src="https://user-images.githubusercontent.com/363587/228325830-75803cc1-3523-4875-87fa-2a89863f554a.gif" alt="before" height="300px"/>
* #### After
    <img src="https://user-images.githubusercontent.com/94846379/228917347-c1f71005-977c-4e57-b9a5-2be25623c21f.gif" alt="after" height="300px"/>

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/22696
JIRA: https://mattermost.atlassian.net/browse/MM-50460 

#### Release Note
```
NONE
```

2023-03-30 17:42 UTC, masif2002 commented
/release-note-none

2023-04-03 09:56 UTC, AshishDhama requested changes
This fix will break the edge case it was there for in first place, could you please look for some other solutions

2023-04-03 14:35 UTC, masif2002 commented
> This fix will break the edge it was there for in first place, could you please look for some other solutions

Sure, i'll take a look

2023-04-05 01:07 UTC, masif2002 commented on webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
> -            input.style.maxWidth = '100%';
> @masif2002 I am seeing this after your changes, <img alt="Screenshot 2023-04-03 at 3 23 23 PM" width="1425" src="https://user-images.githubusercontent.com/16203333/229476249-e5f5b5ef-a623-47a9-88d7-11ae86797871.png"> The edge case for which we are setting maxWidth like this.

Can you please let me know how i can reproduce what is shown in this screenshot?

2023-04-05 09:13 UTC, LeonardJouve commented on webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
> -            input.style.maxWidth = '100%';
@masif2002 To reproduce, you must hide the formatting bar ('Aa' button) and write a long message in the channel input

2023-04-05 09:31 UTC, kostaspt commented
/update-branch

2023-04-16 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-05-06 00:31 UTC, francislavoie commented
@masif2002 any chance you can follow up on this? I'm bothered by this every day :sweat_smile: so I'd love to see a fix for this

2023-05-22 11:14 UTC, M-ZubairAhmed commented
/update-branch

2023-06-04 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-06-09 03:24 UTC, closed without merging

2023-06-09 03:25 UTC, M-ZubairAhmed commented
We are taking this internally to fix