MM-52881: Fix date picker selected day
mattermost/mattermost pull request #23391
Opened 2023-05-15 15:05 UTC by LeonardJouve

#### Summary
Hi, I noticed the displayed selected day in the date picker is not correct. It is always set to the current date, even if you change it. 

The date picker is used in the custom status and post reminder modal.

For example, here we can see I selected the 17th but the 15 (date of the day I took the screenshot) is still selected.
![Screenshot 2023-05-15 at 17 01 30](https://github.com/mattermost/mattermost-server/assets/81326532/d9e1555a-e72e-4f98-879b-f95281fb60ec)

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-52881

#### Screenshots
|  before  |  after  |
|----|----|
| ![Screenshot 2023-05-15 at 16 40 38](https://github.com/mattermost/mattermost-server/assets/81326532/25087a05-f62f-44aa-bfca-2302b0d895a8) | ![Screenshot 2023-05-15 at 16 41 39](https://github.com/mattermost/mattermost-server/assets/81326532/65472856-2c78-4160-842b-011739761fed)|

#### Release Note

```release-note
NONE
```

2023-05-15 15:05 UTC, mattermost-build commented
Hello @LeonardJouve,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-05-16 02:30 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-05-18 17:14 UTC, calebroseland approved these changes
LGTM. Thanks, @LeonardJouve!

2023-05-18 23:14 UTC, JulienTant reviewed
So I accidentally opened a PR not knowing you were already on this haha. I closed it in favor of your PR!

There's a small bug to fix still: the date picker opens the calendar in the current month by default, you have to declare what month to open by default with `defaultMonth: time.toDate(),`

Also my PR did include an e2e-test, feel free to add it to this one!
https://github.com/mattermost/mattermost-server/pull/23456/files#diff-7396973be282f9c45ad2ce63af48ab18637651ae74fbb3d2083c7320a64cc91e


edit: I accidentally sent this as a comment but this is a request change :P I am not completely awake today haha

2023-05-18 23:14 UTC, JulienTant commented on webapp/channels/src/components/custom_status/date_time_input.tsx
> +        selected: time.toDate(),
If you select a date that is not part of the current month, the calendar will open in the current month still. You can fix this by adding `defaultMonth: time.toDate(),`

2023-05-18 23:15 UTC, JulienTant requested changes
see previous comment

2023-05-19 06:27 UTC, lindy65 approved these changes
Tested as per test steps in the Jira ticket and this is fixed / working as expected 👍

2023-05-24 08:39 UTC, k-kurematsu commented
@JulienTant @calebroseland 
This fix appears to be unrelated to issue #23370.
Issue #23370 is an issue where the selected date is one day earlier than the current date.
This fix seems to fix the DatePicker's selected date, so I think it's a fix for a similar but different problem.

If my thinking is correct, could you please remove issue #23370 from the ticket link?

2023-05-24 12:40 UTC, amyblais commented
I've removed the issue link from the description 👍 It was a confusion on my end.

2023-05-30 15:44 UTC, JulienTant approved these changes
LGTM, Thank you!!

2023-06-10 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-06-14 16:51 UTC, merged

2023-06-14 16:53 UTC, JulienTant commented
Thank you @LeonardJouve!