draft PR
mattermost/mattermost pull request #23477
Opened 2023-05-23 08:46 UTC by nilling4

#### Summary

#### Ticket Link

#### Screenshots

#### Release Note

```release-note

```

2023-05-23 09:00 UTC, nilling4 commented
@M-ZubairAhmed Hi, I was wondering how I can find out what types to assign to the different properties and parameters. This is my first time working on open source so I'm trying my best to learn. Thank you.

2023-05-23 09:20 UTC, M-ZubairAhmed commented
@nilling4 thank you opening up the PR. For starters can you please sign the cla as mentioned in https://github.com/mattermost/mattermost-server/pull/23477#issuecomment-1558829141 then we can run the CI to see what types failed.

2023-05-23 09:31 UTC, nilling4 commented
@M-ZubairAhmed cla signed

2023-05-23 09:36 UTC, M-ZubairAhmed commented
/check-cla

2023-05-23 09:36 UTC, M-ZubairAhmed commented
/release-note-none

2023-05-23 11:41 UTC, nilling4 commented
@M-ZubairAhmed Hi, I was looking at admin_settings.tsx class because I think I need to use some of the props made there in the message_export_settings class, specifically to get the type for config argument in getConfigFromState and getStateFromConfig. I'm just wondering if I should be importing in some things from there or what I should do?

2023-05-24 10:50 UTC, M-ZubairAhmed requested changes

2023-05-24 10:50 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/message_export_settings.tsx
> +        getConfigFromState = (config: { MessageExportSettings: { EnableExport: any; ExportFormat: any; DailyRunTime: any; GlobalRelaySettings: { CustomerType: any; SMTPUsername: any; SMTPPassword: an
there is a config type in mattermost/types, can you check that

2023-05-28 19:42 UTC, sinansonmez requested changes
Thanks for the great effort. However, when I checkout to your PR, I see that there are many type errors in MessageExportSettings. Please correct them all and let us know when this PR is ready for review.

2023-05-28 19:42 UTC, sinansonmez commented on webapp/channels/src/components/admin_console/message_export_settings.tsx
> +import { DeepPartial } from 'redux';
please run `make check-style` as style checker will complain about space before curly braces

2023-05-28 19:42 UTC, sinansonmez commented on webapp/channels/src/components/admin_console/message_export_settings.tsx
> +    getJobDetails = (job: { data: { messages_exported: any; warning_count: number; export_type: string; }; }) => {
Please try to avoid using any as type and find the correct type.

2023-05-28 19:42 UTC, sinansonmez commented on webapp/channels/src/components/admin_console/message_export_settings.tsx
>  export default class MessageExportSettings extends AdminSettings {
AdminSetting component is expecting to receive prop and state types. Please type them accordingly pass like this `AdminSettings<State, Props>`

2023-05-28 19:42 UTC, sinansonmez commented on webapp/channels/src/components/admin_console/message_export_settings.tsx
> +    state: any;
You dont need this if you type the state above

2023-06-08 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-07-02 07:10 UTC, M-ZubairAhmed commented
@nilling4 do you need help with this pr?

2023-10-08 18:51 UTC, closed without merging