[GH-23555] Backspace is forbidden globally
mattermost/mattermost pull request #23626
Opened 2023-06-05 12:03 UTC by akaravashkin

#### Summary
It allows to use `Backspace` in `<div contenteditable="true">`

I used solution from here https://github.com/mattermost/mattermost-webapp/pull/11956/files#diff-cd6ea218d93d3408816b90564beb01b90338fbde9049c3ef2f9574c696eea192R208-R212

#### Ticket Link
https://github.com/mattermost/mattermost/issues/23555

#### Release Note

```release-note
NONE
```

2023-06-05 12:19 UTC, M-ZubairAhmed requested changes

2023-06-05 12:19 UTC, M-ZubairAhmed commented on webapp/channels/src/components/logged_in/logged_in.tsx
> +        ) {
would you be open in improving this code, this piece was written many years ago. We would want to do the following here to improve the readability 
- remove `which` its deprecated and replace it with `isKeyPressed(e, Constants.KeyCodes.BACKSPACE)` these are utility used in codebase
- create constants for `targetElement` and `targetsTagName`
- create `isTargetNotContentEditable` constant

2023-06-06 20:04 UTC, hmhealey approved these changes
Thanks for the PR! This looks great, and I'm sure it'll be helpful in the future whenever we next make improvements to the post textbox.

2023-06-07 12:07 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-06-07 12:27 UTC, mattermost-build commented
We don't have permissions to update this PR, please contact the submitter to apply the update.

2023-06-07 12:29 UTC, mattermost-build commented
We don't have permissions to update this PR, please contact the submitter to apply the update.

2023-06-07 12:38 UTC, stafot commented
/update-branch

2023-06-07 12:38 UTC, mattermost-build commented
We don't have permissions to update this PR, please contact the submitter to apply the update.

2023-06-07 12:49 UTC, akaravashkin commented
@M-ZubairAhmed I tried to use "Sync fork" button in my github fork instead of rebasing manually. It is good now?

2023-06-07 21:21 UTC, yasserfaraazkhan commented
/e2e-test

2023-06-07 21:21 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/342693) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/342693)

2023-06-09 09:35 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/343258) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/343258)

2023-06-09 13:17 UTC, M-ZubairAhmed commented
@yasserfaraazkhan this as well we might have to create upstream branch from this fork for e2e

2023-06-09 16:58 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/343373) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/343373)

2023-06-09 18:04 UTC, yasserfaraazkhan approved these changes

2023-06-09 20:01 UTC, merged

2023-06-09 20:02 UTC, hmhealey commented
Thanks again! This should be available in the July release of MM