makes size_aware_image component types aware
mattermost/mattermost pull request #23703
Opened 2023-06-10 11:54 UTC by jatin33

#### Summary
Migrates types for SizeAwareImage component

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47086
https://github.com/mattermost/mattermost/issues/21083

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-06-10 11:55 UTC, mattermost-build commented
Hello @jatin33,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-06-13 19:07 UTC, mattermost-build commented
E2E tests not automatically triggered, because PR has no approval yet. Please ask a developer to review and then try again to attach the QA label.

2023-06-13 19:10 UTC, M-ZubairAhmed requested changes
Please also check the CI failures

2023-06-13 19:10 UTC, M-ZubairAhmed commented on webapp/channels/src/components/size_aware_image.tsx
> +    handleImageClick = (e: any) => {
lets try to be more specific her all places where `any` is used

2023-06-13 19:10 UTC, M-ZubairAhmed commented on webapp/channels/src/components/size_aware_image.tsx
> +                >
can you please revert the additional formatting introduced? if linter didn't complain no need to change :)

2023-06-15 13:51 UTC, devinbinnie requested changes
Thanks for the PR @jatin33, I've added comments for review.

2023-06-15 13:51 UTC, devinbinnie commented on webapp/channels/src/components/post_view/message_attachments/message_attachment/message_attachment.tsx
> +        if (height && height > 0) {
This can be simplified:
```suggestion
        if (height) {
```

2023-06-15 13:51 UTC, devinbinnie commented on webapp/channels/src/components/size_aware_image.tsx
> +    handleLoad = (event: any) => {
Can we find or define a type for this?

2023-06-15 13:51 UTC, devinbinnie commented on webapp/channels/src/components/size_aware_image.tsx
> +    onEnterKeyDown = (e: any) => {
Same with wrt. `any`. I think this one is a `React.KeyboardEvent`

2023-06-26 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-10-08 18:15 UTC, closed without merging