migrate elasticsearch_settings.jsx to typescript
mattermost/mattermost pull request #23762
Opened 2023-06-15 16:36 UTC by karan2704

#### Summary

Migrate components/admin_console/elasticsearch_settings.jsx to typescript

#### Ticket Link

MM-52845

#### Screenshots

N/A

#### Release Note

```release-note
N/A

```

2023-06-15 16:36 UTC, mattermost-build commented
Hello @karan2704,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-06-15 21:05 UTC, karan2704 commented
kindly go through the changes... I'm still working on the tests and I'll add them once done

2023-06-18 16:49 UTC, M-ZubairAhmed requested changes

2023-06-18 16:49 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/elasticsearch_settings.tsx
> +                    type='input'
type is optional and its default is input

2023-06-18 16:49 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/jobs/table.tsx
> +    getExtraInfoText?: (job: Job) => React.ReactElement|null;
use ReactNode to undertake null as well in the type

2023-06-18 16:49 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/elasticsearch_settings.tsx
> +    getStateFromConfig(config: AdminConfig) {
this is actually `(config: Props['config'])`

2023-06-18 16:49 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/elasticsearch_settings.tsx
> +    doTestConfig = (success: (arg0?: any) => void, error: (arg0: any) => void): void => {
can you change the type to 
```
(
        success: (data?: any) => void,
        error: (error: any) => void
    ) => void;
```

2023-06-18 16:49 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-06-18 17:14 UTC, M-ZubairAhmed commented
@karan2704 please resolve conflicts

2023-06-21 19:15 UTC, closed without merging