migrating file from jsx to tsx
mattermost/mattermost pull request #23785
Opened 2023-06-18 05:37 UTC by notlelouch

resolves #23407 by moving the contents of header_footer_template_route.jsx file to its corresponding header_footer_template_route.tsx file.

2023-06-18 05:38 UTC, mattermost-build commented
Hello @notlelouch,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-06-18 15:22 UTC, M-ZubairAhmed commented
/release-note-none

2023-06-18 15:26 UTC, M-ZubairAhmed requested changes

2023-06-18 15:26 UTC, M-ZubairAhmed commented on webapp/channels/src/components/formatted_markdown_message.test.tsx
please revert this file changes its unrelated

2023-06-18 15:26 UTC, M-ZubairAhmed commented on webapp/channels/src/components/header_footer_template_route.tsx
please change the existing file instead of creating a new file

2023-06-18 15:26 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-06-18 15:27 UTC, M-ZubairAhmed commented
@notlelouch please sign the CLA following this comment https://github.com/mattermost/mattermost/pull/23785#issuecomment-1595969683

2023-06-19 04:13 UTC, notlelouch commented
/check-cla

2023-06-19 06:57 UTC, notlelouch commented
thank you so much for your feedback, I will make the changes that you mentioned. I am sorry I am really new to open source

2023-06-19 10:21 UTC, M-ZubairAhmed commented
> thank you so much for your feedback, I will make the changes that you mentioned. I am sorry I am really new to open source

No problem at all! It's great to see your enthusiasm and willingness. Remember, we all start somewhere. Don't hesitate to reach out whenever you have any questions. 

P.S i am a fan of Kimetsu no Yaiba too

2023-06-21 02:53 UTC, closed without merging