moved database_settings to typescript
mattermost/mattermost pull request #23939
Opened 2023-07-05 06:48 UTC by mnj93

#### Summary

Migrate "components/admin_console/database_settings.jsx" and tests to Typescript.  

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/23435

#### Screenshots

None

#### Release Note

```
NONE
```

2023-07-05 06:48 UTC, mattermost-build commented
Hello @mnj93,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-07-05 06:53 UTC, mnj93 commented
/check-cla

2023-07-05 06:59 UTC, mnj93 commented
/release-note-none

2023-07-05 07:11 UTC, M-ZubairAhmed commented
@mnj93 lets us know when this is ready for review

2023-07-05 07:12 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-07-05 07:41 UTC, mnj93 commented
@M-ZubairAhmed I am done with the changes but one check is failing, can you please help with this?

2023-07-06 11:02 UTC, M-ZubairAhmed commented
/update-branch

2023-07-17 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-07-19 19:03 UTC, M-ZubairAhmed commented
@mnj93 you need to update the failing snapshots in jest

2023-07-20 15:13 UTC, M-ZubairAhmed requested changes

2023-07-20 15:13 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/database_settings.tsx
> +    getStateFromConfig(config: any) {
can we get rid of any here

2023-07-20 15:13 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/database_settings.tsx
> +                    type='input'
these probably should be text?

2023-07-21 06:46 UTC, mnj93 commented on webapp/channels/src/components/admin_console/database_settings.tsx
> +    getStateFromConfig(config: any) {
fixed

2023-07-21 07:06 UTC, mnj93 commented on webapp/channels/src/components/admin_console/database_settings.tsx
> +    getStateFromConfig(config: any) {
fixed

2023-07-23 02:10 UTC, M-ZubairAhmed requested changes

2023-07-23 02:10 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/database_settings.tsx
> +        config.SqlSettings.ConnMaxIdleTimeMilliseconds = this.parseIntNonZero(this.state.connMaxIdleTimeMilliseconds);
I dont think we need to change the method here, lets keep the previous method but we can change the parseIntNonNegative param types

2023-07-23 02:10 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/admin_settings.tsx
> +    public parseIntNonNegative = (str: string, defaultValue?: number) => {
As mentioned in this 

We can allow the str param to be either a string or number and subsequently, in the function body check if its a string, parse it to number or if its a number take it as it is

2023-07-23 02:10 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/database_settings.tsx
> +interface ComponentState extends BaseState {
nit
```suggestion
interface State extends BaseState {
```

2023-07-23 02:10 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/database_settings.tsx
> +import {AdminConfig} from '@mattermost/types/config';
nit: import placement

Place it after 
```
import React from 'react';
import {FormattedMessage} from 'react-intl';

import {AdminConfig} from '@mattermost/types/config';

import {recycleDatabaseConnection, ping} from 'actions/admin_actions';
.
.
```

2023-07-25 03:13 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2023-07-25 06:05 UTC, mnj93 commented
@M-ZubairAhmed snapshot test still failing for this component, I tried running test suit locally but was not able to, can you help me how this snapshot issue can be resolved?

2023-07-25 06:08 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed snapshot test still failing for this component, I tried running test suit locally but was not able to, can you help me with how this snapshot issue can be resolved?

Oh they don't look to fail but yeah here is the steps
```sh
cd channels
npm run test -- -u
```

2023-07-25 06:34 UTC, mnj93 commented
[This](https://github.com/mattermost/mattermost/actions/runs/5648470660/job/15311521711?pr=23939) check is failing. 

Also tried running `npm run test -- -u` but its failing with this error for all the test cases

![Screenshot 2023-07-25 at 12 01 43 PM](https://github.com/mattermost/mattermost/assets/20276545/75ce8296-513e-4641-9421-efb257e1a8ad)

2023-07-25 06:50 UTC, M-ZubairAhmed commented
/update-branch

2023-08-06 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-08-18 11:20 UTC, mnj93 commented
@M-ZubairAhmed Hey, anything pending from my end for this PR?

2023-09-04 08:26 UTC, M-ZubairAhmed commented
/update-branch

2023-09-04 08:27 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-09-04 08:27 UTC, M-ZubairAhmed commented
/update-branch

2023-09-04 08:27 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.

2023-09-04 08:30 UTC, M-ZubairAhmed commented
/update-branch

2023-09-06 08:50 UTC, yasserfaraazkhan commented
/update-branch

2023-09-11 07:09 UTC, M-ZubairAhmed commented
@mnj93 can you please update the branch

2023-09-12 06:04 UTC, mnj93 commented
/update-branch

2023-09-12 06:26 UTC, M-ZubairAhmed commented
/update-branch

2023-09-12 06:28 UTC, M-ZubairAhmed commented
@yasserfaraazkhan can you recheck if the e2e for this passes?

2023-09-12 06:54 UTC, yasserfaraazkhan commented
/e2e-test

2023-09-12 06:54 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/369498) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/369498)

2023-09-12 07:28 UTC, M-ZubairAhmed commented
@mnj93 can you check the failing CI

2023-09-12 17:37 UTC, mnj93 commented
> [This](https://github.com/mattermost/mattermost/actions/runs/5648470660/job/15311521711?pr=23939) check is failing.
> 
> Also tried running `npm run test -- -u` but its failing with this error for all the test cases
> 
> ![Screenshot 2023-07-25 at 12 01 43 PM](https://user-images.githubusercontent.com/20276545/255810908-75ce8296-513e-4641-9421-efb257e1a8ad.png)

@M-ZubairAhmed Still facing this error when I try to run the tests.

2023-09-13 06:33 UTC, M-ZubairAhmed commented
> > [This](https://github.com/mattermost/mattermost/actions/runs/5648470660/job/15311521711?pr=23939) check is failing.
> > Also tried running `npm run test -- -u` but its failing with this error for all the test cases
> > ![Screenshot 2023-07-25 at 12 01 43 PM](https://user-images.githubusercontent.com/20276545/255810908-75ce8296-513e-4641-9421-efb257e1a8ad.png)
> 
> @M-ZubairAhmed Still facing this error when I try to run the tests.

This error is not produced in the CI, you can verify. Its just the snapshot update error. There is something not correct with your local setup for it to have that error.

2023-09-13 07:26 UTC, mnj93 commented
@M-ZubairAhmed Yeah and for updating snapshot I guess I need to run this command but its not working on my local setup.  Is there any other way to update the snapshot?

2023-09-24 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-10-02 12:59 UTC, hanzei commented
@mnj93 Heads up that I updated the snapshots for you.

@yasserfaraazkhan The PR is ready for your review.

2023-10-02 22:36 UTC, yasserfaraazkhan commented
/e2e-test

2023-10-02 22:36 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/374538) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/374538)

2023-10-03 04:54 UTC, yasserfaraazkhan approved these changes

2023-10-03 05:35 UTC, merged

2023-10-03 05:41 UTC, hanzei commented
Thanks for the contribution @mnj93 :tada: