[GH-21163] Migrate "utils/message_html_to_component.jsx" to TypeScript
mattermost/mattermost pull request #23972
Opened 2023-07-07 19:47 UTC by veronicadip

I've read the Contribution Checklist, your blog post, and the repository documentation.

#### Summary
Migrated `message_html_to_component.jsx` and `message_html_to_component.test.jsx` to TypeScript.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/21163

#### Release Note
```
NONE
```

2023-07-07 19:47 UTC, mattermost-build commented
Hello @veronicadip,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-07-10 12:51 UTC, M-ZubairAhmed commented
/release-note-none

2023-07-10 12:52 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-07-20 08:35 UTC, larkox approved these changes
Nothing blocking, but a few potential improvements.

2023-07-20 15:12 UTC, lieut-data commented
Apologies, I won't have the time to be able to review this one -- hoping @calebroseland can help (or delegate again ;P)

2023-07-21 21:17 UTC, calebroseland requested changes
Thanks for the contribution, @veronicadip! Seems like there are some mission properties on `Options`: `emoji`, `images`, `latex`, `inlinelatex`, & `markdown`—would you mind adding those, too?

2023-07-21 21:17 UTC, calebroseland commented on webapp/channels/src/types/external/html-to-react.d.ts
> +            mentionAttrib: string | undefined;
Are `data-edited-post-id` and `mentionAttrib` needed? Could they be covered by the index signature?

2023-08-04 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-10-16 10:34 UTC, jespino commented
This was handled internally. Anyway, thanks for the effort and time dedicated here @veronicadip! We really appreciate it.

2023-10-16 10:34 UTC, closed without merging