MM-6482: Across teams channel auto complete
mattermost/mattermost pull request #24137
Opened 2023-07-26 15:31 UTC by AshishDhama

#### Summary
Across team channel auto complete

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/20606

#### Screenshots

#### Release Note
```release-note
* Channel auto completion will now return results across all teams.
```

2023-07-26 15:31 UTC, mattermost-build commented
Hello @AshishDhama,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-07-26 16:12 UTC, unode commented
@AshishDhama many thanks for this and the cross reference from the older issue.

If I understand the code correctly the syntax is `~channel-name(team-name)`.
Would you be so kind to add this information to the description of this PR?

This will be relevant to answer #24132 .

2023-07-27 08:56 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-07-27 09:35 UTC, agnivade reviewed
Thanks Dhama. Left some comments.

2023-07-27 09:35 UTC, agnivade commented on server/public/model/channel_mentions.go
> +func ChannelMentionsAcrossTeams(message string) map[string][]string {
Let's add a test for this.

Also, can we add some docs to explain the format of the `map[string][]string`?

2023-07-27 09:35 UTC, agnivade commented on server/public/model/channel_mentions.go
> +			teamString := channelMentionTeamRegexp.FindString(match)
Any reason we need to use regexes again to extract the channel and team names? We can just declare groups in the regex and use `FindAllStringSubmatch` to get the submatches as well in a single shot.

See: https://pkg.go.dev/regexp#pkg-overview for more info

> If 'Submatch' is present, the return value is a slice identifying the successive submatches of the expression. Submatches are matches of parenthesized subexpressions (also known as capturing groups) within the regular expression, numbered from left to right in order of opening parenthesis. Submatch 0 is the match of the entire expression, submatch 1 is the match of the first parenthesized subexpression, and so on.

For an example implementation, see: https://github.com/mattermost/mattermost-plugin-github/blob/11815f80ac05b110a5de479bbb7a9b1ff2995463/server/plugin/permalinks.go#L46

2023-07-27 09:35 UTC, agnivade commented on server/channels/app/post.go
> +	ChannelMentionsAcrossTeams := post.ChannelMentionsAcrossTeams()
Let's also add a test similar to `TestPostChannelMentions` to test this functionality and verify that the post prop gets set properly.

2023-07-27 09:35 UTC, agnivade commented on server/channels/app/post.go
> +				mlog.Warn("Failed to get team of the channel mention", mlog.String("mentionedTeam", channel.TeamId))
Use `c.Logger().Warn(` instead of `mlog.Warn`. Let's do the change in L485 as well.

2023-08-07 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-08-09 19:43 UTC, hmhealey requested changes
Thanks, Ashish!

One thing I'm not sure about with this is the `~channel(team)` format for these in the text. I think it's the regular brackets that have me a bit worried because people might use those when writing text normally. I saw `~channel:team` suggested above which does look a bit cleaner, but that might run into the same issue as https://mattermost.atlassian.net/browse/MM-34627 where the Markdown parser tries to treat it as a URL instead of plain text because of the `:`. Ideally, we'd encode them as something like `~channelId` since then we wouldn't need the team name at all, but that drastic of a change leads to more compatibility concerns and poor UX if we don't have a richer post editor by that point.

Thoughts on potentially changing that? I haven't seen any discussion on that previously, so I'm curious about your thinking here too.

Also, speaking of compatibility concerns, we'll also need to support mobile with this as well. Would you be interested in working on that too, or should we split that off into a separate ticket?

2023-08-09 19:43 UTC, hmhealey commented on webapp/channels/src/utils/text_formatting.tsx
> +                value: `<a class="mention-link" href="${href}" data-channel-mention="${channelName}" data-channel-mention-team="${team.name}">~${displayName}</a>`,
Would we also want the team name to be displayed here? I can't remember the difference between these two cases

2023-10-16 07:24 UTC, unode commented
Was this accidentally closed?

2024-02-29 16:19 UTC, AshishDhama commented
I discussed with @hmhealey, that since the current solution isn't taking care of all the cases I am closing this pr.

2024-02-29 16:19 UTC, closed without merging

2024-03-01 10:13 UTC, unode commented
@AshishDhama would it be possible to have a summary of the cases?
Perhaps someone can then craft another PR that addresses all points.

2024-03-04 18:54 UTC, hmhealey commented
It's a bit hard to explain since there's a lot of history here, but the short version of this is that cross-team channel linking is a lot larger effort than initially expected because those short links were written before MM users could be on multiple teams. There's issues around both permissions, caching, and Markdown, and the Markdown changes in particular introduce compatibility issues with mobile which would also need to be solved, so we have to think more about when we'll be able to do this

2024-03-05 13:10 UTC, unode commented
Thanks @hmhealey. Personally I still see this feature as quite important to users, particularly new ones to the MM ecosystem. For instance, in a direct message, the meaning of a channel link `~Town Square` changes depending on which team you have active when reading the message or clicking the link. This regularly causes confusion and messages ending up in the wrong channels.

I would be happy to contribute if there's any direction that seems promising or if there is space to propose complete or partial solutions. Possibly even a series of changes to be slowly introduced over several versions.

Specifically, I see two sub-tasks (in order of relevance):
1. Syntax for cross-team channel reference (possibly even cross-instance) that is compatible with current markdown parsers and unambiguously refers to a channel.
2. Auto-complete behavior (by channel name before team? by team before channel? public channels only? private channels that the user is a member of?)