[GH-24246]Add JSON null check to unmarshaling in api4 .go files
mattermost/mattermost pull request #24256
Opened 2023-08-12 10:24 UTC by shubmjagtap

#### Summary

Added conditional checks to check that the item being unmarshaled is null or empty .

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24246
Jira https://mattermost.atlassian.net/browse/MM-54024

#### Screenshots

#### Release Note

```release-note

```

2023-08-12 10:24 UTC, mattermost-build commented
Hello @shubmjagtap,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-08-12 10:26 UTC, shubmjagtap commented
Note : More files from "server/channels/api4" directory or other directory are still remaining ( just waiting for your confirmation ) , thank you.

2023-08-12 10:44 UTC, shubmjagtap commented
/check-cla

2023-08-23 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-08-24 08:39 UTC, Willyfrog approved these changes

2023-08-24 08:40 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-08-24 08:40 UTC, Willyfrog commented
@shubmjagtap seems like there are some failing checks (linting) can you check them and fix it?

2023-08-24 08:58 UTC, hanzei requested changes
Thanks for jumping on the issue :+1: @shubmjagtap 

The issue reported inhttps://github.com/mattermost/mattermost/issues/24246 only effects cases where we son unmarshal into a pointer. In cases like in `server/channels/api4/remote_cluster.go` where a value is used, we don't need to check if they payload is `null`. Other checks will catch semantic errors like that one later.

2023-08-24 08:58 UTC, hanzei commented on server/channels/api4/cloud.go
> +	if err = json.Unmarshal(bodyBytes, &subscriptionChange); len(bodyBytes) == 0 || err != nil {
I don't think that approach helps here. If the input is `null`, ` len(bodyBytes)` will be greater then zero. Should we instead check if `subscriptionChange` is not longer `nil`?

2023-08-24 08:58 UTC, hanzei commented on server/channels/api4/post_test.go
> +			err := event.GetData()["post"].(string) == "" || json.Unmarshal([]byte(event.GetData()["post"].(string)), &wpost)
No need to update tests. The payload here is fine.

2023-09-04 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-09-10 18:48 UTC, shubmjagtap commented
sorry for late reply @Willyfrog  & @hanzei  ( due to some other imp work this was delayed ) , i will work on this issue now .

2025-06-19 08:15 UTC, closed without merging

2025-06-19 08:15 UTC, Willyfrog commented
It's been stale for a very long time, I'm proceeding to close it. If this is still relevant, feel free to create a new PR