fixed status code
mattermost/mattermost pull request #24313
Opened 2023-08-19 19:17 UTC by harshal2030

#### Summary

Fixes the status code for /api/v4/channels for wrong json data from 403 to 400

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24291
#### Screenshots

#### Release Note

```release-note
NONE
```

2023-08-19 19:18 UTC, mattermost-build commented
Hello @harshal2030,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-09-07 16:49 UTC, harshal2030 commented
Hi, Is there anything else that needs a change by me, there are no reviewer yet

2023-11-23 08:14 UTC, hanzei commented
@harshal2030 Sorry it took so long to get your PR reviewed. Taking a look right now!

2023-11-23 08:21 UTC, agnivade requested changes

2023-11-23 08:21 UTC, agnivade commented on server/channels/api4/channel.go
> +	if channel.TeamId == "" || channel.Name == "" || channel.DisplayName == "" {
I think we should just verify the `Type` and `TeamId` to let the permission checks pass. The rest of the validation is taken care of by the store and app layers. Let's also add a unit test please. Thanks.

2023-11-23 08:35 UTC, hanzei requested changes

2023-11-23 08:35 UTC, hanzei commented on server/channels/api4/channel.go
> +		c.SetInvalidParam("channel")
Can we make the error more descriptive? The current output is 
```json
{
    "detailed_error": "",
    "id": "api.context.invalid_body_param.app_error",
    "message": "Invalid or missing channel in request body.",
    "request_id": "kcofxp4mwtropx683kngokqn1h",
    "status_code": 400
}
```

2023-12-18 15:20 UTC, hanzei commented
@harshal2030 Please let me know if you have any questions regarding the feedback.

2024-01-24 10:04 UTC, closed without merging