Added license change listener
mattermost/mattermost pull request #24342
Opened 2023-08-23 09:19 UTC by harshilsharma63

#### Summary
Added license change listener to run fix job if needed

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53899

#### Release Note

```release-note
Updated the fix to run on license change on running server, thus removing the step to restart Mattermost server for the fix to take affect.
```

2023-08-23 09:21 UTC, larkox approved these changes

2023-08-23 09:31 UTC, agnivade approved these changes

2023-08-24 13:55 UTC, jupenur requested changes

2023-08-24 13:55 UTC, jupenur commented on server/channels/app/migrations.go
> +	s.AddLicenseListener(func(oldLicense, newLicense *model.License) {
This looks very wrong. Doesn't `doElasticsearchFixChannelIndex` return early if the server isn't licensed for ES? So if the server isn't licensed, the listener doesn't get added? And if the listener gets added, the server *is* licensed and the listener will never do anything?

2023-08-29 13:00 UTC, jupenur approved these changes
Should we check the migration key before adding the listener, to avoid an unnecessary listener? Also is it even possible to upload a license to a build where `model.BuildEnterpriseReady != "true"` or could that check be removed?

2023-10-10 04:59 UTC, agnivade commented on server/channels/app/migrations.go
> +		}
This looks like the same code is being repeated again. Perhaps we can refactor to a separate function?

2023-10-13 06:09 UTC, agnivade commented
Looks good. Going to ask for Jesse's review because he has been working with the job framework recently to ensure nothing has been missed out.

2023-10-16 16:33 UTC, lieut-data approved these changes

2023-10-16 16:33 UTC, lieut-data commented on server/channels/app/migrations.go
> +	if model.BuildEnterpriseReady != "true" || license == nil || !*license.Features.Elasticsearch {
Can you elaborate on the need for this check in the first place? Is it a startup race where we try to execute the job before we apply the license? Or is it an attempt to ensure we run the job at some point when the user upgrades and installs a license?

2023-11-27 02:43 UTC, harshilsharma63 commented
/update-branch

2023-11-27 03:19 UTC, merged

2023-11-27 13:56 UTC, amyblais commented
/cherry-pick release-9.3

2023-11-27 13:56 UTC, mattermost-build commented
Cherry pick is scheduled.

2023-11-29 20:01 UTC, amyblais commented
/cherry-pick release-9.2

2023-11-29 20:01 UTC, mattermost-build commented
Cherry pick is scheduled.