MM-49627: Suppress transformation of embedded images via image proxy
mattermost/mattermost pull request #24401
Opened 2023-08-29 06:51 UTC by agnivade

There was no check for embedded images which made "copy text" paste
the siteURL instead of the actual image content.

This does not change the behavior of actually rendering the image
which is how other sites behave as well.

https://mattermost.atlassian.net/browse/MM-49627
```release-note
NONE
```

2023-08-29 06:51 UTC, agnivade commented
Adding Juho because this concerns image proxy which has been a sensitive area.

2023-08-29 08:07 UTC, agarciamontoro approved these changes
Does this render the image inline?

2023-08-29 08:08 UTC, agnivade commented
It does not. And that's how other sites behave. This just fixes the "copy text" functionality.

2023-08-29 08:11 UTC, agarciamontoro commented
Got it, makes sense!

2023-08-29 09:36 UTC, jupenur requested changes

2023-08-29 09:36 UTC, jupenur commented on server/platform/services/imageproxy/imageproxy.go
> +	if imageURL == "" || proxy.siteURL == nil || strings.HasPrefix(imageURL, "data:image/") {
This should be case-insensitive.

2023-08-30 07:40 UTC, agnivade commented
/e2e-test

2023-08-30 07:40 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/365507) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/365507)

2023-08-30 17:03 UTC, merged