[MM-54497][MM-54495]Fix updatePost props and plugin hooks
mattermost/mattermost pull request #24543
Opened 2023-09-13 17:16 UTC by larkox

#### Summary
We were using the wrong variable on two different places in the UpdatePost function, causing some issues.

This PR deals with the proper variable names, adds tests, and deals with other side effects.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-54497
Fix https://mattermost.atlassian.net/browse/MM-54495

#### Release Note
```release-note
Fix MessageWillBeUpdated plugin hook to allow rejections
Fix post props on update to proper see channel links
```

2023-09-25 17:53 UTC, crspeller requested changes

2023-09-25 17:53 UTC, crspeller commented on server/channels/app/post.go
> +	if err = a.FillInPostProps(c, newPost, nil); err != nil {
Maybe we should rename "post" to prevent this from happening again.

2023-09-26 21:18 UTC, marianunez approved these changes

2023-09-26 21:19 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-09-26 21:20 UTC, marianunez commented
@larkox can you help with QA Tests on how this issue was showing up before to help validate the fix?

2023-09-27 08:20 UTC, larkox commented
@yasserfaraazkhan Here are the QA steps.
User experience based testing:
- Make a post with a link to an open channel you are not a member of (e.g. `~channel-name`)
- Refresh the page
- See how the channel is properly linked and show the channel display name (e.g. `~Channel Name`)
- Update the post and add the name of a different channel (e.g. `~channel-name-2`)
- Refresh the page
  - Expected: The channel is linked and show the channel display name
  - Before the fix: The channel shows "raw" (`~channel-name` without a link format)

Technical testing:
- Make a post with a link to an open channel you are not a member of (e.g. `~channel-name`)
- Refresh the page
- The props of the post (that can be found in the unreads network request for this channel) contain the mention for this channel, stating the channel display name.
- Update the post and add the name of a different channel (e.g. `~channel-name-2`)
- Refresh the page
  - Expected: The props of the post (that can be found in the unreads network request for this channel) contain the mention for the new channel, stating the channel display name.
  - Before the fix: The props of the post contains the same information as before the update.

2023-09-27 08:52 UTC, yasserfaraazkhan commented
/e2e-test

2023-09-27 08:52 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/373120) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/373120)

2023-10-03 05:11 UTC, yasserfaraazkhan commented
/update-branch

2023-10-03 15:48 UTC, crspeller approved these changes

2023-10-04 21:11 UTC, yasserfaraazkhan approved these changes
Thank you for sharing the steps @larkox 
I've tried those and renaming channel, editing posts, in center, RHS, thread section.

2023-10-05 07:40 UTC, merged

2023-11-24 14:22 UTC, amyblais commented
/cherry-pick release-9.1

2023-11-24 14:22 UTC, mattermost-build commented
Cherry pick is scheduled.

2023-11-24 14:22 UTC, amyblais commented
/cherry-pick release-9.0

2023-11-24 14:22 UTC, mattermost-build commented
Cherry pick is scheduled.

2023-11-24 14:22 UTC, mattermost-build commented
Cherry pick is scheduled.