[GH-24528] Only add user who isn't in the channel
mattermost/mattermost pull request #24540
Opened 2023-09-13 13:05 UTC by alexdecamillo

#### Summary

This PR prevents the redux actions that occur after a user addition from executing if the user is already in the channel

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24528
Jira https://mattermost.atlassian.net/browse/MM-54356

#### Screenshots

![mattermost-user-channel](https://github.com/mattermost/mattermost/assets/13474424/ba840ae0-f344-4a99-a897-51cdfc5329f9)

#### Release Note

```release-note
Fixed a bug where the channel member count increased when adding an already present user
```

2023-09-13 13:05 UTC, mattermost-build commented
Hello @alexdecamillo,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-09-13 16:40 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-09-13 18:59 UTC, devinbinnie approved these changes
LGTM! Just one non-blocking comment.
Thanks @alexdecamillo!

2023-09-13 18:59 UTC, devinbinnie commented on webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
> +        if (!membersInChannel || !(userId in membersInChannel)) {
We can simplify a bit here:

```suggestion
        if (!(membersInChannel && userId in membersInChannel)) {
```

2023-09-15 15:49 UTC, M-ZubairAhmed requested changes
Thank you pending Devin's comment

2023-09-15 18:06 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2023-09-15 18:07 UTC, M-ZubairAhmed commented
/update-branch

2023-09-17 11:54 UTC, yasserfaraazkhan commented
/e2e-test

2023-09-17 11:54 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/371004) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/371004)

2023-09-17 13:06 UTC, yasserfaraazkhan approved these changes
thank you for the changes! working as expected!

2023-09-19 06:49 UTC, merged