MM-21466 mmctl deleteUsersCmdF Review
mattermost/mattermost pull request #24585
Opened 2023-09-18 08:56 UTC by IronOnet

#### Summary

This PR implements a refactor of the deleteUsersCmdF, the aim of the 
refactor improve error handling for this function

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/21466
Jira https://mattermost.atlassian.net/browse/MM-47820

#### Release Note
NONE

2023-09-18 08:56 UTC, mattermost-build commented
Hello @IronOnet,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-09-19 12:44 UTC, IronOnet commented
@mgdelacroix @isacikgoz Let me fix the errors,

2023-09-20 09:48 UTC, IronOnet commented
@mgdelacroix @isacikgoz I've fixed the e2e tests

2023-09-26 07:52 UTC, isacikgoz commented
@toninis the tests didn't run for this PR, could it be related to closing and re-opening the PR?

2023-09-26 09:10 UTC, toninis commented
@isacikgoz Tests are not triggered because the conditions have not met . 
This is a fork PR and the condition is that Server tests are passing . 
In any case we can use [this](https://github.com/mattermost/delivery-platform/tree/master/automations/mattermost#manual-trigger) documentation for manual trigger .

2023-10-03 10:52 UTC, isacikgoz commented
/update-branch

2023-10-13 21:25 UTC, IronOnet commented
/update-branch

2023-10-15 03:36 UTC, IronOnet commented
@mgdelacroix ,  @isacikgoz , I've completed this issue, need a review😊😊

2023-10-16 10:01 UTC, isacikgoz requested changes
@IronOnet thanks for contribution! I think there is a slight change needed below:

2023-10-16 10:01 UTC, isacikgoz commented on server/cmd/mmctl/commands/user.go
>  	if err != nil {
```suggestion
	if err != nil {
		result = multierror.Append(result, err)
```

2023-10-19 22:28 UTC, IronOnet commented
/update-branch

2023-10-20 13:42 UTC, IronOnet commented
@isacikgoz i've made the change

2023-10-23 08:02 UTC, isacikgoz approved these changes

2023-10-23 18:50 UTC, isacikgoz requested changes
Hey @IronOnet we discussed this offline, I overlooked the remaining part of the code and now I see that this is not a valid use case of the `multierror`. Sorry for the confusion here. 

So, basically we need to use multierror on `L:656` and `L:659`  where we actually receive an error scenario.

2023-10-24 15:52 UTC, IronOnet commented
@isacikgoz no probs, I'll take care of it...

2023-11-04 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-12-06 21:00 UTC, IronOnet commented
/update-branch

2024-02-02 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-02-02 14:17 UTC, hanzei commented
@crspeller would you please review the PR as @mgdelacroix is out?

2024-02-03 13:52 UTC, closed without merging