[MM-54522] Add trial info to log + support packet
mattermost/mattermost pull request #24596
Opened 2023-09-20 16:36 UTC by JulienTant

#### Summary

Add `is_trial` to the start log:

```json
{"timestamp":"2023-09-19 13:45:35.680 -07:00","level":"info","msg":"Current version is 9.1.0 (dev/n/a/88d043a97164544587cdbeba9acfb8e740685ad3/0350cb2cf5d2ef2cea76f10a8d8fdbfcc8a22f9d)","caller":"app/server.go:433","is_trial":false,"current_version":"9.1.0","build_number":"dev","build_date":"n/a","build_hash":"88d043a97164544587cdbeba9acfb8e740685ad3","build_hash_enterprise":"0350cb2cf5d2ef2cea76f10a8d8fdbfcc8a22f9d","service_environment":"dev"}
```

And `license_is_trial` to the support packet

```yaml
# ...
license_is_trial: "false"
# ...
```

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54522

#### Release Note
```release-note
NONE
```

2023-09-20 16:36 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-09-25 19:57 UTC, BenCookie95 approved these changes

2023-09-26 08:53 UTC, hanzei requested changes

2023-09-26 08:53 UTC, hanzei commented on server/channels/app/support_packet.go
> +		LicenseIsTrial:        strconv.FormatBool(isTrial),
Can you please elaborate on the use case of having the trial license information is? Do we already know from sales force if a customer is using a trial license?

2023-09-27 08:17 UTC, hanzei commented on server/channels/app/support_packet.go
> +		LicenseIsTrial:        strconv.FormatBool(isTrial),
Resolved via https://community.mattermost.com/private-core/pl/bqznibnfd7fhjmben8chkmprnr

2023-09-27 08:17 UTC, hanzei commented on server/channels/app/server.go
> +		mlog.Bool("is_trial", isTrial),
@JulienTant This is still a concern.

2023-10-17 18:20 UTC, JulienTant commented on server/channels/app/server.go
> +		mlog.Bool("is_trial", isTrial),
Are we really concerned about the few bytes this will add to this specific log line?

2023-10-24 08:08 UTC, hanzei approved these changes
LGTM, I left one non-blocking suggestion.

2023-10-24 08:08 UTC, hanzei commented on server/channels/app/server.go
> +		mlog.Bool("is_trial", isTrial),
You are right, this is not a blocking comment.

But one thought to add: This log line currently is about the build version and not about version information. Does it make sense to add an additional log line about the license and add the trial information there?

2023-10-26 17:58 UTC, JulienTant commented on server/channels/app/server.go
> +		mlog.Bool("is_trial", isTrial),
moving it to the log dedicarted to enterprise build

2023-10-26 18:29 UTC, mattermost-build commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2023-10-26 19:22 UTC, mattermost-build commented
Trying to auto merge this PR.

2023-10-26 19:22 UTC, merged

2023-10-26 19:22 UTC, mattermost-build commented
Pull Request successfully merged
SHA: 375404c12e0a4fa62826e625e9a2a54baa4ae804