Fix style for notices
mattermost/mattermost pull request #24636
Opened 2023-09-28 11:39 UTC by larkox

#### Summary
The style of the notices broke, probably after the latest button refactor (and maybe due to bad merges).

This fixes it.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-54583

#### Screenshots
|  before  |  after  |
|----|----|
| ![Screenshot from 2023-09-28 13-34-34](https://github.com/mattermost/mattermost/assets/1933730/a2c8b0ef-5f6b-4f07-8cb4-e53a76187202) | ![Screenshot from 2023-09-28 13-32-05](https://github.com/mattermost/mattermost/assets/1933730/69b8eb9e-0662-49f6-b7b2-6e6be4022b20) |
| ![Screenshot from 2023-09-28 13-34-49](https://github.com/mattermost/mattermost/assets/1933730/1b3c7a55-be1d-4694-9514-ff6bfc7dd927) | ![Screenshot from 2023-09-28 13-34-34](https://github.com/mattermost/mattermost/assets/1933730/c13747e4-972f-4112-bc89-91165d021bf3) |

#### Release Note
None needed if released on 9.1
```release-note
NONE
```

2023-09-28 11:39 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-09-28 13:38 UTC, matthewbirtch requested changes
Just made one comment on the button size. Other than that, while we're editing the style here, can we adjust the `line-height` on `.system-notice_body` to be `line-height: 20px;`

The icon could also use an update to use compass icons, but the above gets us closer and we can update the icon another time if that's too complex.

2023-09-28 13:38 UTC, matthewbirtch commented on webapp/channels/src/components/system_notice/system_notice.tsx
> +                                className='btn btn-tertiary'
I think we can add the `btn-sm` class to get the smaller version of the button for these notices. Should apply that to all buttons in these notices

2023-09-28 15:07 UTC, matthewbirtch approved these changes
Thanks!

2023-09-28 19:41 UTC, hmhealey approved these changes

2023-10-02 22:25 UTC, yasserfaraazkhan approved these changes

2023-10-03 09:03 UTC, merged

2023-10-03 09:03 UTC, mattermost-build commented
Cherry pick is scheduled.

2023-10-03 14:18 UTC, amyblais commented
/cherry-pick cloud

2023-10-03 14:18 UTC, mattermost-build commented
Cherry pick is scheduled.