[MM-54024] Handle JSON nulls when unmarshalling in api4
mattermost/mattermost pull request #24656
Opened 2023-10-02 02:07 UTC by Delaney

#### Summary
Fixes code where `null` JSON values are not handled in the `api4` files.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/24246
Jira https://mattermost.atlassian.net/browse/MM-54024

#### Release Note

```release-note
Handle JSON null value case correctly by also checking pointer is no longer null when unmarshalling to a pointer
```

2023-10-02 02:07 UTC, mattermost-build commented
Hello @Delaney,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-02 11:11 UTC, hanzei requested changes
The changes look fine, but there are some instances that you missed like https://github.com/mattermost/mattermost/blob/6dc472e8ae920512631de74c59a3b79ce97a33f1/server/channels/api4/channel.go#L86-L91

I've searched for them using the following regex: `var (.*) \*`. Maybe that helps you find addition code pieces that need this threadment.

2023-10-02 12:21 UTC, hanzei approved these changes
LGTM :+1:

2023-10-03 06:33 UTC, agnivade requested changes
Looks good, but can we add a few unit tests?

2023-10-03 06:33 UTC, agnivade commented on server/channels/api4/team.go
> +	if jsonErr := json.NewDecoder(r.Body).Decode(&members); jsonErr != nil || members == nil {
Is this really needed? There's a check which verifies the length of a slice after this.

2023-10-03 06:33 UTC, agnivade commented on server/channels/api4/cloud.go
> +		if err != nil || sanitizedProducts == nil {
Same. This is unncessary as well. It will just write `null` as the output which is valid if the input is null.

2023-10-04 11:56 UTC, Delaney commented
@agnivade I'm still writing tests, will be pushing those soon. Also, I'm unable to test on my local setup. Keeping getting this error:

```
panic: cannot read file: open mattermost/server/channels/testlib/testdata/postgres_migration_warmup.sql: no such file or directory
```

Could I get some help with that?

2023-10-04 14:13 UTC, agnivade commented
Sure. Can you tell me what have you tried to solve the issue? Maybe you can search the codebase for the error, or set a debugger while running the test and see where it fails?

2023-10-04 14:25 UTC, Delaney commented
@agnivade I think, for some reason, `postgres_migration_warmup.sql` can't be found. I'm using a hacky method where I'm executing the SQL directly, and skipping the `PreloadMigrations` method in `testlib/helper.go`

2023-10-04 15:34 UTC, Delaney commented
> Looks good, but can we add a few unit tests?

More tests added, ready for review

2023-10-05 04:30 UTC, agnivade approved these changes
Thanks!

2023-10-05 04:30 UTC, agnivade commented
/e2e-test

2023-10-05 04:30 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/375233) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/375233)

2023-10-05 05:48 UTC, agnivade commented
@saturninoabril - The e2e [test](https://automation-dashboard.vercel.app/cycle/375233) shows one unrelated failure. What should be the procedure here?

2023-10-05 07:11 UTC, saturninoabril commented
True, it's unrelated but it's fixed on master - https://github.com/mattermost/mattermost/pull/24614. This could be updated and may run the test again.

2023-10-05 07:11 UTC, saturninoabril commented
/update-branch

2023-10-05 09:41 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/375302) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/375302)

2023-10-05 13:55 UTC, merged