update regex to force first character to be alpha
mattermost/mattermost pull request #24675
Opened 2023-10-02 21:49 UTC by sbishel

#### Summary

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-54502

#### Screenshots

#### Release Note

```release-note

```

2023-10-12 20:57 UTC, sbishel commented
After seeing all the different tests that needed fixed for this, I worry this could be considered a breaking change to the API. Could this break other client apps? plugins? or does it matter?

2023-10-16 15:16 UTC, isacikgoz requested changes
There are some logs needs to be removed, apart from that why we are preventing usernames to start with numeric characters? Also, what would happen to usernames before this change?

2023-10-16 15:16 UTC, isacikgoz commented on server/channels/api4/apitestlib.go
> +	mlog.Debug("INITBASIC")
Are these logs forgotten?

2023-10-17 09:04 UTC, isacikgoz commented
Thanks for the info, I think we should only be concerned existing usernames. Tools like https://github.com/mattermost/mattermost-load-test-ng are relying on server side verification. Also we may never know what current users have as usernames. If they created users/bots from CLI, it will still fall under the server side verification. So, eg. importing users may have some exclusions on this regard. Thoughts?

2023-10-17 16:54 UTC, hmhealey commented
> @hmhealey was this causing an issue somewhere or just something you noticed?

It's mostly something I noticed. I know we've made some assumptions about usernames starting with letters in the code, but it does seem like most places handle it fine. The only place I've 100% found an issue is that at-mentions on mobile won't render correctly for those users because the pattern makes that assumption (https://github.com/mattermost/commonmark.js/blob/master/lib/inlines.js#L949)

2023-11-01 19:38 UTC, sbishel commented
@hmhealey @isacikgoz @streamer45 - I'm thinking this is a case where the cure is worse than the disease.  This fix is essentially making a breaking change to our APIs. As Ibrahim mentioned above, load test tools rely on server side verification, so they would probably fail and need updated. I would guess this will also cause issues in the wild. 

Thoughts on closing this as "won't fix" or making it with next major version?

2023-11-01 21:30 UTC, hmhealey commented
Yeah, that makes sense. I agree that it's a technically a breaking change, so we should leave it until the next major version at least. While there's that one issue I found caused by this, we can always fix that independently or just treat it as a known issue and fix it if anyone actually runs into it in the wild.

2023-11-02 08:46 UTC, isacikgoz commented
Agreed on postponing to major release, thanks @sbishel!

2023-12-15 17:33 UTC, hmhealey commented
Related report: https://github.com/mattermost/mattermost-mobile/issues/4850

2024-06-11 14:55 UTC, hmhealey commented
Unassigning myself until we're ready to merge this. Feel free to reassign when it's ready for merging or if we want to review it early

2024-06-12 20:54 UTC, sbishel commented
/update-branch

2024-07-12 20:41 UTC, sbishel commented
/update-branch

2024-07-15 21:30 UTC, sbishel commented
@hmhealey @isacikgoz @streamer45 - The window for v10.0 has opened. Is this breaking change we still want to take otherwise I will close.

2024-07-16 21:12 UTC, hmhealey commented
Yes, I think it would be good to include this for 10.0 since it'll help ensure that the state of the app stays correct. While it has slight potential to be a breaking change for someone, I think it's more likely that we'd run into a weird bug report for a case that seemingly shouldn't happen if we leave were to leave this unfixed

2024-07-17 20:35 UTC, hmhealey approved these changes

2024-07-18 13:56 UTC, streamer45 approved these changes

2024-07-18 13:58 UTC, streamer45 commented
@sbishel Not sure if this deserves a quick security pass, given that, technically speaking, we are dealing with credentials.

2024-07-18 18:49 UTC, sbishel commented
> @sbishel Not sure if this deserves a quick security pass, given that, technically speaking, we are dealing with credentials.

Added security, but not sure they will have time.

2024-07-22 11:45 UTC, isacikgoz approved these changes
lgtm, thanks for your patience @sbishel 💪

2024-07-23 11:09 UTC, esarafianou approved these changes

2024-07-31 14:14 UTC, mattermost-build commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2024-07-31 14:27 UTC, mattermost-build commented
Trying to auto merge this PR.

2024-07-31 14:27 UTC, merged

2024-07-31 14:27 UTC, mattermost-build commented
Pull Request successfully merged
SHA: 08ed72f0601c26d6ee2e298f2f7455c5f5b73544

2024-10-17 08:19 UTC, NadavTasher commented
This PR breaks users synced with LDAP - if their username begins with a number (i.e 1234username) a new username is randomized on every LDAP sync, making it impossible to mention these users in posts.