MM-54558 SSO code challenge verification
mattermost/mattermost pull request #24734
Opened 2023-10-06 08:44 UTC by enahum

#### Summary
When using the mobile app to login using SSO, previously the Session Token and CSRF Token were included in the callback uri once the login was successful.

This is now mitigated by sending a random token so that we can then execute an additional request with the generated server token and the client verification code so that only the client that initiated the flow can have access to the session and csrf tokens, very similar to the pattern of PKCE for OAuth.

The way this works is:
1. The client generates a code verification string
2. the code verification gets hash and encoded then sent in the login request that opens on the browser as a `code_challenge` parameter in the query string
3. code challenge is stored in the DB as the extra field while generating a temporary token
4. temporary token code_challenge_token is set in the state of the SSO request as we initiate the login flow
5. Once the login is successful, we retrieve the DB record with the temporary token that is in the state and update the record with the session and crsf tokens
6. redirect back to the mobile application with the temporary token
7. the mobile application now initiates another request that includes the temporary token and the code verification string generated on step 1
8. server retrieves the record from the DB that matches the temporary token and encodes and hash the verification code and determines if it matches the code challenge stored in the record
9. if the verification is successful, the session and crsf tokens are return in the body of the response
10. mobile app uses the session and crsf tokens from this moment on

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54558

#### Release Note

```release-note
Added code challenge verification for SSO login initiated from the mobile app
```

2023-10-10 10:58 UTC, jupenur requested changes

2023-10-10 10:58 UTC, jupenur commented on server/channels/app/sso.go
> +	if codeChallenge != extraMap["code_challenge"] {
`crypto/subtle.ConstantTimeCompare`?

2023-10-10 10:58 UTC, jupenur commented on server/channels/app/sso.go
> +	token, err := a.Srv().Store().Token().GetByToken(codeChallengeToken)
The token type must be checked before making any updates, otherwise it could be any kind of token

2023-10-10 10:58 UTC, jupenur commented on server/channels/app/sso.go
> +	token, err := a.Srv().Store().Token().GetByToken(codeChallengeToken)
Token type should be checked here as well.

2023-10-10 10:58 UTC, jupenur commented on server/channels/web/saml.go
> +	codeChallenge := html.EscapeString(r.URL.Query().Get("code_challenge"))
Why the HTML escaping?

2023-10-10 10:58 UTC, jupenur commented on server/channels/app/oauth.go
> +func (a *App) GetOAuthLoginEndpoint(w http.ResponseWriter, r *http.Request, service, teamID, action, redirectTo, loginHint string, isMobile bool, desktopToken, codeChallenge string) (string, *model.A
Confusing naming here. Shouldn't this be the `codeChallengeToken` and not the `codeChallenge`?

2023-10-10 11:48 UTC, enahum commented on server/channels/web/saml.go
> +	codeChallenge := html.EscapeString(r.URL.Query().Get("code_challenge"))
no need really..

2023-10-10 13:41 UTC, jupenur reviewed
Just a quick comment; I'll do another proper round of reviews once the mobile PR is also ready.

And could we also get a dev reviewer for this? I'd assign someone myself but I'm not sure who that should be.

2023-10-10 13:41 UTC, jupenur commented on server/channels/app/sso.go
> +	token := model.NewToken("pkce", string(extraProps))
3/5 I think we should get rid of the references to PKCE because this really has very little to do with PKCE even if it is PKCE-inspired.

2023-10-10 13:43 UTC, enahum commented
> Just a quick comment; I'll do another proper round of reviews once the mobile PR is also ready.
> 
> 
> 
> And could we also get a dev reviewer for this? I'd assign someone myself but I'm not sure who that should be.

Added @mgdelacroix mobile PR is also up to date

2023-11-01 21:44 UTC, enahum commented
Closing as won't accept

2023-11-01 21:44 UTC, closed without merging