[MM-54794] Convert `./components/widgets/icons/fa_next_icon.tsx` to function component
mattermost/mattermost pull request #24785
Opened 2023-10-06 18:51 UTC by fyfirman

#### Summary
Convert `./components/widgets/icons/fa_next_icon.tsx` to function component. I also update the snapshot result since it has different behaviour.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/24758
Jira [MM-54794](https://mattermost.atlassian.net/browse/MM-54794)

#### Screenshots
![image](https://github.com/mattermost/mattermost/assets/37064641/2e17b775-2bdb-4fd2-8bda-2147debdd116)
Example place in Emoji List

#### Release Note

```release-note
NONE
```

2023-10-06 18:51 UTC, mattermost-build commented
Hello @fyfirman,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-06 19:48 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-07 11:58 UTC, larkox requested changes
Great again. And again the same three changes :sweat_smile:

2023-10-07 11:58 UTC, larkox commented on webapp/channels/src/components/widgets/icons/fa_next_icon.tsx
> +function NextIcon(props: Props) {
Again, the same changes as in https://github.com/mattermost/mattermost/pull/24787

2023-10-07 17:20 UTC, fyfirman commented
I just fixed it @larkox , thanks for the feedback.

2023-10-09 11:09 UTC, larkox approved these changes

2023-10-10 14:18 UTC, devinbinnie approved these changes
LGTM! Thanks @fyfirman!

2023-10-10 15:34 UTC, yasserfaraazkhan commented
/e2e-test

2023-10-10 15:34 UTC, yasserfaraazkhan commented
/e2e-tests

2023-10-14 13:04 UTC, varghesejose2020 commented
@lindy65 I would like to test this PR as a QA.

2023-10-16 06:39 UTC, lindy65 commented
Thanks @varghesejose2020 🎉 

Log into the test server above using the sysadmin credentials

![image](https://github.com/mattermost/mattermost/assets/13020833/14c5640d-4ac5-4cb3-ad8a-d1dfcbd172cc)

- Go to the system console from Main Menu (grid icon) > Authentication > AD/LDAP
- Change `Synchronization Interval (minutes):` setting and check that it Saves without error
- Then click on `AD/LDAP Synchronize Now` and check that the process completes without error

2023-10-16 06:43 UTC, lindy65 commented
Thanks @varghesejose2020 🎉 

- Log into the test server above using the sysadmin credentials
- From the Main Menu (grid icon) select Integrations
- Then select Custom Emoji
- Create a custom emoji and check that it saves correctly
- Go back to channels and make a post using the emoji you created

2023-10-16 17:06 UTC, varghesejose2020 commented
I tested the changes on the Test Server and it LGTM.
![image](https://github.com/mattermost/mattermost/assets/71702982/758d26f8-76fc-45a7-87a7-0a3cdbfba31b)
![image](https://github.com/mattermost/mattermost/assets/71702982/0dc70f14-b0ea-46a1-8de2-ec0c24e084c4)
created a custom emoji and it posted on channel and it working as expected

2023-10-17 10:13 UTC, lindy65 approved these changes
Thanks @fyfirman - looks good to merge 👍 

Thanks for testing @varghesejose2020 🎉

2023-10-17 10:49 UTC, merged

2023-10-17 10:49 UTC, larkox commented
Thanks for the contribution!