[MM-54795] Convert `./components/widgets/icons/fa_previous_icon.tsx` to function component
mattermost/mattermost pull request #24786
Opened 2023-10-06 19:25 UTC by fyfirman

#### Summary
Convert `./components/widgets/icons/fa_previous_icon.tsx` to function component. I also update the snapshot result since it has different behaviour.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/24759
Jira [MM-54795](https://mattermost.atlassian.net/browse/MM-54795)

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-10-06 19:25 UTC, mattermost-build commented
Hello @fyfirman,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-06 19:48 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-07 11:56 UTC, larkox requested changes
Great work! It would be great if you could address the same stuff I noted in a different PR. The components are really similar and should be handled in a similar way too :smile:

2023-10-07 11:56 UTC, larkox commented on webapp/channels/src/components/widgets/icons/fa_previous_icon.tsx
> +function PreviousIcon(props: Props) {
Exactly the same 3 comments I gave you on https://github.com/mattermost/mattermost/pull/24787

2023-10-07 17:19 UTC, fyfirman commented
I just fixed it @larkox , thanks for the feedback.

2023-10-09 15:37 UTC, larkox approved these changes
Great work. Thanks!

2023-10-10 17:20 UTC, hmhealey approved these changes
Looks great! Thanks for the PR and for helping us move to `defineMessage` as well 🙂

2023-10-10 17:21 UTC, merged

2023-10-10 17:21 UTC, hmhealey commented
Skipping QA review since there's not really any functionality to test here