migrate DropdownSetting component from class based to function based component
mattermost/mattermost pull request #24796
Opened 2023-10-07 06:22 UTC by tanmaythole

#### Summary

Migrate `DropdownSetting` component from class based to function based component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24750

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-10-07 06:22 UTC, mattermost-build commented
Hello @tanmaythole,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-07 07:47 UTC, jespino commented on webapp/channels/src/components/admin_console/dropdown_setting.tsx
> +    const handleChange = (e: ChangeEvent<HTMLSelectElement>) => {
Can we put this in a `useCallback`?

2023-10-07 07:48 UTC, jespino commented on webapp/channels/src/components/admin_console/dropdown_setting.tsx
> +    const options = useMemo(() =>
Nice improvement! :)

2023-10-07 07:49 UTC, jespino requested changes
I tiny improvement suggestion, but it looks great. Thanks @tanmaythole! :fireworks:

2023-10-07 08:05 UTC, tanmaythole commented on webapp/channels/src/components/admin_console/dropdown_setting.tsx
> +    const handleChange = (e: ChangeEvent<HTMLSelectElement>) => {
👍🏻

2023-10-07 08:13 UTC, jespino commented on webapp/channels/src/components/admin_console/dropdown_setting.tsx
> +const DropdownSetting: FC<Props> = ({
Nice!

2023-10-07 08:13 UTC, jespino approved these changes
Now looks good to me! Thanks @tanmaythole! :notes:

2023-10-07 11:21 UTC, larkox approved these changes
LGTM! Just a minor nitpick. Approving so we can move into QA, but it would be great if you could change it :smile:

2023-10-07 11:21 UTC, larkox commented on webapp/channels/src/components/admin_console/dropdown_setting.tsx
> +const DropdownSetting: FC<Props> = ({
The explicit type definition should not be needed. You can do something like `const Component = ({...}:Props) => {...}`.

2023-10-07 11:23 UTC, larkox commented
@tanmaythole There seem to be some problems with the tests. Just some snapshots not passing. It should be solved by running `npm run test -- -u -- path/to/test/file.test.ts` in the channels folder.

Here the details: https://github.com/mattermost/mattermost/actions/runs/6439967230/job/17488367246?pr=24796

2023-10-07 11:23 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-09 10:40 UTC, larkox commented
/update-branch

2023-10-18 08:04 UTC, lindy65 commented
/update-branch

2023-10-19 09:14 UTC, lindy65 approved these changes
Thanks @tanmaythole - looks good to me 👍 

cc @larkox

2023-10-19 10:09 UTC, larkox commented
/e2e-test

2023-10-19 10:09 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/379834) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/379834)

2023-10-19 10:58 UTC, merged

2023-10-19 10:58 UTC, larkox commented
Thank you for the contribution!