convert EmojiIcon component from class based to function based component
mattermost/mattermost pull request #24792
Opened 2023-10-07 05:48 UTC by tanmaythole

#### Summary

This PR converts the EmojiIcon component from class based component to functional based component

#### Ticket Link

https://github.com/mattermost/mattermost/issues/24753

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-10-07 05:48 UTC, mattermost-build commented
Hello @tanmaythole,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-07 07:43 UTC, jespino approved these changes
It looks good to me. Thanks @tanmaythole! :partying_face:

2023-10-07 11:39 UTC, larkox approved these changes
LGTM! Just the same minor thing I have flagged in a few of your PRs.

2023-10-07 11:39 UTC, larkox commented on webapp/channels/src/components/widgets/icons/emoji_icon.tsx
> +const EmojiIcon: FC<React.HTMLAttributes<HTMLSpanElement>> = (props) => {
The explicit typing is not needed (i.e. `FC<...>`). You can move the props types inside the parenthesis and should be enough.

2023-10-07 11:39 UTC, larkox commented
/update-branch

2023-10-07 11:40 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-08 08:10 UTC, jespino commented on webapp/channels/src/components/widgets/icons/emoji_icon.tsx
> +export default EmojiIcon;
The component was a `PureComponent` so we need to wrap it in a `React.memo` call here:
```suggestion
export default React.memo(EmojiIcon);
```

2023-10-08 08:11 UTC, jespino requested changes
A tiny improvement needed.

2023-10-08 08:56 UTC, jespino approved these changes
No looks good to me. Thanks @tanmaythole! :tada:

Take into account that the `React.memo` change can break the tests.

2023-10-12 14:07 UTC, coltoneshaw commented
@lindy65 - I'll take QA here based on [your post](https://community.mattermost.com/core/pl/f8ug44zcft8mbkrda16niscygh).

2023-10-14 08:20 UTC, lindy65 commented
Thanks @coltoneshaw 👍 

@larkox - please run E2E tests on this PR

2023-10-16 08:40 UTC, larkox commented
/e2e-test

2023-10-16 08:40 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/378591) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/378591)

2023-10-16 09:30 UTC, larkox commented
@lindy65 e2e tests seem to be failing on non-related tests only. This should be good to merge.

2023-10-16 15:00 UTC, lindy65 approved these changes
Thanks @tanmaythole - looks good to me 👍 

Thanks for QA-ing @coltoneshaw :)

cc @larkox

2023-10-16 15:05 UTC, merged