Mm 54799/convert menu header to func comp
mattermost/mattermost pull request #24799
Opened 2023-10-07 07:56 UTC by dipandhali2021

#### Summary
This PR converts the MenuHeader component from class based component to functional based component

#### Ticket Link
Fixes #24763

#### Screenshots

#### Release Note

```
NONE
```

2023-10-07 07:56 UTC, mattermost-build commented
Hello @dipandhali2021,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-10-07 08:07 UTC, jespino commented on webapp/channels/src/components/widgets/menu/menu_header.tsx
> +const MenuHeader: React.FC<Props> = ({ children, onClick }) => {
nit: It is more consistent with the examples to use directly the Props type in the parameters directly, something like:
```suggestion
const MenuHeader = ({ children, onClick }: Props) => {
```

2023-10-07 08:07 UTC, jespino commented on webapp/channels/src/components/widgets/menu/menu_header.tsx
> +export default MenuHeader;
It was a pure component so it is expected to have here a `React.memo` to make it memoized.
```suggestion
export default React.memo(MenuHeader);
```

2023-10-07 08:08 UTC, jespino requested changes
A couple of improvements needed, but in general looks good to me. Thanks @dipandhali2021! :sparkles:

2023-10-07 09:21 UTC, dipandhali2021 commented
Hey, @jespino .Thanks for reviewing the PR and suggestions. I have committed new changes and suggestion.

2023-10-07 11:12 UTC, larkox commented
@dipandhali2021 Have you signed the CLA? You can see in this comment the details: https://github.com/mattermost/mattermost/pull/24799#issuecomment-1751642447

2023-10-07 11:12 UTC, larkox approved these changes

2023-10-07 11:13 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-07 11:57 UTC, dipandhali2021 commented
/check-cla

2023-10-07 12:02 UTC, larkox commented
@dipandhali2021 You can see in the checks on the PR that there are a few test and linter errors. The linter errors can be almost sure auto fixed, so you just have to run `npm run fix` in the channels folder. Also, the tests seem to be just snapshot tests, so you should be able to fix those running `npm run test -- -u -- path/to/test/file.test.tsx`

2023-10-07 18:55 UTC, closed without merging

2023-10-09 11:13 UTC, dipandhali2021 commented
Hey, @larkox . I am sorry to close this PR. Previously I didn't setup properly mattermost locally due to which `npm run fix` was not working. But now I have setup mattermost properly. I will submit the PR by today only. 
Sorry for the inconvenience provided.

2023-10-09 11:14 UTC, larkox commented
No problem at all :smile: Just wanted to make sure if you dropped working on it so we could get the ticket back to up for grabs. But if you plan to keep working on it, all is fine :smile: