#24774 Converted ./plugins/rhs_plugin/rhs_plugin.tsx to Function Component
mattermost/mattermost pull request #24802
Opened 2023-10-07 10:12 UTC by balajik

#### Summary

In this PR, converted the RhsPlugin component from class component to functional component.

#### Ticket Link

Fixed #24774
Jira ticket: https://mattermost.atlassian.net/browse/MM-54811

#### Release Note

```release-note
Converted RhsPlugin component to functional component
```

2023-10-07 10:12 UTC, mattermost-build commented
Hello @balajik,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-07 10:54 UTC, larkox approved these changes
LGTM, just one small change.

2023-10-07 10:54 UTC, larkox commented on webapp/channels/src/plugins/rhs_plugin/rhs_plugin.tsx
> +const RhsPlugin: React.FC<Props> = ({ showPluggable, pluggableId, title }) => {
The explicit typing is not needed.

2023-10-07 10:56 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-07 11:10 UTC, larkox commented on webapp/channels/src/plugins/rhs_plugin/rhs_plugin.tsx
> +const RhsPlugin: React.FC<Props> = ({ showPluggable, pluggableId, title }) => {
Yes. You can leave it just like this:
```suggestion
const RhsPlugin = ({ showPluggable, pluggableId, title }) => {
```

2023-10-08 08:08 UTC, jespino commented on webapp/channels/src/plugins/rhs_plugin/rhs_plugin.tsx
> +export default RhsPlugin;
It was a `PureComponent`, so we need `React.memo` here to avoid re-renders.
```suggestion
export default React.memo(RhsPlugin);
```

2023-10-08 08:08 UTC, jespino requested changes
I tiny improvement needed.

2023-10-08 08:29 UTC, jespino approved these changes
Nice! Thanks @balajik! :partying_face:

2023-10-09 10:59 UTC, larkox commented
@balajik Tests are failing, probably due to snapshots not being updated. You can update them by running `npm run test -- -u -- file/to/test/file.test.ts` on the channels folder.

2023-10-09 11:36 UTC, larkox commented
@balajik I just checked the tests, and they seem to be unrelated to the PR. Sorry about that.

I will check internally and see if those tests can get fixed in master.

2023-10-16 09:12 UTC, larkox commented
This is now on QA phase. @lindy65 will take care of that, but please be patient. :smile:

2023-10-16 15:59 UTC, lindy65 approved these changes
Thanks @balajik - looks good 👍 

cc @larkox

2023-10-16 16:00 UTC, lindy65 commented
Please run E2E tests on this PR @larkox - thanks!

2023-10-16 16:17 UTC, larkox commented
/e2e-test

2023-10-16 16:17 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/378914) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/378914)

2023-10-17 08:42 UTC, larkox commented
@lindy65 There are a few tests failing on e2e, but seem to be unrelated. Merging this.

2023-10-17 08:43 UTC, merged

2023-10-17 08:43 UTC, larkox commented
@balajik Thank you for your contribution!