Update loading_spinner.tsx from class based to functional based
mattermost/mattermost pull request #24813
Opened 2023-10-07 20:25 UTC by Krishnakalani111

#### Summary
Converted ./components/widgets/loading/loading_spinner.tsx from Class Component to Function Component #24771

#### Ticket Link
Fixes #24771 

#### Screenshots

#### Release Note

```release-note
Converted ./components/widgets/loading/loading_spinner.tsx from Class Component to Function Component #24771
```

2023-10-07 20:25 UTC, mattermost-build commented
Hello @Krishnakalani111,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-08 07:58 UTC, jespino commented on webapp/channels/src/components/widgets/loading/loading_spinner.tsx
> +const LoadingSpinner: React.FC<Props> = React.memo(({text, style}) => {
nit: We normally put the `React.memo` at the export line, leave it cleaner.

2023-10-08 07:59 UTC, jespino commented on webapp/channels/src/components/widgets/loading/loading_spinner.tsx
> +LoadingSpinner.defaultProps = {
The `defaultProps` is not the recomended approach for functional components, is prefered to use the default value for parameters, something like: `const LoadingSpinner: React.FC<Props> = ({text = null, style}) => {`

2023-10-08 08:00 UTC, jespino requested changes
A couple of comments, but otherwise looks good to me. Thanks @Krishnakalani111! :woman_dancing:

2023-10-08 08:03 UTC, Krishnakalani111 commented
Ok I will do the require changes👍

2023-10-08 14:51 UTC, Krishnakalani111 commented
I have done the required changes please review it.

2023-10-09 07:23 UTC, jespino approved these changes
Nice! Thanks @Krishnakalani111! :tada:

2023-10-09 07:39 UTC, larkox requested changes
Thank you for the contribution! A few minor changes out of the scope, I hope you don't mind.

2023-10-09 07:39 UTC, larkox commented on webapp/channels/src/components/widgets/loading/loading_spinner.tsx
> +const LoadingSpinner: React.FC<Props> = ({ text = null, style }) => {
There is no need for the explicit typing. We prefer to have this as:
```
const ComponentName = ({
   prop1,
   ...
}: Props) => {
```

2023-10-09 07:39 UTC, larkox commented on webapp/channels/src/components/widgets/loading/loading_spinner.tsx
> +            className={'LoadingSpinner' + (text ? ' with-text' : '')}
Out of the scope, but do you mind using `classNames` for this? You should be able to do something like this:
```suggestion
            className={classNames('LoadingSpinner', {'with-text': Boolean(text)})}
```

2023-10-09 07:39 UTC, larkox commented on webapp/channels/src/components/widgets/loading/loading_spinner.tsx
> +                title={{ id: t('generic_icons.loading'), defaultMessage: 'Loading Icon' }}
We want to get rid of the `t` function, so do you mind moving this outside of the component and define it with defineMessage?

Something like...

```
const IconTitle = defineMessage({id: 'generic_icons.loading', defaultMessage: 'Loading Icon'});
const LoadingSpinner: React.FC<Props> = ({ text = null, style }) => {
    ...
        title={IconTitle}
```
The other good thing about this is that you only define the string once, so you always pass the same object to the icon, avoiding potential re-renders down the line, and you put less strain in the GC, having to clean up the old message after every re-render.

2023-10-09 07:40 UTC, larkox commented
@Krishnakalani111 Also, see that there are a few lint and types errors in the checks. You should fix those too. Running `npm run fix` in the channels folder should fix most of the lint issues, and `npm run check-types` should let you know about the types errors.

2023-10-20 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-10-20 08:15 UTC, larkox commented
@Krishnakalani111 Is this something you are still working on?

2023-12-06 07:34 UTC, closed without merging