[MM-24823] Convert LocalizedInput of 'emoji_list.tsx' to regular input component
mattermost/mattermost pull request #24839
Opened 2023-10-09 13:47 UTC by Kritik-J

Summary

Replaces the 'LocalizedInput' component in webapp/channels/src/components/password_reset_form/password_reset_form.tsx' to a regular input component

#### Ticket Link

Fixes: #24823 

#### Release Note

```release-note
NONE
```

2023-10-09 13:47 UTC, mattermost-build commented
Hello @Kritik-J,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-09 13:56 UTC, M-ZubairAhmed requested changes

2023-10-09 13:56 UTC, M-ZubairAhmed commented on webapp/channels/src/components/password_reset_form/password_reset_form.tsx
> +export default memo(injectIntl(PasswordResetForm));
Since this is a functional component you can directly use the hook https://formatjs.io/docs/react-intl/api/#useintl-hook

2023-10-09 13:56 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-09 14:58 UTC, M-ZubairAhmed requested changes
Looks good, just some minor nits to keep in scope of the PR 😉

2023-10-09 14:58 UTC, M-ZubairAhmed commented on webapp/channels/src/components/password_reset_form/password_reset_form.tsx
> +        ) => Promise<{ data: any; error: ServerError }>;
can you please revert this unrelated formatting

2023-10-09 14:58 UTC, M-ZubairAhmed commented on webapp/channels/src/components/password_reset_form/password_reset_form.tsx
> +        const token = new URLSearchParams(location.search).get('token');
please revert this as well

2023-10-09 14:58 UTC, M-ZubairAhmed commented on webapp/channels/src/components/password_reset_form/password_reset_form.tsx
> +        );
this as well

2023-10-09 14:58 UTC, M-ZubairAhmed commented on webapp/channels/src/components/password_reset_form/password_reset_form.tsx
> +            <label className='control-label'>{error}</label>
this

2023-10-09 14:58 UTC, M-ZubairAhmed commented on webapp/channels/src/components/password_reset_form/password_reset_form.tsx
> +                    >
this as well

2023-10-09 16:34 UTC, M-ZubairAhmed approved these changes
Amazing thank you for doing this issue :D

2023-10-10 08:23 UTC, jespino approved these changes
Nice! Thanks @Kritik-J! :partying_face:

2023-10-10 08:24 UTC, jespino commented
@Kritik-J The test snapshoots needs to be tested, you can fix it running `npm run test -- -u` in the `webapp/channels` directory.

2023-10-10 16:26 UTC, M-ZubairAhmed commented
/update-branch

2023-10-11 06:10 UTC, merged