[GH-24833] Converted LocalizedInput of system_users.tsx to regular in…
mattermost/mattermost pull request #24858
Opened 2023-10-10 09:00 UTC by harsh-solanki21

#### Summary

Converted `LocalizedInput ` component in  'system_users.tsx' to regular `input` component and removed unused imported components.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24833

#### Release Note

```
NONE
```

2023-10-10 12:35 UTC, M-ZubairAhmed requested changes

2023-10-10 12:35 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_users/system_users.tsx
> +                        placeholder={searchUsersPlaceholder}
please add the translation inline here instead of declaring a new variable

2023-10-10 12:35 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_users/system_users.tsx
> +        const searchUsersPlaceholder = Utils.localizeMessage('filtered_user_list.search', 'AD/LDAP ID') || 'Search users';
please refer to https://github.com/mattermost/mattermost/pull/24818

2023-10-10 12:38 UTC, M-ZubairAhmed commented
please sign the CLA https://github.com/mattermost/mattermost/pull/24858#issuecomment-1754763860

2023-10-10 17:16 UTC, harsh-solanki21 commented
/check-cla

2023-10-11 06:47 UTC, M-ZubairAhmed requested changes

2023-10-11 06:47 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_users/system_users.tsx
> -import LocalizedInput from 'components/localized_input/localized_input';
t import should also be removed, since we removed its usage

2023-10-11 06:47 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_users/system_users.tsx
> +                        placeholder={this.props.intl.formatMessage({id: t('filtered_user_list.search'), defaultMessage: 'Search users'})}
I dont think props has intl object because we didn't wrap this component with `injectIntl`

2023-10-11 06:47 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_users/system_users.tsx
> +     */
nit : this is self explanatory so we can remove this comment for this prop

2023-10-11 07:31 UTC, harsh-solanki21 commented
@M-ZubairAhmed made suggested changes. Let me know if anything is still not up to the mark. Really appreciate your guidance 🙏

2023-10-11 07:31 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-11 07:35 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed made suggested changes. Let me know if anything is still not up to the mark. Really appreciate your guidance 🙏

Thank you this took a really good shape, Lets wait for the CI to turn green, if it didn't please check the which CI step failed and rectify. Please let me know if you need any help with that

2023-10-11 07:44 UTC, M-ZubairAhmed commented
@harsh-solanki21 please check the test for this component `system_users.test.tsx` for type errors

2023-10-11 11:22 UTC, harsh-solanki21 commented
@M-ZubairAhmed I've tried everything but snapshot tests are failing for `system_user.test.tsx` file.
Would you please guide me on this!

2023-10-11 13:27 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed I've tried everything but snapshot tests are failing for `system_user.test.tsx` file. Would you please guide me on this!

Thank you for reaching out, I know the solution but i want you to figure out the solution and i will guide you.

- First since we wrapped the component with `injectIntl` we have to use `shallowWithIntl` instead of `shallow`
- the part you did `export {SystemUsers as RawSystemUsers};` was spot on, and we need to type assert the instance foribly to that `const instance = wrapper.instance() as RawSystemUsers;` then the actions of the component will get type resolved.

Its might take a while to figure this out but you got this 💪🏽

2023-10-11 18:11 UTC, harsh-solanki21 commented
@M-ZubairAhmed Hey, I was close but wouldn't do it without your guidance 😄
Tested locally and it is passing all the test cases 👍
Really appreciate your efforts and thanks a lot for your guidance and help 🚀

2023-10-12 04:30 UTC, M-ZubairAhmed requested changes
This is amazing work thank you. Just a small nit

2023-10-12 04:30 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_users/system_users.test.tsx
> +        await instance.loadDataForTeam(SearchUserTeamFilter.ALL_USERS, '');
🎉

2023-10-12 04:30 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_users/system_users.test.tsx
> +import type {SystemUsers as RawSystemUsers} from './system_users';
nit : lets calls this SystemUserClass

2023-10-12 04:57 UTC, harsh-solanki21 commented on webapp/channels/src/components/admin_console/system_users/system_users.test.tsx
> +import type {SystemUsers as RawSystemUsers} from './system_users';
done 👍

2023-10-12 10:46 UTC, M-ZubairAhmed approved these changes
Impressive work 🚀

2023-10-16 07:46 UTC, yasserfaraazkhan approved these changes
the user search is working as expected.

2023-10-16 10:41 UTC, M-ZubairAhmed commented
@jespino gentle ping on this one

2023-10-17 03:43 UTC, harshilsharma63 approved these changes

2023-10-17 09:28 UTC, merged