Fix mark as unread on GMs
mattermost/mattermost pull request #24880
Opened 2023-10-11 13:05 UTC by larkox

#### Summary
When we mark as unread the GMs, we don't get the number badges, unlike DMs.

This is because we missed a change on the "GM as DM" PR, in particular, the part that counts the number of mentions in a channel after marking it as unread.

Considering the groups messages there is enough.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-54778

#### Release Note
If it reaches the same version as the "GM as DM" PR, no release note needed
```release-note
Fix issue where marking as unread a GM won't show the mention badges correctly.
```

2023-10-11 13:05 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-11 13:36 UTC, larkox commented
/update-branch

2023-10-11 21:12 UTC, hmhealey approved these changes

2023-10-12 04:43 UTC, harshilsharma63 approved these changes

2023-10-12 04:43 UTC, harshilsharma63 commented
No tests needed?

2023-10-16 08:02 UTC, yasserfaraazkhan approved these changes
after marking as unread, the badge shows correct numbered notification badge.

2023-10-16 11:33 UTC, larkox commented
Re-requesting review since I have changed the behavior of the way we get the mentions, and may have bigger implications.

2023-10-17 16:09 UTC, hmhealey requested changes

2023-10-17 16:09 UTC, hmhealey commented on server/channels/store/sqlstore/channel_store.go
> -		query = query.Where(sq.Eq{"UserId": userId})
Would you mind renaming this parameter to something like `excludeUserId` that makes it clearer that this works opposite to how it did before?

2023-10-17 16:09 UTC, hmhealey commented on server/channels/store/sqlstore/channel_store.go
> -		query = query.Where(sq.Eq{"Posts.UserId": userId})
Same here

2023-10-18 05:00 UTC, harshilsharma63 approved these changes

2023-10-18 08:22 UTC, larkox commented
@agarciamontoro Adding you as reviewer since I am changing how some things work on the server side, and just verify I am not missing anything in terms of performance and such.

This is a "rare" action (mark a channel as unread) so there should be not many performance implications, but better safe than sorry.

2023-10-19 13:50 UTC, hmhealey approved these changes

2023-10-23 10:31 UTC, agarciamontoro approved these changes
Changes look good, thanks!

First a nit: The same change `userID` > `excludedUserID` you did in the declaration of `CountPostsAfter` should also be done in the definition of `CountPostsAfter` and in the declaration and definition of `CountUrgentPostsAfter`.

Now on the performance side of things: I don't foresee any impact from this change, given that the query is triggered by a not so common user action, and usually with a fairly small number of posts. It is safe to merge without a load-test.

2023-10-23 10:48 UTC, larkox commented
@yasserfaraazkhan Make sure when testing that your own posts do not contribute to the badge number.

Also, make sure the DMs and Urgent feature also work as it should.

2023-10-23 10:53 UTC, larkox commented
/update-branch

2023-10-24 10:42 UTC, larkox commented
/update-branch

2023-10-24 13:24 UTC, larkox commented
@yasserfaraazkhan Finally the server is updated and the checks are green, so... this is ready to test :smile:

2023-10-24 13:25 UTC, yasserfaraazkhan approved these changes
thank you @larkox the badge does not include logged in users posts.

<img width="500" alt="Screenshot 2023-10-24 at 6 53 01 PM" src="https://github.com/mattermost/mattermost/assets/15979783/3cc1701a-5063-45a2-ab57-9c5258c49324">
 

<img width="500" alt="Screenshot 2023-10-24 at 6 53 06 PM" src="https://github.com/mattermost/mattermost/assets/15979783/9f083470-0c34-4b66-a467-779936fe3084">

<img width="432" alt="image" src="https://github.com/mattermost/mattermost/assets/15979783/0f766685-b918-40d0-ba31-d2c6aca9eb3b">

2023-10-24 13:27 UTC, merged