We move mmctl CI tests to free tier
mattermost/mattermost pull request #24899
Opened 2023-10-12 09:20 UTC by agnivade

Only the -race tests in master branch takes
more memory. Going to test and see.

```release-note
NONE
```

2023-10-12 09:54 UTC, toninis requested changes

2023-10-12 09:54 UTC, toninis commented on .github/workflows/mmctl-test-template.yml
> -    runs-on: ubuntu-latest-8-cores
```
runs-on: ubuntu-22.04
```

2023-10-13 08:37 UTC, agnivade commented
All tested and works fine.

2023-10-13 08:37 UTC, toninis approved these changes

2023-10-13 15:39 UTC, merged