chore: migrate user_grid_remove to fun. component
mattermost/mattermost pull request #24912
Opened 2023-10-12 22:09 UTC by sp6370

#### Summary
This pull request migrates the existing user_grid_remove component to a react functional component. The component is primarily used in the Admin Console. 

One of the locations where the component is used: `admin_console/team_channel_settings/team/details/team_members/team_members.tsx`

#### Ticket Link
Github Issue: https://github.com/mattermost/mattermost/issues/24778
Jira: https://mattermost.atlassian.net/browse/MM-54817

#### Screenshots
1. Test passing for parent component (No specific test exist for the migrated component).
![image](https://github.com/mattermost/mattermost/assets/26037101/64789407-aac6-40b9-bace-10f4579b3c01)

2. No specific UI changes. Adding component image here to make it easier for QA.
![Screenshot from 2023-10-12 17-59-47](https://github.com/mattermost/mattermost/assets/26037101/821882a2-bbce-4ff4-8282-067cfa537312)

The specific component is the remove button on bottom right side of the image.

#### Release Note
```
None
```

PS: Special thanks to @sinansonmez and @M-ZubairAhmed for helping me with my first issue.

2023-10-12 22:09 UTC, mattermost-build commented
Hello @sp6370,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-13 10:17 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-13 10:20 UTC, larkox requested changes
Thank you for your contribution! Just one small change. The second comment you can ignore.

2023-10-13 19:05 UTC, sinansonmez approved these changes
Apart from @larkox comments LGTM 🚀

2023-10-17 04:48 UTC, sp6370 commented on webapp/channels/src/components/admin_console/user_grid/user_grid_remove.tsx
> +    const handleClick = (e: React.MouseEvent<HTMLAnchorElement>) => {
Got it! I am leaving it as it is!

2023-10-17 04:49 UTC, sp6370 commented on webapp/channels/src/components/admin_console/user_grid/user_grid_remove.tsx
> +    const {user, removeUser, isDisabled} = props;
I have addressed your suggestion. Please mark the conversation resolved, if it looks good.

2023-10-17 07:32 UTC, larkox approved these changes

2023-10-18 07:51 UTC, larkox commented
/update-branch

2023-10-18 21:21 UTC, sinansonmez approved these changes
LGTM 🚀

2023-10-19 16:23 UTC, varghesejose2020 commented
@lindy65 I would like to test this PR as a QA.

2023-10-19 16:47 UTC, lindy65 commented
/update-branch

2023-10-20 06:30 UTC, lindy65 commented
@varghesejose2020 - test server is ready

Log in to the test server using sysadmin credentials and go to the system console.  The component you're testing is explained below (from the contributor's summary at the top of this PR)

> 2. No specific UI changes. Adding component image here to make it easier for QA.
>    ![Screenshot from 2023-10-12 17-59-47](https://user-images.githubusercontent.com/26037101/274743272-821882a2-bbce-4ff4-8282-067cfa537312.png)
> 
> **The specific component is the remove button on bottom right side of the image.**

Let me know if you have any questions!

2023-10-21 08:16 UTC, varghesejose2020 commented
@lindy65 I tested the changes on the Test Server and it LGTM.
![teamconf](https://github.com/mattermost/mattermost/assets/71702982/a1c29830-bd09-4b0c-b3cc-bf14257f7951)
Tested the Remove button on bottom right side .it working as expected

2023-10-21 08:32 UTC, lindy65 approved these changes
Thanks @sp6370 - looks good 👍 

Thanks for QA'ing @varghesejose2020 🎉

2023-10-23 10:32 UTC, larkox commented
/e2e-test

2023-10-23 10:32 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/380938) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/380938)

2023-10-24 10:42 UTC, larkox commented
/e2e-test

2023-10-30 11:18 UTC, merged

2023-10-30 11:18 UTC, larkox commented
Thank you for the contribution!