[GH-24779]
mattermost/mattermost pull request #24939
Opened 2023-10-14 05:12 UTC by escofresco

#### Summary
Refactors SystemPermissionGate class to function. Tested by running 

Referenced [blog post on refactoring Default Props](https://blog.bitsrc.io/understanding-react-default-props-5c50401ed37d)
#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/24779
Jira https://mattermost.atlassian.net/browse/MM-54818

#### Release Note
```release-note
NONE
```

2023-10-14 05:12 UTC, mattermost-build commented
Hello @escofresco,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-16 08:41 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-16 08:45 UTC, larkox requested changes
Thank you for the contribution! Just a few minor style changes.

2023-10-16 08:45 UTC, larkox commented on webapp/channels/src/components/permissions_gates/system_permission_gate/system_permission_gate.tsx
> +export default function SystemPermissionGate(props: Props) {
Just for consistency, we prefer to have arrow functions and the export separated at the end. i.e.:
```
const SystemPermissionGate = (props: Props) => {
   ...
}
export default SystemPermissionGate;

2023-10-16 08:45 UTC, larkox commented on webapp/channels/src/components/permissions_gates/system_permission_gate/system_permission_gate.tsx
> +SystemPermissionGate.defaultProps = {
For function components, you wouldn't use defaultProps. The most common approach we use is to expand the props on the function and assign there the default. In this case...

```
const SystemPermissionGate = ({
   permissions,
   hasPermissions,
   invert = false,
   children, 
}: Props) => {
```

2023-10-16 19:49 UTC, sinansonmez approved these changes
LGTM 🚀 thanks

2023-10-17 08:12 UTC, larkox approved these changes
LGTM. Thanks!

2023-10-17 08:44 UTC, larkox commented
@escofresco There seem to be some issues with lint and types. You can see the details in the checks. Let me know if you have any problem fixing those.

2023-10-19 11:08 UTC, larkox commented
@escofresco There seem to be still some errors around lint, types and tests. Can you take a look at them?

2023-10-19 22:57 UTC, escofresco commented
Will investigate right now

2023-10-20 15:12 UTC, escofresco commented
@larkox Style issues should be fixed now, runs fine locally, also combined
```typescript   
if (hasPermission && !invert) {
    …
}
if (!hasPermission && invert) {
    …
}
```
into 
```typescript
if (hasPermission !== invert) {
    …
}
``` 
because seems like XOR to me. Let me know if you'd like that to be reverted though

2023-10-20 17:08 UTC, escofresco commented
Tests were also failing locally until `--update-snapshot` because the original test snapshots contained `invert={false}` which were unmatched when the invert default prop was set as default destructure argument in `SystemPermissionGate`. Otherwise, I wasn't able to find a way for the snapshots to match without using `SystemPermissionGate.defaultProps = { invert: false }`

2023-10-26 06:00 UTC, lindy65 commented
/update-branch

2023-10-26 08:43 UTC, lindy65 commented
Hi @escofresco - please run `npm run test -- -u` for failing tests :)

2023-10-26 21:16 UTC, escofresco commented
@lindy65 added the new snapshot

2023-10-27 15:03 UTC, larkox commented
/e2e-test

2023-10-27 15:03 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/382348) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/382348)

2023-10-27 15:11 UTC, lindy65 approved these changes
Thanks @escofresco - looks good to me 👍 

cc// @larkox - good to go after E2E run

2023-10-30 08:51 UTC, larkox commented
@lindy65 Can you double check the cases where the e2e are failing? It should not be related, but better safe than sorry.

2023-10-30 09:41 UTC, lindy65 commented
Checked the failing E2E tests @larkox - they are not related to this PR 👍

2023-10-30 09:41 UTC, merged