Mm 54931 - Updating settings modals
mattermost/mattermost pull request #24934
Opened 2023-10-13 21:31 UTC by asaadmahmood

#### Summary
Mm 54931 - Updating settings modals

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-54931

#### Screenshots
<img width="847" alt="Screenshot 2023-10-14 at 2 30 16 AM" src="https://github.com/mattermost/mattermost/assets/11034289/23b9176e-a55d-40b6-a72a-8df4fdac8381">
<img width="840" alt="Screenshot 2023-10-14 at 2 30 25 AM" src="https://github.com/mattermost/mattermost/assets/11034289/7430a906-bd25-4e19-8564-5300147449a5">
<img width="847" alt="Screenshot 2023-10-14 at 2 30 32 AM" src="https://github.com/mattermost/mattermost/assets/11034289/aa0badf7-77b1-4db4-91ea-da0e8b7c16b8">

#### Release Note
```release-note
None
```

2023-10-13 21:32 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-14 01:53 UTC, matthewbirtch approved these changes
Nothing blocking for me @asaadmahmood. Nice work!

I left one comment in the code and the only other thing I was wondering is if we should consider adjusting the size of the subheading in the main content area of the modal ("Display Settings" in the screenshot). The font-size looks the same as the font size on the modal header (22px). So, maybe we go to 18px for the sub title within the main content area.

Nothing else blocking for me!

<img width="863" alt="Screenshot 2023-10-13 at 9 48 04 PM" src="https://github.com/mattermost/mattermost/assets/2040554/01b7f237-941d-498b-a104-3dfc1b266239">

2023-10-14 01:53 UTC, matthewbirtch commented on webapp/channels/src/sass/components/_settings-modal.scss
> +                padding: 24px;
what do you think about changing this to `padding: 16px`? It feels like it might be a bit too much padding right now maybe

2023-10-14 01:58 UTC, matthewbirtch requested changes
Spoke too soon, sorry. It looks like keyboard tabbing through settings no longer works to access the internal settings because the edit button has been hidden. Try tabbing through when you open a modal and you can't open any of the settings via keyboard anymore.

2023-10-14 06:44 UTC, asaadmahmood commented
@matthewbirtch All of those should be fixed.
I didn't mind the 24px like it was in the designs, but I made it 16px too.

2023-10-14 13:54 UTC, M-ZubairAhmed commented
@asaadmahmood @matthewbirtch i was working on this user setting component. i made a small improvement in the mobile web view of this which might conflict with this PR. Can you folks check it out https://github.com/mattermost/mattermost/pull/24905
<img width="853" alt="image" src="https://github.com/mattermost/mattermost/assets/17708702/958175ad-d314-409d-af6f-292f00cd3ebb">

2023-10-14 14:27 UTC, M-ZubairAhmed commented
> Spoke too soon, sorry. It looks like keyboard tabbing through settings no longer works to access the internal settings because the edit button has been hidden. Try tabbing through when you open a modal and you can't open any of the settings via keyboard anymore.

Tabbing in this component was done through force focusing on the edit button.

2023-10-14 14:28 UTC, M-ZubairAhmed commented
Also just a small reminder that we have few e2e tests for a11y for this component that needs to be changed/updated to accommodate the design changes

2023-10-16 08:04 UTC, asaadmahmood commented
/e2e-test

2023-10-16 08:04 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/378580) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/378580)

2023-10-16 13:13 UTC, asaadmahmood commented
/e2e-test

2023-10-16 13:13 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/378729) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/378729)

2023-10-16 13:42 UTC, matthewbirtch approved these changes
LGTM, @asaadmahmood. We can do the edit button on hover in a follow-up later.

2023-10-18 04:57 UTC, harshilsharma63 approved these changes
Awesome work!

2023-10-18 07:57 UTC, M-ZubairAhmed approved these changes

2023-10-19 06:13 UTC, lindy65 approved these changes
Thanks @asaadmahmood - looks good to me 👍

2023-10-19 06:14 UTC, merged

2023-10-19 07:22 UTC, saturninoabril commented
@lindy65 @asaadmahmood The 3 failed spec at https://github.com/mattermost/mattermost/pull/24934#issuecomment-1764461034 seemed to be related to this change. Could you help check?

2023-10-19 09:15 UTC, asaadmahmood commented
@lindy65 Me and @saturninoabril met and looks like most of the issues there **aren't** reproducing on master.
There was a separate issue about a background color of something which I can fix in a separate PR.

2023-10-19 09:25 UTC, lindy65 commented
Thanks for checking @asaadmahmood and @saturninoabril 🤗