[MM-54803] Convert ./components/channel_header_dropdown/mobile_channel_header_dropdown_animation.tsx from Class to Functional component
mattermost/mattermost pull request #24949
Opened 2023-10-16 12:46 UTC by Kritik-J

#### Summary

This PR Convert ./components/channel_header_dropdown/mobile_channel_header_dropdown_animation.tsx from Class to Functional component

#### Ticket Link

fixes: #24766 

#### Jira Ticket

https://mattermost.atlassian.net/browse/MM-54803

### Release Note

```release-note
Convert ./components/channel_header_dropdown/mobile_channel_header_dropdown_animation.tsx from Class to Functional component
```

2023-10-16 12:46 UTC, mattermost-build commented
Hello @Kritik-J,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-16 13:17 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-16 13:45 UTC, larkox requested changes
Great work! Just a minor change.

2023-10-16 13:45 UTC, larkox commented on webapp/channels/src/components/channel_header_dropdown/mobile_channel_header_dropdown_animation.tsx
> +            }}
Can we define this outside of the component? If not, on every render, we are passing a new value to `timeout`, potentially triggering a re-render underneath.

2023-10-16 14:48 UTC, larkox approved these changes

2023-10-18 08:08 UTC, jespino approved these changes
Nice! Looks good to me. Thanks @Kritik-J! :tada:

2023-10-18 08:13 UTC, lindy65 commented
/update-branch

2023-10-21 14:19 UTC, josephjosedev commented
@lindy65  i would like to test this PR as a QA

2023-10-23 05:51 UTC, lindy65 commented
Thanks @josephjosedev - the test server is ready.  You will need to test this on the [latest build of the mobile app](https://mattermost.com/download/#mobile) as the channel drop-down menu needs to be smoketested.

Let me know if you have any questions :)

2023-10-23 14:53 UTC, lindy65 commented
Hi @josephjosedev - yes - tap on the name "Off Topic" and test some of the options that you see in the menu that appears after tapping on the channel name.

Also, create your own new public and private channels and test the channel drop-down from these newly created channels

2023-10-23 15:39 UTC, larkox commented
@lindy65 @josephjosedev The idea here is not so much about the mobile application, but mobile web browser. You can test this either by opening the mattermost server from a browser in the phone (instead of from the app), or reduce the width of the browser to a really narrow size. Sorry for the confusion!

2023-10-23 15:46 UTC, lindy65 commented
> @lindy65 @josephjosedev The idea here is not so much about the mobile application, but mobile web browser. You can test this either by opening the mattermost server from a browser in the phone (instead of from the app), or reduce the width of the browser to a really narrow size. Sorry for the confusion!

Aah!  Thanks for the clarification @larkox :)

2023-10-23 17:33 UTC, josephjosedev commented
i tested the  options on the channel dropdown and some bugs are noted and the noted issues are attaching below
![image](https://github.com/mattermost/mattermost/assets/71834579/29b12a16-d210-4cd0-8e81-4ea575801925)
1.On channel Action Option the placeholder text is cutoffed..
2. 
![image](https://github.com/mattermost/mattermost/assets/71834579/fab7a945-5082-4098-b66e-e7fdf096392d)
Convert to private channel option 2 buttons are touching Yes and No button

3.
![image](https://github.com/mattermost/mattermost/assets/71834579/989991a3-89b2-4848-b27d-dca90a180d56)
Add members invite to the team text is congested in the space..

2023-10-24 10:25 UTC, lindy65 approved these changes
Thanks @Kritik-J  - looks good 👍 

@josephjosedev - thanks for your thorough QA!  I'll file separate tickets for the issues you found as they are not caused by this PR

cc @larkox

2023-10-24 10:37 UTC, larkox commented
/e2e-test

2023-10-24 10:37 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/381309) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/381309)

2023-10-30 11:18 UTC, merged

2023-10-30 11:19 UTC, larkox commented
Thank you for the contribution!