Convert ./components/permissions_gates/any_team_permission_gate/any_t…
mattermost/mattermost pull request #24970
Opened 2023-10-17 07:41 UTC by sjcode99

This PR convert ./components/permissions_gates/any_team_permission_gate/any_team_permission_gate.tsx from Class Component to Function Component.

Fixes #24776

2023-10-17 07:41 UTC, mattermost-build commented
Hello @sjcode99,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-10-17 07:56 UTC, larkox requested changes
Thanks for the contribution! Just a few comments.

2023-10-17 07:56 UTC, larkox commented on webapp/channels/src/components/permissions_gates/any_team_permission_gate/any_team_permission_gate.tsx
> +const AnyTeamPermissionGate: React.FC<Props> = ({
Just for coherence with the rest of the code, we prefer not having the explicit type here. Better something like:
`const Foo = ({...}: Props) => {...}`

2023-10-17 07:56 UTC, larkox commented on webapp/channels/src/components/permissions_gates/any_team_permission_gate/any_team_permission_gate.tsx
> +}) => <>{hasPermission !== invert ? children : null}</>
I appreciate the simplicity, but I feel having this in multiple lines is more readable. Something like this:
```suggestion
}) => (
    <>
        {hasPermission !== invert ? children : null}
    </>
);
```

2023-10-17 07:56 UTC, larkox commented on webapp/channels/src/components/permissions_gates/any_team_permission_gate/any_team_permission_gate.tsx
> +export default AnyTeamPermissionGate;
This used to be a PureComponent, so add here a `React.memo`.

2023-10-17 07:57 UTC, larkox commented
@sjcode99 Also, please make sure that `npm run fix` and `npm run test` in the channels folder work fine.

2023-10-17 07:57 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-17 15:27 UTC, larkox approved these changes

2023-10-17 15:39 UTC, sjcode99 commented
@larkox oh!! seems it got missed!. will do it now

2023-10-18 21:20 UTC, sinansonmez approved these changes
Great work, thanks 🚀

2023-10-23 08:10 UTC, sjcode99 commented
Hey @larkox , I can see the PR is still not merged. Is there anything which I missed doing?

2023-10-23 08:14 UTC, larkox commented
@sjcode99 Nothing missing from your side. Just waiting for QA Review. @lindy65 is leading that process. This may take some time (take in mind we had the weekend in the middle since I added her to this pr :smile: ) but if you don't hear from us, feel free to ping again to make sure this is not stuck.

2023-10-23 08:29 UTC, lindy65 commented
@sjcode99 @larkox - This PR hasn't been picked up by the community QAs yet so  I'll test it as soon as the test server is up

2023-10-23 08:37 UTC, lindy65 approved these changes
Thanks @sjcode99 - looks good to me 👍 

cc @larkox

2023-10-23 08:45 UTC, merged

2023-10-23 08:45 UTC, larkox commented
Thank you for the contribution!