Using the lightbulb icon for linking to the documentation
mattermost/mattermost pull request #25013
Opened 2023-10-19 07:29 UTC by jespino

#### Summary
Using the lightbulb icon for the in-app documentation links.

#### Ticket Link
There is not a ticket for this, but is to easy the community development of tickets like #25000

#### Screenshots

#### Release Note
```release-note
NONE
```

2023-10-19 07:36 UTC, M-ZubairAhmed requested changes
Just a question if we have CompassIcon for this so we can move away from these css based icons

2023-10-19 08:14 UTC, jespino commented
thanks @M-ZubairAhmed for point it, actually both are the same, the class based icon is the compass icon too, but in this case makes sense to use the component. Let me change it.

2023-10-19 08:21 UTC, jespino commented
@M-ZubairAhmed PTAL

2023-10-19 13:07 UTC, cwarnermm commented
@matthewbirtch - @jespino explored how to apply a new icon to an in-product link (to docs) so that we could guide contributors on the work needed to add Academy in-product links.

2023-10-19 13:25 UTC, matthewbirtch commented
> Just a question if we have CompassIcon for this so we can move away from these css based icons

For what it's worth @M-ZubairAhmed @jespino the lightbulb icon _is_ part [compass icons](https://mattermost.github.io/compass-icons/). It's identified as `icon-lightbulb-outline`.

I'm not sure what our preferred strategy for the use of compass icons is, so I'll leave that to you guys to recommend.

Visually, it looks good to me!

2023-10-19 13:25 UTC, matthewbirtch approved these changes

2023-10-19 13:50 UTC, M-ZubairAhmed approved these changes

2023-10-19 13:54 UTC, cwarnermm approved these changes

2023-10-19 14:38 UTC, mattermost-build commented
You don't have permissions to trigger this command.
 It's only available for organization members.

2023-10-19 14:38 UTC, jespino commented
I going to add QA to this, just in case. It should be 100% straight forward

2023-10-21 08:20 UTC, lindy65 approved these changes
Thanks @jespino - I've created a [Jira ticket](https://mattermost.atlassian.net/browse/MM-55065) as this change is sure to break some automated tests.

Looks good to me 👍

2023-10-23 11:41 UTC, merged