[GH-24843]: Fix customize_your_experience tour point position
mattermost/mattermost pull request #25053
Opened 2023-10-22 10:30 UTC by umrkhn

#### Summary
This PR fixes `customize_your_experience` tour point position to point to the settings icon in the global header

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/24843
Jira https://mattermost.atlassian.net/browse/MM-54744

#### Screenshots
|  before  |  after  |
|----|----|
![tour_point_before](https://github.com/mattermost/mattermost/assets/75561750/ead9f3c1-ece6-4bfc-83a1-80838b87a8e1) | ![tour_tip_fixed](https://github.com/mattermost/mattermost/assets/75561750/7c89fe08-3d4f-4dad-9efe-dc7a19a3f407)

#### Release Note

```release-note
NONE
```

2023-10-22 10:30 UTC, mattermost-build commented
Hello @umrkhn,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-31 12:58 UTC, umrkhn commented
> @cwarnermm can you please tag reviewers for this PR ? Thanks

Although the issue was fixed but this PR goes further and fixes the overlay position as shown in the screenshots above. let me know if it's required or I should close it.

2023-10-31 12:59 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-31 13:00 UTC, umrkhn commented
Thanks @cwarnermm appreciate the help :+1:

2023-10-31 14:24 UTC, matthewbirtch approved these changes
Nice improvement. Thanks @umrkhn!

2023-10-31 14:30 UTC, devinbinnie commented
/update-branch

2023-11-01 05:23 UTC, M-ZubairAhmed requested changes
thank you @umrkhn

2023-11-01 05:23 UTC, M-ZubairAhmed commented on webapp/channels/src/components/global_header/right_controls/right_controls.tsx
>  export type Props = {
nit empty line inbetween

2023-11-01 05:23 UTC, M-ZubairAhmed commented on webapp/channels/src/components/global_header/right_controls/right_controls.tsx
> +                <div style={{marginLeft: '8px'}}>
can we replace this inline styling

2023-11-01 05:23 UTC, M-ZubairAhmed commented on webapp/channels/src/components/global_header/right_controls/right_controls.tsx
> +
nit empty line removal from here

2023-11-01 09:53 UTC, yasserfaraazkhan approved these changes
Tested this on Mac Chrome, desktop and win desktop.
working as expected.

2023-11-02 14:17 UTC, M-ZubairAhmed approved these changes

2023-11-02 14:33 UTC, devinbinnie approved these changes
LGTM! Thanks @umrkhn!

2023-11-02 14:33 UTC, devinbinnie commented
@umrkhn Can you fix this lint issue and then we can merge?
```
/home/runner/work/mattermost/mattermost/webapp/channels/src/components/global_header/right_controls/right_controls.tsx
Error:   51:2  error  Missing semicolon  semi
```

2023-11-03 19:51 UTC, devinbinnie commented
/update-branch

2023-11-03 19:51 UTC, devinbinnie approved these changes

2023-11-10 08:42 UTC, hanzei commented
@devinbinnie @M-ZubairAhmed Can we merge this PR?

2023-11-10 14:01 UTC, merged