MM-52280: Generate higher contrast for some usernames
mattermost/mattermost pull request #25073
Opened 2023-10-23 23:09 UTC by KuSh

#### Summary

Generate higher contrast for some usernames

I've kept the 3 tries but return the best value instead of the last one.
Added test to check that it works.

For the record I've tested increasing the number of tries but it isn't especially good:
| tries | # over 4.5 | worst ratio |
| ----- | ---------- | ----------- |
| 03    | 3/8        | 2.29        |
| 04    | 3/8        | 2.5         |
| 05    | 5/8        | 2.5         |
| 06    | 5/8        | 2.64        |
| 07    | 6/8        | 2.64        |
| 08    | 6/8        | 2.95        |
| 09    | 6/8        | 2.95        |
| 10    | 6/8        | 2.95        |

This is in contrast with the previous implementation:
| tries | # over 4.5 | worst ratio |
| ----- | ---------- | ----------- |
| 03    | 3/8        | 1.07        |
| 04    | 3/8        | 1.05        |
| 05    | 5/8        | 1.35        |
| 06    | 5/8        | 1.04        |
| 07    | 6/8        | 1.20        |
| 08    | 6/8        | 1.88        |
| 09    | 6/8        | 1.67        |
| 10    | 6/8        | 1.66        |

I've also tried to use tested hex color as salt instead of "salt" but it isn't better:
| tries | # over 4.5 | worst ratio |
| ----- | ---------- | ----------- |
| 3     | 3          | 1.74        |
| 4     | 4          | 1.83        |
| 5     | 4          | 1.83        |
| 6     | 4          | 1.83        |
| 7     | 6          | 2.93        |
| 8     | 6          | 2.93        |
| 9     | 7          | 3.61        |
| 10    | 7          | 3.61        |

Perhaps we could switch to 5 tries but if we need better ratio for every username we should switch to something else than hex from salted string. I've found prior art here:
- https://github.com/jxnblk/hello-color
- https://github.com/Tanaguru/Contrast-Finder
- https://github.com/material-foundation/material-color-utilities

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/23018
Jira https://mattermost.atlassian.net/browse/MM-52280

#### Screenshots

#### Release Note

```release-note
Generate higher contrast for some usernames
```

2023-10-23 23:09 UTC, mattermost-build commented
Hello @KuSh,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-24 18:28 UTC, hmhealey commented
Thanks for the PR! Switching to use the best colour of the 3 makes a ton of sense.

I do agree that we could increase the number of iterations by a bit as well since, by your numbers, it does look like we see a bit of an improvement in the chances of finding one that's high enough contrast. If we were to go up to 10 iterations, I wouldn't expect the performance to be notably different since that calculation is relatively small and only happens once when you first see a post be a user, but I'll CC @devinbinnie since he was involved in the original discussion.

As for switching to a different library, I don't think that's necessary at this point since I don't know if we'd be able to use them to generate pseudo-random colours for users. I'm also not sure if we could use those first 2 due to them not being MIT/Apache

2023-10-24 18:30 UTC, hmhealey requested changes
As above, would you mind increasing the number of iterations to 10 then?

2023-10-24 20:03 UTC, KuSh commented
Just for the record @hmhealey hello-color is MIT, its a little bit hidden in a footnote on the README, but IMHO the most promising option is material ui tools, even if I agree actual solution is sufficient

I'll increase the iterarion country.

2023-10-25 21:46 UTC, hmhealey commented
> Just for the record @hmhealey hello-color is MIT, its a little bit hidden in a footnote on the README, but IMHO the most promising option is material ui tools, even if I agree actual solution is sufficient

Ah, I missed that. It's also in the `package.json` too.

I do agree that the Material one is probably the best one, but it seems a bit heavy weight for what we use it for. Maybe it'd let us replace some other colour dependencies like `tinycolor2` and `color-contrast-checker` as well, but I haven't looked into that much

2023-10-25 21:46 UTC, hmhealey approved these changes

2023-10-26 16:20 UTC, calebroseland approved these changes

2023-10-26 19:48 UTC, merged