[GH-25020] Add new resource links to [Help (?) drop-down menu] & icons
mattermost/mattermost pull request #25070
Opened 2023-10-23 18:14 UTC by umrkhn

#### Summary
This PR add new resource links to `Help (?) drop-down menu` also adds icons to existing links.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25020
Jira https://mattermost.atlassian.net/browse/MM-55024

#### Screenshots

#### Release Note

```release-note
NONE
```

2023-10-23 18:14 UTC, mattermost-build commented
Hello @umrkhn,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-23 18:18 UTC, umrkhn commented
This PR is currently being worked on, will update it when its done.

2023-10-24 17:43 UTC, umrkhn commented
Currently there is no `Give feedback` option, do I have to add it and where should it navigate to ?

2023-10-27 13:16 UTC, cwarnermm commented
@sbishel @matthewbirtch - We'll need some Engineering and UX support for this PR, please.

2023-10-27 15:07 UTC, matthewbirtch commented
> Currently there is no `Give feedback` option, do I have to add it and where should it navigate to ?

Let's keep the existing `Give feedback` menu option and it should behave exactly as it does right now (opening the feedbackbot). I believe this menu option will only display if you have the `User Satisfaction Surveys` plugin installed and enabled in the System Console

2023-10-27 15:30 UTC, matthewbirtch requested changes
Thanks for the contribution @umrkhn. A few minor UI details:

1. Can we adjust the icon color in the menu items to `color: rgba(var(--center-channel-color-rgb), 0.72);`
2. For some reason, the icons all look like they are sitting slightly too low. 
<img width="258" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/6e6acb95-1986-44f1-b628-09f3e81f1b92">

2023-10-30 14:49 UTC, matthewbirtch approved these changes
Looks good to me @umrkhn! Thanks for working on this one

2023-10-30 18:35 UTC, cwarnermm approved these changes
Thank you, @umrkhn!

2023-10-31 12:43 UTC, cwarnermm commented on webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
> +        url="https://academy.mattermost.com/courses"
```suggestion
        url="https://academy.mattermost.com/"
```

2023-10-31 12:44 UTC, cwarnermm commented on webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
> +        url="https://academy.mattermost.com/courses"
```suggestion
        url="https://academy.mattermost.com/"
```

2023-10-31 12:44 UTC, cwarnermm commented on webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
> +        url="https://academy.mattermost.com/courses"
```suggestion
        url="https://academy.mattermost.com/"
```

2023-10-31 12:45 UTC, cwarnermm commented on webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
> +const trainingResourcesLink = 'https://academy.mattermost.com/courses';
```suggestion
const trainingResourcesLink = 'https://academy.mattermost.com/';
```

2023-10-31 12:45 UTC, cwarnermm approved these changes

2023-10-31 14:57 UTC, crspeller approved these changes

2023-11-03 20:29 UTC, cwarnermm commented
@crspeller - Are you open to addressing the merge conflicts for this PR?

2023-11-06 14:30 UTC, cwarnermm approved these changes
Thank you, @umrkhn!!

2023-11-12 18:12 UTC, umrkhn commented
@cwarnermm what's the status for this PR?

2023-11-13 14:25 UTC, cwarnermm commented
@crspeller - Are you open to addressing the merge conflicts on this PR so that it can be merged?

2023-11-14 09:16 UTC, hanzei commented
/update-branch

2023-11-14 15:42 UTC, merged