Replace usage of LocalizedIcon in 'plain_log_list.tsx' with i/span tags #25083
mattermost/mattermost pull request #25135
Opened 2023-10-25 07:39 UTC by Sudhanva-Nadiger

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-54878

#### Release Note

```release-note
None
```

2023-10-25 07:39 UTC, mattermost-build commented
Hello @Sudhanva-Nadiger,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-25 10:28 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-25 10:29 UTC, M-ZubairAhmed commented
@Sudhanva-Nadiger amazing work before we can start the review can you please follow guidelines of PR checklist mentioned https://github.com/mattermost/mattermost/issues/25083#issue-1958836587

2023-10-25 10:37 UTC, Sudhanva-Nadiger commented
We don't have any snapshot update for this file ! As there is no test for this file ! 

And for the screenshot i couldn't get where this component comes in the app ! If you could help me that would be great

2023-10-25 16:51 UTC, M-ZubairAhmed commented
> We don't have any snapshot update for this file ! As there is no test for this file !
> 
> And for the screenshot i couldn't get where this component comes in the app ! If you could help me that would be great

Hey, the way i would do is to first find out where is the component in question being rendered, and next where is that parent rendered, that's how i climb the ladder until i find something significant or a big component which i know where it is in the app.

Hint : this is inside of admin console page

2023-10-25 16:52 UTC, M-ZubairAhmed requested changes

2023-10-25 16:52 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/server_logs/plain_log_list.tsx
> +                        title={this.props.intl.formatMessage({id: t('generic_icons.previous'), defaultMessage: 'Previous Icon'})}
t should not be neede here

2023-10-27 06:58 UTC, M-ZubairAhmed commented
@Sudhanva-Nadiger gentle ping on this one and i understand you are busy with your other ongoing prs thank you for that 😄

2023-10-28 04:40 UTC, M-ZubairAhmed approved these changes
As always consistent quality contribution 💥💥

2023-10-28 18:38 UTC, yasserfaraazkhan approved these changes
tested this locally by changing config.
working as expected.

2023-10-31 05:20 UTC, Sudhanva-Nadiger commented
@M-ZubairAhmed one non related commit was pushed before ! so i had to drop it and force pushed ! sorry for the inconvenience

2023-10-31 06:24 UTC, M-ZubairAhmed commented
/update-branch

2023-10-31 08:14 UTC, merged