[MM-55122] Replaced the usage of LocalizedIcon in 'fa_warning_icon.tsx' with i/span tags
mattermost/mattermost pull request #25136
Opened 2023-10-25 08:56 UTC by balajik

#### Summary
Replaced the usage of LocalizedIcon in 'fa_warning_icon.tsx' with i tag

#### Ticket Link
Fixes #25088

Jira https://mattermost.atlassian.net/browse/MM-55122

#### Release Note

```release-note
NONE
```

2023-10-25 08:56 UTC, mattermost-build commented
Hello @balajik,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-25 10:26 UTC, M-ZubairAhmed commented
@balajik please follow the "PR checklist" guidelines mentioned in the ticket https://github.com/mattermost/mattermost/issues/25088#issue-1959024456

2023-10-25 13:31 UTC, devinbinnie approved these changes
LGTM! Just one non-blocking question. Thanks @balajik!

2023-10-25 13:31 UTC, devinbinnie commented on webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
> +    public static defaultProps: Partial<Props> = {
How come you added this `Partial` bit here?

2023-10-25 13:44 UTC, devinbinnie commented on webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
> +    public static defaultProps: Partial<Props> = {
You changed `Props` to `Partial<Props>`. Was there a reason why?

2023-10-25 16:33 UTC, M-ZubairAhmed requested changes

2023-10-25 16:33 UTC, M-ZubairAhmed commented on webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
> +import type {IntlShape} from 'react-intl';
```suggestion
import {injectIntl, type IntlShape} from 'react-intl';
```

2023-10-25 16:33 UTC, M-ZubairAhmed commented on webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
> +    additionalClassName?: string | null;
```suggestion
    additionalClassName?: string;
```

2023-10-25 16:33 UTC, M-ZubairAhmed commented on webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
> +    additionalClassName?: string | null;
I dont think null is needed here,

2023-10-26 14:04 UTC, M-ZubairAhmed requested changes

2023-10-26 14:04 UTC, M-ZubairAhmed commented on webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
>          const className = 'fa fa-warning' + (this.props.additionalClassName ? ' ' + this.props.additionalClassName : '');
we can simplify here by using the `classname('fa fa-warning', this.props.additionalclass)`
the library will take care of the string concatenations and empty string checks. That way we don't have to add null as default value

2023-10-26 14:07 UTC, M-ZubairAhmed commented on webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
> +    additionalClassName?: string | null;
please see my latest comment

2023-10-27 06:48 UTC, M-ZubairAhmed approved these changes
Thank you for going extra mile to improve the component as well as the ticket work 🤝

2023-10-27 07:00 UTC, yasserfaraazkhan commented
/e2e-tests

2023-10-27 07:00 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/382214) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/382214)

2023-10-28 04:42 UTC, yasserfaraazkhan approved these changes
<img width="500" alt="image" src="https://github.com/mattermost/mattermost/assets/15979783/4528bfcd-da7d-4021-84aa-885c3041cbe7">

2023-10-28 07:35 UTC, merged