Replace LocalizedIcon with i tag in multiselect.tsx
mattermost/mattermost pull request #25140
Opened 2023-10-25 12:02 UTC by mozi47

#### Summary
Replace LocalizedIcon with i tag in multiselect.tsx

#### Ticket Link
Fixes: #25109

2023-10-25 12:03 UTC, mattermost-build commented
Hello @mozi47,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-25 12:15 UTC, mozi47 commented
I couldn't get where this component comes in the app, which is why the screenshot was not added. If you can help me with that will be great.

2023-10-25 13:02 UTC, M-ZubairAhmed commented
@mozi47 can you please take a look and follow the guidelines mentioned https://github.com/mattermost/mattermost/issues/25109#issue-1959027425

2023-10-25 13:02 UTC, M-ZubairAhmed commented
/release-note-none

2023-10-25 13:02 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-25 16:59 UTC, M-ZubairAhmed requested changes
Please address the CI failures

2023-10-25 16:59 UTC, M-ZubairAhmed commented on webapp/channels/src/components/multiselect/multiselect.tsx
> +                            title={this.props.intl.formatMessage({id: 'generic_icons.info', defaultMessage: 'Info Icon'})}
this component doesnt have props `intl` injected how did this work?

2023-10-27 09:04 UTC, M-ZubairAhmed commented
@mozi47 it still has error can you please check , we can only begin the review once the CI is green 😄

2023-10-30 13:57 UTC, M-ZubairAhmed commented
@mozi47 a lot of failures are in test file of the component, you can try looking at other components where injectIntl is used and how there test files are

2023-11-02 05:25 UTC, mozi47 commented
I need help. Updation of snapshto is not happening as expected!

2023-11-02 12:46 UTC, M-ZubairAhmed commented
> I need help. Updation of snapshto is not happening as expected!

Thats fine, i will update from my end. Can you check the failing CIs

2023-11-02 12:47 UTC, M-ZubairAhmed commented
> I need help. Updation of snapshto is not happening as expected!

You need to run `npm run test -- -u` from channels folder

2023-11-06 06:05 UTC, M-ZubairAhmed commented
@mozi47 please check the failing check types. And for the failing test i would recommend taking a look at other tests which uses the injectIntl

2023-11-20 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-12-06 07:03 UTC, closed without merging