[MM-55104]-Replace usage of LocalizedIcon in 'rhs_header_post.tsx' with i/span tags
mattermost/mattermost pull request #25159
Opened 2023-10-26 07:44 UTC by Sudhanva-Nadiger

#### Summary
- fixes: #25106
- eliminate the usage of LocalizedIcon in the `webapp/channels/src/components/rhs_header_post/rhs_header_post.tsx`

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-55104

#### Screenshots

|before  |  after  |
|----|----|
| ![image](https://github.com/mattermost/mattermost/assets/93595710/25babd90-012a-4a94-a0ab-aaaa8a2507fa) |![image](https://github.com/mattermost/mattermost/assets/93595710/ade4de81-487b-47d1-a228-3054e0399517) |

|before  |  after  |
|----|----|
| ![image](https://github.com/mattermost/mattermost/assets/93595710/f8c0eaee-7cb0-46c0-ba5c-4d10103330c7) |![image](https://github.com/mattermost/mattermost/assets/93595710/6df4208a-b0ea-462d-8b5c-d1d432e60567) |

#### Release Note

```release-note
None
```

2023-10-26 07:44 UTC, mattermost-build commented
Hello @Sudhanva-Nadiger,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-26 08:37 UTC, M-ZubairAhmed requested changes
Can you please check if the test file for this component would require any changes?

2023-10-26 08:37 UTC, M-ZubairAhmed commented on webapp/channels/src/components/rhs_header_post/rhs_header_post.tsx
> +class RhsHeaderPost extends React.PureComponent<RhsHeaderPostProps> {
nit lets rename `RhsHeaderPostProps` to Props

2023-10-26 13:28 UTC, Sudhanva-Nadiger commented
All tests are passing 🎉 

![image](https://github.com/mattermost/mattermost/assets/93595710/c11ffa86-6cbe-4aae-964b-ccaab344a0af)
![image](https://github.com/mattermost/mattermost/assets/93595710/e27b1488-5940-42a9-b3c3-8d950e14a394)

2023-10-26 13:35 UTC, M-ZubairAhmed approved these changes
Thanks for your remarkable contributions; your work is outstanding. 1️⃣ 0️⃣ 0️⃣ %

2023-10-26 13:35 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-10-27 10:16 UTC, yasserfaraazkhan approved these changes
verified in pinned, saved, threads, playbook.
works as expected.

2023-10-27 10:26 UTC, M-ZubairAhmed commented
@jespino gentle ping on this one

2023-10-27 13:50 UTC, jespino approved these changes
Looks good to me. Thanks @Sudhanva-Nadiger! :confetti_ball:

2023-10-27 13:51 UTC, jespino commented
@M-ZubairAhmed is this ready to merge?

2023-10-27 13:53 UTC, merged