[MM-55004] Add warning log message when app run as root
mattermost/mattermost pull request #25213
Opened 2023-10-30 11:38 UTC by Paul-vrn

#### Summary

Add a warning log message when Mattermost app is running with root user

#### Ticket Link

Fixes #24996 
JIRA: https://mattermost.atlassian.net/browse/MM-55004

#### Release Note

```release-note
NONE
```

2023-10-30 11:38 UTC, mattermost-build commented
Hello @Paul-vrn,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-10-31 12:08 UTC, hanzei requested changes
Thanks for the contribution @Paul-vrn Let's ensure the warning is placed close to other similar messanges :+1:

2023-10-31 12:08 UTC, hanzei commented on server/channels/app/server.go
> +	}
Let's move that code closer to other sanity checks. Next to https://github.com/mattermost/mattermost/blob/37da0531919032722dfc8036b293bd1bdc900a7b/server/channels/app/server.go#L415-L417 would be a good place.

2023-10-31 12:08 UTC, hanzei commented on server/channels/app/server.go
> +		mlog.Warn("Running as root is not recommended")
```suggestion
		mlog.Warn("Running Mattermost as root is not recommended. Please use a separate user")
```

2023-10-31 12:33 UTC, hanzei approved these changes

2023-10-31 18:27 UTC, streamer45 commented
@hanzei I wonder if we should add the check at the command level. You can technically still run the binary as root without getting a warning if you run any other subcommand. I'd argue that would equally be a bad idea in most cases so maybe we could just move the check to the entry point `cmd/mattermost/main.go`.

2023-11-01 10:11 UTC, Paul-vrn commented
> @hanzei I wonder if we should add the check at the command level. You can technically still run the binary as root without getting a warning if you run any other subcommand. I'd argue that would equally be a bad idea in most cases so maybe we could just move the check to the entry point `cmd/mattermost/main.go`.

Yeah, that's what I implemented in the beginning. But I saw most of the log messages being generated in the `app/server.go`, so I changed my mind. 😄
I'll make the change depending on what Hanzei suggests!

2023-11-01 10:42 UTC, hanzei commented
Good point. Most commands are not safe to run as root. Let's move the check.

2023-11-06 08:17 UTC, hanzei requested changes

2023-11-06 08:17 UTC, hanzei commented on server/channels/app/server.go
> +
```suggestion

```

2023-11-06 08:17 UTC, hanzei commented on server/channels/app/server.go
> +
Please remove the unrelated change.

2023-11-06 08:17 UTC, hanzei commented on server/cmd/mattermost/main.go
> +	}
While the code works correctly, I think it should be placed in `root.go` instead to keep `main.go` clean. You can use the `PersistentPreRun` field of `RootCmd`.

2023-11-06 18:16 UTC, streamer45 commented
@Paul-vrn Looks like our linter is not happy with some minor formatting. Could you run `gofmt -s -w cmd/mattermost/commands/root.go` and commit?

2023-11-06 19:21 UTC, Paul-vrn commented
> gofmt -s -w cmd/mattermost/commands/root.go

ah yess didn't see, my bad, next time I'll run this command thx!

2023-11-06 19:34 UTC, streamer45 approved these changes
Looks good! Thank you for the contribution @Paul-vrn! :tada:

2023-11-07 09:06 UTC, hanzei commented
/update-branch

2023-11-07 09:09 UTC, hanzei approved these changes

2023-11-07 09:09 UTC, hanzei commented on server/channels/app/server.go
>  	if _, err = url.ParseRequestURI(*s.platform.Config().ServiceSettings.SiteURL); err != nil {
Nit: Would you mind removing the unrelated change?

2023-11-07 09:09 UTC, hanzei commented on server/cmd/mattermost/main.go
> +
Same here

2023-11-07 11:08 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-11-07 11:09 UTC, hanzei commented
Thank you very much for your contribution and for bearing with me while we figure out the best solution @Paul-vrn !

2023-11-08 10:13 UTC, yasserfaraazkhan approved these changes
🎉 
<img width="600" alt="image" src="https://github.com/mattermost/mattermost/assets/15979783/2252ebf2-3331-471a-b1e9-a7a5cda9c84a">

2023-11-08 10:39 UTC, merged