[MM-55009] Remove pre-fetch preference and set new pre fetch limits
mattermost/mattermost pull request #25251
Opened 2023-10-31 19:14 UTC by BenCookie95

#### Summary
The goal of this is to find a balance for pre-fetching and making the webapp more usable for people with a high number of unread channels. After experimenting on Community we came up with these limits.

1. <10 unread channels. Prefetch everything.

2. 10-20 unread. Prefetch only mentions, capped to 10.

3. ">20 unread. Don't prefetch anything.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-55009

#### Screenshots

#### Release Note

```release-note
Remove pre-fetch preference and set new pre fetch limits for the webapp
```

2023-11-01 04:37 UTC, M-ZubairAhmed requested changes

2023-11-01 04:37 UTC, M-ZubairAhmed commented on webapp/channels/src/components/data_prefetch/index.ts
>  const prefetchQueue = memoizeResult((
Would you be open to adding a few unit tests for the conditions mentioned here

2023-11-01 21:00 UTC, hmhealey requested changes

2023-11-01 21:00 UTC, hmhealey commented on webapp/channels/src/components/data_prefetch/index.ts
> +        if (unreadChannelsCount >= 10 && defaultResult[Priority.high].length >= 10) {
Would you mind adding constants for the 10/20? It'll make it easier to update those if we want to tweak them a bit

2023-11-01 21:04 UTC, BenCookie95 commented on webapp/channels/src/components/data_prefetch/index.ts
> +    if (!unreadChannelsCount || unreadChannelsCount > 20) {
Yeah there is a low chance of pre-loading the correct channels but you're right that it's odd. We could do the same behaviour as 10-20 where we pre-load your first 10 mentions?

2023-11-02 04:37 UTC, agnivade commented on webapp/channels/src/components/data_prefetch/index.ts
> +    if (!unreadChannelsCount || unreadChannelsCount > 20) {
The 10-20 range is a rough number that I came up with after asking several folks on community on their avg unread count. The reasoning is that when there are >20 unreads, the user behavior is that they don't actually read all the unreads, but rather go through them in batches. Therefore, any amount of preloading is actually wasted. Therefore, we decided not to preload anything.

2023-11-06 17:29 UTC, BenCookie95 commented
/update-branch

2023-11-07 00:47 UTC, M-ZubairAhmed approved these changes

2023-11-08 22:23 UTC, hmhealey commented on webapp/channels/src/components/data_prefetch/index.ts
> +    if (!unreadChannelsCount || unreadChannelsCount > 20) {
Makes sense. This looks good then

2023-11-08 22:23 UTC, hmhealey approved these changes

2023-11-08 22:23 UTC, merged