Run arficats jobs conditionally, add test change
mattermost/mattermost pull request #25279
Opened 2023-11-02 14:57 UTC by mvitale1989

#### Summary

Workflows running on PRs targeting `release-7x` are currently failing, see for example https://github.com/mattermost/mattermost/pull/25185
The root cause is explained in the same commit.

This PR will exclude problematic jobs if the workflow is not running in a monorepo.

#### Ticket Link

None, this is a hotfix

#### Release Note

```release-note
NONE
```

2023-11-02 17:22 UTC, amyblais approved these changes

2023-11-02 17:58 UTC, mvitale1989 commented
/update-branch

2023-11-03 15:07 UTC, toninis approved these changes

2023-11-03 15:10 UTC, merged

2023-11-03 15:10 UTC, phoinixgrr requested changes

2023-11-03 15:10 UTC, phoinixgrr commented on .github/workflows/server-ci-artifacts.yml
> +          echo "is_monorepo=$IS_MONOREPO" | tee --append "$GITHUB_OUTPUT"
```suggestion
          echo "is_monorepo=$IS_MONOREPO" | tee --apend "$GITHUB_OUTPUT"
```