Simplify workflow failure check
mattermost/mattermost pull request #25366
Opened 2023-11-07 20:15 UTC by lieut-data

#### Summary
Consolidate the workflow failure check directly into *-master.yml. This results in some code duplication, but makes it much clearer as to what's going on. While we're in here, remove the legacy reference to the `monorepo` branch when triggering.

#### Ticket Link

#### Screenshots

#### Release Note

```release-note

```

2023-11-08 12:55 UTC, mvitale1989 commented on .github/workflows/server-ci-master.yml
> +    if: ${{ always() && needs.master-ci.result == 'failure' }}
TIL that `always() && needs.master-ci.result == 'failure'` is not equivalent to just `needs.master-ci.result == 'failure'` :open_mouth:  That's very useful to know, thanks Jesse!

2023-11-08 12:55 UTC, mvitale1989 commented on .github/workflows/server-ci-master.yml
> +          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
This wouldn't work. The [`github.event.workflow_run.*` event data](https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run) is only available in a `workflow_run`-triggered workflow, but after this change the context for this workflow is within a `push` event.
Let me check the docs for the correct equivalent interpolation

2023-11-08 13:19 UTC, toninis requested changes
@lieut-data We can keep the same logic . No need to add this to the rest workflows

2023-11-08 13:29 UTC, mvitale1989 commented on .github/workflows/server-ci-master.yml
> +          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
Ah true, as [Antonis mentions](https://github.com/mattermost/mattermost/pull/25366#pullrequestreview-1720337002) the remediation of simply putting the untrusted interpolations within intermediary variables should be all we need, according to the Jira ticket.
I think we can still keep the failure report within its `workflow_run` file, in this case

2023-11-08 14:04 UTC, mvitale1989 commented on .github/workflows/server-ci-master.yml
> +            ${{ secrets.MM_COMMUNITY_DEVELOPERS_INCOMING_WEBHOOK_FROM_GH_ACTIONS }}
I wonder if this variable can be accessed by untrusted workflows? Let me double check, but perhaps this was the reason we needed to have this workflow as privileged :thinking:

2023-11-08 14:10 UTC, mvitale1989 commented on .github/workflows/server-ci-master.yml
> +            ${{ secrets.MM_COMMUNITY_DEVELOPERS_INCOMING_WEBHOOK_FROM_GH_ACTIONS }}
Never mind, afaiu this should run just fine, as long as it doesn't run within repo forks.

2023-11-09 15:27 UTC, toninis approved these changes

2023-11-09 16:01 UTC, merged