[MM-55332] Convert `./components/permissions_gates/channel_permission_gate.tsx` from Class Component to Function Component
mattermost/mattermost pull request #25399
Opened 2023-11-10 06:43 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/permissions_gates/channel_permission_gate.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25361
Jira https://mattermost.atlassian.net/browse/MM-55332

#### Release Note

```release-note
NONE
```

2023-11-10 06:43 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-11-10 08:00 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-11-10 11:05 UTC, larkox requested changes
One minor improvement, but looks great otherwise!

2023-11-10 12:36 UTC, Syed-Ali-Abbas-Zaidi commented on webapp/channels/src/components/permissions_gates/channel_permission_gate/channel_permission_gate.tsx
> +    if (hasPermission && !invert) {
Done.

2023-11-10 15:47 UTC, devinbinnie approved these changes
LGTM! Thanks @Syed-Ali-Abbas-Zaidi!

2023-11-13 09:21 UTC, larkox commented
/update-branch

2023-11-13 09:22 UTC, larkox approved these changes
Great work! Thanks!

2023-11-13 16:47 UTC, yasserfaraazkhan commented
/e2e-tests

2023-11-13 16:47 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/387664) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/387664)

2023-11-13 17:32 UTC, yasserfaraazkhan approved these changes

2023-11-13 20:37 UTC, merged