Updated mmctl export create command flag
mattermost/mattermost pull request #25474
Opened 2023-11-17 14:51 UTC by cwarnermm

#### Summary
Updated mmctl export create command flag to align with product documentation (updated via https://github.com/mattermost/docs/pull/6796)

#### Release Note

```release-note
NONE
```

2023-11-17 14:54 UTC, hanzei requested changes
You need to update the source go file. The rst docs are auto-generated.

2023-11-17 14:59 UTC, cwarnermm commented
Oh wow! Thanks, @hanzei! It's been so long since I made changes here, I'd completely forgotten about that.

2023-11-17 15:17 UTC, cwarnermm commented on server/cmd/mmctl/docs/mmctl_export_create.rst
> +      --no-attachments              Omit file attachments in the export file.
```suggestion
      --no-attachments              Exclude file attachments from the export file.
```

2023-11-17 15:19 UTC, cwarnermm commented
@hanzei - Given that the mmctl docs are auto-generated, is it necessary for me to revert the doc changes, or will they simply be overwritten with the Go changes?

2023-11-17 22:08 UTC, JulienTant approved these changes

2023-11-17 22:11 UTC, JulienTant commented
@cwarnermm I believe the process is to change the go file, then run `make mmctl-docs`, and commit the result. Chances are that your manual changes will match exactly what the tool would have done automatically and you'll have nothing to commit! :)

2023-11-20 14:27 UTC, cwarnermm commented
@JulienTant - When I ran the ``make mmctl-docs`` command within my local branch, I see the error: ``make: *** No rule to make target `mmctl-docs'.  Stop.``. Not sure how to proceed. Any suggestions?

2023-11-20 14:40 UTC, hanzei commented
@cwarnermm Did you run the command from within `server`?

2023-11-20 15:02 UTC, cwarnermm commented
Thanks, @hanzei! I re-ran the command via the ``server`` directory. This time the result was a different error: Error 1.

```
M1 detected, applying elasticsearch override
rm -rf ./cmd/mmctl/docs
cd ./cmd/mmctl && go run mmctl.go docs
# github.com/mattermost/mattermost/server/v8/einterfaces
../../einterfaces/cloud.go:57:46: undefined: model.AllowedIPRanges
../../einterfaces/cloud.go:58:38: undefined: model.AllowedIPRanges
../../einterfaces/ip_filtering.go:9:40: undefined: model.AllowedIPRanges
../../einterfaces/ip_filtering.go:10:25: undefined: model.AllowedIPRanges
# github.com/mattermost/mattermost/server/v8/channels/store
../../channels/store/store.go:124:70: undefined: model.RetentionIdsForDeletion
../../channels/store/store.go:740:35: undefined: model.RetentionIdsForDeletion
make: *** [mmctl-docs] Error 1
```

2023-11-20 18:12 UTC, cwarnermm commented
Unfortunately, that too wasn't successful, @JulienTant.

2023-11-23 08:03 UTC, hanzei approved these changes
LGTM :+1: 

Thanks for updating _all_ the sources. Looking forward to simplifying the process.

2023-11-23 13:58 UTC, merged