Convert class to func component
mattermost/mattermost pull request #25487
Opened 2023-11-18 17:09 UTC by rohitkbc

#### Summary
Fixes #25358 

#### Ticket Link
JIRA LINK: [MM-55329](https://mattermost.atlassian.net/browse/MM-55329)

2023-11-18 17:09 UTC, mattermost-build commented
Hello @rohitkbc,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-11-18 17:11 UTC, rohitkbc commented
/release-note-none

2023-11-22 10:50 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-11-22 12:55 UTC, M-ZubairAhmed requested changes

2023-11-22 12:55 UTC, M-ZubairAhmed commented on webapp/channels/src/plugins/test/post_type.test.tsx
> +const PostTypePlugin: React.FunctionComponent = () => (
```suggestion
const PostTypePlugin = () => (
```
nit we can remove that

2023-11-22 12:55 UTC, M-ZubairAhmed commented
/update-branch

2023-11-22 15:04 UTC, devinbinnie approved these changes
LGTM other than Zubair's comment. Thanks @rohitkbc!

2023-12-01 15:54 UTC, larkox commented
@rohitkbc Are you still working on this? Can you take a look to the review comments?

2023-12-06 06:51 UTC, M-ZubairAhmed requested changes
@rohitkbc can you please the failing CI checks

2023-12-06 06:51 UTC, M-ZubairAhmed commented
/update-branch

2023-12-06 07:31 UTC, M-ZubairAhmed approved these changes

2023-12-06 07:36 UTC, merged