#25093 Replace usage of LocalizedIcon in 'view_user_group_modal_header.tsx' with i/span tags
mattermost/mattermost pull request #25537
Opened 2023-11-25 06:58 UTC by PulkitGarg-code

…Intl

#### Summary

#### Ticket Link

#### Screenshots

#### Release Note

```release-note

```

2023-11-25 06:58 UTC, mattermost-build commented
Hello @PulkitGarg-code,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-11-30 06:43 UTC, PulkitGarg-code commented on webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
> +        const {formatMessage} = useIntl();
i have resolved this, once check

2023-12-06 06:52 UTC, M-ZubairAhmed commented
@PulkitGarg-code it looks like you haven't sign the CLA
please follow this https://github.com/mattermost/mattermost/pull/25537#issuecomment-1826234729

2023-12-06 06:56 UTC, M-ZubairAhmed requested changes
Please check the failing CI and rerun the test to see why they are failing, you might have to run update snapshots on these

2023-12-06 06:56 UTC, M-ZubairAhmed commented on webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
> +        const {formatMessage} = this.props;
Oops we deleted the `theme` variable here
```
const {formatMessage, theme} = this.props
```

2023-12-06 06:56 UTC, M-ZubairAhmed commented on webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
> +export default injectIntl(CustomThemeChooser);
empty line after this

2023-12-06 13:55 UTC, M-ZubairAhmed commented
/update-branch

2023-12-06 13:56 UTC, M-ZubairAhmed commented
@PulkitGarg-code the issue https://github.com/mattermost/mattermost/issues/25093 was already done and merged, so we can focus on https://github.com/mattermost/mattermost/issues/25100 in this PR

2023-12-07 17:54 UTC, PulkitGarg-code commented
/update-branch

2023-12-08 08:57 UTC, M-ZubairAhmed requested changes
The code looks really good. Can you please try to resolve the errors in the CI failures?

2023-12-11 21:04 UTC, M-ZubairAhmed commented
/update-branch

2023-12-13 05:22 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-12-13 18:30 UTC, PulkitGarg-code commented
/check-cla

2023-12-13 18:34 UTC, PulkitGarg-code commented
/update-branch

2023-12-13 18:48 UTC, PulkitGarg-code commented
Hi @M-ZubairAhmed, almost all the checks have passed. please review and let me know if anything is required from my side to merge this PR.

2023-12-14 03:37 UTC, M-ZubairAhmed commented
/update-branch

2023-12-14 04:41 UTC, M-ZubairAhmed approved these changes

2023-12-14 08:58 UTC, yasserfaraazkhan approved these changes

2023-12-14 11:51 UTC, merged