[MM-55330]: Convert `./components/widgets/popover/index.tsx` from Class Component to Function Component
mattermost/mattermost pull request #25541
Opened 2023-11-25 09:55 UTC by 0xJamin

#### Summary

This PR converts the popover widgets from a class component to a function component and also updates the snapshots of other components that use the popover widgets.
#### Ticket Link

#### Screenshots

#### Release Note

```release-note

```

2023-11-25 09:55 UTC, mattermost-build commented
Hello @0xJamin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-11-25 10:02 UTC, 0xJamin commented on webapp/channels/src/components/widgets/popover/popover.test.tsx
> +import {render} from '@testing-library/react';
Also, I converted the test to use `@testing-library`

2023-11-25 11:01 UTC, 0xJamin commented on webapp/channels/src/components/widgets/popover/popover.test.tsx
> +import {render} from '@testing-library/react';
/check-cla

2023-11-25 11:01 UTC, 0xJamin commented
/check-cla

2023-11-27 09:20 UTC, larkox requested changes
Great work! Just one minor change and looks fine :smile:

2023-11-27 09:20 UTC, larkox commented on webapp/channels/src/components/widgets/popover/index.tsx
> +const Popover = ({placement = 'right', popoverSize = 'sm', children, popoverStyle = 'info', title, id, onMouseOut, onMouseOver, className, style}: Props) => {
To improve readability, keep one Prop per line:

```suggestion
const Popover = ({
    placement = 'right',
    popoverSize = 'sm',
    children,
    popoverStyle = 'info',
    title,
    id,
    onMouseOut,
    onMouseOver,
    className,
    style,
}: Props) => {
```

2023-11-27 10:59 UTC, 0xJamin commented
@larkox  changes updated

2023-11-27 11:03 UTC, larkox approved these changes

2023-11-27 15:16 UTC, M-ZubairAhmed approved these changes
Amazing work thank you 👍🏽

2023-11-27 15:17 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-12-04 16:21 UTC, larkox commented
@0xJamin There seems to be some type errors. Could you take a look?

2023-12-05 14:07 UTC, yasserfaraazkhan commented
/update-branch

2023-12-14 08:41 UTC, larkox commented
@0xJamin There seems to be some errors in the PR (regarding types). Can you look at those?

2023-12-14 08:42 UTC, 0xJamin commented
Hi @larkox I'll check it out today

2023-12-14 13:54 UTC, 0xJamin commented
Hi @larkox, Can you run the tests now to see if it passes?

2023-12-17 19:12 UTC, yasserfaraazkhan commented
/e2e-tests

2023-12-17 19:12 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/397251) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/397251)

2023-12-17 20:06 UTC, yasserfaraazkhan approved these changes

2023-12-18 09:46 UTC, merged