MM-25111 Replace usage of LocalizedIcon in 'channel_members_rhs/header.tsx' with i/span tags
mattermost/mattermost pull request #25616
Opened 2023-12-04 06:07 UTC by Vinecreeper888

Removed LocalizedIcon in header.tsx
Replaced it with <i/> tag and used useIntl hook of react-intl for the aria label in header.tsx
Resolves https://github.com/mattermost/mattermost/issues/25111

Screenshots
BEFORE
![old](https://github.com/mattermost/mattermost/assets/26576656/7d74fb4f-e51f-4692-8fe7-030293691856)

AFTER
<img width="887" alt="new" src="https://github.com/mattermost/mattermost/assets/26576656/0a78e911-321a-4a82-adb1-8c93668dac27">

https://mattermost.atlassian.net/browse/MM-55099

```release-note
NONE
```

2023-12-04 06:07 UTC, mattermost-build commented
Hello @Vinecreeper888,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-12-04 18:08 UTC, M-ZubairAhmed commented
@Vinecreeper888 can you please check the failing CI

2023-12-06 07:07 UTC, M-ZubairAhmed requested changes
Please check the failing CI

2023-12-06 07:07 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_members_rhs/header.tsx
> +                        aria-label={useIntl().formatMessage({
please define hook seperately

```
    const {formatMessage} = useIntl();
   ```

2023-12-06 09:01 UTC, Vinecreeper888 commented on webapp/channels/src/components/channel_members_rhs/header.tsx
> +                        aria-label={useIntl().formatMessage({
has been resolved

2023-12-10 06:42 UTC, Vinecreeper888 commented
@M-ZubairAhmed how do I check the Enterprise CI/tests that have failed?

2023-12-11 05:42 UTC, M-ZubairAhmed commented
/update-branch

2023-12-11 05:43 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed how do I check the Enterprise CI/tests that have failed?

Sorry these cannot be checked without correct permissions. I have updated to latest branch to see if it solves that issue

2023-12-11 06:29 UTC, M-ZubairAhmed approved these changes
Looks great @Vinecreeper888 thank you for your contribution

2023-12-11 06:30 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-12-11 06:31 UTC, M-ZubairAhmed commented
/e2e-test

2023-12-11 06:31 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/395465) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/395465)

2023-12-11 17:06 UTC, yasserfaraazkhan approved these changes

2023-12-11 18:42 UTC, merged