[MM-56008] Convert `./components/widgets/settings/bool_setting.tsx` to functional component
mattermost/mattermost pull request #25614
Opened 2023-12-03 03:37 UTC by Amir-Helali

#### Summary

Converted ```./components/widgets/settings/bool_setting.tsx``` to a functional component. And, updated the ```bool_setting.test.tsx```.
#### Ticket Link

Fixes #25600

#### Release Note

```release-note
NONE
```

2023-12-04 20:38 UTC, Amir-Helali commented on package-lock.json
Done

2023-12-04 20:39 UTC, Amir-Helali commented on webapp/channels/src/components/widgets/settings/bool_setting.test.tsx
> +      const onChange = jest.fn();
Yeah, that was weird to me as well.

2023-12-04 20:56 UTC, Amir-Helali commented on webapp/channels/src/components/widgets/settings/bool_setting.tsx
> +const BoolSetting: React.FC<Props> = ({
Made the changes for this.

2023-12-04 20:56 UTC, Amir-Helali commented on webapp/channels/src/components/widgets/settings/bool_setting.tsx
> +export default BoolSetting;
made the changes for this

2023-12-05 09:27 UTC, larkox approved these changes
Great work!

2023-12-06 06:31 UTC, M-ZubairAhmed requested changes
Amir can you check the failing lint errors?

2023-12-06 19:20 UTC, Amir-Helali commented
@M-ZubairAhmed I tried running the ESLint fixer but It did not work for me :(

2023-12-07 04:13 UTC, M-ZubairAhmed commented
@

> @M-ZubairAhmed I tried running the ESLint fixer but It did not work for me :(

you can do `npm run fix` it should many for you if not if will show you the errors and you can fix them manually

2023-12-18 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-12-18 09:44 UTC, larkox commented
@Amir-Helali Are you able to look into this?

2023-12-21 02:27 UTC, Amir-Helali commented
@larkox sorry I've been very busy the past couple of weeks finishing up my semester and moving to a new place, so I didn't have access to my computer. I should finish my move by the end of this week and I'll have my computer up and running then. I can take a look at it early next week if that is ok.

2023-12-21 09:36 UTC, larkox commented
@Amir-Helali No problem. If you still want to work on this, feel free to take your time, and let us know when it is ready. For the time being I will remove the stale label.

2024-01-01 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-01-08 15:09 UTC, larkox commented
@Amir-Helali Have you got any chance to look into this? Checking on you just because the automation put back the stale tag. If you need more time just let me know.

2024-01-08 18:28 UTC, Amir-Helali commented
@larkox Hi Daniel, unfortunately my dad was hospitalized during the holidays and I haven't had the time to do any work. I think I'll have my hands full for a couple of more weeks at least with taking care of him, so I won't have the time to work on this.

2024-01-10 15:05 UTC, larkox commented
@Amir-Helali I am really sorry to hear that. Do not worry. I will probably take over this PR and make it through the finish line. Take the time you need to take care of him.

2024-01-10 17:01 UTC, Amir-Helali commented
@larkox thank you very much. Sorry I couldn't finish the whole thing.

2024-01-10 17:03 UTC, larkox commented
@Amir-Helali Don't be sorry. Life happens. I am glad you did your best while you were able. Now focus on what is important now :smile:

2024-04-05 16:03 UTC, larkox commented
/update-branch

2024-04-08 09:33 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-04-08 09:34 UTC, mattermost-build commented
You don't have permissions to trigger this command.
 It's only available for organization members.

2024-04-08 09:36 UTC, larkox commented
@yasserfaraazkhan This is mainly used on the bool settings in the interactive dialog, so running dialog command of the demo plugin and see everything looks nice there should be enough.

2024-04-08 11:53 UTC, yasserfaraazkhan approved these changes

2024-04-08 11:54 UTC, merged

2024-04-08 11:54 UTC, larkox commented
Thank you @Amir-Helali For your work here :smile: