[MM-56006] Convert ./components/discard_changes_modal.tsx from Class Component to Function Component
mattermost/mattermost pull request #25620
Opened 2023-12-04 10:06 UTC by Alpha-4

**Summary**
Fixes https://github.com/mattermost/mattermost/issues/25598

**Ticket Link**
JIRA LINK: https://mattermost.atlassian.net/browse/MM-56006

**QA Notes**
Component is converted to React Functional Component, no change in functionality is expected. Component appears on Admin Console.

```release-note
NONE
```

2023-12-04 10:06 UTC, mattermost-build commented
Hello @Alpha-4,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-12-04 11:10 UTC, larkox requested changes
Great work! Just one minor style thing.

2023-12-04 11:10 UTC, larkox commented on webapp/channels/src/components/discard_changes_modal.tsx
> +const DiscardChangesModal = ({show, onConfirm, onCancel}: Props) => {
Just to follow the pattern we follow in other files, put each argument in a different line:

```suggestion
const DiscardChangesModal = ({
    show,
    onConfirm,
    onCancel,
}: Props) => {
```

This makes it easier in the future to recognize in a glance what props have been added / removed by a change.

2023-12-04 16:50 UTC, yasserfaraazkhan commented
/e2e-tests

2023-12-04 16:50 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/393733) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/393733)

2023-12-04 19:04 UTC, yasserfaraazkhan approved these changes
tested in console by changing teams, channels data.
The discard changes works as expected.

2023-12-05 09:29 UTC, merged

2023-12-05 09:29 UTC, larkox commented
Thank you for the contribution!