[MM-56005] Convert `./components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.tsx` from Class Component to Function Component
mattermost/mattermost pull request #25646
Opened 2023-12-06 08:34 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings/team_in_list/team_in_list.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25597
Jira https://mattermost.atlassian.net/browse/MM-56005

#### Release Note

```release-note
NONE
```

2023-12-06 08:35 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-12-06 09:40 UTC, larkox requested changes
Great work! Just 2 minor things.

2023-12-06 09:40 UTC, larkox commented on webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.tsx
> +const TeamInList = ({team, isDisabled, onRemoveTeam}: Props) => {
Can you put each prop in a different line?
```suggestion
const TeamInList = ({
    team,
    isDisabled,
    onRemoveTeam,
}: Props) => {
```

2023-12-06 09:40 UTC, larkox commented on webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.tsx
> +                className={isDisabled ? 'remove disabled' : 'remove'}
Can we change this to use `classnames`? (you can see how it is used in other files in the codebase)

If I remember correctly, it should be something like `classnames('remove', {disabled: isDisabled})`.

2023-12-06 09:48 UTC, larkox approved these changes

2023-12-07 22:09 UTC, hmhealey approved these changes
Thanks for the PR. This looks good to me!

2023-12-08 14:37 UTC, merged