[MM-56004] Convert `./components/post_view/new_message_separator/new_message_separator.tsx`  from Class Component to Function Component
mattermost/mattermost pull request #25647
Opened 2023-12-06 08:44 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/post_view/new_message_separator/new_message_separator.tsx`  from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25596
Jira https://mattermost.atlassian.net/browse/MM-56004

#### Release Note

```release-note
NONE
```

2023-12-06 08:44 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-12-06 09:37 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-12-06 09:37 UTC, larkox approved these changes
Great work!

2023-12-11 06:33 UTC, M-ZubairAhmed requested changes

2023-12-11 06:33 UTC, M-ZubairAhmed commented on webapp/channels/src/components/post_view/new_message_separator/new_message_separator.tsx
> +            ref={wrapperRef}
i dont think ref can be passed this way, dont we have to use forwardRef? cc @larkox

2023-12-14 08:40 UTC, larkox commented
/update-branch

2023-12-25 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2023-12-25 07:30 UTC, M-ZubairAhmed approved these changes

2024-01-05 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-01-08 07:50 UTC, lindy65 approved these changes
Thanks @Syed-Ali-Abbas-Zaidi - looks good to me 👍 

cc// @M-ZubairAhmed

2024-01-08 10:13 UTC, merged