Fix MM53181
mattermost/mattermost pull request #25684
Opened 2023-12-11 16:48 UTC by larkox

#### Summary
Fix MM53181

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-53181

#### Release Note
```release-note
NONE
```

2023-12-12 11:20 UTC, jupenur approved these changes

2023-12-12 19:25 UTC, hmhealey approved these changes

2023-12-13 07:11 UTC, harshilsharma63 requested changes

2023-12-13 07:11 UTC, harshilsharma63 commented on server/channels/app/post.go
> +
Can we add a test for this so we don't accidently break it again later?

2023-12-13 09:56 UTC, larkox commented
@jupenur heads up that I added a minor "safeguard" to some other places where we are "doing the same". Probably won't change much the result, but better safe than sorry :smile:

2023-12-14 06:18 UTC, harshilsharma63 approved these changes
Looks good!

2023-12-14 08:32 UTC, merged

2023-12-14 18:16 UTC, amyblais commented
/cherry-pick release-9.4

2024-01-10 15:40 UTC, amyblais commented
/cherry-pick release-8.1

2024-01-10 15:40 UTC, mattermost-build commented
Cherry pick is scheduled.

2024-01-10 15:40 UTC, mattermost-build commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-#25684-upstream-release-8.1-1704901221
Switched to a new branch 'automated-cherry-pick-of-mattermost-#25684-upstream-release-8.1-1704901221'
Branch 'automated-cherry-pick-of-mattermost-#25684-upstream-release-8.1-1704901221' set up to track remote branch 'release-8.1' from 'upstream'.

+++ About to attempt cherry pick of PR #25684 with merge commit 917a032baf421a112b2fedc1e3cbcc7ff70f466d.

Auto-merging server/channels/app/post.go
CONFLICT (content): Merge conflict in server/channels/app/post.go
Auto-merging server/channels/app/post_test.go
error: could not apply 917a032baf... Fix MM53181 (#25684)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

+++ Conflicts detected:

UU server/channels/app/post.go
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```