[MM-56295] Convert `./components/post_view/message_attachments/message_attachment_list.tsx` from Class Component to Function Component
mattermost/mattermost pull request #25767
Opened 2023-12-18 17:06 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/post_view/message_attachments/message_attachment_list.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25757
Jira https://mattermost.atlassian.net/browse/MM-56295

#### Release Note

```release-note
NONE
```

2023-12-18 17:06 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-12-19 10:00 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-12-19 10:03 UTC, larkox requested changes
One minor change, but looks great!

2023-12-19 10:03 UTC, larkox commented on webapp/channels/src/components/post_view/message_attachments/message_attachment_list.tsx
> +    imagesMetadata = {},
To make sure the default is always the same, you can define outside of the component something like `const EMPTY_METADATA: Record<string, PostImage> = {};` and use that here. That way, the default is always the same reference, and you avoid potential re-renders down the line.

2023-12-19 14:13 UTC, larkox approved these changes

2023-12-20 10:41 UTC, Syed-Ali-Abbas-Zaidi commented
/update-branch

2023-12-21 10:12 UTC, harshilsharma63 approved these changes
👌👌👌

2023-12-21 10:12 UTC, merged