[MM-56290] Convert `./components/channel_header_dropdown/menu_items/toggle_favorite_channel/toggle_favorite_channel.tsx` from Class Component to Function Component
mattermost/mattermost pull request #25762
Opened 2023-12-18 16:41 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/channel_header_dropdown/menu_items/toggle_favorite_channel/toggle_favorite_channel.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25752
Jira https://mattermost.atlassian.net/browse/MM-56290

#### Release Note

```release-note
NONE
```

2023-12-18 16:41 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-12-19 09:58 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-12-19 23:02 UTC, hmhealey requested changes
Thanks for the PR, @Syed-Ali-Abbas-Zaidi! This looks good to me, but the snapshot tests for this component need to be updated. Would you mind doing that?

Generally, you can run `npm run test:updatesnapshot` to update the snapshots for all tests, although in this case, you could instead run `npm test -w channels -- -u components/channel_header_dropdown` to update just the snapshots for this component

2023-12-25 07:36 UTC, M-ZubairAhmed approved these changes

2024-01-03 09:25 UTC, yasserfaraazkhan approved these changes

2024-01-05 16:57 UTC, hmhealey commented
Thanks again for the PR!

2024-01-05 16:57 UTC, merged