[MM-56296] Convert `./components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx` from Class Component to Function Component
mattermost/mattermost pull request #25768
Opened 2023-12-18 17:17 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25758
Jira https://mattermost.atlassian.net/browse/MM-56296

#### Release Note

```release-note
NONE
```

2023-12-18 17:17 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2023-12-19 09:54 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2023-12-19 09:58 UTC, larkox requested changes
One minor change, but looks great!

2023-12-19 09:58 UTC, larkox commented on webapp/channels/src/components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx
> +    }, [membersCount]);
Since we are calling the function in line 62 instead of passing it as a prop, it is safe not to use a useCallback here.

2023-12-19 14:14 UTC, larkox approved these changes

2023-12-25 07:39 UTC, M-ZubairAhmed approved these changes

2024-01-05 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-01-08 15:17 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/401587) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/401587)

2024-01-08 19:07 UTC, yasserfaraazkhan approved these changes

2024-01-09 14:24 UTC, merged