Fixed user reporting pagination
mattermost/mattermost pull request #25780
Opened 2023-12-19 10:45 UTC by harshilsharma63

#### Summary
Fixed issue where no results were returned when sorting in descending order, and going to previous page didn't work.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-56281

#### Release Note
```release-note
none
```

2023-12-19 12:39 UTC, larkox approved these changes
LGTM, just two small considerations

2023-12-19 12:39 UTC, larkox commented on server/channels/store/sqlstore/user_store.go
> +	query = query.OrderBy(filter.SortColumn+" "+sortDirection, "u.Id")
Nit: using `fmt.Sprintf` may make this a bit more legible, but 0/5.

2023-12-19 12:39 UTC, larkox commented on server/channels/store/sqlstore/user_store.go
> +
Is it cheaper to reverse on database than reverse on memory?

2023-12-20 13:38 UTC, M-ZubairAhmed requested changes

2023-12-20 13:38 UTC, M-ZubairAhmed commented on server/channels/store/sqlstore/user_store.go
> +	if filter.Direction == "up" {
we thought of renaming these to prev/next, can we do that in this PR or next

2024-01-02 15:40 UTC, M-ZubairAhmed approved these changes

2024-01-02 15:41 UTC, merged