MM-40045 add checks for admin user in PermanentDeleteUser
mattermost/mattermost pull request #25813
Opened 2023-12-24 06:46 UTC by titanventura

#### Summary

#### Ticket Link

#### Screenshots

#### Release Note

```release-note

```

2023-12-24 06:46 UTC, mattermost-build commented
Hello @titanventura,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-01-04 13:30 UTC, hanzei commented
Some tests are failing. Could you please take a look?

2024-01-13 15:55 UTC, titanventura commented
let me know if there is anything else @hanzei

2024-01-22 08:12 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2024-01-22 10:53 UTC, hanzei commented
/update-branch

2024-02-05 16:55 UTC, hmhealey commented
/update-branch

2024-02-05 19:09 UTC, hmhealey commented
@titanventura Sorry for the lack of responses. I think there's been some hesitation on reviewing this since it was assumed the tests were still broken and then when we went to re-run those, it appeared that the tests were broken by something in the enterprise code which is why people kept merging the latest version of master into the branch.

Despite all that, there is actually one remaining failure I'm seeing which is that your PR adds some new error messages to the code without adding them to `server/i18n/en.json`. Could you run `make i18n-extract` in the `server` folder and then update that file with an English message for both of those errors?

2024-02-06 02:24 UTC, titanventura commented
Thanks for the review @hmhealey . And sure, will make the changes !

2024-02-07 16:25 UTC, hmhealey commented
Thanks for updating that, but it looks like your editor has made some changes to the whitespace in that file which the i18n tooling is now complaining about. I forgot to mention it but you can run `make i18n-check` to locally check what the CI pipeline is checking

2024-02-18 04:39 UTC, titanventura commented
reference: https://community.mattermost.com/core/pl/n361swdsmb8hurkrpzbbhqizsa

2024-03-06 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-03-21 10:20 UTC, isacikgoz commented
/update-branch

2024-03-21 15:27 UTC, isacikgoz requested changes
Sorry for the late review, this was way below my queue and not sure how it got there. Anyway, I'm requesting changes on design of this feature. Feel free to reach me out at https://community.mattermost.com for further clarification if that's necessary.

2024-03-21 15:27 UTC, isacikgoz commented on server/channels/api4/user_test.go
> +		require.Nil(t, appErr)
Why do we delete the basic team, can you elaborate that please?

2024-03-21 15:27 UTC, isacikgoz commented on server/channels/store/sqlstore/team_store.go
> +	}
This request should've been checked by the permissions, and here the team e-mail is not reliable source. I would rather rely on permissions system.

2024-03-21 15:27 UTC, isacikgoz commented on server/channels/app/user.go
> +	isUserAdminOfTeam, isUserAdminOfTeamErr := a.Srv().Store().Team().IsUserAdminOfTeam(user.Email)
See my comment on the store method, this should be handled with the permissions. Also, I would try to tackle this issue within the API layer if possible.

2024-04-29 17:50 UTC, closed without merging