[MM-56065] Fix missing search results when clicking on a hashtag in a text message
mattermost/mattermost pull request #26011
Opened 2024-01-23 09:21 UTC by trangology

#### Summary
While hashtags in the `text` and `pretext` of the `attachments` field aren't parsed and saved into the DB, the search query looks for a hashtag in the DB, more specifically, in the `Hashtag` column of the `Post` table. This has led to the missing search results.

To solve the issue, this PR parses hashtags in both the text & pretext of the "attachments" field and then adds them to the post hashtags.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/25705
Jira https://mattermost.atlassian.net/browse/MM-56065

#### Screenshots
|  Channel View  |  Search Results  |
|----|----|
| <img width="317" alt="Screenshot 2024-01-22 at 19 50 20" src="https://github.com/mattermost/mattermost/assets/37827647/ca92e88e-1220-4137-8b2b-3ad15865fb22"> | <img width="400" alt="Screenshot 2024-01-22 at 19 46 28" src="https://github.com/mattermost/mattermost/assets/37827647/208e2260-1395-44c3-bf27-aa0b0f8e431b"> |

#### Release Note
```
NONE
```

2024-01-24 14:26 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2024-02-04 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-02-21 14:29 UTC, trangology commented
Hi @streamer45, @calebroseland. Could you please take some time to review this PR?

2024-02-21 22:33 UTC, calebroseland commented
/update-branch

2024-02-23 21:34 UTC, calebroseland requested changes
Hi @trangology, apologies for the delay in reviewing this.

This currently only processes hashtags in attachments during post creation, and not also in `UpdatePost`, during importing posts, etc.

I think `ParseHashtags` should probably handle the final `hashtags` result, because it already takes the max length into account. Perhaps the combined contents of all `attachment.Pretext`s and `attachment.Text`s could be combined with `post.Message`? e.g. something like `... = model.ParseHashtags(messageAndAttachmentsText)`?

Then if updated where `ParseHashtags` is currently called, this would probably then handle hashtags in the other flows (post edit, imports, etc.), too.

Also, if at all possible, it would be nice to see unit tests added where necessary.

2024-02-23 21:34 UTC, calebroseland commented on server/channels/app/post.go
> +
Hashtags is limited to a length of 1000, this doesn't currently take that into account.

2024-03-02 11:59 UTC, trangology commented
Hi @calebroseland, thanks for the review! 

> This currently only processes hashtags in attachments during post creation, and not also in UpdatePost, during importing posts, etc.

Do you mean besides `CreatePost`, hashtags in `UpdatePost` and other post-related implementations should be parsed as well?

> I think ParseHashtags should probably handle the final hashtags result, because it already takes the max length into account. Perhaps the combined contents of all attachment.Pretexts and attachment.Texts could be combined with post.Message? e.g. something like ... = model.ParseHashtags(messageAndAttachmentsText)?

This makes sense to me.

> Then if updated where ParseHashtags is currently called, this would probably then handle hashtags in the other flows (post edit, imports, etc.), too.

Yeah I think I should probably make the change in another place, rather than the `CreatePost` function.

> Also, if at all possible, it would be nice to see unit tests added where necessary.

Sure, I'll try to write some unit tests.

2024-03-13 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2026-04-29 14:56 UTC, lieut-data commented
Closing an old pull request. If the root cause remains an issue, feel free to reopen as needed!

2026-04-29 14:56 UTC, closed without merging