[MM-56589] Add activation status filter menu to the filter popover to the users admin table
mattermost/mattermost pull request #26013
Opened 2024-01-23 12:23 UTC by M-ZubairAhmed

#### Summary

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56589

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-01-23 12:23 UTC, M-ZubairAhmed commented
/update-branch

2024-01-23 22:21 UTC, devinbinnie requested changes

2024-01-23 22:21 UTC, devinbinnie commented on webapp/channels/src/components/admin_console/system_users/system_users_search/index.tsx
> +    const [inputValue, setInputValue] = useState(props.searchTerm);
Is there a reason we are prop drilling this instead of grabbing it from redux? Does it matter?

2024-01-23 22:21 UTC, devinbinnie commented on webapp/channels/src/reducers/views/admin.ts
> +    filterStatus: '',
We don't need a default value for this. If there's nothing that we want to filter on, should this not be `undefined`?

2024-01-25 13:01 UTC, M-ZubairAhmed commented
closing in favour of https://github.com/mattermost/mattermost/pull/26042

2024-01-25 13:01 UTC, closed without merging