Mm 21466 mmctl delete users cmd bis
mattermost/mattermost pull request #26103
Opened 2024-02-03 13:50 UTC by IronOnet

Summary

This PR implements a refactor of the deleteUsersCmdF, the aim of the
refactor improve error handling for this function
Ticket Link, it is a replacement for this one: https://github.com/mattermost/mattermost/pull/24585

Fixes https://github.com/mattermost/mattermost/issues/21466
Jira https://mattermost.atlassian.net/browse/MM-47820
Release Note

NONE

2024-02-03 13:50 UTC, mattermost-build commented
Hello @IronOnet,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-02-03 13:51 UTC, IronOnet commented
@mgdelacroix @isacikgoz can you review this one?

2024-02-05 16:12 UTC, isacikgoz requested changes
Thanks @IronOnet! Can you please address the comments below? Seems like there could be some further improvements.

2024-02-05 16:12 UTC, isacikgoz commented on server/cmd/mmctl/commands/user.go
> +			return err
Trailing space here, better to remove.

2024-02-05 16:12 UTC, isacikgoz commented on server/cmd/mmctl/commands/user.go
> +				err = errors.New("There were issues with deleting profile image of the user. Please delete it manually. Id: " + user.Id)
Is this valid for only profile picture deletions? Might wanna be more general on the error?
```suggestion
				err = fmt.Errorf("deletion for user %s is partially done, check the server logs", user.Id)
```

2024-02-05 16:12 UTC, isacikgoz commented on server/cmd/mmctl/commands/user.go
>  				printer.PrintError("There were issues with deleting profile image of the user. Please delete it manually. Id: " + user.Id)
We might want to remove this as errors should anyway printed once the function returns. Can you check whether there is a duplication or not?

2024-02-16 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-03-25 08:15 UTC, hanzei commented
@IronOnet Do you have any questions regarding the feedback?

2025-02-25 10:17 UTC, closed without merging