[MM-56683] Auto select first emoji in emoji picker
mattermost/mattermost pull request #26165
Opened 2024-02-08 13:37 UTC by yeoji

#### Summary
- Auto selects the first emoji in the emoji picker so the user can press enter to insert the first emoji without navigating with the arrow keys

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/26119

#### Screenshots
![Screenshot 2024-02-09 at 12 29 12 am](https://github.com/mattermost/mattermost/assets/8002179/ad056af7-5fad-4d2a-9a36-7d89b76dbfdb)
![Screenshot 2024-02-09 at 12 29 31 am](https://github.com/mattermost/mattermost/assets/8002179/2cf4d97a-056a-4637-a332-ed8846e44e68)

#### Release Note
```
First emoji is auto selected in the emoji picker
```

2024-02-08 13:37 UTC, mattermost-build commented
Hello @yeoji,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-02-08 14:49 UTC, devinbinnie requested changes
Thanks @yeoji this works great!
I have a few small style comments, but otherwise LGTM!

2024-02-08 14:49 UTC, devinbinnie commented on webapp/channels/src/components/emoji_picker/emoji_picker.tsx
> +        if (!firstEmoji) {
We can just check falsy on `emojiPositions[0]` to simplify
```suggestion
        if (!emojiPositions[0]) {
```

2024-02-08 14:49 UTC, devinbinnie commented on webapp/channels/src/components/emoji_picker/emoji_picker.tsx
> +        const cursorEmoji = getEmojiById(firstEmoji.emojiId);
We're already destructuring props above, so calling this one as `firstEmoji.emojiId` seems redundant.

I'm okay with either or, but if we're destructuring already we should use those.
```suggestion
        const cursorEmoji = getEmojiById(emojiId);
```

2024-02-08 14:49 UTC, devinbinnie commented on webapp/channels/src/components/emoji_picker/emoji_picker.tsx
> +        const {rowIndex, emojiId} = firstEmoji;
As per above:
```suggestion
        const {rowIndex, emojiId} = emojiPositions[0];
```

2024-02-08 22:01 UTC, yeoji commented
Thanks for the feedback @devinbinnie Have made the changes :)

2024-02-09 14:34 UTC, devinbinnie commented
@M-ZubairAhmed I think we're okay to skip UX review for this one - the change is pretty straight forward and matches what we expect. We can have @yasserfaraazkhan do a quick QA pass in case there's any cases we missed.

2024-02-09 16:02 UTC, yasserfaraazkhan approved these changes
works as expected on web and Mac desktop 5.6.

<img width="187" alt="Screenshot 2024-02-09 at 9 28 27 PM" src="https://github.com/mattermost/mattermost/assets/15979783/8c193258-d040-486d-9da2-da1ca537aa99">

2024-02-09 19:05 UTC, M-ZubairAhmed approved these changes

2024-02-09 19:41 UTC, merged