MM-56625: Use patchConfig to update configs from system console
mattermost/mattermost pull request #26332
Opened 2024-02-29 06:25 UTC by agnivade

While updating config from admin console, the webapp would set
any config param to null if the user doesn't have permission to edit
that setting.

This is common in cloud environments where a lot of config settings
are set to `cloud_restrictable`.

The problem due to that is since the client uses the updateConfig
endpoint, this acts as a full config replace and therefore, the null
fields get replaced by their default values.

To fix this, we use the patch endpoint which only updates the fields
that are actually set.

https://mattermost.atlassian.net/browse/MM-56625

```release-note
Fix a bug where config cannot be updated from admin console
in cloud environments.
```

2024-02-29 06:26 UTC, agnivade commented
I found two separate bugs related to the admin console that happens only in cloud envs. Lots of untested code paths there.

1. Trying to load the database section crashes the webapp because SqlSettings aren't available in cloud licenses.
2. Trying to type "data retention" in the search bar of admin console also crashes the webapp.

2024-02-29 14:38 UTC, nickmisasi approved these changes
LGTM! Thanks!

2024-02-29 15:47 UTC, M-ZubairAhmed commented
/update-branch

2024-02-29 22:27 UTC, hmhealey requested changes

2024-02-29 22:27 UTC, hmhealey commented on webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
Could you actually remove the old `updateConfig` action and any corresponding tests that it might still have? I can't imagine we're going to want to use it after this since that seems like it would likely reintroduce the same issue.

You should still leave the `Client4` method for it though since that should stay for as long as the server still supports that endpoint

2024-03-04 04:09 UTC, agnivade commented
/e2e-test

2024-03-04 04:09 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](http://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/411962) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/411962)

2024-03-05 03:31 UTC, mattermost-build commented
You don't have permissions to trigger this command.
 It's only available for organization members.

2024-03-08 15:49 UTC, DHaussermann approved these changes
Tested and passed
- Confirmed that once the code change was applied, values such as `TLSCertFile` do not get reverted when there is a cloud license applied and the system console is saved. 
- Tested this for all areas listed in the ticket (Terms of Service, Data Retention, Plugin Settings, Open id and post time limit)
- Using details provided in the Jira ticket, I spot checked some the other fields besides `TLSCertFile` to ensure the values are preserved as expected.  
- No issues found

LGTM!

2024-03-08 15:51 UTC, merged

2024-03-08 15:52 UTC, agnivade commented
@amyblais - This is a serious bug, but it _only_ affects cloud installations. Since no cloud customer has reported this, I'll leave it to you to decide whether this warrants a hotfix release or not.

2024-03-12 12:51 UTC, amyblais commented
/cherry-pick release-9.6

2024-03-12 12:51 UTC, mattermost-build commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
From github.com:mattermost/mattermost
   00dc59f39e..7a132b40d2  MM-56609-headers -> upstream/MM-56609-headers
   f85aad9db2..0f5686b55b  bookmarks        -> upstream/bookmarks
 * [new branch]            cacheNaming      -> upstream/cacheNaming
   c308f1f4c9..ca26cd3ff6  dbRPCPerPlugin   -> upstream/dbRPCPerPlugin
 * [new branch]            fix_e2e_script_for_macos -> upstream/fix_e2e_script_for_macos
   75f0b99298..76bab25199  master           -> upstream/master
   ff70cd5a8e..eec2853da2  profile-popover-floating -> upstream/profile-popover-floating
   cc0beb3908..571a78ab9f  release-9.7      -> upstream/release-9.7
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-#26332-upstream-release-9.6-1710247869
Switched to a new branch 'automated-cherry-pick-of-mattermost-#26332-upstream-release-9.6-1710247869'
Branch 'automated-cherry-pick-of-mattermost-#26332-upstream-release-9.6-1710247869' set up to track remote branch 'release-9.6' from 'upstream'.

+++ About to attempt cherry pick of PR #26332 with merge commit f34445a6f4946ad19c24064d23ebe196f76bc7cf.

Auto-merging webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
Auto-merging webapp/channels/src/components/admin_console/schema_admin_settings.test.jsx
CONFLICT (content): Merge conflict in webapp/channels/src/components/admin_console/schema_admin_settings.test.jsx
Auto-merging webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Auto-merging webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
error: could not apply f34445a6f4... MM-56625: Use patchConfig to update configs from system console (#26332)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

+++ Conflicts detected:

UU webapp/channels/src/components/admin_console/schema_admin_settings.test.jsx
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2024-03-12 12:51 UTC, amyblais commented
@agnivade Looks like it needs a manual cherry-pick PR for ``release-9.6`` branch.