Added log to show which URL is blocked by CORS.
mattermost/mattermost pull request #26347
Opened 2024-02-29 20:10 UTC by Aryakoste

#### Summary

Added log which shows which url is blocked by Cross Origin.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26235
Jira https://mattermost.atlassian.net/browse/MM-56662

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-02-29 20:10 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-03-05 15:22 UTC, hanzei requested changes
Thanks for the PR @Aryakoste :tada:

2024-03-05 15:22 UTC, hanzei commented on server/channels/api4/websocket.go
> +
The change is fine, but the downside of how it's implemented is that `upgrader.CheckOrigin` gets called twice. I wonder if we can get the log message into the checker method. Is it an option to pass a logger to `c.App.OriginChecker` and log the warning in there?

2024-03-05 15:23 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2024-03-11 08:27 UTC, hanzei approved these changes
Nice work :+1:

2024-03-12 04:41 UTC, agnivade requested changes
I think this would be the wrong place to add the URL. The better place is to add the origin to the original log message which shows the failure, rather than splitting the info in two places.

Please see api4/websocket.go:L35, and then add a new param with the `r.Header["Origin"]`, and also modify the en.json accordingly to log the new param.

2024-03-14 04:04 UTC, agnivade reviewed
Looking good! Just some small things to take care of.

2024-03-14 04:04 UTC, agnivade commented on server/channels/app/server.go
> +func (a *App) OriginChecker(logger *mlog.Logger) func(*http.Request) bool {
We can revert this now.

2024-03-14 04:04 UTC, agnivade commented on server/channels/app/server.go
> +
Unnecessary newline

2024-03-15 03:09 UTC, agnivade commented on server/channels/app/server_test.go
> +		res := th.App.OriginChecker(th.TestLogger)(r)
This will need to be removed as well.

2024-03-25 08:51 UTC, hanzei commented
/update-branch

2024-03-25 10:17 UTC, hanzei commented
@Aryakoste heads up that `TestWebSocketUpgrade` is failing due to your changes. Please update the tets.

2024-03-25 12:35 UTC, Aryakoste commented
Done

2024-03-26 03:14 UTC, agnivade approved these changes
Thanks!

2024-03-26 03:14 UTC, agnivade commented
/e2e-test

2024-03-26 03:14 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](http://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/416262) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/416262)

2024-04-06 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-04-06 02:55 UTC, merged