[MM-56931] Date separator shows repeated when Saved RHS is open while in Threads view
mattermost/mattermost pull request #26627
Opened 2024-03-30 04:39 UTC by Karimaljandali

#### Summary
- Adds logic to `PostComponent` that will prevent duplicate `DateSeperator` tags when RHS is open the replies are consecutive posts.
- Adds unit test for the above logic

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/26591
Jira https://mattermost.atlassian.net/browse/MM-56931

#### Screenshots

|  before  |  after  |
|----|----|
| ![mm-56999-before](https://github.com/mattermost/mattermost/assets/18295079/faaaf7b2-9216-485d-8702-da9d1c19c62d)  | ![mm-56999-after](https://github.com/mattermost/mattermost/assets/18295079/520c9062-8571-4627-8499-dcc86a399a8f) |

#### Release Note

```
Fixes duplicate Date Separator bug on threads panel.
```

2024-03-30 04:39 UTC, mattermost-build commented
Hello @Karimaljandali,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-08 17:47 UTC, hmhealey requested changes
Thanks for the PR! This helps for some cases, but there area still extra date separators between posts by different users

![Screenshot 2024-04-08 at 1 37 24 PM](https://github.com/mattermost/mattermost/assets/3277310/0b790c4e-4dbe-4b80-a14f-48ff37ef93d0)

Instead of checking `isConsecutivePost`, I think this should probably be fixed by checking the `location` prop. I'm not sure why the condition for showing the `DateSeparator` is that complicated since I would expect it to just be `props.location === Locations.CENTER`. Could you maybe try changing that? I'll see if I can find some time to figure out why that condition is so complicated.

Also, could you merge the latest master branch into your PR? That should fix the failing CI check

2024-04-19 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-05-27 14:41 UTC, hmhealey commented
Hi @Karimaljandali. Do you have any questions about my comment above, or do you need any help on this? If you're not able to keep working on this, please let us know since we've had some other reports of this

2024-05-27 16:15 UTC, Karimaljandali commented
Hi @hmhealey unfortunately I don't have the time to work on this currently 😞

2024-05-29 21:21 UTC, hmhealey commented
No worries at all. We appreciate the work on this regardless, so thanks for that!

I'm going to close this and unassign the ticket from you, but I'll leave a link to this in case whoever picks it up wants to work off of it. If no one else grabs it and you want to pick it back up again, feel free to reopen this

2024-05-29 21:21 UTC, closed without merging

2024-05-30 10:18 UTC, MReza8 commented
greetings i would be more than happy to work on this