[MM-21473] Review archiveTeamsCmdF function to return an error in case of a failure
mattermost/mattermost pull request #26622
Opened 2024-03-28 16:27 UTC by TealWater

#### Summary

Used `multiError.Error` to return non-zero error values to the root handler when `mmctl` subcommand fail.  This PR involves only changing the `archiveTeamsCmdF` function.
#### Ticket Link

Fixes: https://github.com/mattermost/mattermost/issues/21473
#### Screenshots

#### Release Note

```release-note
none
```

2024-03-28 16:27 UTC, mattermost-build commented
Hello @TealWater,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-04 12:19 UTC, hanzei requested changes
Thanks for the contribution @TealWater

2024-04-04 12:19 UTC, hanzei commented on server/cmd/mmctl/commands/team.go
>  	return nil
`ErrorOrNil` makes this easier to read.

```suggestion
	return result.ErrorOrNil()
```

2024-04-04 12:19 UTC, hanzei commented on server/cmd/mmctl/commands/team.go
> +	var errorString multierror.Error
Let's stick to the naming schema for other methods.
```suggestion
	var result *multierror.Error
```

2024-04-04 15:32 UTC, hanzei approved these changes

2024-04-04 16:44 UTC, TealWater commented
@hanzei 

One of the tests for `mmctl` failed.  Here is the output:

```
Error Trace:	/mattermost/server/cmd/mmctl/commands/team_e2e_test.go:366
        	            				/mattermost/server/cmd/mmctl/commands/mmctl_test.go:92
        	            				/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
        	Error:      	Expected nil, but got: *multierror.Error{Errors:[]error{(*errors.errorString)(0xc00421aa00)}, ErrorFormat:(multierror.ErrorFormatFunc)(nil)}
```

I don't understand why this is an issue when we used `return result.ErrorOrNil()` which should return `nil`

not `*multierror.Error{Errors:[]error{(*errors.errorString)(0xc00421aa00)}, ErrorFormat:(multierror.ErrorFormatFunc)(nil)}`

2024-04-15 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-08-05 18:55 UTC, hanzei commented
/update-branch

2024-08-06 14:27 UTC, hanzei commented
@TealWater The tests need to be updated. You can see that searching for a team fails, and we log an error. (See https://github.com/TealWater/mattermost/blob/a6eae2577934216ef88ee0a14fbc5d9403c63e9c/server/cmd/mmctl/commands/team_e2e_test.go#L341-L345)

2024-08-06 21:49 UTC, TealWater commented
@hanzei 

Hmm, just a thought....

Given the fact that the error being returned is a string:

```
Error:      	Expected nil, but got: *multierror.Error{Errors:[]error{(*errors.errorString)(0xc00421aa00)}, ErrorFormat:(multierror.ErrorFormatFunc)(nil)}
```

Can I delete https://github.com/TealWater/mattermost/blob/a6eae2577934216ef88ee0a14fbc5d9403c63e9c/server/cmd/mmctl/commands/team_e2e_test.go#L370?

Maybe even require the type to `error.string`?

2024-08-12 06:51 UTC, hanzei commented
Comparing the actual error via `EqualError` is a fine approach. One simpler solution is to use the `Error` method and check that any error was returned instead of the the `Nil` check that exits today.

2024-08-13 14:36 UTC, hanzei approved these changes
LGTM :+1:

2024-08-13 14:38 UTC, BenCookie95 approved these changes

2024-08-13 14:49 UTC, merged