[MM-57724] Convert `./components/channel_header_dropdown/mobile_channel_header_dropdown.tsx` from Class Component to Function Component
mattermost/mattermost pull request #26719
Opened 2024-04-08 15:38 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26692
Jira https://mattermost.atlassian.net/browse/MM-57724

#### Release Note

```release-note
NONE
```

2024-04-08 15:38 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-09 08:47 UTC, larkox requested changes
Great work! Just one minor thing.

2024-04-09 08:47 UTC, larkox commented on webapp/channels/src/components/channel_header_dropdown/mobile_channel_header_dropdown.tsx
>  export default injectIntl(MobileChannelHeaderDropdown);
Let's remove the inject and use `useIntl` instead.

2024-04-09 13:25 UTC, devinbinnie approved these changes
LGTM other than @larkox's comment. Thanks @Syed-Ali-Abbas-Zaidi!

2024-04-09 14:28 UTC, larkox approved these changes
Looks great now!

2024-04-09 14:28 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2024-04-12 11:18 UTC, yasserfaraazkhan commented
/update-branch

2024-04-12 15:15 UTC, yasserfaraazkhan approved these changes

2024-04-15 07:47 UTC, merged