[MM-57718] Convert `./components/post_view/message_attachments/action_button/action_button.tsx` from Class Component to Function Component
mattermost/mattermost pull request #26728
Opened 2024-04-09 06:07 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/post_view/message_attachments/action_button/action_button.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26686
Jira https://mattermost.atlassian.net/browse/MM-57718

#### Release Note

```release-note
NONE
```

2024-04-09 06:07 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-09 08:26 UTC, larkox requested changes
Great work. Some minor changes requested :smile:

2024-04-09 08:26 UTC, larkox commented on webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
> +    const getStatusColors = (theme: Theme) => {
This doesn't depend on anything inside the component, so let's move it outside of the component.

2024-04-09 08:26 UTC, larkox commented on webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
> +            onClick={(e) => handleAction(e, action.options)}
Use a `useCallback` to avoid a new function on every render.

2024-04-09 08:26 UTC, larkox commented on webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
> +                    }}
Since this is the same on every render, let's move it also outside of the component, so we don't pass a new object on every render.

2024-04-22 10:49 UTC, larkox approved these changes

2024-04-24 18:42 UTC, hmhealey approved these changes
Looks good to me! Thanks for the PR

2024-04-24 18:43 UTC, merged