[MM-57725] Convert `./components/common/chip/chip.tsx` from Class Component to Function Component
mattermost/mattermost pull request #26729
Opened 2024-04-09 07:05 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/common/chip/chip.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26693
Jira https://mattermost.atlassian.net/browse/MM-57725

#### Release Note

```release-note
NONe
```

2024-04-09 07:05 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-09 08:49 UTC, larkox requested changes
A couple of minor things, but great work!

2024-04-09 08:49 UTC, larkox commented on webapp/channels/src/components/common/chip/chip.tsx
> +    const handleClick = (e: React.MouseEvent) => {
Use a `useCallback` to avoid passing new functions on every render.

2024-04-09 08:49 UTC, larkox commented on webapp/channels/src/components/common/chip/chip.tsx
> +                    emojiStyle={{marginRight: '11px'}}
Let's extract this to a constant outside of the component so we always pass the same object.

2024-04-22 10:46 UTC, larkox approved these changes

2024-04-23 04:58 UTC, harshilsharma63 approved these changes

2024-04-23 04:58 UTC, merged