[MM-57723] Convert `./components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx` from Class Component to Function Component
mattermost/mattermost pull request #26720
Opened 2024-04-08 18:49 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26691
Jira https://mattermost.atlassian.net/browse/MM-57723

#### Release Note

```release-note
NONE
```

2024-04-08 18:49 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-09 08:44 UTC, larkox requested changes
Great work, just one minor change.

2024-04-09 08:44 UTC, larkox commented on webapp/channels/src/components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx
> +                    ariaLabel={intl.formatMessage({id: 'team_members_dropdown.menuAriaLabel', defaultMessage: 'Change the role of a team member'})}
:heart:

2024-04-09 08:44 UTC, larkox commented on webapp/channels/src/components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx
> +                        onClick={() => doMakeUserTeamAdmin(team.id)}
Let's move the three `onClick`s to useCallback, to avoid passing a new function on every render.

2024-04-09 14:12 UTC, larkox requested changes
One more refactoring.

2024-04-09 14:12 UTC, larkox commented on webapp/channels/src/components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx
> +                        onClick={useCallback(() => doRemoveUserFromTeam(team.id), [team.id, doRemoveUserFromTeam])}
Can we move this out? As in...
```
const TeamListDropdown({...}: Props) => {
    ...
    const makeTeamAdminOnClick = useCallback(() => ...);
    const makeTeamMemberOnClick = useCallback(() => ...);

    return (
        ...
            <Menu.ItemAction
                ...
                onClick={makeTeamAdminOnClick}
            />
       ...
    );
};
```

It is a bit more verbose, but helps not breaking the rule of hooks in the future.

2024-04-09 14:20 UTC, larkox approved these changes
Great. Thanks for the changes!

2024-04-18 10:19 UTC, M-ZubairAhmed approved these changes

2024-04-18 11:01 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2024-04-21 18:55 UTC, yasserfaraazkhan approved these changes

2024-04-22 10:45 UTC, merged