[MM-57722] Convert `./components/admin_console/team_channel_settings/group/group_list.tsx` from Class Component to Function Component
mattermost/mattermost pull request #26721
Opened 2024-04-08 19:06 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26690
Jira https://mattermost.atlassian.net/browse/MM-57722

#### Release Note

```release-note
NONE
```

2024-04-08 19:06 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-09 08:42 UTC, larkox requested changes
Great work. Just a couple of minor things.

2024-04-09 08:42 UTC, larkox commented on webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.tsx
> +            {...props}
I feel we are passing here many things to abstract list that are not needed.
In particular, none of the props we are using here (`removeGroup`, `setNewGroupRole`, `type` or `isDisabled`) are expected in AbstractList. So we can change how we expand the props to do it like...

```
const GroupList = ({
    removeGroup,
    ...,
    ...restProps
}: Props) => {
    ...
    return (<AbstractList header={<Header/>} renderRow={renderRow} {...restProps} />);
};
```

2024-04-09 08:42 UTC, larkox commented on webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.tsx
> +    const renderRow = (item: Partial<Group>) => {
Use `useCallback` to avoid passing a new function on every render.

2024-04-09 20:20 UTC, hmhealey requested changes

2024-04-09 20:20 UTC, hmhealey commented on webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.tsx
> +const Header = () => (
Could you revert the changes to the `Header` component? They're not really needed, and they make it harder to see what's changing in this PR

2024-04-20 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-04-22 10:48 UTC, larkox approved these changes

2024-04-22 18:54 UTC, hmhealey approved these changes

2024-04-23 10:11 UTC, mattermost-build commented
You don't have permissions to trigger this command.
 It's only available for organization members.

2024-04-23 11:31 UTC, yasserfaraazkhan commented
/e2e-tests

2024-04-23 11:31 UTC, mattermost-build commented
Successfully triggered E2E testing!
[GitLab pipeline](http://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/422281) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/422281)

2024-04-23 19:03 UTC, yasserfaraazkhan commented
/e2e-tests

2024-04-23 19:03 UTC, mattermost-build commented
The command /e2e-test requires all PR checks to pass.

2024-04-24 06:26 UTC, yasserfaraazkhan approved these changes

2024-04-24 08:11 UTC, merged