[MM-57716] Convert `./components/setting_item.tsx` from Class Component to Function Component
mattermost/mattermost pull request #26828
Opened 2024-04-20 06:43 UTC by Syed-Ali-Abbas-Zaidi

#### Summary

Convert `./components/setting_item.tsx` from Class Component to Function Component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26684
Jira https://mattermost.atlassian.net/browse/MM-57716

#### Release Note

```release-note
NONE
```

2024-04-20 06:43 UTC, mattermost-build commented
Hello @Syed-Ali-Abbas-Zaidi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-22 06:33 UTC, M-ZubairAhmed reviewed
When QA this we have to be carefull we dont break the functions as commented here

> We want to bring back focus to the edit button when the section is opened and then closed along with all sections are closed

2024-04-22 07:50 UTC, larkox requested changes
Great work! A few changes.

2024-04-22 07:50 UTC, larkox commented on webapp/channels/src/components/setting_item.tsx
> +export default SettingItem;
Since this was a pure component, let's use a `memo` here.

2024-04-22 07:50 UTC, larkox commented on webapp/channels/src/components/setting_item.tsx
> +    const prevActive = useRef<boolean>(active);
Move this before the effect.

2024-04-22 07:50 UTC, larkox commented on webapp/channels/src/components/setting_item.tsx
> -        // We want to bring back focus to the edit button when the section is opened and then closed along with all sections are closed
Bring back this comment

2024-04-22 07:50 UTC, larkox commented on webapp/channels/src/components/setting_item.tsx
> +    useEffect(() => {
In the original logic, we only do this on update. We should already have a `useDidUpdate` hook.

2024-05-03 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-05-03 08:07 UTC, larkox commented
@Syed-Ali-Abbas-Zaidi Are you still working on this?

2024-06-29 08:54 UTC, larkox commented
Closing as stale, and reopening for contributions.

2024-06-29 08:54 UTC, closed without merging