Mm 45796 add channel member role commands to mmctl that manipulates channel member roles
mattermost/mattermost pull request #26844
Opened 2024-04-23 06:01 UTC by ezekielchow

#### Summary

Add command to mmctl that manipulates channel member roles

#### Ticket Link

Jira [MM-45796](https://mattermost.atlassian.net/browse/MM-45796)

#### Release Note

```release-note
NONE
```

2024-04-23 06:01 UTC, mattermost-build commented
Hello @ezekielchow,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-29 16:04 UTC, BenCookie95 commented
Hey @ezekielchow, let us know if you need any help getting this over the line!

2024-04-30 00:48 UTC, ezekielchow commented
> Hey @ezekielchow, let us know if you need any help getting this over the line!

I need help getting a conclusion for the susggestions in the issue [here](https://github.com/mattermost/mattermost/issues/26576#issuecomment-2065680506)

2024-05-21 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-09-30 15:53 UTC, BenCookie95 requested changes
@ezekielchow Very sorry this got lost at the bottom of my review list, just one comment and there are some conflicts. Thank you for the contribution

2024-09-30 15:53 UTC, BenCookie95 commented on server/cmd/mmctl/commands/channel_users_roles.go
> +	Example: `  channel users roles add myteam:mychannel userA,userB roleA,roleB
@ezekielchow Can you make it more clear as to how the command works please. On my first reading of this I thought userA was being assigned roleA and userB was being assigned roleB. It wasn't clear that userA and userB were being assigned both roles

2025-02-25 10:16 UTC, hanzei commented
@ezekielchow Do you still plan to work on this issue?

2025-03-19 13:07 UTC, ezekielchow commented
@BenCookie95 Hi, could i take up this task? I want to finish it

2025-03-19 13:26 UTC, BenCookie95 commented
> @BenCookie95 Hi, could i take up this task? I want to finish it

Yeah feel free to finish this up! Thanks

2025-03-20 08:43 UTC, ezekielchow commented on server/cmd/mmctl/commands/channel_users_roles.go
> +	Example: `  channel users roles add myteam:mychannel userA,userB roleA,roleB
@BenCookie95 I've updated the description. Please have a look

2025-04-14 08:42 UTC, hanzei commented
@ezekielchow Heads up that CI is failing. Please let me know if you need help fixing it.

2025-06-06 06:19 UTC, hanzei commented
@ezekielchow Are you still working on this PR?

2026-06-23 09:41 UTC, closed without merging