Get posts for a channel has_next attribute fix
mattermost/mattermost pull request #26901
Opened 2024-04-27 18:14 UTC by Aryakoste

#### Summary

Fixed the issue where has_next attribute always returned false. Made has_next attribute pointer and made changes accordingly.  

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26862
Jira https://mattermost.atlassian.net/browse/MM-57937

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-04-27 18:14 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-04-30 13:23 UTC, mattermost-build commented
E2E tests not automatically triggered, because the PR is not in a mergeable state. Please update the branch with the base branch and resolve outstanding conflicts.

2024-05-02 04:19 UTC, agnivade requested changes
Also, as I mentioned here: https://github.com/mattermost/mattermost/issues/26862#issuecomment-2075066486, please add a test in the getPostsForChannel API endpoint (see api4/post_test.go) and confirm that the pointer is nil in the response.

2024-05-02 04:19 UTC, agnivade commented on server/channels/store/storetest/post_store.go
> +		require.Nil(t, r1.HasNext)
These changes seem wrong. The assertion should still be true here. I would assume something like: `assert.True(t, *r1.HasNext)` after a `require.NotNil(t, r1.HasNext)`

2024-05-15 04:43 UTC, agnivade commented
@Aryakoste - please check the CI for failures

```
PASS channels/store/localcachelayer.TestPostStore/LocalCache+PostgreSQL/GetForThread/Post_threadmembership_does_not_exist (0.01s)
=== RUN   TestPostStore/LocalCache+PostgreSQL/GetForThread/Pagination
    post_store.go:796: 
        	Error Trace:	/mattermost/server/channels/store/storetest/post_store.go:796
        	Error:      	Should be true
        	Test:       	TestPostStore/LocalCache+PostgreSQL/GetForThread/Pagination
    post_store.go:812: 
        	Error Trace:	/mattermost/server/channels/store/storetest/post_store.go:812
        	Error:      	Should be true
        	Test:       	TestPostStore/LocalCache+PostgreSQL/GetForThread/Pagination
    post_store.go:864: 
        	Error Trace:	/mattermost/server/channels/store/storetest/post_store.go:864
        	Error:      	Should be true
        	Test:       	TestPostStore/LocalCache+PostgreSQL/GetForThread/Pagination
    post_store.go:881: 
        	Error Trace:	/mattermost/server/channels/store/storetest/post_store.go:881
        	Error:      	Should be true
        	Test:       	TestPostStore/LocalCache+PostgreSQL/GetForThread/Pagination
--- FAIL: TestPostStore/LocalCache+PostgreSQL/GetForThread/Pagination (0.02s)
```

The code needs to be changed as well for the tests to work.

2024-05-26 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-26 04:21 UTC, agnivade commented
@Aryakoste - Please feel free to request a review when this is ready. Thanks!

2024-07-02 06:11 UTC, agarciamontoro commented
Hey, @Aryakoste, let us know if we can help with this PR!

2024-07-02 17:50 UTC, agarciamontoro commented
Hey @Aryakoste! The first thing we need to check is whether the failing tests are valid. Let me take a look and I'll get back to you!

2024-07-05 16:17 UTC, agarciamontoro commented
I didn't have time to check this this week, and I'll be out next week, so it'll have to wait until the week after. Sorry!

2024-08-19 16:17 UTC, agarciamontoro requested changes
Sorry for the late response!

I just tested this locally, and I believe you need to revert the `False`->`True` changes you made to the tests (I added individual comments below where you need to revert). The only modification the tests need is the dereference of the pointer, which you already did. Can you fix the `False`->`True` changes and push so that we can check whether CI passes? Thanks!

2024-08-19 16:17 UTC, agarciamontoro commented on server/channels/store/storetest/post_store.go
> +		assert.True(t, *r1.HasNext)
```suggestion
		assert.False(t, *r1.HasNext)
```

2024-08-19 16:17 UTC, agarciamontoro commented on server/channels/store/storetest/post_store.go
> +		assert.True(t, *r1.HasNext)
```suggestion
		assert.False(t, *r1.HasNext)
```

2024-08-19 16:17 UTC, agarciamontoro commented on server/channels/store/storetest/post_store.go
> +		assert.True(t, *r1.HasNext)
```suggestion
		assert.False(t, *r1.HasNext)
```

2024-08-19 16:17 UTC, agarciamontoro commented on server/channels/store/storetest/post_store.go
> +		assert.True(t, *r1.HasNext)
```suggestion
		assert.False(t, *r1.HasNext)
```

2024-08-19 18:02 UTC, Aryakoste commented
Hello @agarciamontoro I have made the changes.

2024-08-20 08:35 UTC, agarciamontoro approved these changes
Things look good now! Thank you, @Aryakoste

2024-08-21 03:19 UTC, agnivade commented
/update-branch

2024-08-21 04:47 UTC, agnivade approved these changes
Thanks!

2024-08-21 04:47 UTC, agnivade commented
/e2e-test

2024-08-21 05:30 UTC, agnivade commented
E2E tests passed. Merging.

2024-08-21 05:30 UTC, merged

2024-08-21 15:29 UTC, agarciamontoro commented
Thank you for your work (and your patience!), @Aryakoste :tada: