[MM-57407] Add setting to disable the wake up on reconnect handler
mattermost/mattermost pull request #26924
Opened 2024-04-29 18:01 UTC by devinbinnie

#### Summary
There is an interval in the `team_controller` that checks every 30 seconds if it has run and updated its time, and if not it calls the `reconnect()` handler of the websocket (which just reloads a bunch of data). This is supposed to refresh the data in the front-end store after the computer wakes up, but it appears to be firing when the tab is in the background as well.

Given that we should be calling this anyways when the websocket reconnects, and that the websocket should stay connected until then, I think it makes sense to remove this interval altogether. However, since we can't be confident that removing this outright will not cause other issues, I've hidden it behind an experimental settings we can toggle on/off.

If this proves to cause no issues, we can remove the interval and the setting entirely.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57407

```release-note
NONE
```

2024-04-30 05:52 UTC, M-ZubairAhmed approved these changes

2024-04-30 22:26 UTC, hmhealey requested changes

2024-04-30 22:26 UTC, hmhealey commented on webapp/channels/src/components/team_controller/team_controller.tsx
> +        if (props.disableWakeUpReconnectHandler) {
`disableWakeUpReconnectHandler` should be a dependency of this hook so that it's started/stopped as the setting is changed

2024-05-02 16:46 UTC, streamer45 commented
More of a curiosity of mine. Was this sort of logic introduced in fear of the websocket connection being closed as the tab went in the background? I suppose the timer potentially being throttled could be adding another layer to this.

2024-05-02 17:29 UTC, devinbinnie commented
> More of a curiosity of mine. Was this sort of logic introduced in fear of the websocket connection being closed as the tab went in the background? I suppose the timer potentially being throttled could be adding another layer to this.

This logic has been around for much longer than myself, so I honestly don't know. My guess is that you're right and it was there to try and keep the connection alive.

2024-05-02 22:42 UTC, hmhealey commented
@streamer45 It's actually sort of the opposite of that. We didn't trust the WebSocket to properly detect that it had been disconnected after the computer had gone to sleep, so we used the interval under the assumption that it would only be delayed if the computer had gone to sleep. It's entirely possible that the interval could've been throttled back then though and we just never noticed. This dates back to https://github.com/mattermost/mattermost/pull/5120 if you're curious.

For whatever reason, we couldn't rely on the WS to accurately detect reconnects back then. I'm honestly not sure if we can rely on it for that now though, but I don't think I've ever investigated that or if I'm just remembering how we used to think it worked

2024-05-02 22:43 UTC, hmhealey approved these changes

2024-05-02 22:46 UTC, streamer45 commented
Thanks Harrison. The WebSocket is really a TCP connection underneath so it should timeout rather quickly if, for whatever reason, the browser/OS decides to drop the socket. I can't see a reason for forcing a reconnect when not in response to a `close` or `error` event on the socket.

2024-05-02 22:47 UTC, streamer45 approved these changes
Nice, looking forward to checking this on Community.

2024-05-03 13:06 UTC, merged

2024-05-03 17:57 UTC, hmhealey commented
I was pretty sure it was a TCP connection, so I've never been sure why we used to considered it so unstable. I have to assume that we must've been using it wrong back then, but because of that, we're stuck with a bunch of weird code like this reconnect timer which seem unnecessary.

Hopefully we can prove that it is unnecessary thanks to this PR :)