[PR] emoji position issue while editing message
mattermost/mattermost pull request #26952
Opened 2024-05-03 18:43 UTC by fasal26

Resolved emoji position issue while editing message

Fixes https://github.com/mattermost/mattermost/issues/26914

2024-05-03 18:43 UTC, mattermost-build commented
Hello @fasal26,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-05-07 08:54 UTC, M-ZubairAhmed requested changes
Can you please check the failing CIs

2024-05-16 13:56 UTC, marianunez requested changes
Requesting changes to move off my queue while these are addressed. @fasal26 let us know if you need any help on this

2024-05-20 08:38 UTC, fasal26 commented
Resolved 
Please verify @marianunez @M-ZubairAhmed

2024-05-24 13:37 UTC, marianunez approved these changes
Thanks @fasal26!

2024-05-27 00:58 UTC, M-ZubairAhmed approved these changes

2024-05-27 05:26 UTC, yasserfaraazkhan requested changes
@fasal26 can you take a look at this. 
I used arrow keys to move in between text and then insert emoji. They are still get appended to the end of the post

https://github.com/mattermost/mattermost/assets/15979783/61835673-b8e4-4d4e-807f-71d516f35710

2024-06-15 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-17 22:01 UTC, marianunez commented
@fasal26 let us know if you have any questions on the cases mentioned above that came up in QA

2025-01-16 15:52 UTC, marianunez commented
This has been fixed now with the refactoring of the edit post component. https://github.com/mattermost/mattermost/pull/29398 Closing this stale PR.

2025-01-16 15:52 UTC, closed without merging