[CLD-7724] Allow admin-set announcement banners to stack below system ones
mattermost/mattermost pull request #27171
Opened 2024-05-27 17:42 UTC by nickmisasi

#### Summary
Some users have a requirement to always display an admin-created banner to all users, at all times. This was problematic when a system banner was displayed to administrators, as those would take precedence over the administrator-set ones. This PR makes it so that any banners set by the administrators have their own placement, below that of any system banners. 

Note: this PR makes no changes to the behaviour of existing banners - they will still be displayed in the order of the announcement_bar_controller, it just added a special section to the CSS grid to display the administrator-configured announcements. 

#### Ticket Link

https://mattermost.atlassian.net/browse/CLD-7724

#### Screenshots
Before:
(An admin banner is configured, it's just not visible because it's behind the 3 days left in trial banner)
![image](https://github.com/mattermost/mattermost/assets/12176405/865e3165-6622-475e-baa2-4cc051891b33)

After
![image](https://github.com/mattermost/mattermost/assets/12176405/1d310806-1b2c-46b0-acea-2da91ba59455)

Without a system banner:
![image](https://github.com/mattermost/mattermost/assets/12176405/2d902a77-ee47-4173-ae13-de9c3ef7041f)

#### Release Note

```release-note

```

2024-05-27 17:43 UTC, asaadmahmood approved these changes
LGTM.

2024-05-28 07:59 UTC, larkox approved these changes
Codewise LGTM. Is there any possibility we can add unit tests to this?

2024-05-28 09:22 UTC, yasserfaraazkhan commented
/e2e-tests

2024-05-28 09:39 UTC, yasserfaraazkhan requested changes
<img width="800" alt="image" src="https://github.com/mattermost/mattermost/assets/15979783/bdcae7e0-69d8-45bb-aa15-5f0a9cfc686a">

Able to see the banners stacked up.

@nickmisasi can you check the `Allow Banner Dismissal`, when this is `true`, we dont see a `x` cross mark to dismiss this.

2024-05-28 17:20 UTC, nickmisasi commented
@yasserfaraazkhan should be fixed in the next update

@larkox I've added to the existing announcement_bar unit tests. Long term we probably want to look at some E2E tests for all of the various announcement bars, as they don't look to have any coverage right now.

2024-05-29 08:37 UTC, yasserfaraazkhan approved these changes
🎉

2024-05-29 21:50 UTC, hmhealey approved these changes

2024-05-29 23:18 UTC, merged

2024-06-03 13:46 UTC, mattermost-build commented
Cherry pick is scheduled.

2024-06-03 13:46 UTC, mattermost-build commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
From github.com:mattermost/mattermost
   a3f1e0cfdf..0330e475b6  MM-53491              -> upstream/MM-53491
   c86c672ac1..8f72c27de0  MM-56077              -> upstream/MM-56077
   e4d726b408..70248f9a34  MM-56904_getGMsForLoading -> upstream/MM-56904_getGMsForLoading
 * [new branch]            MM-58008-calls-mobile-ringing -> upstream/MM-58008-calls-mobile-ringing
 * [new branch]            MM-58275_double-proxying -> upstream/MM-58275_double-proxying
   b8a9bdc62c..5f7a14ab15  MM-58323-sanitize-sensitive-values-from-config -> upstream/MM-58323-sanitize-sensitive-values-from-config
   0cd5701543..9f5468f2aa  MM-58341              -> upstream/MM-58341
 * [new branch]            MM-58349_remote_user_no_login -> upstream/MM-58349_remote_user_no_login
   07e29c7a79..9d6e51b0ee  MM-58355              -> upstream/MM-58355
   9908225223..f84150802e  MM-58463              -> upstream/MM-58463
 * [new branch]            MM-58499-Remove-Bolding-For-Icons -> upstream/MM-58499-Remove-Bolding-For-Icons
   7af41a85e0..4edf8b2e85  emoji-tooltip         -> upstream/emoji-tooltip
 * [new branch]            fix/replace-hard-coded-http-verbs -> upstream/fix/replace-hard-coded-http-verbs
   2a21b695d3..b773bc1012  fixInitRerenders      -> upstream/fixInitRerenders
 * [new branch]            hh_may31-lastviewedat -> upstream/hh_may31-lastviewedat
   b561ac8cb2..4ec50a7ddd  master                -> upstream/master
 * [new branch]            patch-9.5.6           -> upstream/patch-9.5.6
   c9c3c5881d..01723a784c  release-9.5           -> upstream/release-9.5
   56a83723f1..69dc7902cc  release-9.6           -> upstream/release-9.6
   24df540c67..757d32081b  release-9.7           -> upstream/release-9.7
   7905e0afd1..d66fc50d21  release-9.8           -> upstream/release-9.8
   4179e17b49..e69a1ed79b  release-9.9           -> upstream/release-9.9
 * [new tag]               v9.5.6                -> v9.5.6
 * [new tag]               v9.9.0                -> v9.9.0
 * [new tag]               v9.9.0-rc4            -> v9.9.0-rc4
 * [new tag]               v9.6.3                -> v9.6.3
 * [new tag]               v9.7.5                -> v9.7.5
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-#27171-upstream-release-9.8-1717422407
Switched to a new branch 'automated-cherry-pick-of-mattermost-#27171-upstream-release-9.8-1717422407'
Branch 'automated-cherry-pick-of-mattermost-#27171-upstream-release-9.8-1717422407' set up to track remote branch 'release-9.8' from 'upstream'.

+++ About to attempt cherry pick of PR #27171 with merge commit 34c7b76fae7165bcefb984c57859aa6c21819a1f.

Auto-merging webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
Auto-merging webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
Auto-merging webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
Auto-merging webapp/channels/src/sass/base/_structure.scss
CONFLICT (content): Merge conflict in webapp/channels/src/sass/base/_structure.scss
Auto-merging webapp/channels/src/sass/components/_announcement-bar.scss
error: could not apply 34c7b76fae... [CLD-7724] Allow admin-set announcement banners to stack below system ones (#27171)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

+++ Conflicts detected:

UU webapp/channels/src/sass/base/_structure.scss
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2024-06-03 14:34 UTC, amyblais commented
/cherry-pick release-9.5

2024-06-03 14:34 UTC, mattermost-build commented
Cherry pick is scheduled.

2024-06-03 14:34 UTC, mattermost-build commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-#27171-upstream-release-9.5-1717425264
Switched to a new branch 'automated-cherry-pick-of-mattermost-#27171-upstream-release-9.5-1717425264'
Branch 'automated-cherry-pick-of-mattermost-#27171-upstream-release-9.5-1717425264' set up to track remote branch 'release-9.5' from 'upstream'.

+++ About to attempt cherry pick of PR #27171 with merge commit 34c7b76fae7165bcefb984c57859aa6c21819a1f.

Auto-merging webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
CONFLICT (content): Merge conflict in webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
Auto-merging webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
Auto-merging webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
Auto-merging webapp/channels/src/sass/base/_structure.scss
CONFLICT (content): Merge conflict in webapp/channels/src/sass/base/_structure.scss
Auto-merging webapp/channels/src/sass/components/_announcement-bar.scss
error: could not apply 34c7b76fae... [CLD-7724] Allow admin-set announcement banners to stack below system ones (#27171)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

+++ Conflicts detected:

UU webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
UU webapp/channels/src/sass/base/_structure.scss
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2024-06-03 14:34 UTC, amyblais commented
@nickmisasi Would you be able to help with a manual cherry-pick PR for ``release-9.5`` (ESR) branch?

2024-06-03 14:41 UTC, nickmisasi commented
@amyblais we'll need to base cherry picks for pre-9.8 on this one here: https://github.com/mattermost/mattermost/pull/27256