[MM-58442] Migrate tooltips of 'components/drafts/panel/panel_header' to WithTooltip
mattermost/mattermost pull request #27197
Opened 2024-05-29 16:42 UTC by ahmadJT

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27176
https://mattermost.atlassian.net/browse/MM-58442

#### Screenshots

#### Release Note

```release-note

```

2024-05-29 16:42 UTC, mattermost-build commented
Hello @ahmadJT,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-06-01 03:28 UTC, M-ZubairAhmed commented
/release-note-none

2024-06-01 03:30 UTC, M-ZubairAhmed requested changes

2024-06-01 03:30 UTC, M-ZubairAhmed commented on webapp/channels/src/components/drafts/panel/panel_header.tsx
> +                            }}
We should be using
```
<FormattedMessage
                id='drafts.info.sync'
                defaultMessage='Updated from another device'
            />
            ```

2024-06-12 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-19 12:20 UTC, M-ZubairAhmed commented
@ahmadJT can we get this to finish line

2024-06-20 07:04 UTC, M-ZubairAhmed commented
/update-branch

2024-06-20 07:04 UTC, M-ZubairAhmed approved these changes

2024-06-20 09:32 UTC, yasserfaraazkhan commented
/e2e-tests

2024-06-20 10:29 UTC, yasserfaraazkhan approved these changes

2024-06-21 16:40 UTC, merged