[MM-58410] Migrate tooltips of 'components/post/post_component' to WithTooltip
mattermost/mattermost pull request #27199
Opened 2024-05-29 17:46 UTC by ahmadJT

#### Summary

- [x] Migrate tooltips of 'components/post/post_component' to WithTooltip

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27153
https://mattermost.atlassian.net/browse/MM-58410

#### Screenshots

#### Release Note

```release-note

```

2024-05-29 17:46 UTC, mattermost-build commented
Hello @ahmadJT,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-06-01 03:36 UTC, M-ZubairAhmed requested changes

2024-06-01 03:36 UTC, M-ZubairAhmed commented on webapp/channels/src/components/post/post_component.tsx
> +                                        }}
Please add FormattedMessage component for it's translation to be extractable

2024-06-01 03:36 UTC, M-ZubairAhmed commented
/release-note-none

2024-06-12 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-15 08:03 UTC, M-ZubairAhmed commented
@ahmadJT can we get this to finish line?

2024-06-20 04:40 UTC, M-ZubairAhmed commented
/update-branch

2024-06-20 05:06 UTC, M-ZubairAhmed approved these changes

2024-06-20 05:07 UTC, M-ZubairAhmed commented
@Rajat-Dabade can you review this one out

2024-06-20 06:16 UTC, Rajat-Dabade approved these changes

2024-06-20 07:07 UTC, yasserfaraazkhan commented
/e2e-tests

2024-06-20 09:23 UTC, yasserfaraazkhan approved these changes
Hi @M-ZubairAhmed 
can you help in reviewing failing tests ?

I checked the message posts tool tips manually.

2024-06-24 08:45 UTC, M-ZubairAhmed commented
@yasserfaraazkhan i checked all the failing tests they are not due to any of the changes in this PR

2024-06-24 08:45 UTC, merged