[MM-58355] Send invalidate cache message across the cluster so that websocket connections on other instances are invalidated correctly
mattermost/mattermost pull request #27204
Opened 2024-05-30 15:42 UTC by devinbinnie

#### Summary
When a new channel is added to a channel (either to a regular channel, or created as part of a GM), the app is supposed to invalidate the caches for all users added to the channel. This behaviour was having issues due to for some reason the cache not being invalidated at the websocket level, and the websocket was deciding not to send events since it was under the impression that the user wasn't a channel member yet.

A quick fix I made was to just tell the app to send the event directly to the users added to the channel and not to broadcast across the channel. This fixed the issue around the `user_added` and `group_added` messages being missed, but then `POSTED` events were being missed as well, so we needed to fix the caching issue.

This was only happening in HA, and after some digging I found that we were just not sending the event across the cluster. So if you happened to be connected to the instance where the `user_added` event was created from, the cache would be invalidated, but if not then the cache would never update until you reset the websocket connection, or found another way to invalidate the cache somehow.

This PR sends that message explicitly, and removes the quick fix I did for `user_added`.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-58355

```release-note
Fixed an issue where cache invalidation messages for websocket connections were not being sent across the cluster, causing missed websocket events.
```

2024-05-30 20:35 UTC, devinbinnie commented
/update-branch

2024-05-31 04:18 UTC, agnivade requested changes
Wow, nice catch. I think I also found another bug similar to this. Some comments:

1. Just passing the cluster message like this will trigger `ClearSessionCacheForUserSkipClusterSend` which also calls `ps.ClearUserSessionCacheLocal`. So therefore, you will clear the session cache and webconn cache on all other nodes, but only clear webconn cache in the originating node. Assuming you want to clear both caches in all nodes, it would be something like this:
```diff
diff --git a/server/channels/app/platform/session.go b/server/channels/app/platform/session.go
index c01e520813..d019f93606 100644
--- a/server/channels/app/platform/session.go
+++ b/server/channels/app/platform/session.go
@@ -70,7 +70,7 @@ func (ps *PlatformService) ClearAllUsersSessionCacheLocal() {
 }

 func (ps *PlatformService) ClearUserSessionCache(userID string) {
-       ps.ClearUserSessionCacheLocal(userID)
+       ps.ClearSessionCacheForUserSkipClusterSend(userID)

        if ps.clusterIFace != nil {
                msg := &model.ClusterMessage{
diff --git a/server/channels/app/platform/web_hub.go b/server/channels/app/platform/web_hub.go
index 4dab982c41..6198479329 100644
--- a/server/channels/app/platform/web_hub.go
+++ b/server/channels/app/platform/web_hub.go
@@ -197,7 +197,7 @@ func (ps *PlatformService) InvalidateCacheForChannelPosts(channelID string) {

 func (ps *PlatformService) InvalidateCacheForUser(userID string) {
        ps.Store.Channel().InvalidateAllChannelMembersForUser(userID)
-       ps.invalidateWebConnSessionCacheForUser(userID)
+       ps.ClearUserSessionCache(userID)

        ps.Store.User().InvalidateProfilesInChannelCacheByUser(userID)
        ps.Store.User().InvalidateProfileCacheForUser(userID)
```

2. Secondly, this also means that my original solution is also technically valid and could also happen if there are replicas involved. Suggest bringing that back as well.

2024-06-03 13:47 UTC, agnivade requested changes

2024-06-03 13:47 UTC, agnivade commented on server/channels/app/platform/web_hub.go
> +	}
You don't need this anymore since `ClearUserSessionCache` already sends the cluster message.

2024-06-03 13:47 UTC, agnivade commented on server/channels/store/localcachelayer/channel_layer.go
> +func (s LocalCacheChannelStore) GetAllChannelMembersForUser(ctx request.CTX, userId string, allowFromCache bool, includeDeleted bool) (map[string]string, error) {
The convention is to use `rctx` for request.CTX, and `ctx` for `context.Context`. Let's use that for any new occurences.

2024-06-03 14:28 UTC, agnivade approved these changes
Dev review looks good. Suggest heavy amount of QA on an HA setup to check for edge cases. This is modifying some HA clustering code and can cause regressions.

2024-06-03 15:39 UTC, isacikgoz approved these changes
LGTM, indeed functional testing should be a good way of validating this.

2024-06-03 16:13 UTC, yasserfaraazkhan commented
/e2e-tests

2024-06-06 10:56 UTC, yasserfaraazkhan approved these changes
executed [test cycle](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testPlayer/MM-R8864)

posts, user statuses were working as expected.

2024-06-06 13:38 UTC, devinbinnie commented
@enzowritescode Can you do a quick security pass on this?

2024-06-06 21:48 UTC, enzowritescode approved these changes

2024-06-07 13:38 UTC, merged