MM-58514 Migrate tooltips of "components/channel_members_rhs/header.tsx" to WithTooltip
mattermost/mattermost pull request #27241
Opened 2024-06-02 02:30 UTC by BrandonS09

#### Summary

Updated "components/channel_members_rhs/header.tsx" to use WithTooltip instead of OverlayTrigger and Tooltip
#### Ticket Link

Fixes [#27232](https://github.com/mattermost/mattermost/issues/27232)
Jira [#58514](https://mattermost.atlassian.net/browse/MM-58514)

#### Screenshots

|  before  |  after  |
|----|----|
| ![Screenshot 2024-06-01 192700](https://github.com/mattermost/mattermost/assets/83319404/a0113ca4-4883-4545-86a8-b7f476f1ecc2) | ![Screenshot 2024-06-01 191909](https://github.com/mattermost/mattermost/assets/83319404/225b9138-25e2-46bd-a842-e05360ee431c) |
#### Release Note

```release-note
NONE
```

2024-06-02 02:30 UTC, mattermost-build commented
Hello @BrandonS09,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-06-03 05:42 UTC, M-ZubairAhmed requested changes

2024-06-03 05:42 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_members_rhs/header.tsx
> -            />
Use this translation in title of WithTooltip

2024-06-03 06:05 UTC, M-ZubairAhmed requested changes

2024-06-03 06:05 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_members_rhs/header.tsx
> +import WithTooltip from 'components/with_tooltip';
Lets revert this and other unrelated spacing changes

2024-06-05 03:12 UTC, M-ZubairAhmed approved these changes

2024-06-05 07:45 UTC, yasserfaraazkhan approved these changes

2024-06-06 04:27 UTC, harshilsharma63 approved these changes

2024-06-17 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-19 06:12 UTC, M-ZubairAhmed commented
/update-branch

2024-06-19 09:39 UTC, merged