Tooltips to WithTooltip shared_channel_indicator.tsx
mattermost/mattermost pull request #27247
Opened 2024-06-02 17:51 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27231
Jira https://mattermost.atlassian.net/browse/MM-58515
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-06-02 17:51 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-06-13 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-20 07:13 UTC, M-ZubairAhmed requested changes

2024-06-20 07:13 UTC, M-ZubairAhmed commented on webapp/channels/src/components/shared_channel_indicator.tsx
> +import WithTooltip from './with_tooltip';
can we use absolute paths here eg `components/with_tooltip` ?

2024-06-25 06:49 UTC, M-ZubairAhmed commented
@Aryakoste hows it going with this?

2024-06-25 12:33 UTC, M-ZubairAhmed commented
@Aryakoste can you check the failing CI ?

2024-06-26 06:57 UTC, M-ZubairAhmed commented
/update-branch

2024-06-26 08:23 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-06-26 08:45 UTC, Rajat-Dabade approved these changes

2024-06-26 09:18 UTC, yasserfaraazkhan commented
@M-ZubairAhmed is there a setup required to view shared channel?
can you help with the setup?

2024-06-26 11:13 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed is there a setup required to view shared channel? can you help with the setup?

Yes there is here is the docs https://docs.mattermost.com/onboard/shared-channels.html#set-up-shared-channels

2024-06-26 14:33 UTC, yasserfaraazkhan commented
@M-ZubairAhmed I've tried this, but see it not working. Can you please set it up for QA? 

![Screenshot 2024-06-26 200246](https://github.com/mattermost/mattermost/assets/15979783/a74e74da-03e3-4085-83d2-cebe0500d090)


![Screenshot 2024-06-26 200127](https://github.com/mattermost/mattermost/assets/15979783/848c0f1e-d778-4035-9c45-0e05ac6649d9)

2024-07-08 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-07-20 09:35 UTC, M-ZubairAhmed commented
This is a simple component so skipping QA since it requires setting up Shared channels

2024-07-20 09:35 UTC, merged