Migrate tooltips to WithTooltip (user_grid_role_dropdown.tsx)
mattermost/mattermost pull request #27242
Opened 2024-06-02 11:27 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27237
Jira https://mattermost.atlassian.net/browse/MM-58509

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-06-02 11:27 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-06-02 15:34 UTC, M-ZubairAhmed requested changes

2024-06-02 15:34 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/user_grid/user_grid_role_dropdown.tsx
> +                        id='shared_user_indicator.tooltip'
```suggestion
                        id='sharedUserIndicator.Tooltip'
```

2024-06-02 15:42 UTC, M-ZubairAhmed requested changes

2024-06-02 15:42 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/user_grid/user_grid_role_dropdown.tsx
> +                                id='shared_user_indicator.tooltip.text'
lets not change the translation

2024-06-03 05:45 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/user_grid/user_grid_role_dropdown.tsx
> +                        id='shared_user_indicator.tooltip'
@Aryakoste we missed this one

2024-06-05 03:15 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-06-05 07:41 UTC, yasserfaraazkhan requested changes
@M-ZubairAhmed @Aryakoste 

the screen crashes when we click on users in the System Console > Users page

![Screenshot 2024-06-05 130324](https://github.com/mattermost/mattermost/assets/15979783/10ada1d2-da0e-47cf-bd8b-9d128872bbc0)

2024-06-16 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-20 07:15 UTC, M-ZubairAhmed commented
/update-branch

2024-06-24 10:27 UTC, M-ZubairAhmed commented
/update-branch

2024-06-27 08:41 UTC, M-ZubairAhmed commented
/update-branch

2024-06-27 12:02 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed @Aryakoste
> 
> the screen crashes when we click on users in the System Console > Users page
> 
> ![Screenshot 2024-06-05 130324](https://private-user-images.githubusercontent.com/15979783/336733917-10ada1d2-da0e-47cf-bd8b-9d128872bbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODk5NjYsIm5iZiI6MTcxOTQ4OTY2NiwicGF0aCI6Ii8xNTk3OTc4My8zMzY3MzM5MTctMTBhZGExZDItZGEwZS00N2NmLWJkOGItOWQxMjg4NzJiYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEyMDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYTQxM2U4OGUyOGIyNjRjOGJhOWQ1NzUxZjkyMzZlOTBkOWJhZjkyMzRkMTdjNGE5NDBjZjQ2Y2U1ZTNiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lRyhL1LqssM4QYr5OdwaC9-pB2np9kclS_3MCOG0WqI)

This should be fixed by https://github.com/mattermost/mattermost/pull/27419

2024-07-01 07:27 UTC, yasserfaraazkhan approved these changes

2024-07-01 08:48 UTC, merged