MM-58513 Migrate tooltips of "components/channel_info_rhs/header.tsx" to WithTooltip
mattermost/mattermost pull request #27240
Opened 2024-06-02 01:56 UTC by BrandonS09

#### Summary

Updated "components/channel_info_rhs/header.tsx" to use WithTooltip instead of OverlayTrigger
#### Ticket Link

Fixes [#27233](https://github.com/mattermost/mattermost/issues/27233)
Jira [#58513](https://mattermost.atlassian.net/browse/MM-58513)
#### Screenshots

|  before  |  after  |
|----|----|
| ![Screenshot 2024-06-01 185241](https://github.com/mattermost/mattermost/assets/83319404/82b6e0c9-6cb1-4922-9b6f-3487fc49e49e) | ![Screenshot 2024-06-01 150520](https://github.com/mattermost/mattermost/assets/83319404/6f3b9112-e92a-4aca-a3f0-5218e28d0c3c) |

#### Release Note

```release-note

```

2024-06-02 01:56 UTC, mattermost-build commented
Hello @BrandonS09,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-06-03 05:43 UTC, M-ZubairAhmed requested changes

2024-06-03 05:43 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_info_rhs/header.tsx
> -            />
This should be used in title

2024-06-05 03:11 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-06-05 07:52 UTC, yasserfaraazkhan approved these changes

2024-06-06 04:28 UTC, harshilsharma63 approved these changes

2024-06-17 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-19 06:12 UTC, M-ZubairAhmed commented
/update-branch

2024-06-19 09:39 UTC, merged