[MM-58518] Migrate tooltips of "components/copy_text.tsx" to WithTooltip #27228
mattermost/mattermost pull request #27276
Opened 2024-06-04 08:56 UTC by Gesare5

#### Summary

#### Ticket Link

#### Release Note

2024-06-16 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-06-19 12:27 UTC, M-ZubairAhmed requested changes

2024-06-19 12:27 UTC, M-ZubairAhmed commented on webapp/channels/src/components/copy_text.tsx
> +import WithTooltip from './with_tooltip';
instead of relative importing can you use absolute like `import X from 'components/x'

2024-06-19 13:31 UTC, M-ZubairAhmed commented
@Gesare5 apologies would you be able to work on https://github.com/mattermost/mattermost/issues/27156 i noticed there are some changes which might be needed in this component.

2024-06-19 14:29 UTC, Gesare5 commented
@M-ZubairAhmed No problem

2024-06-20 04:09 UTC, M-ZubairAhmed commented
Closing in favour of https://github.com/mattermost/mattermost/pull/27413

2024-06-20 04:09 UTC, closed without merging