[Mm-56931] Resolved the date separation issue #26591
mattermost/mattermost pull request #27288
Opened 2024-06-05 15:42 UTC by MReza8

#### Summary

#### Ticket Link

#### Screenshots

#### Release Note

```release-note

```

2024-06-05 15:42 UTC, mattermost-build commented
Hello @MReza8,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-06-18 18:12 UTC, M-ZubairAhmed requested changes

2024-06-18 18:12 UTC, M-ZubairAhmed commented on my_changes.patch
Please remove this file

2024-07-01 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2026-04-29 14:56 UTC, lieut-data commented
Closing an old pull request. If the root cause remains an issue, feel free to reopen as needed!

2026-04-29 14:56 UTC, closed without merging