[MM-58408] Migrate tooltips of 'components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav' to WithTooltip
mattermost/mattermost pull request #27422
Opened 2024-06-20 23:20 UTC by Camillarhi

#### Summary

Migrate tooltips to use WithTooltip in 'components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav' file

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27155
Jira https://mattermost.atlassian.net/browse/MM-58408

#### Screenshots
| ![image](https://github.com/mattermost/mattermost/assets/92169163/4dc71936-43e8-4303-9059-1322f03e6fe7) | ![image](https://github.com/mattermost/mattermost/assets/92169163/044868ed-7290-4386-9bc5-a5183973d530)|

| ![image](https://github.com/mattermost/mattermost/assets/92169163/8b1d85ef-ce91-4bfa-8ce7-a3c032d84cce) | ![image](https://github.com/mattermost/mattermost/assets/92169163/03664b9a-4be2-43f4-8581-b5810944fb08)|

#### Release Note

```
NONE
```

2024-06-20 23:20 UTC, mattermost-build commented
Hello @Camillarhi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-06-24 08:46 UTC, M-ZubairAhmed commented
/release-note-none

2024-06-24 08:49 UTC, M-ZubairAhmed requested changes
Hey @Camillarhi to update the test snapshots you can
`npm run test:updatesnapshot` and to automatically fix the eslint errors you can `npm run fix`

2024-06-24 08:49 UTC, M-ZubairAhmed commented on webapp/channels/src/components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.tsx
> -            key='previewArrowLeft'
@Camillarhi lets have the key prop back as it was before

2024-06-24 08:49 UTC, M-ZubairAhmed commented on webapp/channels/src/components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.tsx
> -            key='publicLink'
same key from before here as well

2024-06-24 15:25 UTC, Rajat-Dabade approved these changes

2024-06-25 06:38 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-06-25 20:41 UTC, yasserfaraazkhan approved these changes

2024-06-26 06:31 UTC, merged