Mm 59268 fix datetime formats
mattermost/mattermost pull request #27569
Opened 2024-07-04 21:02 UTC by shaon72

#### Summary

Changed the datetime format of expiry time of custom status to make it same as DND

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-59268

#### Screenshots

Before:
![Before](https://github.com/mattermost/mattermost/assets/46700335/176300fb-3b9f-4e32-98f3-399f23f69ce3)

After:
![After](https://github.com/mattermost/mattermost/assets/46700335/10c565af-4812-4be0-8c83-ae24df64883a)

#### Release Note

```release-note
Change the expiry time format of status. Merge remote-tracking branch 'upstream/master' into MM-59268-fix-datetime-formats.
```

2024-07-04 21:02 UTC, mattermost-build commented
Hello @shaon72,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-07-07 09:57 UTC, shaon72 commented
/update-branch

2024-07-11 12:19 UTC, tnir commented
@shaon72 Thanks for fixing it, but it still looks like a little bit weird to me in terms of i18n (screenshot in `zh-TW`). What do you think while I know it is out of scope of #27511?

![](https://github.com/mattermost/mattermost/assets/10229505/eb583fce-7012-465c-aed7-365541351a2a)

2024-07-22 08:08 UTC, larkox commented
@asaadmahmood Can you verify what is exactly the expected behavior here? The change make it so some part of the time is more simple (it will say the date and time instead of saying just "sunday", for example). But not sure if that is really the intended change.

@shaon72 In order to address also @tnir comment, when @asaadmahmood verifies what is the expected behavior, could you refactor the logic out of the two components into a new component/new function/existing component to make sure the exact same logic is used in both places?

2024-07-22 10:21 UTC, asaadmahmood commented
@larkox It should not show the date exactly if its near, it should say the day like before, and only the date if it its further than the week.

So something like:
Until Tomorrow at 12:00PM
Until Saturday (if its the end of saturday)
Until Saturday at 3:00PM

Until 29th at 12:00PM (If its the next week)

2024-08-02 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-08-03 05:39 UTC, tnir commented
@asaadmahmood Can you merge this first and then will we make some minor improvements in another minor version?

2024-08-08 10:01 UTC, larkox commented
@tnir Given that the code changes are small, and it doesn't properly fix the issue, we would prefer to have the right approach together in this PR. What do you think?

2024-09-30 16:06 UTC, asaadmahmood requested changes
I think we're waiting for the changes before we merge this one.

2025-03-16 17:32 UTC, closed without merging