ci: use Node.js 20 instead of Node.js 16 on action-junit-report
mattermost/mattermost pull request #27592
Opened 2024-07-09 09:43 UTC by tnir

#### Summary

Updates action-junit-report from v3.7.7, using Node.js 16, to the latest v4.3.1, using Node.js 20.

- cf. https://github.com/mikepenz/action-junit-report/releases/tag/v4.0.0

On the other hand, as `mikepenz/action-junit-report@dfc44cebdda1e40b1e3c3b244a84dc303b952fb0 # v3.7.7 + count retries + check urls` has been actually in its fork `lieut-data/action-junit-report`, forked by @lieut-data (see #23820).

#### Ticket Link

n/a

#### Screenshots

n/a

#### Release Note

```release-note
NONE
```

2024-07-09 09:43 UTC, mattermost-build commented
Hello @tnir,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-07-09 12:36 UTC, lieut-data commented
Thanks, @tnir! I can't remember why I didn't upstream my changes -- we're currently relying on them to detect flaky tests and notify either in PR or in our Developers channel (if the flakiness is detected on `master`).

Would you be open to helping update https://github.com/lieut-data/action-junit-report with these latest changes as a short-term fix to both upgrade as well as keep the patches? We could also move this fork into the `mattermost` organization to make it more official until we get the changes upstreamed.

2024-07-23 10:56 UTC, mvitale1989 requested changes
Thanks tnir! As per @lieut-data suggestion, i'll mark this PR as awaiting for changes, to use lieut-data's fork also for the version bump.
Please request another review after the change.

2024-08-03 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2026-04-29 15:40 UTC, lieut-data commented
Closing this old PR. If the root cause is still an issue, please feel free to reopen!

2026-04-29 15:40 UTC, closed without merging