Overlay Trigger to WithTooltip draft_actions/action.tsx
mattermost/mattermost pull request #27650
Opened 2024-07-14 15:40 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27562
Jira https://mattermost.atlassian.net/browse/MM-59330

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-07-14 15:40 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-07-19 06:41 UTC, M-ZubairAhmed requested changes

2024-07-19 06:41 UTC, M-ZubairAhmed commented on webapp/channels/src/components/drafts/draft_actions/action.tsx
> +                id={`tooltip_${id}`}
```suggestion
                id={`drafts_action_tooltip_${id}`}
```

2024-07-19 06:41 UTC, M-ZubairAhmed commented
/update-branch

2024-07-19 07:23 UTC, M-ZubairAhmed requested changes
@Aryakoste can you also please check the failing CI checks

2024-07-23 08:23 UTC, M-ZubairAhmed commented
@Aryakoste any update on this one?

2024-07-23 19:08 UTC, Aryakoste commented
/update-branch

2024-07-24 07:45 UTC, M-ZubairAhmed commented
/update-branch

2024-07-24 07:45 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-07-26 06:12 UTC, yasserfaraazkhan approved these changes

2024-07-28 19:02 UTC, merged

2024-08-16 13:30 UTC, amyblais commented
@holopin-bot @Aryakoste Mattermost Most Valued Professional (MVP)