update overlaytrigger and tooltip with withtooltip
mattermost/mattermost pull request #27744
Opened 2024-07-23 19:39 UTC by pathakyashwardhan

#### Summary

#### Ticket Link

#### Screenshots

#### Release Note

```release-note

```

2024-07-23 19:39 UTC, mattermost-build commented
Hello @pathakyashwardhan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-07-24 09:15 UTC, larkox requested changes
Great work! A couple of small improvements.

2024-07-24 09:15 UTC, larkox commented on webapp/channels/src/components/custom_status/custom_status_suggestion.tsx
> +import WithTooltip from 'components/with_tooltip'; //Import the WithTooltip component
The comment is not needed.

2024-07-24 09:15 UTC, larkox commented on webapp/channels/src/components/custom_status/custom_status_suggestion.tsx
> +                tooltipText={'Clear'}
Out of the scope, but can we translate this string? instantiate `intl` by doing `const intl = useIntl();` and then here something like:

```suggestion
                tooltipText={intl.formateMessage({id: 'input.clear', defaultMessage: 'Clear'})}
```

2024-07-24 09:53 UTC, pathakyashwardhan commented on webapp/channels/src/components/custom_status/custom_status_suggestion.tsx
> +import WithTooltip from 'components/with_tooltip'; //Import the WithTooltip component
All changes are done

2024-07-25 03:29 UTC, pathakyashwardhan commented
all changes are updated

2024-07-29 12:09 UTC, M-ZubairAhmed commented
@pathakyashwardhan Ah there was an already existing PR to this issue which got merged already. I know this is not the experience you would want to have from the project and we are sorry about that but we have to close this one out. There are more open issues related to the above campaign. Can you head over to https://github.com/mattermost/mattermost/issues?q=is%3Aissue+is%3Aopen+to+WithTooltip+of+label%3A%22Help+Wanted%22+ to take a look ?

2024-08-09 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-08-12 07:20 UTC, closed without merging