Rename CRT to Threaded Discussions
mattermost/mattermost pull request #27755
Opened 2024-07-25 17:32 UTC by marianunez

#### Summary

Rename Collapsed Reply Threads to Threaded Discussions in the Admin Console screens. No changes are done to config settings to avoid migration changes. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-57431

#### Screenshots

#### Release Note

```release-note
Rename Collapsed Reply Threads to Threaded Discussions in System Console
```

2024-07-25 20:31 UTC, esethna approved these changes

2024-07-26 06:07 UTC, M-ZubairAhmed requested changes
We have the term CRT even in the user settings as well. Dont we want to change there as well?

2024-07-26 12:46 UTC, cwarnermm commented
I agree with @M-ZubairAhmed that we have CRT references in user preferences that also need to be renamed. 

There's also the 2 modal popups about CRT threads (one for admins and one for end users); not sure how/when the end user one is triggered, but worth reviewing/updating.

![Screenshot 2024-07-26 at 8 43 40 AM](https://github.com/user-attachments/assets/e718afa1-8f55-44f7-8ec2-dd0b810ea31d)

![Screenshot 2024-07-26 at 8 42 59 AM](https://github.com/user-attachments/assets/58cab9c7-a148-409c-8099-28571198183a)

2024-07-26 13:58 UTC, marianunez commented
> We have the term CRT even in the user settings as well. Dont we want to change there as well?

Yes, I had changed the title in the translation file for the user settings. Just missed the Default Message. Added

2024-07-26 14:05 UTC, marianunez commented on webapp/channels/src/components/admin_console/admin_definition.tsx
> +                            help_text: defineMessage({id: 'admin.experimental.collapsedThreads.desc', defaultMessage: 'When enabled (default off), users must enable Threaded Discussions in Settings.
@esethna do we still add this link to known issues for CRT in the System Console now that is no longer in Beta?

2024-07-26 14:08 UTC, marianunez commented
> There's also the 2 modal feature discovery popups about CRT threads (one for admins and one for end users); not sure how/when the end user one is triggered, but worth reviewing/updating.

@cwarnermm those modals were product notices that we push out from a different repository and are not part of the product. Those are no longer live so no additional changes required for them.

2024-07-26 14:10 UTC, cwarnermm commented
@marianunez - I am able to make the admin modal show up in my cloud instance by setting CRT to off by default. Would that one be part of the product and something to update?

2024-07-29 15:06 UTC, marianunez commented
/update-branch

2024-07-29 16:42 UTC, esethna commented
Also realized, there is a CRT end user tutorial tour for first time users. Not sure if that cas any references to "Collapsed Reply Threads"? @marianunez

2024-07-29 16:46 UTC, amyblais commented
> can you help update the term "Collapsed Reply Threads" > "Threaded Discussions" in any notices we are currently shipping?

Opened https://github.com/mattermost/notices/pull/410.

2024-07-29 17:03 UTC, marianunez commented
> Also realized, there is a CRT end user tutorial tour for first time users. Not sure if that has any references to "Collapsed Reply Threads"? @marianunez

@esethna Double checked and none of the wording in the Tutorial mentions the feature `Collapsed Reply Threads or CRT`. The tutorial references the new areas of `Threads`, `Follow`, `Unreads`, etc.

2024-07-30 04:46 UTC, M-ZubairAhmed approved these changes
Please also cross check the E2Es as well

2024-07-30 12:03 UTC, marianunez commented
> Please also cross check the E2Es as well

Double checked the E2E tests and there is no action to change CRT settings or any action that uses the UI elements. All tests are using the config directly that was not impacted with this change. 

Thanks @M-ZubairAhmed!

2024-07-31 13:29 UTC, amyblais commented
@cwarnermm Kind reminder for this PR review.

2024-07-31 13:47 UTC, cwarnermm approved these changes

2024-07-31 13:48 UTC, mattermost-build commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2024-07-31 14:57 UTC, mattermost-build commented
Trying to auto merge this PR.

2024-07-31 14:57 UTC, merged

2024-07-31 14:57 UTC, mattermost-build commented
Pull Request successfully merged
SHA: 988939521eeb5a356ed19e558fba43c7ded04e6b