[MM-59896] Migrate tooltips of 'components/channel_members_dropdown/channel_members_dropdown.tsx' to WithTooltip
mattermost/mattermost pull request #27806
Opened 2024-07-29 23:21 UTC by BrandonS09

#### Summary

Updated 'components/channel_members_dropdown/channel_members_dropdown.tsx' to use WithTooltip instead of OverlayTrigger and Tooltip
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27785
Jira https://mattermost.atlassian.net/browse/MM-59896
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-07-29 23:21 UTC, mattermost-build commented
Hello @BrandonS09,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-07-30 04:38 UTC, M-ZubairAhmed requested changes
Code looks good can you take a look at the CI failures

2024-08-02 13:31 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-08-06 04:12 UTC, Rajat-Dabade approved these changes

2024-08-07 08:26 UTC, merged