[MM-59905] Migrate tooltips of 'components/threading/channel_threads/thread_footer/thread_footer.tsx' to WithTooltip (#27796)
mattermost/mattermost pull request #27802
Opened 2024-07-29 17:35 UTC by BrandonS09

#### Summary

Updated 'components/threading/channel_threads/thread_footer/thread_footer.tsx' to use WithToolTip instead of SimpleToolTip
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27796 
Jira [#59905](https://mattermost.atlassian.net/browse/MM-59905)
#### Screenshots

|  before  |  after  |
|----|----|
| ![59905Before](https://github.com/user-attachments/assets/1ec80289-5b0c-43e7-91c2-6e9465eedd76) | ![59905After](https://github.com/user-attachments/assets/f05bb13b-b5d2-4bf9-8861-f0f800dabd5a) |
#### Release Note

```release-note
NONE
```

2024-07-29 17:35 UTC, mattermost-build commented
Hello @BrandonS09,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-07-30 04:38 UTC, M-ZubairAhmed requested changes
Code looks good can you take a look at the CI failures

2024-08-02 13:24 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-08-06 04:10 UTC, Rajat-Dabade approved these changes

2024-08-06 14:57 UTC, yasserfaraazkhan approved these changes

2024-08-07 08:19 UTC, merged