[MM-59906] Migrate tooltips of 'components/threading/global_threads/thread_item/thread_item.tsx' to WithTooltip
mattermost/mattermost pull request #27803
Opened 2024-07-29 18:30 UTC by BrandonS09

#### Summary

Updated 'components/threading/global_threads/thread_item/thread_item.tsx' to use WithTooltip instead of SimpleTooltip
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27795
Jira [#59906](https://mattermost.atlassian.net/browse/MM-59906)
#### Screenshots

|  before  |  after  |
|----|----|
| ![59906Before](https://github.com/user-attachments/assets/d26e1702-00d1-4202-8285-6a0350565c7d) | ![59906After](https://github.com/user-attachments/assets/9b620641-9746-4af3-af15-7e30b708fc9f) |
#### Release Note

```release-note
NONE
```

2024-07-29 18:30 UTC, mattermost-build commented
Hello @BrandonS09,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-07-30 04:38 UTC, M-ZubairAhmed requested changes
Code looks good can you take a look at the CI failures

2024-08-01 12:16 UTC, M-ZubairAhmed commented
@BrandonS09 the snapshots are still failing

2024-08-02 13:25 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-08-06 04:11 UTC, Rajat-Dabade approved these changes

2024-08-06 14:59 UTC, yasserfaraazkhan approved these changes

2024-08-07 08:22 UTC, merged