Skips TestCreateZipFileAndAddFiles racy test
mattermost/mattermost pull request #27881
Opened 2024-08-08 11:19 UTC by mgdelacroix

https://mattermost.atlassian.net/browse/MM-60056

```release-note
NONE
```

2024-08-12 07:24 UTC, streamer45 approved these changes

2024-08-12 10:58 UTC, hanzei approved these changes
Heads up that https://github.com/mattermost/mattermost/pull/27923 is in the pipeline

2024-08-13 09:02 UTC, hanzei requested changes
https://github.com/mattermost/mattermost/pull/27923 should fix the flaky test. Let's see if we even need to skip it.

2024-08-19 10:37 UTC, mgdelacroix commented
awesome, thanks @hanzei, closing this one then

2024-08-19 10:37 UTC, closed without merging