[MM-60066] Convert ./components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.tsx from Class Component to Function Component
mattermost/mattermost pull request #27913
Opened 2024-08-11 13:34 UTC by Camillarhi

#### Summary

Convert class component to function component

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27888
Jira https://mattermost.atlassian.net/browse/MM-60066
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-08-11 13:34 UTC, mattermost-build commented
Hello @Camillarhi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-08-12 08:41 UTC, larkox requested changes
Great work! Just some minor comments.

2024-08-12 08:41 UTC, larkox commented on webapp/channels/src/components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.tsx
> +export default function MenuItemToggleMuteChannel({id, isMuted, channel, user, actions}: Props) {
Can we put each prop in a different line?
```suggestion
export default function MenuItemToggleMuteChannel({
    id,
    isMuted,
    channel,
    user,
    actions
}: Props) {
```

2024-08-12 08:41 UTC, larkox commented on webapp/channels/src/components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.tsx
> +    const handleClick = () => {
This is passed as a prop, so let's use a `useCallback`.

2024-08-12 08:41 UTC, larkox commented on webapp/channels/src/components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.tsx
> +        text = isMuted ? localizeMessage('channel_header.unmuteConversation', 'Unmute Conversation') : localizeMessage('channel_header.muteConversation', 'Mute Conversation');
We are trying to get rid of `localizeMessage` so do you mind using intl here? (`useIntl` and `intl.formatMessage`)

2024-08-13 09:19 UTC, larkox approved these changes
Great work! Just one minor thing, but I am approving it early.

2024-08-13 09:19 UTC, larkox commented on webapp/channels/src/components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.tsx
> +    actions}: Props) {
Small nit, just to be the same in all the codebase (yes, I should find a linting rule for this :sweat_smile: )
```suggestion
    actions,
}: Props) {
```

2024-08-14 06:49 UTC, Rajat-Dabade commented on webapp/channels/src/components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.tsx
> +    }, [actions]);
Should `isMuted`, `user.id`, and `channel.id` be added as the dependency for `useCallback`? So to ensure the function is updated correctly when any of these values change.

2024-08-16 10:08 UTC, Rajat-Dabade approved these changes

2024-08-22 14:30 UTC, yasserfaraazkhan commented
/update-branch

2024-08-22 17:57 UTC, yasserfaraazkhan approved these changes

2024-08-23 11:37 UTC, merged