Remove mysql from Docker-based development environment by default
mattermost/mattermost pull request #27910
Opened 2024-08-11 06:26 UTC by tnir

#### Summary

This change removes MySQL from the Docker-based development environment, but it can be enabled bysetting `ENABLED_MYSQL=true` at runtime.
For example, to run the development environment with MySQL enabled, run the following command:

```sh
cd server && ENABLED_MYSQL=true make run
```

Same as before, the following command would run only PostgreSQL service without MySQL:

```sh
cd server && make run
```

#### Ticket Link

- Fixes #27909

#### Screenshots

n/a

#### Release Note

```release-note
NONE
```

2024-08-11 06:26 UTC, mattermost-build commented
Hello @tnir,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-08-12 05:20 UTC, agnivade requested changes
@tnir - You do not need to edit the Makefile for this. Simply set whatever services you want in your config.override.mk and set the `ENABLED_DOCKER_SERVICES` variable there.

By default, we still want to keep mysql because we still are testing against both databases.

2024-08-23 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-08-23 03:00 UTC, closed without merging

2024-08-23 03:00 UTC, agnivade commented
Going to close this for now. Please leave a comment if you have any thoughts.

2024-09-08 04:00 UTC, tnir commented
@agnivade Thanks for clarifying the overriding way for the purpose. It make sense to me to close this PR :grinning: