[MM-59903] Migrate tooltips of 'components/channel_invite_modal/group_option/group_option.tsx' to WithTooltip
mattermost/mattermost pull request #27918
Opened 2024-08-11 19:12 UTC by Camillarhi

#### Summary

Migrate tooltips of `components/channel_invite_modal/group_option/group_option.tsx` to WithTooltip
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27798
Jira https://mattermost.atlassian.net/browse/MM-59903
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-08-11 19:12 UTC, mattermost-build commented
Hello @Camillarhi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-08-12 07:06 UTC, M-ZubairAhmed commented
/update-branch

2024-08-12 07:10 UTC, M-ZubairAhmed reviewed
Thank you so much for adding these new test love it. Can you make a few changes to the test

2024-08-12 07:10 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_invite_modal/group_option/group_option.test.tsx
> +        const wrapper = render(
Instead of using render directly we can use renderWithContext from `tests/react_testing_utils`

2024-08-12 07:11 UTC, M-ZubairAhmed requested changes
There are few linting issues as well

2024-08-12 08:51 UTC, pvev approved these changes
besides @M-ZubairAhmed comments and the lint issues, I think this PR looks good to me. Thanks for your contribution @Camillarhi 🚀 .

2024-08-12 08:51 UTC, pvev commented on webapp/channels/src/components/channel_invite_modal/group_option/group_option.test.tsx
> +    it('should cleanup keydown event listener on unmount', () => {
thank you for adding this tests, this is a great addition. Could you in this same test assert that before the unmounting the event is dispatched correctly.

2024-08-13 06:54 UTC, M-ZubairAhmed requested changes

2024-08-13 06:54 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_invite_modal/group_option/group_option.test.tsx
> +    test('should match snapshot', () => {
isnt this `should match snapshot` and `should render correctly` exactly the same, we can remove either one of them

2024-08-13 06:54 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_invite_modal/group_option/group_option.test.tsx
> +        setTimeout(() => {
can we use split this into two `await waitFor` here instead? First one to check `addUserProfileMock` is called and after unmount & dispatch another wait to check `addUserProfileMock` is not called

2024-08-13 09:41 UTC, M-ZubairAhmed commented
/update-branch

2024-08-13 14:50 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-08-13 18:16 UTC, yasserfaraazkhan requested changes
@M-ZubairAhmed is it this part of the UI ? the tooltop here does not appear.
<img width="559" alt="image" src="https://github.com/user-attachments/assets/e6c843cd-bc84-4868-bbd0-b0d9c671f3bd">

2024-08-16 12:47 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed is it this part of the UI ? the tooltop here does not appear.
> <img alt="image" width="559" src="https://private-user-images.githubusercontent.com/15979783/357525470-e6c843cd-bc84-4868-bbd0-b0d9c671f3bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTI1OTgsIm5iZiI6MTcyMzgxMjI5OCwicGF0aCI6Ii8xNTk3OTc4My8zNTc1MjU0NzAtZTZjODQzY2QtYmM4NC00ODY4LWJiZDAtYjBkOWM2NzFmM2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEyNDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOTk3Njk1Yzg2ODZlZjUxNDViNDZiZGYxNzU4MWQ2MGMxZmVjNTdiMjM1YWYyOTA1MTIxZDA1MWYyZWNkNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W8xQS6cULls29vt3sqCS1IZHU5CcYgk_sE22r7tGt6U">
> 
> on master it shows as below, <img alt="image" width="313" src="https://private-user-images.githubusercontent.com/15979783/357526516-99a13217-0bfa-411f-a382-1f34f9ae3a81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTI1OTgsIm5iZiI6MTcyMzgxMjI5OCwicGF0aCI6Ii8xNTk3OTc4My8zNTc1MjY1MTYtOTlhMTMyMTctMGJmYS00MTFmLWEzODItMWYzNGY5YWUzYTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDEyNDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOTcxOGNmODc5ZjQyYzAxZWNkNWJiMzU3NjdmNThkZjY3NzdkN2JjZjM3NjIxOWQ2YWMzMTEwMWU3YTYzYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H6bZzc5ygUBrs8xq7KGCw7RLNvSQGJ5ZcKc4rM0LJq8">

@Camillarhi please take a look at the QA feedback here

2024-08-20 09:18 UTC, M-ZubairAhmed commented
@Camillarhi gentle ping on this one

2024-08-20 18:49 UTC, Camillarhi commented
> @Camillarhi gentle ping on this one

Thanks, I will look into it and make an update soon

2024-08-22 18:54 UTC, Camillarhi commented
@M-ZubairAhmed  I was unable to produce this exact view on the component but I tested the component independently and the styling remained the same, do you have a suggestion on how to proceed from here?

2024-08-23 03:52 UTC, M-ZubairAhmed requested changes
Few test changes

2024-08-23 03:52 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_invite_modal/group_option/group_option.test.tsx
> +                <Provider store={store}>
Can you remove these as they are inbuilt in renderWithContext. Similarly in other tests as well

2024-08-23 03:52 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_invite_modal/group_option/group_option.test.tsx
> +    let props: ComponentProps<typeof GroupOption>;
```suggestion
    let props: Props;
```

you can import Props directly from `group_option`

2024-08-23 03:52 UTC, M-ZubairAhmed commented on webapp/channels/src/components/channel_invite_modal/group_option/group_option.test.tsx
> +    beforeEach(() => {
we dont need beforeEach here. You can define props as constant and in test where you are changing the props you can
```
const defaultProps = {
// default props
}


test('xxx', () => {
const props = {...defaultProps, isSelected:true}
}
```

2024-08-23 03:59 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed I was unable to produce this exact view on the component but I tested the component independently and the styling remained the same, do you have a suggestion on how to proceed from here?

True this is an existing issue, I have opened the ticket for it here: https://mattermost.atlassian.net/browse/MM-60260 i have added the steps to reproduce the issue in the ticket as well.

cc @yasserfaraazkhan we can proceed with this saying its a know issue. If you refresh the app you should see the tooltips though

2024-08-23 20:19 UTC, M-ZubairAhmed approved these changes

2024-08-26 07:06 UTC, yasserfaraazkhan approved these changes

2024-08-26 11:45 UTC, merged