[MM-60073] Migrate `/components/admin_console/custom_enable_disable_guest_accounts_setting.tsx` from class to function component
mattermost/mattermost pull request #27963
Opened 2024-08-13 17:37 UTC by Tihomir-N

#### Summary
- Refactor `/components/admin_console/custom_enable_disable_guest_accounts_setting.tsx` from class component to functional component.
- Refactor component`s tests using react-testing-library

**QA Notes:**
This is a small settings component located in System Console at Authentication > Guest Access ([follow instructions](https://docs.mattermost.com/configure/authentication-configuration-settings.html#guest-enable) to view). There are no functional changes.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/27895
Jira https://mattermost.atlassian.net/browse/MM-60073

#### Screenshots
No UI changes

#### Release Note
NONE

2024-08-13 17:37 UTC, mattermost-build commented
Hello @Tihomir-N,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-08-14 07:32 UTC, larkox requested changes
Great work! Specially with the tests. A couple of comments though.

2024-08-14 07:32 UTC, larkox commented on webapp/channels/src/components/admin_console/custom_enable_disable_guest_accounts_setting.tsx
> +                onConfirm={() => handleChange(id, false, true)}
This generates a new function on every render. Can you move it to a `useCallback`?

2024-08-14 07:32 UTC, larkox commented on webapp/channels/src/components/admin_console/custom_enable_disable_guest_accounts_setting.tsx
> +    const handleChange = useCallback((id: string, value: boolean, submit = false) => {
Not sure if the linter will complain, but you are redefining here several variables (id and value) which makes things a bit more confusing. Do you mind renaming the variables?

I guess they could be `targetId`, and `newValue`, but I am horrible at naming...

2024-08-14 07:32 UTC, larkox commented on webapp/channels/src/components/admin_console/custom_enable_disable_guest_accounts_setting.tsx
> +const CustomEnableDisableGuestAccountsSetting: React.FC<Props> = ({
Just for consistency with most of the rest of the code, there is no need to be explicit with the React.FC type. We can leave it something like `const foo = ({...}: Props) {`
```suggestion
const CustomEnableDisableGuestAccountsSetting = ({
```

2024-08-14 07:32 UTC, larkox commented on webapp/channels/src/components/admin_console/custom_enable_disable_guest_accounts_setting.test.tsx
> +    const renderComponent = (props = {}) => {
You should be able to use `renderWithContext`, that does most of what you are doing here.

2024-08-14 07:32 UTC, larkox commented on webapp/channels/src/components/admin_console/custom_enable_disable_guest_accounts_setting.test.tsx
>              expect(wrapper).toMatchSnapshot();
What you want to match to the snapshot is `wrapper.container`, not the whole `wrapper`. The reality is that what `render` returns is not really a wrapper, but an object with several util functions. That is why the snapshot looks so weird.

2024-08-14 08:13 UTC, M-ZubairAhmed commented
/release-note-none

2024-08-14 17:22 UTC, Tihomir-N commented
@larkox Thanks for the comments. I have applied the changes. Let me know, if anything is needed.

2024-08-16 09:28 UTC, larkox approved these changes
Looks great. Thanks!

2024-08-27 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-08-27 07:06 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-08-27 07:06 UTC, M-ZubairAhmed commented
@Tihomir-N can you also resolve the conflicts

2024-08-28 16:29 UTC, Tihomir-N commented
@M-ZubairAhmed Merge it's done! 🚀

2024-08-29 10:53 UTC, M-ZubairAhmed commented
/update-branch

2024-08-30 09:26 UTC, merged