[MM-60167] Migrate tooltips of "components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx" to WithTooltip
mattermost/mattermost pull request #27979
Opened 2024-08-15 00:05 UTC by Camillarhi

#### Summary

- Migrate tooltips of `components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx` to WithTooltip
- Add  `onEntering` as a prop to `Withtooltip` component
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27929
Jira https://mattermost.atlassian.net/browse/MM-60167
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-08-16 13:37 UTC, M-ZubairAhmed requested changes

2024-08-16 13:37 UTC, M-ZubairAhmed commented on webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
>                      onEntering={this.removeTooltipLink}
lets remove this onEntering prop

2024-08-17 09:20 UTC, M-ZubairAhmed requested changes

2024-08-17 09:20 UTC, M-ZubairAhmed commented on webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
> -                    onEntering={this.removeTooltipLink}
lets remove `removeTooltipLink` unused function as well

2024-08-18 17:33 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-08-18 18:13 UTC, Camillarhi commented
> This looks good :shipit: Thank you

Thanks

2024-08-19 06:27 UTC, Rajat-Dabade approved these changes

2024-08-22 17:17 UTC, yasserfaraazkhan approved these changes

2024-08-23 03:00 UTC, merged