[MM-60155] Migrate tooltips of "components/advanced_text_editor/show_formatting/show_formatting.tsx" to WithTooltip
mattermost/mattermost pull request #27981
Opened 2024-08-15 01:12 UTC by Camillarhi

#### Summary

- Migrate tooltips of `components/advanced_text_editor/show_formatting/show_formatting.tsx` to WithTooltip
- Add test file for `components/advanced_text_editor/show_formatting/show_formatting.tsx` file
#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27941
Jira https://mattermost.atlassian.net/browse/MM-60155
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-08-15 01:12 UTC, mattermost-build commented
Hello @Camillarhi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-08-16 12:43 UTC, M-ZubairAhmed commented
/update-branch

2024-08-16 13:27 UTC, M-ZubairAhmed requested changes
Thanks you so much for adding more tests 🎉

2024-08-16 13:27 UTC, M-ZubairAhmed commented on webapp/channels/src/components/advanced_text_editor/show_formatting/show_formatting.test.tsx
> +                    onClick={() => {}}
nit this can we jest.fn()

2024-08-16 13:27 UTC, M-ZubairAhmed commented on webapp/channels/src/components/advanced_text_editor/show_formatting/show_formatting.test.tsx
> +                    onClick={() => {}}
nit this could be a jest mock

2024-08-16 13:27 UTC, M-ZubairAhmed commented on webapp/channels/src/components/advanced_text_editor/show_formatting/show_formatting.tsx
> +        />
minor nit, could you just pass this directly instead of creating a new variable

2024-08-16 16:41 UTC, M-ZubairAhmed requested changes

2024-08-16 16:41 UTC, M-ZubairAhmed commented on webapp/channels/src/components/advanced_text_editor/show_formatting/show_formatting.test.tsx
> +        const {getByLabelText} = renderWithContext(
we should be using screen from tests/react_testing_utils instead of getting it from the return value. In all of this test file

2024-08-17 23:48 UTC, Camillarhi commented
> Thanks you so much for adding more tests 🎉

You are welcome 🎉

2024-08-18 17:27 UTC, M-ZubairAhmed requested changes
Sorry minor nits

2024-08-18 17:27 UTC, M-ZubairAhmed commented on webapp/channels/src/components/advanced_text_editor/show_formatting/show_formatting.test.tsx
> +import {renderWithContext} from 'tests/react_testing_utils';
Nit lets use imports directly from the utils
```suggestion
import {renderWithContext, fireEvent, screen} from 'tests/react_testing_utils';
```

2024-08-18 17:27 UTC, M-ZubairAhmed commented on webapp/channels/src/components/advanced_text_editor/show_formatting/show_formatting.test.tsx
> +            <IntlProvider locale='en'>
` <IntlProvider locale='en'>` is already wrapped in renderWithContext so we dont need this

2024-08-18 17:27 UTC, M-ZubairAhmed commented on webapp/channels/src/components/advanced_text_editor/show_formatting/show_formatting.test.tsx
> +            <IntlProvider locale='en'>
` <IntlProvider locale='en'>` is already wrapped in renderWithContext so we dont need this

2024-08-18 17:27 UTC, M-ZubairAhmed commented on webapp/channels/src/components/advanced_text_editor/show_formatting/show_formatting.test.tsx
> +            <IntlProvider locale='en'>
` <IntlProvider locale='en'>` is already wrapped in renderWithContext so we dont need this

2024-08-19 12:51 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-08-20 09:01 UTC, larkox approved these changes

2024-08-22 17:06 UTC, yasserfaraazkhan approved these changes

2024-08-23 02:58 UTC, merged