MM-59260: allowed group channels to be deleted
mattermost/mattermost pull request #28108
Opened 2024-09-01 10:48 UTC by EndlessNight191

#### Summary
update validation group channel for delete group

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/27489
Jira https://mattermost.atlassian.net/browse/MM-59260

2024-09-01 10:48 UTC, mattermost-build commented
Hello @EndlessNight191,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-09-01 10:51 UTC, EndlessNight191 commented
/check-cla

2024-09-12 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-09-16 08:09 UTC, larkox requested changes
This doesn't solve the issue.

This will allow you to both soft and hard delete group messages, that we don't want. We only want to be able to hard delete them, not soft delete them.

Also, we want to be able to hard delete both. Direct and group messages.

Finally, the ticket also mentions that a specific permission should be used to make sure it is possible to delete these channels.

2024-09-27 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-09-30 11:12 UTC, larkox commented
@EndlessNight191 Are you still looking into this?

2026-07-24 06:03 UTC, vish9812 commented
The JIRA ticket needs more refinement especially around the roles/permissions needed for the operation.
Closing it for now.

2026-07-24 06:03 UTC, closed without merging