MM-60200 Fix for Plugin Dialog with wrong channel ID.
mattermost/mattermost pull request #28122
Opened 2024-09-04 20:47 UTC by sbishel

#### Summary
When using a Plugin Dialog, the `currentChannel` is used when the dialog is submitted. The currentChannelID is the center channel. This causes a couple different issues when used with threads.

If "Threads" are being displayed in the center channel, then currentChannelId is empty and it causes an error when attempting to submit the dialog.

If another channel is displayed in the center dialog, the result of the dialog submission is displayed in the wrong (center) channel.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-60200

#### Release Note

```release-note
Fixed issue with plugin dialogs error on submission.
```

2024-09-12 14:56 UTC, idesers commented
Hi @sbishel, thanks for the PR that fixes my problem)

I'm not sure, but as far as I understand `dialogArguments` are only passed when opening a dialog by executing a command. A dialog can also be opened by pressing a button in message attahments, and in this situation channel_id will not be passed.

2024-09-12 15:16 UTC, idesers commented
I've been thinking about how to solve this problem too

My idea was to make a proxy action in `webapp/channels/src/actions/integration_actions.tsx` that checks if a thread is open. If channel_id === “”, then take the channel_id of the selected thread as channel_id and then call the action from mattermost-redux.

It goes something like this:
```ts
// webapp/channels/src/actions/integration_actions.tsx
export function submitInteractiveDialog(submission: DialogSubmission): ActionFuncAsync<SubmitDialogResponse, GlobalState> {
    return async (dispatch, getState) => {
        const state = getState();
        const currentChannelId = getCurrentChannelId(state);
        const selectedThread = getSelectedThreadInCurrentTeam(state);

        if (currentChannelId === '' && selectedThread) {
            submission.channel_id = selectedThread.post.channel_id;
        } else {
            submission.channel_id = currentChannelId;
        }

        const {data} = await dispatch(IntegrationActions.submitInteractiveDialog(submission));

        return {data};
    };
}

// In mattermost-redux/src/actions/integrations.ts we just check if channel_id is already set or not
export function submitInteractiveDialog(submission: DialogSubmission): ActionFuncAsync<SubmitDialogResponse> {
.....
        submission.channel_id ||= getCurrentChannelId(state);
        submission.team_id ||= getCurrentTeamId(state);
.....
}
```

2024-09-13 22:38 UTC, sbishel commented
@idesers - Unfortunately, I haven't been able to get back to this. So, yes, I would welcome a PR.

The one issue I see when both `currentChannelId` and `selectedThread` have values, but different values. I believe this can happen if you have one channel open in the center panel and a thread from a different channel in the right pane. Then we need to know which panel the dialog was launched from. We may need to set something when the dialog is launched? I'll try to explore that early next week.

Thanks for your help.

2025-03-14 22:55 UTC, pylizard commented
Hi @sbishel , I came across this PR and saw that it addresses an issue I've encountered. Do you have any updates on its status? I’d love to see this merged. Thanks for your time!

2025-04-14 19:32 UTC, sbishel commented
/update-branch

2025-04-15 14:25 UTC, sbishel commented on webapp/channels/src/actions/command.ts
> +            dispatch({type: IntegrationTypes.RECEIVED_DIALOG_ARGUMENTS, data: args});
This handles slash commands, such as Demo plugin `/dialog`.

2025-04-15 14:25 UTC, sbishel commented on webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
> +                }});
This handles interactive dialogs, such as Matterpoll.

2025-04-15 14:31 UTC, sbishel commented
@idesers - After further investigation, there was more than the "threading" scenario that required handling. I just didn't see a way without setting information into state when it was launched. I did incorporate your "proxy action" feedback. Let me know if you see other issues with this fix.

@pylizard - Let me know if this still works for you.

2025-04-15 14:56 UTC, pylizard commented
@sbishel Great work, thanks! Looks like it does solve the issue. I will update the version as soon as the patch becomes available.

2025-04-24 15:14 UTC, hmhealey requested changes

2025-04-24 15:14 UTC, hmhealey commented on webapp/channels/src/packages/mattermost-redux/src/reducers/entities/integrations.ts
> +function dialogArguments(state = '', action: MMReduxAction) {
The type of the default value here is incorrect since it doesn't match the type added below

2025-04-24 15:14 UTC, hmhealey commented on webapp/platform/types/src/integrations.ts
> +    dialogArguments?: CommandArgs;
I'm not sure if we should be reusing this type here because `CommandArgs` has an extra field and may later be changed in a way that doesn't fit for interactive dialogs

2025-04-25 20:54 UTC, sbishel commented on webapp/channels/src/packages/mattermost-redux/src/actions/integrations.ts
> +        submission.user_id ||= getCurrentUserId(state);
For channel_id, that is exactly what we want. If Dialog Arguments don't exist, channel_id, is intentionally set to an empty string. The other two are never set and will always get set here, so I reverted that code back to simply set those two properties.

2025-04-28 14:39 UTC, sbishel commented
/update-branch

2025-05-08 20:51 UTC, hmhealey approved these changes
Sorry, I love track of this for a couple weeks. Looks good to me now

2025-05-15 22:27 UTC, calebroseland approved these changes

2025-05-16 08:10 UTC, lindy65 approved these changes
Thanks @sbishel - I'll test this post merge - added QA-deferred label

2025-06-02 17:22 UTC, sbishel commented
/update-branch

2025-06-02 19:12 UTC, merged