fix: enable preview for all image types without initial or mini preview
mattermost/mattermost pull request #28121
Opened 2024-09-04 12:59 UTC by Ovgodd

#### Summary
- This pr aims to update the logic for generating file previews to ensure that all image types specified in Constants.IMAGE_TYPES can have a preview, even if they not have an initial or mini preview. Previously, only images with a predefined preview or mini preview were displayed, which excluded certain image types like PSD files.

- the issues appeared when the file was the first message in a thread (GIF when upload via fileUpload / WEBP)
 
- Modified the preview generation logic in File component to check if an image type is supported and does not have initial or mini previews.

- Ensured that all image types listed in Constants.IMAGE_TYPES are eligible for preview by fetching the full file URL.

#### Ticket Link

#### Screenshots

#### Release Note

```release-note
fix: enable preview for all image types without initial or mini preview
```

2024-09-15 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-09-19 19:48 UTC, hmhealey requested changes
Thanks for the PR, @Ovgodd!

When we don't have a preview image, I don't think we want to always load the full sized image because that'll often use a large amount of bandwidth and may slow down the app if someone posts an image that takes a lot of memory to load. Sometimes, the server doesn't generate preview images specifically because of how big the image is, so we definitely don't want the web app to load it then.

Instead of showing the original image, I think we can still fix the broken image icon by instead showing whatever icon we show for an unrecognized file type. How does that sound?

I think the `FileAttachment` component that's used for showing file attachments on posts in a channel already does that, so that might be a good reference for how to do the same thing here

2024-09-30 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2026-08-04 13:46 UTC, lieut-data commented
Thank you everyone for the feedback on this proposed solution. There are outstanding changes requested on this pull request that prevent us from merging this solution as-is. Given the age, I'm going to close this pull request for now, but leave the related issues open in case another community member wants to propose another solution.

2026-08-04 13:46 UTC, closed without merging