Add MobileExternalBrowser to client config
mattermost/mattermost pull request #28180
Opened 2024-09-13 06:00 UTC by enahum

#### Summary
Introducing a client config property that determines if the mobile app should use the default external browser to perform SSO Authentication instead of the internal one.

Value defaults to **false**.

Note: It does not include an admin console UI.

Important: We want to include this in the latest ESR as will mostly be used by certain enterprise customers.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-60332

#### Release Note
```release-note
Added config setting NativeAppSettings -> MobileExternalBrowser that tells the mobile app to perform the SSO Authentication using the external default browser
```

2024-09-13 06:51 UTC, enahum commented
/update-branch

2024-09-13 16:08 UTC, sbishel requested changes

2024-09-13 22:40 UTC, enahum commented on server/public/model/config.go
> +	MobileExternalBrowser  bool     `access:"site_customization,write_restrictable,cloud_restrictable"`
Alright, I'll change it to a pointer and set the default as false

2024-09-16 14:29 UTC, sbishel approved these changes
Thanks

2024-09-16 23:12 UTC, enahum commented
@amyblais will we cherry pick this one for the ESR ?

2024-09-17 12:10 UTC, amyblais commented
> will we cherry pick this one for the ESR ?

Yes, that's correct.

2024-09-17 12:33 UTC, rahimrahman approved these changes

2024-09-18 11:50 UTC, merged

2024-09-18 11:50 UTC, mattermost-build commented
Cherry pick is scheduled.

2024-10-21 13:28 UTC, amyblais commented
/cherry-pick release-10.1

2024-10-21 13:28 UTC, mattermost-build commented
Cherry pick is scheduled.