[MM-59870] Fixed reminder to post in direct messages send email with malformed url to the post
mattermost/mattermost pull request #28218
Opened 2024-09-17 20:07 UTC by fume4mattermost

#### Summary

Fixed the malformed URL in the email sent for the reminder

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-59870

#### Screenshots

#### Release Note

```release-note

```

2024-09-17 20:07 UTC, mattermost-build commented
Hello @fume4mattermost,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-09-18 15:23 UTC, marianunez requested changes
@fume4mattermost After creating the proposed fix in the ticket, we realized that we don't need to make any changes in the frontend as we have logic to cover the missing team in the url. We've updated the ticket and now specified that the changes should be in the backend when we construct the email for the reminder. Please take a look at the ticket for directions on the backend fix.  

Apologies for the change of direction after you had started to work on this!

2024-09-18 15:47 UTC, fume4mattermost commented
> @fume4mattermost After creating the proposed fix in the ticket, we realized that we don't need to make any changes in the frontend as we have logic to cover the missing team in the url. We've updated the ticket and now specified that the changes should be in the backend when we construct the email for the reminder. Please take a look at the ticket for directions on the backend fix.
> 
> Apologies for the change of direction after you had started to work on this!

No worries, starting right away!

2024-09-19 09:51 UTC, fume4mattermost commented
I’ve reviewed the latest ticket details and implemented the necessary changes on the backend to ensure the correct email construction for the reminder. Since the frontend logic already covers the missing team in the URL, no changes were made there as per your instructions.

Please let me know if any further adjustments are needed!

2024-09-25 21:22 UTC, marianunez requested changes
@fume4mattermost it some of the email tests are failing due to the changes. Can you take a look?

2024-10-15 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2026-05-20 13:34 UTC, lieut-data commented
Closing this old issue, will triage further internally.

2026-05-20 13:34 UTC, closed without merging