[MM-56033]Added unit tests for UpdateUserCustomStatus and RemoveUserCustomStatu…
mattermost/mattermost pull request #28216
Opened 2024-09-17 14:43 UTC by fume4mattermost

…s functions

#### Summary

Added missing unit tests for the following functions in [mattermost/server/channels/api4/status.go at master · mattermost/mattermost](https://github.com/mattermost/mattermost/blob/master/server/channels/api4/status.go) :
updateUserCustomStatus
getUserStatusesByIds
removeUserCustomStatus

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-56033

#### Screenshots

#### Release Note

```release-note

```

2024-09-17 14:43 UTC, mattermost-build commented
Hello @fume4mattermost,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-09-18 03:37 UTC, agnivade reviewed
Great work on adding tests. Left some comments.

2024-09-18 03:37 UTC, agnivade commented on server/channels/api4/status_test.go
> +        require.NoError(t, err)
Just use `user.GetCustomStatus()`

2024-09-18 03:37 UTC, agnivade commented on server/channels/api4/status_test.go
> +		CheckNotImplementedStatus(t, resp)
Also check that the error id is `api.custom_status.disabled`

2024-09-18 03:37 UTC, agnivade commented on server/channels/api4/status_test.go
> +        assert.Equal(t, toUpdateCustomStatus.Duration, customStatus["duration"])
Same as before

2024-09-18 03:37 UTC, agnivade commented on server/channels/api4/status_test.go
> +		assert.Empty(t, user.Props["customStatus"])
Same

2024-09-18 17:48 UTC, JulienTant requested changes
Hey @fume4mattermost, thanks for your contribution!

In addition to the comments @agnivade left earlier, it looks like the file has not been formatted (there's a mix of tabs and spaces, the import order are not correct also).

2024-09-20 03:39 UTC, agnivade approved these changes
Nice bot!

2024-10-03 15:12 UTC, jwilander commented
@fume4mattermost can you merge latest master into this branch too?

@JulienTant mind taking a look at this PR?

2024-10-03 16:16 UTC, JulienTant approved these changes
Thank you for your contribution @fume4mattermost!

And thank you @jwilander for the reminder, it fell off my radar!

2024-10-04 05:09 UTC, agnivade commented
/e2e-test

2024-10-04 06:28 UTC, agnivade commented
/e2e-test

2024-10-04 07:32 UTC, agnivade commented
e2e tests passed. Merging.

2024-10-04 07:32 UTC, merged