MM-59954 Community plugins telemetry
mattermost/mattermost pull request #28226
Opened 2024-09-18 11:00 UTC by Willyfrog

#### Summary
Include known community supported plugins that are no longer available in the market place as part of the telemetry

#### Ticket Link
[MM-59954](https://mattermost.atlassian.net/browse/MM-59954)

#### Release Note
```release-note
NONE
```

2024-09-18 12:47 UTC, lieut-data requested changes
Thanks, @Willyfrog! Glad to see this corner case getting fixed.

One request below.

2024-09-18 12:47 UTC, lieut-data commented on server/platform/services/telemetry/telemetry.go
> +			if err != nil {
This `err` is too far removed, contextually, to use it like this. Before, we used either the `knowPluginIDs` /or/ the `marketplacePlugins`, but now it looks like we do both, so can we just always range over `marketplacePlugins`, even if it happens to be empty, and skip this condition altogether?

2024-09-19 12:11 UTC, lieut-data approved these changes

2024-09-20 20:56 UTC, BenCookie95 approved these changes

2024-09-23 10:58 UTC, Willyfrog commented
no QA step here, so marking as QA deferred as I don't see an easy way for QA to test data that we send to Rudder

2024-09-23 10:59 UTC, merged