MM-59260: allowed permanently deleting a direct and group message
mattermost/mattermost pull request #28274
Opened 2024-09-22 14:39 UTC by ksharinarayanan

#### Summary
allowed permanently deleting a direct and group message

#### Ticket Link
[https://mattermost.atlassian.net/browse/MM-59260](https://mattermost.atlassian.net/browse/MM-59260)

2024-09-22 14:39 UTC, mattermost-build commented
Hello @ksharinarayanan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-09-23 16:00 UTC, lieut-data requested changes
Thanks, @ksharinarayanan. A few comments below.

2024-09-23 16:00 UTC, lieut-data commented on server/channels/api4/channel.go
> -	if c.Params.Permanent {
While it should not be possible to soft delete direct and group channels, it should still be possible to soft delete public and private channels. Let's keep the `c.Params.Permanent` handling for such cases.

2024-09-23 16:00 UTC, lieut-data commented on server/channels/api4/channel_local.go
>  	} else {
This code needs to be updated to match the desired semantics.

2024-09-23 16:00 UTC, lieut-data commented on server/channels/api4/channel_test.go
> +		th.App.UpdateConfig(func(cfg *model.Config) { cfg.ServiceSettings.EnableAPIChannelDeletion = &enableAPIChannelDeletion })
Let's stick to the pattern of modifying the existing pointer vs. assigning it to the new one.

2024-09-23 16:00 UTC, lieut-data commented on server/channels/api4/channel_test.go
Can we add coverage to verify that permanent deletion allowed, but temporary isn't?

2024-10-04 01:01 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2026-07-24 06:03 UTC, vish9812 commented
The JIRA ticket needs more refinement especially around the roles/permissions needed for the operation.
Closing it for now.

2026-07-24 06:03 UTC, closed without merging