[MM-56032] Add tests for data_retention endpoints
mattermost/mattermost pull request #28283
Opened 2024-09-23 11:58 UTC by fume4mattermost

#### Summary

Added unit tests for the functions in data data_retention.go

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-56032

#### Screenshots

#### Release Note

```release-note

```

2024-09-23 11:58 UTC, mattermost-build commented
Hello @fume4mattermost,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-09-25 19:49 UTC, jwilander commented
@fume4mattermost looks like some [Go linting isn't passing](https://github.com/mattermost/mattermost/actions/runs/10993755993/job/30565870020?pr=28283) - can you address that?

2024-09-26 12:08 UTC, hanzei requested changes
https://github.com/mattermost/mattermost/pull/28283#issuecomment-2375119767

2024-09-27 07:59 UTC, hanzei requested changes
@fume4mattermost  Some of the tests are not passing. Can you please take a look?

2024-10-03 15:09 UTC, jwilander commented
@fume4mattermost seeing the following lint errors:

```
Error: channels/api4/data_retention_test.go:90:19: Error return value of `th.Client.Logout` is not checked (errcheck)
		th.Client.Logout(context.Background())
		                ^
Error: channels/api4/data_retention_test.go:224:19: Error return value of `th.Client.Logout` is not checked (errcheck)
		th.Client.Logout(context.Background())
		                ^
Error: channels/api4/data_retention_test.go:319:19: Error return value of `th.Client.Logout` is not checked (errcheck)
		th.Client.Logout(context.Background())
```

2024-10-04 15:22 UTC, BenCookie95 commented
@fume4mattermost Looks like there are still a few more lint errors:
```
Error: channels/api4/data_retention_test.go:435:19: Error return value of `th.Client.Logout` is not checked (errcheck)
		th.Client.Logout(context.Background())
		                ^
Error: channels/api4/data_retention_test.go:512:19: Error return value of `th.Client.Logout` is not checked (errcheck)
		th.Client.Logout(context.Background())
		                ^
Error: channels/api4/data_retention_test.go:602:19: Error return value of `th.Client.Logout` is not checked (errcheck)
		th.Client.Logout(context.Background())
```

2024-10-04 15:22 UTC, BenCookie95 requested changes
Lint errors from https://github.com/mattermost/mattermost/pull/28283#issuecomment-2393950720

2024-10-07 21:00 UTC, fume4mattermost commented
Hey @BenCookie95. The linting errors are now fixed. Can you look at this again?

2024-10-08 13:42 UTC, BenCookie95 approved these changes
Thank you @fume4mattermost, these tests are extremely helpful 🚀

2024-10-09 10:45 UTC, hanzei requested changes
Can you please double-check if the `th.Login` calls are needed?

Secondly, the sub tests should not duplicate the test name of the parent test. Please update them.

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +	mockDataRetentionInterface.On("GetPolicies", mock.Anything, mock.Anything).Return(samplePolicyList, nil)
Can we be a bit stricter here and use something else than `mock.Anything`?

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +		th.LoginSystemAdmin()
Is that call really required?

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +		th.LoginBasic()
Is that call really required?

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +		_, err := th.Client.Logout(context.Background())
Can you please also check the first return variable? Thanks!

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +	th.App.Srv().SetLicense(model.NewTestLicense("data_retention"))
`SetLicense` returns a boolean. Please check that it is `true`.

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +	mockDataRetentionInterface.On("GetPoliciesCount").Return(int64(3), (*model.AppError)(nil))
Is returning `nil` enough?

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +	th.App.Channels().DataRetention = (mockDataRetentionInterface)
Why are the braces needed?

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +		_, resp, err := th.Client.GetDataRetentionPoliciesCount(context.Background())
Please also check the first return variable.

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +		}
Please remove this block

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +		_, err := th.Client.Logout(context.Background())
Please also check the first return variable

2024-10-09 10:45 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +		_, err := th.Client.Logout(context.Background())
Please also check the first return variable

2024-10-24 12:30 UTC, jwilander commented
@fume4mattermost looks the the CI lint check is failing - can you take a look?

2024-10-25 09:40 UTC, hanzei approved these changes
LGTM :+1:

2024-10-25 09:40 UTC, hanzei commented on server/channels/api4/data_retention_test.go
> +		t.Logf("Calling GetDataRetentionPolicies with page=%d, perPage=%d", page, perPage)
Can you please remove all calls to `t.Logf` from this file? Thanks.

2024-10-25 09:40 UTC, hanzei requested changes
Blocking on https://github.com/mattermost/mattermost/pull/28283#discussion_r1816307524

2024-10-29 10:56 UTC, hanzei approved these changes

2024-10-29 15:04 UTC, merged