[CLD-8377] Add ability to open invitation modal from a query parameter
mattermost/mattermost pull request #28315
Opened 2024-09-25 13:35 UTC by nickmisasi

#### Summary
As part of the Cloud Enteprise Trial redesign, the marketing team is hoping to send an email to a customer containing a link that allows them to land on Mattermost with the invitation modal open. In the past we've had precedent around this for things like opening pricing or purchase modals, but no re-useable way to do so. 

I've added the QueryParamActionController component that's mounted at the root of Mattermost. This component contains a predefined map of action names, corresponding to ModalData, and dispatches openModal for any that match. The component then removes the relevant query parameter from the URL so it's not executed on refresh.

For example, navigating to https://community.mattermost.com/?action=open_invitation_modal will have you land on Mattermost with the invitation modal open. 

As part of this PR I've updated the styling of the No Permissions View for the invitation modal per UX request. 

#### Ticket Link

#### Screenshots

Before:
![image](https://github.com/user-attachments/assets/1fa034b4-f59f-4633-88c4-070fe627e3bc)

After:
![image](https://github.com/user-attachments/assets/a6a04950-33bf-4d4c-be06-548400b33652)

#### Release Note

```release-note
None
```

2024-09-25 13:59 UTC, nickmisasi commented
FYI @emdecr

2024-09-25 15:02 UTC, M-ZubairAhmed requested changes

2024-09-25 16:59 UTC, nickmisasi commented on webapp/channels/src/components/root/root.tsx
> +                        <QueryParamActionController/>
In the past when we've had actions to invoke like this they've involved pages in the system console - so I think it makes the most sense to have it at the root layer, that way it'll work in both places

2024-09-25 17:01 UTC, nickmisasi commented on webapp/channels/src/components/query_param_actions/query_param_action_controller.test.tsx
> +import {render} from '@testing-library/react';
Updated!

2024-09-25 17:15 UTC, nickmisasi commented
@abhijit-singh @yasserfaraazkhan I'm having some issues with this in the Spinwick - works 100% of the time locally, but won't work on a new tab. 

@yasserfaraazkhan  for now hold off on QA until I figure it out. 

@abhijit-singh, you can have a look at the updated modal by inviting yourself as a guest, then with that guest user, add ?action=open_invitation_modal to the end of the URL, and refresh the page.

2024-09-25 20:20 UTC, nickmisasi commented on webapp/channels/src/components/root/root.tsx
> +                        <QueryParamActionController/>
Discussed this a bit with Harrison while troubleshooting an issue and he explained to me why moving it down would be better, so I've moved to the channel controller.

2024-09-26 17:12 UTC, nickmisasi commented
@yasserfaraazkhan you should be all good now

2024-09-26 21:27 UTC, yasserfaraazkhan approved these changes
thank you @nickmisasi 
curious question: If this link is opened in a incognito mode, it'll ask user to log in. After login should the user have this modal opened?

Currently, it doesn't open invite modal. Just lands on channels.

2024-09-26 22:29 UTC, abhijit-singh approved these changes
Looks good @nickmisasi! Just one request - For the no permissions modal, the title `Unable to invite people` should have the font `Metropolis` which is used for headings instead of the current Open Sans.

> If this link is opened in a incognito mode, it'll ask user to log in. After login should the user have this modal opened?

I believe the current behaviour is fine. We can expect them to be logged-in in most cases.

2024-09-27 17:00 UTC, M-ZubairAhmed approved these changes

2024-10-02 14:20 UTC, gabrieljackson approved these changes

2024-10-02 14:21 UTC, nickmisasi commented
/update-branch

2024-10-07 14:55 UTC, merged