Fixed the tabbing twice issue
mattermost/mattermost pull request #28363
Opened 2024-09-30 19:41 UTC by adityasoni2019

#### Summary

Fixed the tabbing twice and the Enter key press issue. The use can now switch to another category without clicking twice. Made the text inside the category not tabbable. Also, when the user presses enter on any category, the functionality is working as expected.

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost/issues/26488
Jira: https://mattermost.atlassian.net/browse/MM-55273

#### Screenshots

NA

#### Release Note

```release-note
Fixes the tabbing twice and the Enter key press issue. 
```

2024-09-30 19:41 UTC, mattermost-build commented
Hello @adityasoni2019,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-01 15:09 UTC, wiggin77 commented
@adityasoni2019 it looks like this change breaks 2 of the end-to-end tests.  

```
  Verify Accessibility Support in Channel Sidebar Navigation
    1) MM-T1470 Verify Tab Support in Channels section
    ✓ MM-T1473 Verify Tab Support in Unreads section
    2) MM-T1474 Verify Tab Support in Favorites section
    ✓ MM-T1475 Verify Up & Down Arrow support in Channel Sidebar (7910ms)

  2 passing (2m)
  2 failing

  1) Verify Accessibility Support in Channel Sidebar Navigation
       MM-T1470 Verify Tab Support in Channels section:
     AssertionError: Timed out retrying after 30000ms: expected '<a#sidebarItem_off-topic.SidebarLink>' to be 'focused'
      at Context.eval (webpack://cypress/./tests/integration/channels/accessibility/accessibility_sidebar_spec.ts:77:0)

  2) Verify Accessibility Support in Channel Sidebar Navigation
       MM-T1474 Verify Tab Support in Favorites section:
     AssertionError: Timed out retrying after 30000ms: expected '<a#sidebarItem_off-topic.SidebarLink>' to be 'focused'
      at Context.eval (webpack://cypress/./tests/integration/channels/accessibility/accessibility_sidebar_spec.ts:105:0)
```

It appears the tests need to be updated to reflect the new behavior.

2024-10-01 16:03 UTC, adityasoni2019 commented
Okay, let me look into this @wiggin77. Is there any way that I can run these test on my local so that I'd know if what I'm pushing will fix this? Thanks

2024-10-01 16:37 UTC, adityasoni2019 commented
Is there any way that I can these tests on my local to see if what I'm pushing is correct? @wiggin77 

Thanks

2024-10-01 17:23 UTC, wiggin77 commented
> Is there any way that I can these tests on my local to see if what I'm pushing is correct? @wiggin77

@adityasoni2019  you can go into the `e2e-tests/cypress` directory and then `npm run cypress:open`.  That will open the cypress UI and allow you to select a browser and choose specific tests to run.  

You may need to `nvm use` from the project root to get the right environment up, and `npm install` in the `e2e-tests/cypress` directory to get the dependencies.

2024-10-03 19:14 UTC, hmhealey commented
@asaadmahmood I'm not sure if this ticket is actually valid. While this doesn't follow [the accordion pattern](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/), I think that the current behaviour is actually correct because it allows a keyboard-only user to drag and drop categories in the LHS.

https://github.com/user-attachments/assets/40fc5613-dc5b-42cd-8398-e9ece8570b52

There's some visual bugs which we should probably address, but the outer div expands/collapses the category and the inner div acts as a drag handle. We could change the style to make it clearer that that's what it does, but I don't know how we'd want to do that

2024-10-09 17:09 UTC, adityasoni2019 commented
So what's the plan of action here? @hmhealey

2024-10-11 15:36 UTC, hmhealey commented
Sorry, we're still trying to decide what the best direction is here. We want to make it quicker to tab through the channel list, but we also want to ensure that keyboard users can still rearrange the list. Let's keep this open for now while we figure out how the keyboard support should work because we may still need it

2024-10-11 16:29 UTC, hmhealey requested changes
Okay, so we're going to go forward with this approach of there only being one focusable element, but we want that element to both act as both the drag handle and as the a clickable element. For that, we need to make sure that:
1. Clicking on the category header expands/collapses it
2. Dragging the header rearranges it
3. Pressing enter when focused on the header expands/collapses it
4. Pressing space when focused on the header starts dragging it as it does now

How does that sound?

We're likely going to move the `dragHandleProps` onto the `button` element, but we'll have to see if that conflicts with the button behaviour. We might have to look at what `dragHandleProps` contains and maybe work with that

2024-10-17 19:58 UTC, adityasoni2019 commented
Okay @hmhealey, let me look at this over the weekend

2024-10-28 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-10-28 18:51 UTC, adityasoni2019 commented
Currently working on the bug, might raise a PR by this week

2024-12-05 18:53 UTC, closed without merging

2024-12-05 18:53 UTC, hmhealey commented
Closing this in favour of #29007