Errcheck issues fixed in server/channels/api4/brand_test.go
mattermost/mattermost pull request #28364
Opened 2024-09-30 19:47 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28351
Jira https://mattermost.atlassian.net/browse/MM-60708
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-01 09:48 UTC, hanzei requested changes
One question

2024-10-01 09:48 UTC, hanzei commented on server/channels/api4/brand_test.go
> +	require.Error(t, err)
Why should this error?

2024-10-01 10:06 UTC, Aryakoste commented on server/channels/api4/brand_test.go
> +	require.Error(t, err)
I changed this. It should be NoError

2024-10-01 10:53 UTC, hanzei approved these changes

2024-10-01 14:34 UTC, merged

2024-10-02 07:25 UTC, hanzei commented
@Aryakoste Heads up that I opened more tickets: https://github.com/mattermost/mattermost/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+errcheck+label%3A%22Up+For+Grabs%22

Are you interested in working on another `errcheck` issue?

2024-10-02 07:38 UTC, Aryakoste commented
Yes thanks for informing I would love to work on more such issues.

2024-10-02 07:40 UTC, hanzei commented
Awesome, I'm looking forward to more contributions from you! :rocket: