Update import_test.go (handle error properly)
mattermost/mattermost pull request #28443
Opened 2024-10-03 13:45 UTC by TheInvincibleRalph

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28393

```release-note
NONE
```

2024-10-03 13:45 UTC, mattermost-build commented
Hello @TheInvincibleRalph,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-03 13:51 UTC, hanzei reviewed
Let's see what CI reports

2024-10-03 13:51 UTC, hanzei commented on server/channels/api4/import_test.go
> +
Unrelated change?

2024-10-03 13:51 UTC, hanzei commented on server/channels/api4/import_test.go
> +	// Sanity check to ensure new posts are actually added in the system.
Unrelated change?

2024-10-03 14:46 UTC, TheInvincibleRalph commented on server/channels/api4/import_test.go
> +
Fixed.

2024-10-03 14:46 UTC, TheInvincibleRalph commented on server/channels/api4/import_test.go
> +	// Sanity check to ensure new posts are actually added in the system.
Fixed

2024-10-03 14:57 UTC, hanzei commented on server/channels/api4/import_test.go
> +
Unrelated change

2024-10-03 14:57 UTC, hanzei commented on server/channels/api4/import_test.go
Can you please remove `channels/api4/import_test.go` from the ignore list of golangci-lint?

2024-10-03 15:36 UTC, TheInvincibleRalph commented on server/channels/api4/import_test.go
Removed already. [Here](https://github.com/mattermost/mattermost/pull/28428/commits/9e6cee1c7b80a3d38d80b96caf90b80e52846f95)

2024-10-05 10:21 UTC, hanzei requested changes

2024-10-05 10:21 UTC, hanzei commented on server/channels/api4/import_test.go
Can you please do that as part of this PR? Let's keep every PR self-contained.

2024-10-05 22:33 UTC, closed without merging