refactor: migrate not_extended_when_disabled to ts
mattermost/mattermost pull request #28465
Opened 2024-10-03 16:08 UTC by hereje

#### Summary

refactor: migrate not_extended_when_disabled to ts

- migrate js files to ts
- add missing types
- update docs
- fix lint issues

#### Ticket Link

Fixes: #21306

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-03 16:08 UTC, mattermost-build commented
Hello @hereje,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-08 11:26 UTC, saturninoabril commented on e2e-tests/cypress/tests/support/ldap_server_commands.ts
> +declare global {
Yes, we're doing it here.

2024-10-08 21:45 UTC, saturninoabril approved these changes
Thanks @hanzei, LGTM except for the one comment about `any`. Approving now given it's to be resolved.

2024-10-20 02:42 UTC, hereje commented on e2e-tests/cypress/tests/integration/channels/enterprise/extend_session/not_extended_when_disabled/with_saml_login_spec.ts
> +    let samlLdapUser: any;
I have changed it to type LdapUser

2024-10-21 05:51 UTC, M-ZubairAhmed requested changes

2024-10-21 05:51 UTC, M-ZubairAhmed commented on e2e-tests/cypress/tests/support/fetch_commands.ts
> +                    // TODO: define parameters for onerror
can you remove this todo

2024-10-29 06:18 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-29 06:19 UTC, merged