[GH-28503] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/invitation_modal/add_to_channels.tsx' with FormattedMessage
mattermost/mattermost pull request #28519
Opened 2024-10-05 09:21 UTC by gvarma28

#### Summary
Replace FormattedMarkdownMessage in `webapp/channels/src/components/invitation_modal/add_to_channels.tsx` with FormattedMessage

#### Ticket Link
Fixes: #28503 

#### Release Note
```release-note
NONE
```

2024-10-05 09:21 UTC, mattermost-build commented
Hello @gvarma28,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-07 16:17 UTC, M-ZubairAhmed requested changes
Can you update the test snapshots?

2024-10-07 19:15 UTC, gvarma28 commented
I had missed adding the `values` field. This should be good now.

2024-10-08 18:33 UTC, M-ZubairAhmed requested changes

2024-10-08 18:33 UTC, M-ZubairAhmed commented on webapp/channels/src/components/invitation_modal/add_to_channels.tsx
> +                        defaultMessage='<b>(Optional)</b>'
can we change the casing to `optional` in align with `required`?

2024-10-09 17:24 UTC, gvarma28 commented
@M-ZubairAhmed 
Added the suggested change. 🚀

2024-10-10 02:19 UTC, M-ZubairAhmed commented
/update-branch

2024-10-10 02:20 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-11 05:53 UTC, yasserfaraazkhan approved these changes

2024-10-11 11:55 UTC, pvev approved these changes
LGTM! thanks @gvarma28 🎉

2024-10-11 11:57 UTC, merged