[MM-60809] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/license_settings/trial_license_card/trial_license_card.tsx' with FormattedMessage
mattermost/mattermost pull request #28554
Opened 2024-10-06 09:45 UTC by Gesare5

#### Summary

Replaces FormattedMarkdownMessage with FormattedMessage in trial_license_card.tsx
Updates en.json

#### Ticket Link

Fixes  [#28471](https://github.com/mattermost/mattermost/issues/28471)
Jira  [https://mattermost.atlassian.net/browse/MM-60809](https://mattermost.atlassian.net/browse/MM-60809)

#### Release Note

```release-note
NONE
```

2024-10-06 09:45 UTC, mattermost-build commented
Hello @Gesare5,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-07 14:56 UTC, M-ZubairAhmed requested changes

2024-10-07 14:56 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
> +                id='trialLicenseCard.description'
nit `trialLicenseCard.expiringAfterFewDays`

2024-10-09 13:00 UTC, larkox commented on webapp/channels/src/components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
> +                        b: (chunks: string) => <b>{chunks}</b>,
@M-ZubairAhmed Same question about `<b>` vs `<strong>` as in the other PR.

2024-10-10 02:04 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-11 05:51 UTC, yasserfaraazkhan approved these changes

2024-10-11 07:43 UTC, larkox commented
/update-branch

2024-10-11 09:19 UTC, merged