[MM-60808] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx' with FormattedMessage
mattermost/mattermost pull request #28552
Opened 2024-10-06 08:23 UTC by Gesare5

#### Summary

Replaces FormattedMarkdownMessage with FormattedMessage in team_edition_right_panel.tsx 
Updates en.json

#### Ticket Link

Fixes  [#28472](https://github.com/mattermost/mattermost/issues/28472)
Jira  [https://mattermost.atlassian.net/browse/MM-60808](https://mattermost.atlassian.net/browse/MM-60808)

#### Release Note

```release-note
NONE
```

2024-10-06 08:23 UTC, mattermost-build commented
Hello @Gesare5,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-06 08:28 UTC, Gesare5 commented
Hey @M-ZubairAhmed , 'localizeMessage' is also used in this component(line 132) and is deprecated, so I was wondering, do I just go ahead and swap that out for FormattedMessage?

2024-10-07 15:03 UTC, M-ZubairAhmed requested changes

2024-10-07 15:03 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
> +                        id='teamEditionRightPanel.acceptTermsInitial'
can we have the name space as `admin.licenseSettings.teamEdition.teamEditionRightPanel.xxx` in others as well

2024-10-07 15:03 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
> +                        id='teamEditionRightPanel.upgraded-restart'
```suggestion
                        id='admin.licenseSettings.teamEdition.teamEditionRightPanel.upgradedRestart'
```

2024-10-07 15:04 UTC, M-ZubairAhmed commented
> Hey @M-ZubairAhmed , 'localizeMessage' is also used in this component(line 132) and is deprecated, so I was wondering, do I just go ahead and swap that out for FormattedMessage?

That would be much appreciated thank you. You can use the useIntl hook

2024-10-08 18:46 UTC, M-ZubairAhmed requested changes

2024-10-08 18:46 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
>                                  id: 'admin.license.enterprise.restarting',
can we keep the consistent ID pattern as we did above here

2024-10-08 18:47 UTC, M-ZubairAhmed requested changes

2024-10-08 18:47 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
>      const onHandleUpgrade = (e: React.MouseEvent<HTMLButtonElement>) => {
```suggestion
    const intl = useIntl();
    
    const onHandleUpgrade = (e: React.MouseEvent<HTMLButtonElement>) => {
```

2024-10-09 10:35 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-09 12:50 UTC, larkox approved these changes

2024-10-09 13:55 UTC, M-ZubairAhmed commented
/update-branch

2024-10-10 02:04 UTC, M-ZubairAhmed commented
/e2e-test

2024-10-11 13:10 UTC, yasserfaraazkhan approved these changes
tested with cloud plugin. displays as expected

2024-10-11 13:11 UTC, merged