Fixed errcheck issues in server/channels/api4/license_local.go
mattermost/mattermost pull request #28558
Opened 2024-10-06 11:07 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28449
Jira https://mattermost.atlassian.net/browse/MM-60793
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-06 11:07 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-07 10:24 UTC, hanzei requested changes
Thanks for the PR :+1:

2024-10-07 10:24 UTC, hanzei commented on server/channels/api4/license_local.go
> +		c.Logger.Warn("Failed to copy file content to buffer", mlog.Err(err))
Failing to copy the input puffer seems like a blocking error to me. I think we should return an error to the client. Is there an existing error ID that we can reuse?

2024-10-15 07:19 UTC, hanzei commented
@Aryakoste Do you have any questions about the feedback?

2024-10-15 17:15 UTC, Aryakoste commented
@hanzei Changes done.

2024-10-16 09:30 UTC, hanzei approved these changes
LGTM :+1:

2024-10-17 15:26 UTC, calebroseland approved these changes

2024-10-18 05:02 UTC, hanzei commented
/update-branch

2024-10-24 10:13 UTC, hanzei commented
/update-branch

2024-10-24 17:53 UTC, merged