Integration action test
mattermost/mattermost pull request #28561
Opened 2024-10-06 17:50 UTC by jopaleti

#### Ticket Link

```release-note
NONE
```

2024-10-06 17:50 UTC, mattermost-build commented
Hello @jopaleti,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-06 17:58 UTC, hanzei approved these changes
Thanks for the contribution :rocket:

2024-10-06 17:58 UTC, hanzei commented on server/channels/api4/integration_action_test.go
> +		mlog.Error("Failed to write response", mlog.Err(err))
Let's properly assert an error here using `require.NoError` instead of just logging the error.

2024-10-06 17:58 UTC, hanzei commented on server/.golangci.yml
> -        channels/api4/ip_filtering_test.go|\
Unrelated change?

2024-10-06 17:58 UTC, hanzei requested changes
Thanks for the contribution :rocket:

2024-10-06 17:58 UTC, hanzei requested changes
Thanks for the contribution :rocket:

2024-10-06 21:09 UTC, hanzei commented on server/.golangci.yml
> -        channels/api4/ip_filtering_test.go|\
Can you please remove this change from the PR?

2024-10-07 14:15 UTC, fmartingr requested changes

2024-10-07 14:15 UTC, fmartingr commented on server/channels/api4/integration_action_test.go
> +	_, err = w.Write([]byte("{}"));
Let's remove that semicolon

```suggestion
	_, err = w.Write([]byte("{}"))
```

2024-10-08 14:39 UTC, fmartingr approved these changes

2024-10-08 15:41 UTC, merged