Replaced FormattedMarkdownMessage with FormattedMessage in delete_category_modal.tsx
mattermost/mattermost pull request #28607
Opened 2024-10-07 18:22 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28508
Jira https://mattermost.atlassian.net/browse/MM-60818
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-07 18:22 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-07 18:25 UTC, M-ZubairAhmed requested changes

2024-10-07 18:25 UTC, M-ZubairAhmed commented on webapp/channels/src/components/delete_category_modal/delete_category_modal.tsx
> +                    defaultMessage="Channels in <b>{category_name}</b> will move back to the Channels and Direct messages categories. You're not removed from any channels."
@Aryakoste can you refer the example PR https://github.com/mattermost/mattermost/pull/28438 
We need to create pass the b variable as XML template

2024-10-07 18:25 UTC, M-ZubairAhmed commented on webapp/channels/src/i18n/en.json
I think there was a problem here, there are too many unrelated deletions here

2024-10-07 18:35 UTC, M-ZubairAhmed commented on webapp/channels/src/i18n/en.json
are you sure you are on latest master? and your local is upto date

2024-10-07 18:35 UTC, M-ZubairAhmed commented on webapp/channels/src/i18n/en.json
may be you can try to `npm run clean` and do a refesh of `npm install`

2024-10-07 18:40 UTC, M-ZubairAhmed commented on webapp/channels/src/i18n/en.json
also please revert these changes

2024-10-07 19:02 UTC, Aryakoste commented on webapp/channels/src/i18n/en.json
I have reverted

2024-10-07 19:03 UTC, Aryakoste commented on webapp/channels/src/i18n/en.json
Or i should revert to the old commit i think. will do it. I just reverted the file

2024-10-08 05:39 UTC, M-ZubairAhmed commented on webapp/channels/src/i18n/en.json
could you replace the default message with the new one in en.json?

2024-10-08 18:12 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-09 13:26 UTC, larkox approved these changes

2024-10-10 01:40 UTC, M-ZubairAhmed commented
/e2e-test

2024-10-11 11:13 UTC, M-ZubairAhmed commented
/update-branch

2024-10-11 13:25 UTC, yasserfaraazkhan approved these changes
<img width="651" alt="image" src="https://github.com/user-attachments/assets/3032e306-8e9d-4d0e-8fbf-23e5f2d4f751">

2024-10-11 13:34 UTC, merged