replace FormattedMarkdownMessage with FormattedMessage
mattermost/mattermost pull request #28628
Opened 2024-10-08 06:13 UTC by TheInvincibleRalph

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/28501

```release-note
NONE
```

2024-10-08 06:13 UTC, mattermost-build commented
Hello @TheInvincibleRalph,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-10 01:54 UTC, M-ZubairAhmed requested changes
Just some nits

2024-10-10 01:54 UTC, M-ZubairAhmed commented on webapp/channels/src/components/mfa/setup/setup.tsx
> +                            id='mfa.setup.step2_mfa'
```suggestion
                            id='mfa.setup.step2_secret'
```

2024-10-10 01:54 UTC, M-ZubairAhmed commented on webapp/channels/src/components/mfa/setup/setup.tsx
> +                            id='mfa.setup.step3_mfa'
```suggestion
                            id='mfa.setup.step3_code'
```

2024-10-10 05:46 UTC, TheInvincibleRalph commented
Thanks for the review, @M-ZubairAhmed.

2024-10-10 07:13 UTC, TheInvincibleRalph commented
Updated i18n. All test should pass now.

2024-10-11 01:28 UTC, M-ZubairAhmed commented
/update-branch

2024-10-11 06:25 UTC, TheInvincibleRalph commented
I think I have made all requested changes. Or are there any other changes left for me to do? @M-ZubairAhmed

2024-10-11 11:47 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-11 11:48 UTC, M-ZubairAhmed commented
/e2e-test

2024-10-11 11:57 UTC, pvev approved these changes
thanks for your contribution @TheInvincibleRalph 🎉

2024-10-11 13:36 UTC, merged