Fix errcheck issues in server/channels/api4/team_test.go
mattermost/mattermost pull request #28636
Opened 2024-10-08 12:11 UTC by azadDsync

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28562

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-08 12:11 UTC, mattermost-build commented
Hello @azadDsync,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-08 14:43 UTC, hanzei requested changes
Can you please take a look at the liner errors reported [here](https://github.com/mattermost/mattermost/actions/runs/11235130908/job/31235871755?pr=28636) and resolve them?

Let me know if you need any guidance.

2024-10-11 07:22 UTC, hanzei requested changes
We are getting there!

Just a couple of issues left:
```
Error: channels/api4/team_test.go:3071:8: assignment mismatch: 1 variable but SystemAdminClient.Logout returns 2 values
Error: channels/api4/team_test.go:3162:12: cannot use client.Logout(context.Background()) (value of type error) as *model.AppError value in assignment: need type assertion
Error: channels/api4/team_test.go:3379:9: no new variables on left side of :=
Error: channels/api4/team_test.go:3894:8: assignment mismatch: 1 variable but th.SystemAdminClient.Logout returns 2 values
Error: channels/api4/team_test.go:3927:17: cannot use th.Client.TeamMembersMinusGroupMembers(context.Background(), team.Id, []string{…}, 0, 100, "") (value of type error) as *model.AppError value in assignment: need type assertion (typecheck)
```

2024-10-11 07:47 UTC, hanzei requested changes
Almost!

```
Error: channels/api4/team_test.go:2943:3: calling require.NoError on *github.com/mattermost/mattermost/server/public/model.AppError, please use require.Nil instead
Error: channels/api4/team_test.go:3536:3: calling require.NoError on *github.com/mattermost/mattermost/server/public/model.AppError, please use require.Nil instead
```

2024-10-11 09:11 UTC, hanzei commented
@azadDsync Can you please check the errors in https://github.com/mattermost/mattermost/actions/runs/11289323045/job/31399016540?pr=28636?

2024-10-14 10:23 UTC, hanzei commented
@azadDsync Here are the errors from the latest run
```
Error: channels/api4/team_test.go:2252:2: calling require.Nil on error, please use require.NoError instead
Error: channels/api4/team_test.go:2267:2: calling require.Nil on error, please use require.NoError instead
Error: channels/api4/team_test.go:2472:4: calling require.NoError on *github.com/mattermost/mattermost/server/public/model.AppError, please use require.Nil instead
Error: channels/api4/team_test.go:2565:2: calling require.NoError on *github.com/mattermost/mattermost/server/public/model.AppError, please use require.Nil instead
Error: channels/api4/team_test.go:2655:2: calling require.Nil on error, please use require.NoError instead
```

You can also run golangci-lint locally using `make golangci-lint`.

2024-10-17 10:39 UTC, hanzei commented
@azadDsync, Can you please check out the remaining errors?

2024-10-17 10:39 UTC, hanzei commented
Wrong button :facepalm:

2024-11-05 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-11-05 07:52 UTC, hanzei commented
@azadDsync Do you have any questions about the feedback?

2024-11-06 22:46 UTC, azadDsync commented
Sorry, I messed up. I've opened a new PR to start fresh and fix it from the beginning.

2024-11-06 22:47 UTC, azadDsync commented
> @azadDsync Do you have any questions about the feedback?

No, I don't have any questions about the feedback

2024-11-17 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-04-29 07:24 UTC, hanzei commented
Closing as https://github.com/mattermost/mattermost/pull/29151 has been merged

2025-04-29 07:25 UTC, closed without merging