[MM-60817]  Replace FormattedMarkdownMessage in 'webapp/channels/src/components/convert_channel_modal/convert_channel_modal.tsx' with FormattedMessage
mattermost/mattermost pull request #28642
Opened 2024-10-08 16:44 UTC by gvarma28

#### Summary
Replace FormattedMarkdownMessage in 'webapp/channels/src/components/convert_channel_modal/convert_channel_modal.tsx' with FormattedMessage

#### Ticket Link
Fixes: #28509 
Jira: MM-60817

#### Release Note
```release-note
NONE
```

2024-10-08 16:44 UTC, mattermost-build commented
Hello @gvarma28,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-08 18:11 UTC, M-ZubairAhmed requested changes

2024-10-08 18:11 UTC, M-ZubairAhmed commented on webapp/channels/src/components/convert_channel_modal/convert_channel_modal.tsx
> +                            id='convert_channel.question_2'
no need of ID change since the defaultMessage wasnt changed

2024-10-08 18:11 UTC, M-ZubairAhmed commented on webapp/channels/src/components/convert_channel_modal/convert_channel_modal.tsx
> +                            id='convert_channel.question_1'
```suggestion
                            id='convertChannel.question1'
```

Same pattern for others as well

2024-10-09 13:28 UTC, larkox approved these changes
No extra comments from my side

2024-10-09 17:18 UTC, gvarma28 commented
@M-ZubairAhmed 
Added the suggested changes, please let know if I missed anything. Thank you!

2024-10-10 01:38 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-10 01:39 UTC, M-ZubairAhmed commented
/update-branch

2024-10-11 01:23 UTC, M-ZubairAhmed commented
/e2e-test

2024-10-11 13:29 UTC, yasserfaraazkhan approved these changes
<img width="719" alt="image" src="https://github.com/user-attachments/assets/896402f6-28c1-4613-afab-a4e3fbf1057c">

2024-10-11 13:55 UTC, merged