Profile settings
mattermost/mattermost pull request #28657
Opened 2024-10-09 08:23 UTC by jopaleti

#### Ticket Link

```release-note
NONE
```
-->

2024-10-09 09:06 UTC, M-ZubairAhmed requested changes

2024-10-09 09:06 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/group_settings/group_details/group_profile_and_settings.tsx
> +                id='admin.team_settings.team_details.groupDetailsToggleDescr_updated'
we can keep the same id since the defaultMessage wasnt changed

2024-10-11 01:11 UTC, M-ZubairAhmed approved these changes

2024-10-11 11:08 UTC, M-ZubairAhmed commented
/update-branch

2024-10-11 15:24 UTC, Rajat-Dabade approved these changes

2024-10-11 15:27 UTC, merged