Replace FormattedMarkdownMessage in 'webapp/channels/src/components/i…
mattermost/mattermost pull request #28667
Opened 2024-10-09 15:28 UTC by azadDsync

…ntegrations/confirm_integration/confirm_integration.tsx' with FormattedMessage

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28506

#### Release Note

```release-note
NONE
```

2024-10-10 01:44 UTC, M-ZubairAhmed requested changes
@azadDsync Great work, If you checkout the en.json file they have not being updated with the new defaultMessages can you change those

2024-10-10 01:44 UTC, M-ZubairAhmed commented on webapp/channels/src/components/integrations/confirm_integration/confirm_integration.tsx
> +                    values={{url: '`' + incomingHookToken + '`', strong: (chunks: string) => <strong>{chunks}</strong>}}
nit :
can this come in two lines for clarity

2024-10-10 01:44 UTC, M-ZubairAhmed commented on webapp/channels/src/components/integrations/confirm_integration/confirm_integration.tsx
> +                    values={{url: '`' + incomingHookToken + '`', strong: (chunks: string) => <strong>{chunks}</strong>}}
similarly in other places as well

2024-10-11 01:25 UTC, M-ZubairAhmed commented
/update-branch

2024-10-11 03:07 UTC, harshilsharma63 approved these changes

2024-10-11 13:18 UTC, M-ZubairAhmed requested changes
@azadDsync can you check the failing CI

2024-10-11 18:13 UTC, azadDsync commented
@M-ZubairAhmed, could you please clarify the error or provide a hint or example?

2024-10-12 10:36 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed, could you please clarify the error or provide a hint or example?

You could run `npm run test:updatesnapshot` in webapp folder

2024-10-15 05:08 UTC, M-ZubairAhmed commented
@azadDsync have you tried the above command?

2024-10-17 06:17 UTC, M-ZubairAhmed commented
@azadDsync do you need help in progressing?

2024-10-17 08:36 UTC, azadDsync commented
@M-ZubairAhmed sir, 
I'm working on it; sorry for the delay due to my exams.

2024-10-17 10:31 UTC, M-ZubairAhmed commented
/update-branch

2024-10-19 02:25 UTC, M-ZubairAhmed requested changes
Thank you for fixing the CI @azadDsync i just have a minor ask

2024-10-19 02:25 UTC, M-ZubairAhmed commented on webapp/channels/src/components/integrations/confirm_integration/confirm_integration.tsx
can you please change all the <strong> here to <b> since is more structurally correct?

2024-10-23 05:35 UTC, M-ZubairAhmed approved these changes

2024-10-23 05:35 UTC, M-ZubairAhmed commented
/update-branch

2024-10-23 06:38 UTC, M-ZubairAhmed commented
/e2e-test

2024-10-23 07:20 UTC, yasserfaraazkhan approved these changes

2024-10-23 08:27 UTC, merged