[MM-60859] FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permissions.tsx' with FormattedMessage
mattermost/mattermost pull request #28732
Opened 2024-10-13 13:28 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28695
Jira  https://mattermost.atlassian.net/browse/MM-60859
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-13 13:28 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-13 13:40 UTC, M-ZubairAhmed requested changes

2024-10-13 13:40 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permissions.tsx
> +                    defaultMessage="The built-in Custom Group Manager role can be used to delegate the administration of <a>Custom Groups</a> to users other than the System Admin.{br}{br}Don't forget
Lets split these into p paragraphs
see https://github.com/mattermost/mattermost/pull/28438/files#r1791547386

2024-10-15 04:56 UTC, M-ZubairAhmed commented
@Aryakoste let me know if you need help with this one

2024-10-15 05:03 UTC, Aryakoste commented
@M-ZubairAhmed After every br I need to create a new p element right ?

2024-10-15 05:04 UTC, Aryakoste commented
Or split the first two lines into one and third line.

2024-10-15 05:13 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed After every br I need to create a new p element right ?

Yes p will make them into single line, and the next p tag will start in new line

2024-10-15 16:38 UTC, Aryakoste commented
@M-ZubairAhmed Changes done.

2024-10-17 01:04 UTC, M-ZubairAhmed requested changes
Looks good just a small nit

2024-10-17 01:04 UTC, M-ZubairAhmed commented on webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permissions.tsx
> +                                        location='manage-custom-groups'
```suggestion
                                        location='adminConsoleSystemRoles'
```

2024-10-17 01:19 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-17 06:12 UTC, M-ZubairAhmed commented
/update-branch

2024-10-17 08:13 UTC, larkox approved these changes

2024-10-17 08:18 UTC, lindy65 commented
I've assigned to you for testing @Rutam21 - let's see if the test server builds - all checks have passed so it should

cc @yasserfaraazkhan

2024-10-17 08:19 UTC, M-ZubairAhmed commented
/e2e-test

2024-10-18 21:37 UTC, Rutam21 commented
## This PR has been tested in the Test Server and the changes are working as expected.

### Current Server UI for Custom Group Manager Permission

![Old-Enterprise_server](https://github.com/user-attachments/assets/276f0234-cca3-4165-a75f-91ea86bdeedd)

### Test Server Update for Custom Group Manager Permission

![PR-Enterprise-Server](https://github.com/user-attachments/assets/e5a08ce2-45f6-4654-a512-ee92276ca627)

**There are no visual changes in the UI after the component update in this PR and the rich text formatting and functionality in this section are preserved as before.**

cc: @lindy65

2024-10-19 01:17 UTC, M-ZubairAhmed commented
@Rutam21 thank you for testing this PR 🎉

2024-10-19 01:17 UTC, merged

2024-10-19 17:46 UTC, lindy65 commented
Thanks for testing @Rutam21 - counted towards Hacktoberfest