[MM-60858] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/commercial_support_modal/commercial_support_modal.tsx' with FormattedMessage
mattermost/mattermost pull request #28737
Opened 2024-10-13 22:40 UTC by aditipatelpro

#### Summary

#### Ticket Link

#### Screenshots

#### Release Note

```release-note

```

2024-10-13 22:40 UTC, mattermost-build commented
Hello @aditipatelpro,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-14 01:59 UTC, M-ZubairAhmed requested changes
Please also check CI failures. We also need to run i18n-extract to generate the changes in en.json

2024-10-14 01:59 UTC, M-ZubairAhmed commented on webapp/channels/src/components/commercial_support_modal/commercial_support_modal.tsx
> +                                        defaultMessage='Before downloading the Support Packet, set <strong>Output Logs to File</strong> to <strong>true</strong> and set <strong>File Log Level</strong
we forgot this one `[here](!/admin_console/environment/logging)`

2024-10-14 01:59 UTC, M-ZubairAhmed commented on webapp/channels/src/components/commercial_support_modal/commercial_support_modal.tsx
>                          <div className='CommercialSupportModal__packet_contents_download'>
since this whole sentence we can make this div to be strong instead. and message could be just `Select your Support Packet contents to download`

2024-10-14 01:59 UTC, M-ZubairAhmed commented on webapp/channels/src/components/commercial_support_modal/commercial_support_modal.tsx
> +                                        location='supportLink'
you can write that as `commercialSupportModal`

2024-10-15 13:57 UTC, M-ZubairAhmed commented
@aditipatelpro do you need help with progressing this PR?

2024-10-15 22:36 UTC, aditipatelpro commented
@M-ZubairAhmed, I will address the suggestions you had. I can probably get this done by today.

2024-10-16 01:00 UTC, M-ZubairAhmed requested changes
Changes look perfectm can you take a look at CI failures

2024-10-16 03:22 UTC, M-ZubairAhmed commented
/update-branch

2024-10-16 13:25 UTC, devinbinnie approved these changes
LGTM! Thanks @aditipatelpro!

2024-10-16 16:32 UTC, M-ZubairAhmed requested changes
Can you check the ci

2024-10-16 23:30 UTC, aditipatelpro commented
@M-ZubairAhmed, I have updated the snap file. Can you please review it?

2024-10-17 06:02 UTC, M-ZubairAhmed commented
/e2e-test

2024-10-17 10:05 UTC, yasserfaraazkhan approved these changes

2024-10-17 10:29 UTC, merged