Replace FormattedMarkdownMessage in 'webapp/channels/src/components/unarchive_channel_modal/unarchive_channel_modal.tsx' with FormattedMessage #28497
mattermost/mattermost pull request #28730
Opened 2024-10-12 17:23 UTC by KvngMikey

#### Summary
The goal of this PR is to remove all instances of “FormattedMarkdownMessage” (imported from “components/formatted_markdown_message”) in the file webapp/channels/src/components/unarchive_channel_modal/unarchive_channel_modal.tsx. 

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28497
Jira https://mattermost.atlassian.net/browse/MM-60829

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-12 17:23 UTC, mattermost-build commented
Hello @KvngMikey,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-13 13:47 UTC, M-ZubairAhmed requested changes
Please run i18n-extract for changes in en.json also there are few CI failures as well

2024-10-14 23:37 UTC, JulienTant approved these changes
Thanks @KvngMikey

2024-10-15 01:48 UTC, M-ZubairAhmed requested changes

2024-10-15 01:48 UTC, M-ZubairAhmed commented on webapp/channels/src/components/unarchive_channel_modal/unarchive_channel_modal.tsx
> +                            id='unarchive_channel_viewArchived.question'
```suggestion
                            id='unarchiveChannelModal.viewArchived.question'
```

2024-10-15 08:17 UTC, KvngMikey commented on webapp/channels/src/components/unarchive_channel_modal/unarchive_channel_modal.tsx
> +                            id='unarchive_channel_viewArchived.question'
done, updated @M-ZubairAhmed

2024-10-15 08:23 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-15 08:24 UTC, M-ZubairAhmed commented
/update-branch

2024-10-16 13:37 UTC, yasserfaraazkhan approved these changes
@M-ZubairAhmed 
can you check the e2e tests? might be unrelated to this PR but most failed tests have same error. Just want to make sure its not related to PR

<img width="775" alt="image" src="https://github.com/user-attachments/assets/50b7cc33-4ed4-410c-b576-a534237e2648">

2024-10-17 06:44 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed can you check the e2e tests? might be unrelated to this PR but most failed tests have same error. Just want to make sure its not related to PR


Cross checked, yes thats unrelated to this PR, since this is from unarchive modal and the test failed on channel search

2024-10-17 06:45 UTC, merged