[MM-60857] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.tsx' with FormattedMessage
mattermost/mattermost pull request #28865
Opened 2024-10-19 04:11 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28697
Jira https://mattermost.atlassian.net/browse/MM-60857
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-19 04:11 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-19 18:42 UTC, M-ZubairAhmed requested changes
Can you check failing ci

2024-10-20 07:24 UTC, Aryakoste commented
/update-branch

2024-10-20 07:24 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.

2024-10-20 18:07 UTC, M-ZubairAhmed commented
/update-branch

2024-10-21 05:09 UTC, M-ZubairAhmed requested changes
Lets change these values to align with correct utm

2024-10-21 05:09 UTC, M-ZubairAhmed commented on webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.tsx
> +                                location='release-notes-modal'
```suggestion
                                location='plugin-marketplace'
```

2024-10-21 05:09 UTC, M-ZubairAhmed commented on webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.tsx
> +                                    location='release-notes-modal'
```suggestion
                                    location='plugin-marketplace'
```

2024-10-21 10:11 UTC, M-ZubairAhmed approved these changes
This looks good :shipit: Thank you

2024-10-21 10:19 UTC, M-ZubairAhmed commented
/update-branch

2024-10-22 07:50 UTC, M-ZubairAhmed commented
/e2e-test

2024-10-22 08:03 UTC, larkox approved these changes

2024-10-22 11:09 UTC, Rutam21 commented
@lindy65 @M-ZubairAhmed Please assign this PR to me for QA Testing. Thanks.

2024-10-22 11:13 UTC, lindy65 commented
Assigned to you for testing @Rutam21 👍

2024-10-22 17:25 UTC, Rutam21 commented
### This PR has been tested in the Test Server, and all the intended changes are working as expected.

- There are no visual changes in the UI and the rich text formatting in the affected areas is preserved.
- There has been no change in the functionality of this section since the component update.

Please find the comparison snapshots of this Test Server with another without these changes.

#### Another Test Server (Without these changes)

![ThisPRTestServerMajorUpdate](https://github.com/user-attachments/assets/14f074f3-0ab3-41f6-9c0d-26116a5ee974)

#### Current PR Test Server

![CurrentPRTestServerMajorUpdate](https://github.com/user-attachments/assets/72620685-d63a-4e87-bd83-1173b10739c3)

The above snapshots confirm the Major Update confirmation dialog.

cc: @lindy65

2024-10-22 17:27 UTC, lindy65 commented
Thanks for testing @Rutam21 - counted towards Hacktoberfest

cc @M-ZubairAhmed

2024-10-23 05:15 UTC, merged