[CLD-8480] Remove duplicate 'Contact Sales' link in pricing modal card
mattermost/mattermost pull request #28899
Opened 2024-10-22 18:29 UTC by nickmisasi

#### Summary
Removes a duplication of contact sales that didn't translate well after the self serve deprecation.

#### Ticket Link
https://mattermost.atlassian.net/browse/CLD-8480

#### Screenshots
Before:
![image](https://github.com/user-attachments/assets/c93c85d6-098c-4e9d-a485-b9d1ca4af82b)
After:
![image](https://github.com/user-attachments/assets/87fab5ec-0c22-4f72-ad1a-16c32db9011d)

#### Release Note

```release-note
None
```

2024-10-23 05:51 UTC, M-ZubairAhmed requested changes

2024-10-23 05:51 UTC, M-ZubairAhmed commented on webapp/package-lock.json
lets revert this

2024-10-23 13:20 UTC, nickmisasi commented on webapp/package-lock.json
Done!

2024-10-23 13:41 UTC, M-ZubairAhmed approved these changes

2024-10-24 08:16 UTC, yasserfaraazkhan approved these changes

2024-10-25 17:38 UTC, merged