Fix errcheck issues in server/channels/web/response_writer_wrapper_te…
mattermost/mattermost pull request #28902
Opened 2024-10-23 09:45 UTC by Ruhi14

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28747
JIRA: [MM-61075](https://mattermost.atlassian.net/browse/MM-61075)

#### Screenshots

#### Release Note

```release-note

```

2024-10-23 09:45 UTC, mattermost-build commented
Hello @Ruhi14,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-10-24 10:58 UTC, hanzei requested changes
One request, otherwiese LGTM :+1:

2024-10-24 17:55 UTC, hanzei commented on server/channels/web/response_writer_wrapper_test.go
>  package web
Please remove the unrelated change

2024-10-25 09:25 UTC, isacikgoz approved these changes
LGTM 👍

2024-10-25 09:26 UTC, merged