Fix errcheck issues in server/channels/web/web.go
mattermost/mattermost pull request #28911
Opened 2024-10-23 18:10 UTC by Ranjana761

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28750
JIRA: [MM-61078](https://mattermost.atlassian.net/browse/MM-61078)

#### Screenshots

#### Release Note

```release-note

```

2024-10-23 18:10 UTC, mattermost-build commented
Hello @Ranjana761,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-24 10:11 UTC, hanzei requested changes
The error changes look good. :+1: 

But could you please remove the unrelated changes? Thanks!

2024-10-24 13:23 UTC, Ranjana761 commented
> The error changes look good. 👍
> 
> But could you please remove the unrelated changes? Thanks!

DONE.

2024-10-24 18:06 UTC, hanzei approved these changes
LGTM :+1:

2024-10-25 23:09 UTC, cpoile approved these changes

2024-10-29 07:45 UTC, merged