Fix errcheck issues in server/channels/utils/fileutils/fileutils_test.go
mattermost/mattermost pull request #28919
Opened 2024-10-24 10:05 UTC by shraddha761

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28753
JIRA: [MM-61081](https://mattermost.atlassian.net/browse/MM-61081)

#### Screenshots

#### Release Note

```release-note

```

2024-10-24 10:06 UTC, mattermost-build commented
Hello @shraddha761,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-10-24 10:07 UTC, shraddha761 commented
/check-cla

2024-10-24 10:37 UTC, hanzei requested changes
Thanks for the PR! 


Can you please remove the unrelated change? Thanks!

2024-10-24 10:37 UTC, hanzei commented on server/channels/utils/fileutils/fileutils_test.go
> -
Please remove the unrelated change

2024-10-24 10:37 UTC, hanzei commented on server/channels/utils/fileutils/fileutils_test.go
> +		}()
No need for a new `err` variable. You can just use the existing one
```suggestion
		defer func() {
			err = os.RemoveAll(tmpDir1)
			require.NoError(t, err)
		}()
```

2024-10-24 10:37 UTC, hanzei commented on server/channels/utils/fileutils/fileutils_test.go
> +			Expected   string
Unrelated change

2024-10-24 10:37 UTC, hanzei commented on server/channels/utils/fileutils/fileutils_test.go
> +					}()
Same here
```suggestion
					defer func() {
						err = os.Chdir(prevDir)
						require.NoError(t, err)
					}()
```

2024-10-24 11:13 UTC, hanzei approved these changes
LGTM :+1:

2024-10-24 11:13 UTC, hanzei commented on server/channels/utils/fileutils/fileutils_test.go
> -
Nit: Unrelated change

2024-10-24 12:03 UTC, fmartingr approved these changes
👍  Thank you!

2024-10-24 18:24 UTC, hanzei commented on server/channels/utils/fileutils/fileutils_test.go
> +
The file is not `gofmt`ed. Can you please fix that?

2024-10-25 07:38 UTC, merged

2024-10-25 07:39 UTC, hanzei commented
Thanks @shraddha761 !