Fix errcheck issues in server/channels/utils/license_test.go
mattermost/mattermost pull request #28912
Opened 2024-10-23 18:26 UTC by Ranjana761

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28754
JIRA: [MM-61082](https://mattermost.atlassian.net/browse/MM-61082)

#### Screenshots

#### Release Note

```release-note

```

2024-10-23 18:27 UTC, mattermost-build commented
Hello @Ranjana761,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-24 10:44 UTC, hanzei requested changes
Thanks for the contribution :rocket:

2024-10-24 10:44 UTC, hanzei commented on server/channels/utils/license_test.go
> +}
Can you please remove the unrelated change? Thanks!

2024-10-24 10:44 UTC, hanzei commented on server/channels/utils/license_test.go
>  		defer os.Unsetenv("MM_SERVICEENVIRONMENT")
Nit pick: You can also use `T.Setenv` instead, as that also cleans up after itself. Not a blocker for the PR.

2024-10-24 18:06 UTC, hanzei requested changes

2024-10-24 18:06 UTC, hanzei commented on server/channels/utils/license_test.go
>  		defer os.Unsetenv("MM_SERVICEENVIRONMENT")
If `t.Setenv` is used, the `defer` clause is not needed.

2024-10-24 18:06 UTC, hanzei commented on server/channels/utils/license_test.go
>  		defer os.Unsetenv("MM_SERVICEENVIRONMENT")
Do you plan to apply the same change here and in other places?

2024-10-24 18:06 UTC, hanzei commented on server/channels/utils/license_test.go
> +
The file is not `gofmt`ed. Can you please fix that?

2024-10-24 19:20 UTC, hanzei approved these changes
Nice one :+1:

2024-10-28 14:54 UTC, sbishel approved these changes

2024-10-30 09:35 UTC, Ranjana761 commented
> Nice one 👍

Please Review.

2024-11-04 10:19 UTC, hanzei requested changes

2025-04-01 10:54 UTC, closed without merging

2025-04-01 10:54 UTC, hanzei commented
Closing as inactive