Fixed errcheck issues in server/channels/app/helper_test.go
mattermost/mattermost pull request #28936
Opened 2024-10-24 14:20 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28929
Jira https://mattermost.atlassian.net/browse/MM-61253

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-24 14:20 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-24 18:13 UTC, hanzei requested changes
Thanks for the quick PR!

2024-10-24 18:13 UTC, hanzei commented on server/channels/app/helper_test.go
> +	}
Can we use the `require.NoError` here?

2024-10-24 18:13 UTC, hanzei commented on server/channels/app/helper_test.go
> +	}
And also in line 56

2024-10-24 18:13 UTC, hanzei commented on server/channels/app/helper_test.go
> +		}
Let's add a `testing.TB` field to `TestHelper` and use `require.Nil` here and in the rest of the file

2024-10-29 14:48 UTC, Aryakoste commented
Working on it.

2024-10-29 15:11 UTC, Aryakoste commented
@hanzei Changes done

2024-10-29 15:12 UTC, Aryakoste commented
/update-branch

2024-10-30 00:11 UTC, hanzei commented
/update-branch

2024-11-04 08:10 UTC, hanzei approved these changes
Great work! Much cleaner now

2024-11-04 08:10 UTC, hanzei commented on server/channels/app/helper_test.go
> +	team, appErr = th.App.CreateTeam(th.Context, team)
Does this also work?
```suggestion
	team, appErr := th.App.CreateTeam(th.Context, team)
```

2024-11-04 08:12 UTC, hanzei approved these changes

2024-11-04 08:12 UTC, hanzei commented on server/channels/app/helper_test.go
> +	require.NoError(th.TB, appErr)
```suggestion
	require.Nil(th.TB, appErr)
```

2024-11-04 08:12 UTC, hanzei commented on server/channels/app/helper_test.go
>  	var channel *model.Channel
Nit: I think we can remove these and use `:=` in L424

2024-11-07 10:08 UTC, hanzei requested changes
It seems like you are not setting `TB` correctly. The tests are failing with a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10bd44e]

goroutine 557 [running]:
testing.tRunner.func1.2({0x2af6b60, 0x534f370})
	/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0x2af6b60?, 0x534f370?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/stretchr/testify/assert.Fail({0x0, 0x0}, {0xc00585fd40, 0x5a}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:363 +0x34e
github.com/stretchr/testify/assert.NoError({0x0, 0x0}, {0x38db460, 0xc00302c480}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1545 +0x125
github.com/stretchr/testify/require.NoError({0x0, 0x0}, {0x38db460, 0xc00302c480}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/require/require.go:1354 +0xb0
github.com/mattermost/mattermost/server/v8/channels/app.(*TestHelper).InitBasic(0xc003509440)
	/mattermost/server/channels/app/helper_test.go:279 +0x1de
github.com/mattermost/mattermost/server/v8/channels/app.TestGetLatestVersion(0xc0034ecea0)
	/mattermost/server/channels/app/admin_test.go:18 +0x4b
testing.tRunner(0xc0034ecea0, 0x310fed0)
	/usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x390
```

2024-11-09 09:35 UTC, Aryakoste commented
I will look into why this panic error is coming and let you know.

2024-11-20 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-12-10 12:39 UTC, hanzei commented on server/channels/app/helper_test.go
> +	require.NoError(th.TB, err)
We can remove the caching via `sync.Once`. It is not helpful and only complicates the code further.

2024-12-17 13:06 UTC, hanzei commented on server/channels/app/helper_test.go
> +	th.BasicUser2, _ = th.App.GetUser(th.BasicUser2.Id)
The tests are failing with 

```
    helper_test.go:263: 
        	Error Trace:	/mattermost/server/channels/app/helper_test.go:263
        	            				/mattermost/server/channels/app/webhook_test.go:26
        	Error:      	Received unexpected error:
        	            	pq: duplicate key value violates unique constraint "users_pkey"
        	Test:       	TestCreateIncomingWebhookForChannel
```


an you please add some error checks, please and look into the test failure? Thanks!

2025-02-09 13:36 UTC, Aryakoste commented on server/channels/app/helper_test.go
> +	th.BasicUser2, _ = th.App.GetUser(th.BasicUser2.Id)
@hanzei I think problem here can be th.CreateUser()  is already inserting the user into the database, calling InsertUsers(users) again will attempt to insert the same users, leading to a primary key conflict.

2025-04-11 08:27 UTC, hanzei commented on server/channels/app/helper_test.go
> +	th.BasicUser2, _ = th.App.GetUser(th.BasicUser2.Id)
Please just remove the caching via `sync.Once`. It is not helpful and only complicates the code further.

2025-04-25 06:23 UTC, Aryakoste commented
Will fix this

2025-04-29 18:32 UTC, Aryakoste commented
@hanzei Done

2025-05-07 08:26 UTC, hanzei commented on server/channels/app/helper_test.go
> +		TB:                tb,
A reviewer pointed out on https://github.com/mattermost/mattermost/pull/30707#discussion_r2073353799 that storing a `testing.TB` in a struct can cause issues with sub-tests. Would you please migrate the code to just pass a testing.TB to all methods that need it. Thanks!

2025-05-18 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-05-19 10:23 UTC, hanzei commented
@Aryakoste Do you plan to continue working on this PR?

2025-05-19 10:46 UTC, Aryakoste commented
Yes will make the change

2025-05-25 12:22 UTC, Aryakoste commented
Working on this

2025-05-25 12:34 UTC, Aryakoste commented
@hanzei if i have to pass the testing.T in the methods then i would have to make changes in the files everywhere it is used is it ok ?.

2025-06-08 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-06-10 10:10 UTC, hanzei commented
@Aryakoste Would you mind of I take ownership of this PR? I would like to push the campaign over the finish line.

2025-06-11 17:22 UTC, Aryakoste commented
No, you can take the ownership @hanzei

2025-06-16 13:53 UTC, hanzei commented
Closing in favour of https://github.com/mattermost/mattermost/pull/31578

Thanks for your time @Aryakoste :+1:

2025-06-16 13:53 UTC, closed without merging