Fix errcheck issues in server/channels/app/imaging/decode_test.go
mattermost/mattermost pull request #28958
Opened 2024-10-25 08:47 UTC by samarth29jc

#### Summary

Fixes errcheck issues in decode_test.go

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28946
JIRA: [MM-61255](https://mattermost.atlassian.net/browse/MM-61255)

#### Screenshots

#### Release Note

```release-note

```

2024-10-25 08:47 UTC, mattermost-build commented
Hello @samarth29jc,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-10-25 08:51 UTC, samarth29jc commented
/check-cla

2024-10-25 09:17 UTC, hanzei requested changes
Nice work :+1:

2024-10-25 09:17 UTC, hanzei commented on server/channels/app/imaging/decode_test.go
> +		defer func() {
Nit pick
```suggestion
		defer func() {
```

2024-10-25 09:17 UTC, hanzei commented on server/channels/app/imaging/decode_test.go
> +}
Unrelated change

2024-10-25 09:38 UTC, hanzei commented on server/channels/app/imaging/decode_test.go
> +		defer func() {
Do you also want to fix the other occurrences?

2024-10-28 20:32 UTC, calebroseland approved these changes
LGTM, please fix lint

2024-10-30 18:53 UTC, samarth29jc commented
> LGTM, please fix lint

DONE. 
Please Review and Merge

2024-11-04 08:16 UTC, hanzei commented on server/channels/app/imaging/decode_test.go
> +		defer func() {
```suggestion
		defer func() {
```

2024-11-04 09:55 UTC, merged