Update file_info.go (fix errcheck issue)
mattermost/mattermost pull request #28966
Opened 2024-10-25 11:34 UTC by TheInvincibleRalph

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28926

```release-note
NONE
```

2024-10-25 12:44 UTC, TheInvincibleRalph commented
/update-branch

2024-11-03 04:36 UTC, TheInvincibleRalph commented
/update-branch

2024-11-04 08:06 UTC, hanzei requested changes
Another one!

2024-11-04 08:06 UTC, hanzei commented on server/channels/app/file_info.go
> +		).Wrap(err)
This seems wrong. Which error are you wrapping here?

2024-11-04 08:06 UTC, hanzei commented on server/channels/app/file_info.go
> +					log.Printf("Failed to seek to the beginning of the data: %v", err)
Let's not log to stdout and instead return an `*model.AppError`. Maybe there is an error code that you can reuse.

2024-11-08 09:22 UTC, hanzei approved these changes
LGTM :+1:

2024-11-11 19:49 UTC, gabrieljackson approved these changes
LGTM

2024-11-12 12:26 UTC, hanzei commented
@TheInvincibleRalph Did you do anything fancy with the branch? I can neither merge the PR nor push to your branch.

2024-11-12 13:43 UTC, TheInvincibleRalph commented
> @TheInvincibleRalph Did you do anything fancy with the branch? I can neither merge the PR nor push to your branch.

No. The branch is still intact.

2024-11-13 14:51 UTC, hanzei commented
/update-branch

2024-11-14 07:42 UTC, merged