Fix errcheck issues in server/channels/jobs/jobs.go
mattermost/mattermost pull request #28972
Opened 2024-10-25 13:41 UTC by Ranjana761

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28762
JIRA: [MM-61089](https://mattermost.atlassian.net/browse/MM-61089)

#### Screenshots

#### Release Note

```release-note

```

2024-10-25 13:42 UTC, mattermost-build commented
Hello @Ranjana761,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-30 09:36 UTC, Ranjana761 commented
@hanzei Review Please

2024-11-04 10:00 UTC, hanzei requested changes
The changes LGTM, but the file is not `go fmt`ed. Can you please fix that? Thanks!

2024-11-25 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-04-01 10:56 UTC, hanzei commented
Closing as inactive

2025-04-01 10:56 UTC, closed without merging