Fixed errcheck issues in server/channels/app/export_test.go
mattermost/mattermost pull request #29004
Opened 2024-10-28 18:59 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28922
Jira https://mattermost.atlassian.net/browse/MM-61246
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-28 18:59 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-04 10:09 UTC, hanzei requested changes
LGTM, one blocking comment

2024-11-04 10:09 UTC, hanzei commented on server/channels/app/export_test.go
> +		err = th1.App.BulkExport(th1.Context, &b, "somePath", nil, model.BulkExportOpts{})
`err` is now an `error`, but `th1.App.BulkExport` returns a `*model.AppError`. Please use a new variable.

2024-11-16 06:47 UTC, Aryakoste commented
@hanzei Changes done.

2024-11-29 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-12-10 13:50 UTC, hanzei commented on server/channels/app/export_test.go
>  		err := th1.App.BulkExport(th1.Context, &b, "somePath", nil, model.BulkExportOpts{})
This need to become an `appErr`

2024-12-10 17:53 UTC, Aryakoste commented
@hanzei Changes done

2024-12-12 13:58 UTC, hanzei requested changes
You are reusing an `err` variable in L309:

```
Error: channels/app/export_test.go:309:3: calling require.Nil on error, please use require.NoError instead
```
Let's make CI happy :smile:

2024-12-14 11:53 UTC, Aryakoste commented
@hanzei In my local branch i was not seeing this error. But when i merged the branch new code was added which is giving this error. I will fix this.

2024-12-14 12:02 UTC, Aryakoste commented
/update-branch

2024-12-17 13:14 UTC, davidkrauser approved these changes
LGTM :+1:

2024-12-17 15:15 UTC, merged