Fixed errcheck issues in server/channels/app/file_bench_test.go
mattermost/mattermost pull request #29003
Opened 2024-10-28 18:44 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/28924
Jira https://mattermost.atlassian.net/browse/MM-61248
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-10-28 18:44 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-10-31 15:24 UTC, hanzei approved these changes
LGTM

2024-10-31 15:24 UTC, hanzei commented on server/channels/app/file_bench_test.go
>  				}
Nit: we can just use `require.Nil`

2024-11-04 05:45 UTC, harshilsharma63 approved these changes
Looks good other that the one change pointed out by @hanzei

2024-11-04 07:54 UTC, hanzei requested changes

2024-11-04 07:54 UTC, hanzei commented on server/channels/app/file_bench_test.go
>  				}
Blocking on this

2024-11-25 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-04-11 08:31 UTC, hanzei commented
/update-branch

2025-04-11 09:52 UTC, hanzei approved these changes

2025-04-11 10:13 UTC, merged