[MM-59363] Shared channel event telemetry
mattermost/mattermost pull request #29024
Opened 2024-10-31 10:58 UTC by Willyfrog

#### Summary
Added events for:
- view shared channel
- mention a remote user
- post a message in a shared channel

Not added:
- DM a remote user as that has been removed from scope of Shared channels

#### Ticket Link
[MM-59363](https://mattermost.atlassian.net/browse/MM-59363)
#### Screenshots

#### Release Note
```release-note
NONE
```

2024-10-31 11:51 UTC, mgdelacroix requested changes
Just one comment, otherwise LGTM!

2024-10-31 11:51 UTC, mgdelacroix commented on server/channels/app/notification.go
> +		if user.IsRemote() && user.RemoteId != nil && *user.RemoteId != "" {
`user.IsRemote()` already checks for `RemoteId`

```suggestion
		if user.IsRemote() {
```

2024-11-05 10:03 UTC, Willyfrog commented
Friendly reminder for reviewing the PR to @ifoukarakis and @mgdelacroix 🔔

2024-11-05 11:33 UTC, ifoukarakis approved these changes

2024-11-05 15:26 UTC, mgdelacroix approved these changes

2024-11-05 15:26 UTC, merged