Fixed errcheck issues in server/channels/app/permissions.go
mattermost/mattermost pull request #29064
Opened 2024-11-02 12:28 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29048
Jira https://mattermost.atlassian.net/browse/MM-61449
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-11-02 12:28 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-04 08:48 UTC, hanzei requested changes
We can cleanup this code instead of refactoring it

2024-11-04 08:48 UTC, hanzei commented on server/channels/app/permissions.go
> +			fmt.Printf("Failed to delete scheme with ID %s: %s\n", schemeID, appErr.Message)
Actually, the whole method `ImportPermissions`, which calls `rollback`, is no longer used. Can you just remove it and `rollback`?

2024-11-25 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-12-11 13:35 UTC, hanzei requested changes
You need to run `make app-layers` and commit the changes.

2024-12-17 09:17 UTC, hanzei approved these changes
Thanks :+1:

2024-12-19 20:13 UTC, isacikgoz commented
@Aryakoste you probably need to remove tests associated with this method.

2024-12-22 13:42 UTC, Aryakoste commented
@isacikgoz Done

2025-01-03 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-03 08:56 UTC, hanzei requested changes
I think we can remove the whole `TestImportPermissions` test

2025-01-06 10:23 UTC, hanzei commented on server/channels/app/permissions_test.go
>  func TestImportPermissions_idempotentScheme(t *testing.T) {
We can also remove this test, right?

2025-01-17 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-18 14:22 UTC, Aryakoste commented
@hanzei Done

2025-01-29 07:54 UTC, hanzei commented
@Aryakoste Can you please merge `master` into your branch?

2025-01-30 08:36 UTC, hanzei commented on server/channels/app/opentracing/opentracing_layer.go
We can delete this file

2025-01-30 08:36 UTC, hanzei commented on server/channels/app/app_iface.go
And this one as well

2025-01-31 13:56 UTC, Aryakoste commented
@hanzei Done.

2025-02-04 14:18 UTC, hanzei approved these changes
LGTM :+1:

2025-02-13 19:06 UTC, isacikgoz commented
/update-branch

2025-02-24 13:38 UTC, hanzei commented
/update-branch

2025-02-25 09:49 UTC, merged

2025-02-25 09:49 UTC, hanzei commented
Thanks @Aryakoste !