Fixed errcheck issues in server/channels/app/plugin_install.go
mattermost/mattermost pull request #29062
Opened 2024-11-02 08:36 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29054
Jira https://mattermost.atlassian.net/browse/MM-61456
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-11-02 08:36 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-04 08:41 UTC, hanzei requested changes

2024-11-04 08:41 UTC, hanzei commented on server/i18n/en.json
> +  },
The order of the translations is not correct. You need to run `make i18n-extract` and commit the changes.

2024-11-16 06:36 UTC, Aryakoste commented
@hanzei Changes done.

2024-11-19 11:32 UTC, hanzei approved these changes
LGTM :+1:

2024-11-20 09:51 UTC, hanzei commented
@Aryakoste Can you please merge `master` into your branch? Thanks!

2024-11-20 10:11 UTC, Aryakoste commented
@hanzei Done

2024-11-21 10:30 UTC, merged

2024-11-21 10:30 UTC, hanzei commented
Thanks @Aryakoste :tada: