Fixed errcheck issues in server/channels/app/migrations.go
mattermost/mattermost pull request #29067
Opened 2024-11-02 19:36 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29031
Jira https://mattermost.atlassian.net/browse/MM-61443
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-11-02 19:36 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-04 09:15 UTC, hanzei requested changes
Thanks for the PR :+1:

2024-11-04 09:15 UTC, hanzei commented on server/channels/app/migrations.go
>  func (a *App) DoEmojisPermissionsMigration() {
Let's return an error and check that. That ensures the error gets surfaced.

2024-11-25 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-11-25 17:32 UTC, Aryakoste commented
@hanzei Changes done

2024-12-12 11:51 UTC, hanzei approved these changes

2024-12-12 11:51 UTC, hanzei commented on server/channels/app/migrations.go
>  func (a *App) DoGuestRolesCreationMigration() {
I would like to see the error getting returned here, but it's not a blocker.

2024-12-12 14:56 UTC, fmartingr approved these changes

2024-12-17 08:44 UTC, hanzei approved these changes

2024-12-17 13:16 UTC, merged

2024-12-17 13:17 UTC, hanzei commented
Thanks @Aryakoste :tada: