Thai tone marks and vowels at the end of the search term is wrongly removed.
mattermost/mattermost pull request #29071
Opened 2024-11-03 16:22 UTC by callmeott

#### Summary

Thai vowels and tone marks at the end of the search term are now (likely unintentionally) removed.

E.g., สวัสดี will become only สวัสด, which is wrong.

This fix allows all Thai characters to be at the end of the search term.

2024-11-03 16:22 UTC, mattermost-build commented
Hello @callmeott,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-11-03 16:28 UTC, callmeott commented
/check-cla

2024-11-06 23:44 UTC, hmhealey requested changes
Thanks for the PR, @callmeott! I'm a bit surprised to see that `\pL` doesn't handle certain types of letters properly, but I really shouldn't be given how complicated Unicode is.

Would you mind adding a unit test for this so that we can make sure that this won't get broken again in the future?

2024-11-06 23:44 UTC, hmhealey commented on server/public/model/search_params.go
> +var searchTermPuncEnd = regexp.MustCompile(`[^\pL\p{Thai}\d\s*"]+$`)
Now that I'm looking into this, it looks like this regex might remove things like accents in other languages as well. Could we maybe make this a bit broader to also support other languages too?

Looking at the list of Unicode categories on [this website](https://www.regular-expressions.info/unicode.html#prop), it looks like `\p{M}` might work for Thai and other languages as well

2024-11-08 16:56 UTC, callmeott commented
Hi,

OK let us check if \p{M} works or not for Thai.

Btw, how should we add a unit test? Can we send you a list of Thai search
terms and the expected output after the regex maching?

Cheer,
Pattara

On Thu, Nov 7, 2024 at 6:44 AM Harrison Healey ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for the PR, @callmeott <https://github.com/callmeott>! I'm a bit
> surprised to see that \pL doesn't handle certain types of letters
> properly, but I really shouldn't be given how complicated Unicode is.
>
> Would you mind adding a unit test for this so that we can make sure that
> this won't get broken again in the future?
> ------------------------------
>
> In server/public/model/search_params.go
> <https://github.com/mattermost/mattermost/pull/29071#discussion_r1831861462>
> :
>
> > @@ -11,7 +11,7 @@ import (
>  )
>
>  var searchTermPuncStart = regexp.MustCompile(`^[^\pL\d\s#"]+`)
> -var searchTermPuncEnd = regexp.MustCompile(`[^\pL\d\s*"]+$`)
> +var searchTermPuncEnd = regexp.MustCompile(`[^\pL\p{Thai}\d\s*"]+$`)
>
> Now that I'm looking into this, it looks like this regex might remove
> things like accents in other languages as well. Could we maybe make this a
> bit broader to also support other languages too?
>
> Looking at the list of Unicode categories on this website
> <https://www.regular-expressions.info/unicode.html#prop>, it looks like
> \p{M} might work for Thai and other languages as well
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mattermost/mattermost/pull/29071#pullrequestreview-2419658330>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB23ZMEJXD7SM5CZGV3RJBDZ7KSV3AVCNFSM6AAAAABRC34RROVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJZGY2TQMZTGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-12 09:54 UTC, callmeott commented
We tested and found that  \p{M}  works fine for Thai.

And here are the example query words that should remain the same after passing this searchTermPuncEnd regex (for unit tests):

สวัสดี
ที่นี่
นี้
กี๊
การันต์
หมาดุ
ลองดู
กู้

Thank you very much,
Pattara

2024-11-12 21:13 UTC, hmhealey commented
I think we only need a test or two added to `TestParseSearchFlags2` in `model/search_params_test.go`. You could use anything that didn't work before as the input for it

2024-11-13 08:47 UTC, callmeott commented
I've revised the patch to use \p{M} instead and add test cases in
https://github.com/mattermost/mattermost/pull/29241

2024-11-15 21:21 UTC, hmhealey approved these changes
Thanks for adding those tests and for changing that regular expression! This looks great!

2024-11-19 03:25 UTC, callmeott commented
Added a related bug fix of Thai search keywords not properly hi-lighted in the search results.

2024-11-20 11:16 UTC, isacikgoz commented
/update-branch

2024-11-20 11:16 UTC, mattermost-build commented
We don't have permissions to update this PR, please contact the submitter to apply the update.

2024-11-20 11:18 UTC, isacikgoz commented
@callmeott can you please update the branch, the CI is having a build failure. Thanks!

2024-11-20 11:55 UTC, isacikgoz approved these changes
LGTM, waiting CI to be green.

2024-11-21 04:39 UTC, callmeott commented
> @callmeott can you please update the branch, the CI is having a build failure. Thanks!

You mean update the branch at https://github.com/MetamediaTechnology/mattermost right? Done.

2024-11-21 12:55 UTC, isacikgoz commented
> > @callmeott can you please update the branch, the CI is having a build failure. Thanks!
> 
> You mean update the branch at https://github.com/MetamediaTechnology/mattermost right? Done.

Yes, if you can also give us the permission to update the branch, we can update before merging it. Thanks!

2024-11-21 13:47 UTC, merged

2024-12-17 02:55 UTC, callmeott commented
We noticed that in your latest release, only the changes in server/public/model folder got included but not those in  webapp/channels/src/utils. Is this normal?

2024-12-18 23:18 UTC, hmhealey commented
> We noticed that in your latest release, only the changes in server/public/model folder got included but not those in webapp/channels/src/utils. Is this normal?

Which release are you seeing that in? This PR was merged shortly after we started releasing 10.3.0, so nothing from it would've made it into that release, and we only just started the release process for 10.4.0 a few days ago.

If you're comfortable running a release candidate, we did just cut the first one of those for 10.4.0 which would have your changes. The tarballs for the Linux versions of 10.4.0 RC1 are available using these links:
https://releases.mattermost.com/10.4.0-rc1/mattermost-team-10.4.0-rc1-linux-amd64.tar.gz
https://releases.mattermost.com/10.4.0-rc1/mattermost-enterprise-10.4.0-rc1-linux-amd64.tar.gz

2024-12-19 04:05 UTC, callmeott commented
We were testing 10.3.0 and found that Thai search was working in some cases so we thought the patch was in. Likely it was rather from DB tuning. 

Sorry for the false alarm, we'll wait for 10.4.0. Thank you very much.