update helper_test.go (fix errcheck issue)
mattermost/mattermost pull request #29158
Opened 2024-11-07 10:20 UTC by TheInvincibleRalph

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29098

```release-note
NONE
```

2024-11-07 10:20 UTC, mattermost-build commented
Hello @TheInvincibleRalph,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-07 11:27 UTC, hanzei requested changes
Thanks for there RP!

There are a couple of cases that you missed:

```
Error: channels/app/slashcommands/helper_test.go:61:17: Error return value of `memoryStore.Set` is not checked (errcheck)
	memoryStore.Set(memoryConfig)
	               ^
Error: channels/app/slashcommands/helper_test.go:109:2: unnecessary trailing newline (whitespace)
```

2024-11-11 11:16 UTC, hanzei requested changes
Another one:
`Error: channels/app/slashcommands/helper_test.go:190:3: calling require.NoError on *github.com/mattermost/mattermost/server/public/model.AppError, please use require.Nil instead`

2024-11-14 08:33 UTC, hanzei commented on server/channels/app/slashcommands/helper_test.go
> +	t                 *testing.T
You also need to set the `t` when creating a `TestHelper`

2024-11-15 06:38 UTC, TheInvincibleRalph commented
/update-branch

2024-11-18 10:51 UTC, hanzei requested changes
The tests are failing with:
```
    helper_test.go:209: 
        	Error Trace:	/mattermost/server/channels/app/slashcommands/helper_test.go:209
        	            				/mattermost/server/channels/app/slashcommands/command_channel_header_test.go:15
        	Error:      	Received unexpected error:
        	            	pq: duplicate key value violates unique constraint "users_pkey"
        	Test:       	TestHeaderProviderDoCommand
```

Can you please check what is going on?

2024-11-20 10:35 UTC, TheInvincibleRalph commented
> The tests are failing with:
> 
> ```
>     helper_test.go:209: 
>         	Error Trace:	/mattermost/server/channels/app/slashcommands/helper_test.go:209
>         	            				/mattermost/server/channels/app/slashcommands/command_channel_header_test.go:15
>         	Error:      	Received unexpected error:
>         	            	pq: duplicate key value violates unique constraint "users_pkey"
>         	Test:       	TestHeaderProviderDoCommand
> ```
> 
> Can you please check what is going on?

I think there is a primary key conflict in the users table in the database. Upon running the test multiple times, the database record somehow might have left some data which is causing the conflict.

2024-11-20 10:37 UTC, TheInvincibleRalph commented
> The tests are failing with:
> 
> ```
>     helper_test.go:209: 
>         	Error Trace:	/mattermost/server/channels/app/slashcommands/helper_test.go:209
>         	            				/mattermost/server/channels/app/slashcommands/command_channel_header_test.go:15
>         	Error:      	Received unexpected error:
>         	            	pq: duplicate key value violates unique constraint "users_pkey"
>         	Test:       	TestHeaderProviderDoCommand
> ```
> 
> Can you please check what is going on?

I think there is a primary key conflict in the users table in the database. Upon running the test multiple times, the database record somehow might have left some data which is causing the conflict. What do you think?

2024-11-27 16:45 UTC, TheInvincibleRalph commented
> > Upon running the test multiple times, the database record somehow might have left some data which is causing the conflict.
> 
> Agreed. Did you got to the root cause? Why are DB records still there?
> 
> Anyway, what do you think about removing the caching from `initBasic` and just recreating the users every time?

I found this on the line preceding the cache function:
> 	// create users once and cache them because password hashing is slow
Based on this comment, I just hope removing cache will not affect performance.

2024-11-27 16:54 UTC, TheInvincibleRalph commented
I have removed the cache layer. I hope it runs now

2024-12-08 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-12-10 13:44 UTC, hanzei commented
There are a couple of think that you can clean you now:

```
Error: channels/app/slashcommands/helper_test.go:179:5: var `initBasicOnce` is unused (unused)
var initBasicOnce sync.Once
    ^
Error: channels/app/slashcommands/helper_test.go:180:5: var `userCache` is unused (unused)
var userCache struct {
    ^
Error: channels/app/slashcommands/helper_test.go:[186](https://github.com/mattermost/mattermost/actions/runs/12054855198/job/34189062856?pr=29158#step:6:187):48: unnecessary leading newline (whitespace)

^
make: *** [Makefile:297: golangci-lint] Error 1
```

2024-12-11 00:48 UTC, TheInvincibleRalph commented
/update-branch

2024-12-18 06:01 UTC, TheInvincibleRalph commented
/update-branch

2025-01-06 12:42 UTC, hanzei commented
There is more to fix @TheInvincibleRalph

```
Error: channels/app/helper_test.go:637:24: sqlStore.GetMasterX undefined (type *sqlstore.SqlStore has no field or method GetMasterX)
Error: channels/app/helper_test.go:643:24: sqlStore.GetMasterX undefined (type *sqlstore.SqlStore has no field or method GetMasterX)
Error: channels/app/helper_test.go:650:24: sqlStore.GetMasterX undefined (type *sqlstore.SqlStore has no field or method GetMasterX)
Error: channels/app/helper_test.go:654:24: sqlStore.GetMasterX undefined (type *sqlstore.SqlStore has no field or method GetMasterX)
Error: channels/app/helper_test.go:658:24: sqlStore.GetMasterX undefined (type *sqlstore.SqlStore has no field or method GetMasterX)
Error: channels/app/helper_test.go:664:24: sqlStore.GetMasterX undefined (type *sqlstore.SqlStore has no field or method GetMasterX) (typecheck)
// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
Error: channels/app/slashcommands/helper_test.go:179:5: var `initBasicOnce` is unused (unused)
var initBasicOnce sync.Once
    ^
Error: channels/app/slashcommands/helper_test.go:180:5: var `userCache` is unused (unused)
var userCache struct {
    ^
Error: channels/app/slashcommands/helper_test.go:[186](https://github.com/mattermost/mattermost/actions/runs/12387299460/job/35192591255?pr=29158#step:6:187):48: unnecessary leading newline (whitespace)
```

2025-01-06 12:43 UTC, hanzei commented
Do you need help setting up your dev environment? A standard `go vet` call or a well-configured IDE should find these errors before you push the code.

2025-04-11 08:24 UTC, hanzei commented
@TheInvincibleRalph Do you plan to continue your work on this PR?

2025-04-29 08:16 UTC, hanzei commented
Closing the PR due to inactivity

2025-04-29 08:16 UTC, closed without merging

2025-04-29 11:19 UTC, hanzei commented
No problem @TheInvincibleRalph. Life happens :wink: Thanks for the time you put into this RP!