[MM-56031] Add DeleteSidebarCategory method and channel category API tests
mattermost/mattermost pull request #29161
Opened 2024-11-07 12:23 UTC by fume4mattermost

#### Summary

	•	Added method:
	       •	DeleteSidebarCategory in server/public/model/client4.go
	•	Added unit tests for the following functions in server/channels/api4/channel_category_test.go:
                •	TestGetCategoriesForTeamForUser
                •	TestGetCategoryOrderForTeamForUser
                •	TestUpdateCategoryOrderForTeamForUser
                •	TestGetCategoryForTeamForUser
                •	TestValidateSidebarCategory
                •	TestValidateSidebarCategoryChannels
                •	TestDeleteCategoryForTeamForUser

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-56031

#### Screenshots

#### Release Note

```release-note

```

2024-11-07 12:23 UTC, mattermost-build commented
Hello @fume4mattermost,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-07 17:36 UTC, jwilander commented
@hmhealey added you as first reviewer since I know you had a big hand in the sidebar category effort but feel free to re-assign if someone else would be a better fit

2024-11-09 00:00 UTC, enahum requested changes
Other than the one missing test that I could think of, the rest looks very good.

2024-11-09 00:00 UTC, enahum commented on server/channels/api4/channel_category_test.go
> +	t.Run("should delete category when user has permission", func(t *testing.T) {
can we add a test that checks once a category is deleted, that the channels it held are moved to the default categories? true for all types of channels.

Thanks

2024-11-13 13:34 UTC, enahum approved these changes

2024-11-15 20:55 UTC, hmhealey requested changes

2024-11-15 20:55 UTC, hmhealey commented on server/channels/api4/channel_category_test.go
> +		require.Nil(t, app_err)
Could you rename `app_error` to follow our naming convention?
```suggestion
		user, appErr := th.App.CreateUser(th.Context, &model.User{
			Email:    th.GenerateTestEmail(),
			Username: "user_" + model.NewId(),
			Password: "password",
		})
		require.Nil(t, appErr)
```

2024-11-15 20:55 UTC, hmhealey commented on server/channels/api4/channel_category_test.go
> +		c := &Context{
This Context is the same between each of these subtests. Could you move it out of the tests instead of repeating it?

2024-11-15 20:55 UTC, hmhealey commented on server/channels/api4/channel_category_test.go
> +		c := &Context{
Same comment here about reusing the same Context

2024-11-15 20:55 UTC, hmhealey commented on server/channels/api4/channel_category_test.go
> +	t.Run("should filter duplicate channel IDs", func(t *testing.T) {
I think this test is named incorrectly since it makes it sound like the function should remove duplicates

2024-11-15 20:55 UTC, hmhealey commented on server/channels/api4/channel_category_test.go
> +	t.Run("should log message for filtered channels", func(t *testing.T) {
This test doesn't actually test that anything is logged

2024-11-15 20:55 UTC, hmhealey commented on server/public/model/client4.go
> +func (c *Client4) DeleteSidebarCategory(ctx context.Context, userId string, teamId string, categoryId string) (*Response, error) {
Can you rename this to `DeleteSidebarCategoryForTeamForUser` to match the name of the other sidebar methods, and can you move it to be defined in the same place in the file as the rest of those?

2024-11-25 20:48 UTC, hmhealey requested changes
Thanks for changing those. There's one last thing below

2024-11-25 20:48 UTC, hmhealey commented on server/public/model/client4.go
> -func (c *Client4) TestNotifications(ctx context.Context) (*Response, error) {
Could you re-add this and `Client4.testNotificationRoute` above? I think they got removed by a bad merge

2024-12-03 21:22 UTC, hmhealey approved these changes

2024-12-03 21:23 UTC, hmhealey commented
Thanks for fixing that! Assuming this passes CI now, it should be good to merge

2024-12-13 18:31 UTC, hmhealey commented
/e2e-test

2024-12-16 21:29 UTC, merged