fix: errcheck issues in channels/app/post_test.go
mattermost/mattermost pull request #29164
Opened 2024-11-07 14:18 UTC by kyrillosisaac2

#### Summary
Fix errcheck issues in channels/app/post_test.go

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/29082
Jira https://mattermost.atlassian.net/browse/MM-61467

#### Release Note]

```release-note
NONE
```

2024-11-07 14:18 UTC, mattermost-build commented
Hello @kyrillosisaac2,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-11 11:37 UTC, hanzei requested changes
Thanks for submitting the PR!

2024-11-14 17:38 UTC, kyrillosisaac2 commented on server/channels/app/post_test.go
> +	require.NoError(t, err)
Thank you for your review. I changed variable name to deleteErr as appErr is used below. deleteErr variable will be used below in equality assertion. So, I cannot use appErr. if there are any modifications needed please let me know.

2024-11-15 10:19 UTC, hanzei commented
@kyrillosisaac2 Can you please merge `master` into your branch? Thanks!

2024-11-18 10:54 UTC, hanzei requested changes
Nice work, we are getting there!

2024-11-18 10:54 UTC, hanzei commented on server/channels/app/post_test.go
> +	require.Nil(t, deleteErr)
This can also be an `appErr`

2024-11-18 10:54 UTC, hanzei commented on server/channels/app/post_test.go
> +	require.Equal(t, "api.post.update_post.can_not_update_post_in_deleted.error", deleteErr.Id)
Copy past error :wink: 
```suggestion
	require.Equal(t, "api.post.update_post.can_not_update_post_in_deleted.error", appErr.Id)
```

2024-11-18 10:54 UTC, hanzei commented on server/channels/app/post_test.go
> +	require.Nil(t, appErr)
```suggestion
	require.Nil(t, appErr)

```

2024-11-29 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-04-01 10:59 UTC, hanzei commented
Closing as inactive

2025-04-01 10:59 UTC, closed without merging