update command_remove_test.go (fix errcheck issue)
mattermost/mattermost pull request #29177
Opened 2024-11-08 05:47 UTC by TheInvincibleRalph

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29096

```release-note
NONE
```

2024-11-08 05:47 UTC, mattermost-build commented
Hello @TheInvincibleRalph,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-08 08:40 UTC, hanzei requested changes
Can you please fix the two cases that you missed?

```
Error: channels/app/slashcommands/command_remove_test.go:56:25: Error return value of `th.App.AddUserToChannel` is not checked (errcheck)
	th.App.AddUserToChannel(th.Context, th.BasicUser, publicChannel, false)
	                       ^
Error: channels/app/slashcommands/command_remove_test.go:77:25: Error return value of `th.App.AddUserToChannel` is not checked (errcheck)
	th.App.AddUserToChannel(th.Context, th.BasicUser, privateChannel, false)
	                       ^
```

2024-11-10 05:18 UTC, TheInvincibleRalph commented
> Can you please fix the two cases that you missed?
> 
> ```
> Error: channels/app/slashcommands/command_remove_test.go:56:25: Error return value of `th.App.AddUserToChannel` is not checked (errcheck)
> 	th.App.AddUserToChannel(th.Context, th.BasicUser, publicChannel, false)
> 	                       ^
> Error: channels/app/slashcommands/command_remove_test.go:77:25: Error return value of `th.App.AddUserToChannel` is not checked (errcheck)
> 	th.App.AddUserToChannel(th.Context, th.BasicUser, privateChannel, false)
> 	                       ^
> ```

Fixed. Thank you!

2024-11-11 15:17 UTC, Willyfrog approved these changes

2024-11-13 19:21 UTC, merged

2025-02-19 11:14 UTC, amyblais commented
@holopin-bot @TheInvincibleRalph Mattermost Most Valued Professional (MVP)