Fixed errcheck issues in server/channels/app/server_test.go
mattermost/mattermost pull request #29199
Opened 2024-11-09 13:42 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29089
Jira https://mattermost.atlassian.net/browse/MM-61491
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-11-09 13:42 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-11 11:30 UTC, hanzei requested changes
Thanks for the PR :+1:

2024-11-11 11:30 UTC, hanzei commented on server/channels/app/server_test.go
> +	require.NoError(t, err)
This is allowed to error.

2024-11-16 06:28 UTC, Aryakoste commented
@hanzei Changes done

2024-11-19 11:30 UTC, hanzei approved these changes
LGTM :+1:

2024-11-19 17:45 UTC, wiggin77 approved these changes
LGTM :+1:

2024-11-19 17:45 UTC, merged