[MM-61477] Fixed exif rotates images width and height is not correctly calculated
mattermost/mattermost pull request #29309
Opened 2024-11-17 18:02 UTC by fxnm

#### Summary

Added additional rotation to the size based on the EXIF rotation of the image.
Because the in the current behavior the image size will wrong (height and width swapped), resulting in a cropped image on mobile.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-mobile/issues/8308
Jira: https://mattermost.atlassian.net/browse/MM-61477

#### Release Note

```release-note
Fixed EXIF rotated image previews not having the correct size.
```

2024-11-17 18:02 UTC, mattermost-build commented
Hello @fxnm,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-18 08:54 UTC, fmartingr requested changes
LGTM! This seems simple enough and do not require modifying the image. Thanks for your contribution!

Can we add one or some test cases to ensure this get's modified the way is intended?

2024-11-20 08:01 UTC, fmartingr commented on server/channels/app/post_metadata_test.go
> +		},
Could we add some cases for PNG as well?

2024-11-25 09:56 UTC, fmartingr commented
/update-branch

2024-12-02 10:53 UTC, fmartingr commented
/update-branch

2024-12-02 10:54 UTC, fmartingr commented
> Any updates?

It seems we have some flaky tests around. Let me check if those were fixed in master first.

2024-12-03 22:20 UTC, hmhealey approved these changes
Thanks for the PR, @fxnm! This looks great!

2024-12-04 04:39 UTC, yasserfaraazkhan approved these changes

2024-12-05 18:16 UTC, merged