MM-61830 - hide actions to no permissions channels
mattermost/mattermost pull request #29319
Opened 2024-11-18 16:06 UTC by pvev

#### Summary
This PR adds the logic to hide the action buttons to non-admin users on scheduled post that were created on channels that the user does not have permissions to.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61830

#### Screenshots
Before:

https://github.com/user-attachments/assets/f423260f-26ac-4df5-89f0-1710beef840d

After:
https://github.com/user-attachments/assets/a5120679-779e-4326-8479-ed1d4e3cec06

#### Release Note
```release-note
NONE
```

2024-11-18 16:22 UTC, pvev commented on webapp/channels/src/components/drafts/drafts_illustration.tsx
> +        height='100%'
not related, fix error shown in console about invalid prop value in svg

2024-11-19 03:40 UTC, harshilsharma63 requested changes
@pvev can you handle just one more case - when you create a scheduled post in a channel and then archive that channel, we show the error code and error indicator in such scheduled posts. In that case as well, can you please hide the edit, send now and reschedule icons?

Everything else looks good and works great locally!

2024-11-19 03:40 UTC, harshilsharma63 commented on webapp/channels/src/components/drafts/placeholder_scheduled_post_title/placeholder_scheduled_posts_title.tsx
> +            defaultMessage={'This was scheduled in a private channel you are no member of.'}
So the `No destination`  can appear even when a channel is hard deleted somehow. So, lets use a generic error message - `The channel either doesn't exist or you do not have access to it`.

2024-11-19 10:35 UTC, pvev commented
done @harshilsharma63 , now covers also scenario for archived channels. Tooltip text was updated too and new unit tests added.


https://github.com/user-attachments/assets/190ebe11-2d2f-4262-98a4-3bf2b415cef4

2024-11-20 00:28 UTC, harshilsharma63 approved these changes

2024-11-20 04:33 UTC, yasserfaraazkhan approved these changes

2024-11-20 12:34 UTC, pvev commented on webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx
> +    const userChannelMember = channel && Object.prototype.hasOwnProperty.call(myChannelsMemberships, channel?.id);
makes sense, good suggestion. will try it and if it works will update the code.

2024-11-20 16:38 UTC, pvev commented
@amyblais can we please cherry-pick this one to 10.3?

2024-11-21 08:00 UTC, harshilsharma63 commented
> @amyblais can we please cherry-pick this one to 10.3?

@pvev I added the cherry pick approved tag, as soon as you merge the PR the cherrypick PR wil open up. You can merge this anythime now.

2024-11-21 08:50 UTC, merged

2024-11-21 08:50 UTC, mattermost-build commented
Cherry pick is scheduled.