err Fixed
mattermost/mattermost pull request #29326
Opened 2024-11-19 11:38 UTC by Hustler-Sameer

#### Summary

Issue Resolved

#### Ticket Link
 
Fixes https://github.com/mattermost/mattermost/issues/29111
Jira https://mattermost.atlassian.net/browse/MM-61507

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-11-19 11:39 UTC, mattermost-build commented
Hello @Hustler-Sameer,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-11-19 11:45 UTC, Hustler-Sameer commented
/check-cla

2024-11-20 09:50 UTC, hanzei requested changes

2024-11-20 09:50 UTC, hanzei commented on server/channels/app/upload.go
> +			}
Let's use a different variable name to not overwrite the error that gets checked in L237.

2024-12-01 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-12-13 06:37 UTC, Hustler-Sameer commented
@hanzei Done

2024-12-17 09:44 UTC, hanzei commented on server/channels/app/upload.go
> +			if err2 = a.RemoveFile(uploadPath); err2 != nil {
You need to define `err2`
```suggestion
			if err2 := a.RemoveFile(uploadPath); err2 != nil {
```

2025-04-01 11:02 UTC, hanzei commented
Closing as inactive

2025-04-01 11:02 UTC, closed without merging