fixed issue
mattermost/mattermost pull request #29327
Opened 2024-11-19 13:09 UTC by Hustler-Sameer

#### Summary

Solved the issue.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29108
Jira https://mattermost.atlassian.net/browse/MM-61504

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-11-19 13:09 UTC, mattermost-build commented
Hello @Hustler-Sameer,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-20 09:17 UTC, hanzei requested changes
Thanks for the PR :+1: 

Can you please use the variable name `err` for any variables of the type `error` and `appErr` for any of the type `*model.AppError`? Thanks!

2024-11-20 09:17 UTC, hanzei commented on server/channels/app/team.go
> +		}
Let's use `appErr` as a variable name

2024-11-20 09:17 UTC, hanzei commented on server/channels/app/team.go
> +			c.Logger().Warn("Error while deleting token", mlog.Err(delErr))
```suggestion
			c.Logger().Warn("Error while deleting expired token", mlog.Err(delErr))
```

2024-11-20 09:17 UTC, hanzei commented on server/channels/app/team.go
> +		if delErr := a.DeleteToken(token); delErr != nil { // Use a new variable for the error
What value does that comment add?

2024-11-20 09:17 UTC, hanzei commented on server/channels/app/team.go
> -
Please add the newline back

2024-11-20 09:17 UTC, hanzei commented on server/channels/app/team.go
> +			}
Why are you returning with an error here and not logging it?

2024-12-01 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2024-12-13 07:06 UTC, Hustler-Sameer commented
@hanzei Done

2024-12-17 09:49 UTC, hanzei requested changes

2024-12-17 09:49 UTC, hanzei commented on server/channels/app/team.go
> -
Can you please cleanup this unrelated change? Thanks!

2024-12-17 09:49 UTC, hanzei commented on server/channels/app/team.go
> -
And here

2025-04-01 11:02 UTC, hanzei commented
Closing as inactive

2025-04-01 11:02 UTC, closed without merging