Update permissions language to be more explicit
mattermost/mattermost pull request #29368
Opened 2024-11-22 18:24 UTC by enzowritescode

#### Summary

"Manage Playbook Members" permission currently says "Add and remove public playbook members" which implies users with the role "Playbook Member". It does not imply the ability to add/remove "Playbook Admin" users even though that is its intention. Adjusted the language to be more explicit.

#### Ticket Link
NA

#### Release Note
```release-note
NONE
```

2024-11-22 19:06 UTC, matthewbirtch approved these changes

2024-11-25 09:38 UTC, esarafianou requested changes
If we want to become more explicit with the permissions language around membership permissions, we need to do this across all permissions. 

Right now we're in the following state:

* **Manage Channel Members** (under _public_ channels section): Add and remove public channel members.
* **Manage Channel Members** (under _private_ channels section): 
Add and remove private channel members: 
 * **Manage Playbook Members** (under public playbooks): Add and remove _public_ playbook members
 * **Manage Playbook Members** (under private playbooks): Add and remove _private_ playbook members


With this PR, we're updating the language to cover the admins case in only one instance, creating more uncertainty into what's happening with the rest 3 cases and more likelihood that Mattermost users will be thinking that admins are not included in the other 3 sections since we don't explicitly mention this.

2024-12-11 18:09 UTC, enzowritescode commented
Tested permissions and made other necessary changes

2024-12-12 21:06 UTC, matthewbirtch approved these changes
Looks good to me

2024-12-13 13:55 UTC, esarafianou approved these changes

2024-12-20 11:53 UTC, crspeller approved these changes

2025-01-13 15:30 UTC, enzowritescode commented
/update-branch

2025-04-09 15:42 UTC, DHaussermann commented
/update-branch

2025-04-10 19:03 UTC, DHaussermann commented
@enzowritescode after looking into this and discussing with @saturninoabril, there is an unrelated Playwright failure which I reported separately. 

That said we can over override E2E tests here. I will apply the label.

2025-04-10 19:53 UTC, merged