[MM-53650] Add disable emoticon rendering setting to webapp
mattermost/mattermost pull request #29414
Opened 2024-11-28 01:50 UTC by uday-rana

#### Summary

This pull request adds a user setting to the webapp to toggle rendering emoticons (`:D`) as emojis (😄).

##### QA Test Steps

1. Navigate to User Settings.
2. Go to the Display category.
3. Find the section labelled "Auto-render emoticons as emoji" and click "Edit".
4. Toggle the setting and click "Save".
5. Emoticon rendering should be toggled client-side with the setting.

#### Ticket Link

Fixes (partially) https://github.com/mattermost/mattermost/issues/26504
Jira https://mattermost.atlassian.net/browse/MM-53650

**Note** the issue and ticket describe adding this feature to the mobile app as well, which this PR does not.

#### Screenshots

#### Release Note

```release-note
Added a new user setting to toggle rendering emoticons (:D) as emojis (😄)
```

2024-12-11 09:49 UTC, larkox requested changes
Great work! Just a few comments

2024-12-13 20:37 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +    const [serverError, setServerError] = useState<string | undefined>(undefined);
Good catch. I'll remove those.

2024-12-13 20:39 UTC, uday-rana commented on webapp/channels/src/utils/text_formatting.test.ts
> +            const output = formatText(`${spaces}${emoji}`, {renderEmoticonsAsEmoji: true}, emptyEmojiMap);
Good point, I'll add tests for that.

2024-12-19 05:18 UTC, uday-rana commented on webapp/channels/src/components/post_markdown/index.ts
> +            renderEmoticonsAsEmoji: getBool(state, Preferences.CATEGORY_DISPLAY_SETTINGS, Preferences.RENDER_EMOTICONS_AS_EMOJI, enableRenderEmoticonsAsEmoji),
I understood preferences to be client-side. If there's a better approach, could you provide some more info?

2024-12-19 12:09 UTC, larkox commented on webapp/channels/src/components/post_markdown/index.ts
> +            renderEmoticonsAsEmoji: getBool(state, Preferences.CATEGORY_DISPLAY_SETTINGS, Preferences.RENDER_EMOTICONS_AS_EMOJI, enableRenderEmoticonsAsEmoji),
What I mean is that there are two settings. One at server level, and one at preferences level. Probably I am the one that misunderstood the ticket, but let me verify with you.

Is the server setting a default, and then you can set the client setting to what you want?

Or is the server setting a switch to enable or disable the feature (and then allow the users to set it to whatever they want in their preferences)?

2024-12-19 18:39 UTC, uday-rana commented on webapp/channels/src/components/post_markdown/index.ts
> +            renderEmoticonsAsEmoji: getBool(state, Preferences.CATEGORY_DISPLAY_SETTINGS, Preferences.RENDER_EMOTICONS_AS_EMOJI, enableRenderEmoticonsAsEmoji),
The server setting is supposed to be the default

2024-12-26 22:19 UTC, uday-rana commented on webapp/channels/src/utils/emoticons.test.tsx
> +            expect(Emoticons.handleEmoticons('":P"', new Map(), true)).
I've added tests for `undefined` and `false`.

I also reverted changes to some tests which I'd previously modified to pass `true` where I realized it wasn't necessary.

2024-12-26 22:19 UTC, uday-rana commented on webapp/channels/src/utils/text_formatting.test.ts
> +            const output = formatText(`${spaces}${emoji}`, {renderEmoticonsAsEmoji: true}, emptyEmojiMap);
Done.

2024-12-26 22:21 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/index.ts
> +    const userPreference = props.adminMode && props.userPreferences ? props.userPreferences : undefined;
Are you talking about removing the check for `props.adminMode`?

2024-12-28 18:26 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +    const [serverError, setServerError] = useState<string | undefined>(undefined);
Done.

2025-01-06 21:59 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/index.ts
> +    const userPreference = props.adminMode && props.userPreferences ? props.userPreferences : undefined;
Hi @larkox, any update on this?

2025-01-07 18:45 UTC, hmhealey requested changes
Thanks for the PR! I have some suggestions, but this is looking pretty good already

2025-01-07 18:45 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +        if (active && areAllSectionsInactive) {
I don't think this is correct since these can never be true at the same time when these are set this way:
```
                <RenderEmoticonsAsEmoji
                    active={this.props.activeSection === 'renderEmoticonsAsEmoji'}
                    areAllSectionsInactive={this.props.activeSection === ''}
```
Perhaps this should be `!active && areAllSectionsInactive`?

2025-01-07 18:45 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +                                    id='user.settings.display.renderEmoticonsAsEmojiOn'
I can't remember why we started using different IDs for "on/off" for each of these settings, but I think we should stop adding more of those. The ID of this one isn't quite correct, but we seem to use it in a few other places, so we can use it here as well
```suggestion
                                    id='user.settings.advance.on'
```

You'll also need to remember to update `en.json` again as well

2025-01-07 18:45 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +                                    id='user.settings.display.renderEmoticonsAsEmojiOff'
```suggestion
                                    id='user.settings.advance.off'
```

2025-01-07 18:45 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +                    defaultMessage='Auto-render emoticons as emojis'
Could you change the wording on this to remove the "Auto-" part? I know it disagrees with the text in the ticket, but I don't think "auto-rendering" is the correct term here
```suggestion
                    defaultMessage='Render emoticons as emojis'
```

2025-01-07 18:45 UTC, hmhealey commented on webapp/channels/src/utils/emoticons.tsx
> +    renderEmoticonsAsEmoji?: boolean,
Could you change this so that the default behaviour is to render emotions as emojis? The `DEFAULT_OPTIONS` in `text_formatting.tsx` only applies when there's no options passed at all, so if we want this to default to true, we have to handle the case where an options object is passed but `renderEmoticonsAsEmoji` isn't passed

```suggestion
    renderEmoticonsAsEmoji = true,
```

2025-01-07 18:45 UTC, hmhealey commented on webapp/platform/types/src/config.ts
> +    EnableRenderEmoticonsAsEmoji: string;
These changes would also need to be reverted if we remove the server-wide setting

2025-01-18 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-19 16:37 UTC, uday-rana commented on server/config/client.go
> +	props["EnableRenderEmoticonsAsEmoji"] = strconv.FormatBool(*c.TeamSettings.EnableRenderEmoticonsAsEmoji)
No problem, I can remove it.

2025-01-19 19:04 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +    const [serverError] = useState<string | undefined>(undefined);
Makes sense to me. I've removed useState and hardcoded `false`.

2025-01-19 19:06 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/index.ts
> +    const userPreference = props.adminMode && props.userPreferences ? props.userPreferences : undefined;
Seems like we didn't need the value from the config. I've gone ahead and removed it.

2025-01-19 19:07 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +        if (active && areAllSectionsInactive) {
Makes sense. I've changed it to `!active && areAllSectionsInactive`.

2025-01-19 19:07 UTC, uday-rana commented on webapp/platform/types/src/config.ts
> +    EnableRenderEmoticonsAsEmoji: string;
Done.

2025-02-16 23:35 UTC, uday-rana commented
Hi @larkox @hmhealey, any chance I could get an update on this? Thanks!

2025-02-17 09:17 UTC, larkox commented
/update-branch

2025-02-26 21:08 UTC, hmhealey requested changes
Sorry for the delay in getting back to this. I have a couple followup changes to make, but I can make them quickly since they're easy and you've been waiting on us for so long

2025-02-26 21:08 UTC, hmhealey commented on webapp/channels/src/i18n/en.json
> +  "user.settings.display.renderEmoticonsAsEmojiTitle": "Auto-render emoticons as emojis",
This needs to be updated to match the new string in the file. Unfortunately, the tooling that extracts these from the code doesn't handle when there's a mismatch between the two
```suggestion
  "user.settings.display.renderEmoticonsAsEmojiTitle": "Render emoticons as emojis",
```

2025-02-26 21:08 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/index.ts
> +    };
Reading over https://github.com/mattermost/mattermost/pull/29414#discussion_r1866070742 again, I realize we both misunderstood what the code was doing here before. The way that the preferences code works when you're an admin editing another user's settings is a bit confusing, so what you had before was correct.

```suggestion
    const userPreferences = props.adminMode && props.userPreferences ? props.userPreferences : undefined;

    return {
        userId: props.adminMode ? props.userId : getCurrentUserId(state),
        renderEmoticonsAsEmoji: get(state, Preferences.CATEGORY_DISPLAY_SETTINGS, Preferences.RENDER_EMOTICONS_AS_EMOJI, Preferences.RENDER_EMOTICONS_AS_EMOJI_DEFAULT, userPreferences),
    };
```

2025-02-26 21:09 UTC, hmhealey approved these changes

2025-02-27 09:31 UTC, larkox commented
/update-branch

2025-02-27 14:45 UTC, yasserfaraazkhan commented
/e2e-tests

2025-03-10 09:57 UTC, yasserfaraazkhan requested changes
Scroll on the Display setting is set at the bottom.
Scroll should be on the top when we first open the link.

https://github.com/user-attachments/assets/08501f1b-ec78-4354-a949-03cc58c670a4

2025-03-11 21:58 UTC, hmhealey commented
Good catch, Yasser!

Comparing this setting with the others, this is the only one written as a functional component, so the issue is that the `useEffect` causes the edit button to be focused when the component mounts whereas the other setting components like this are class components which use `componentDidUpdate`. You can probably replace it with `useDidUpdate` from `components/common/hooks/useDidUpdate`

2025-03-13 14:08 UTC, yasserfaraazkhan commented
@uday-rana do fix the lint. Then we'll se able spin up a server and test

2025-03-13 14:32 UTC, uday-rana commented
@yasserfaraazkhan should be good now

2025-03-14 19:55 UTC, hmhealey commented
Updating this branch to fix some tests that are broken upstream

/update-branch

2025-03-17 20:42 UTC, hmhealey commented
/e2e-test

2025-03-17 22:44 UTC, hmhealey requested changes
@uday-rana Would you mind taking a look at the failing E2E tests as reported in https://automation-dashboard.vercel.app/cycle/13909446601_1-2b89809-pr-onprem-ent? Those look like they might be failing because of the new item in the display settings.

Those tests are in the `e2e-tests/cypress` folder at the root of the repo, and they can be run locally by installing NPM dependencies and then using `npm run cypress:open` to open the testing dashboard. More information on the E2E tests can be found here as well:

https://developers.mattermost.com/contribute/more-info/webapp/e2e-testing/

2025-03-21 06:10 UTC, yasserfaraazkhan commented
/update-branch

2025-03-23 08:12 UTC, yasserfaraazkhan commented
/e2e-tests

2025-03-24 02:50 UTC, yasserfaraazkhan commented
/update-branch

2025-03-24 02:52 UTC, yasserfaraazkhan approved these changes

2025-04-08 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-05-22 18:00 UTC, uday-rana commented
@hmhealey @larkox @yasserfaraazkhan Sorry about the delay in getting back to this. I've looked at the failing tests.

- `MM-T301_2 Change timezone manually` and `MM-T301_1 Change timezone automatically` were failing due to the modal not scrolling to the bottom properly. I’ve addressed this by refactoring the component to align more closely with how `ManageLanguages` and `ManageTimezones` are structured.

- I ran the other failing tests locally, namely `MM-T1100 Lock Teammate Name Display for all users` and `MM-T1465_2 Verify Accessibility Support in each section in Settings and Profile Dialog`. These appear to fail because they expect certain settings to be visible in the admin console and user settings modal, but those settings don’t show up unless specific config flags are enabled. From what I can tell, this is expected behavior without the right config.

Let me know if I've missed anything. I wasn't able to run the full test suite locally because it takes an impractical amount of time on my system (I left it running overnight and it still hadn’t finished by morning).

2025-05-23 13:59 UTC, larkox commented
@uday-rana It seems there are still one file with some snapshot tests failing: `src/components/user_settings/display/user_settings_display.test.tsx`

2025-05-23 14:00 UTC, larkox commented
The enterprise tests are probably just because you need to merge master into this PR.

2025-05-23 17:53 UTC, uday-rana commented
I've updated the snapshot for UserDisplaySettings and updated the branch.

2025-05-23 18:02 UTC, hmhealey requested changes
Thanks for getting back to this, fixing those tests, and attempting to run the rest of the E2E test suite. I do really appreciate the last one since I'm not sure if I've ever ran the whole thing locally before because of how long it takes 😅

2025-05-23 18:33 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.tsx
> +                        />
Fixed in 003dfdbca385073a88494e81baad6a0a1eafddbe

2025-05-23 18:33 UTC, uday-rana commented on webapp/channels/src/components/user_settings/display/render_emoticons_as_emoji/render_emoticons_as_emoji.test.tsx
> +        const {container} = render(
Fixed in 3b6adb00fffc0ca9f66166e528137b2dffc70190

2025-05-29 08:27 UTC, larkox approved these changes

2025-05-30 15:11 UTC, hmhealey approved these changes
Thanks again! This looks good to me!

2025-06-02 10:56 UTC, larkox commented
@yasserfaraazkhan The e2e failure seems to be unrelated to this PR. Can you verify and let us know if we can skip it?

2025-06-02 12:33 UTC, yasserfaraazkhan commented
@larkox I've verified the Pr changes and the e2e failure locally. Its just a flaky test.

this should be good to merge.

2025-06-02 12:35 UTC, merged

2025-06-04 09:16 UTC, larkox commented
Thank you for the contribution @uday-rana !