Fix user reports API docs
mattermost/mattermost pull request #29506
Opened 2024-12-06 10:20 UTC by hanzei

#### Summary
This is an example output of the API:
```json
[
    {
        "id": "a35iwstytb8m8xu3yejkm1fama",
        "create_at": 1726737170269,
        "update_at": 1726737215826,
        "delete_at": 0,
        "username": "dev.four",
        "auth_data": "",
        "auth_service": "ldap",
        "email": "success+devfour@simulator.amazonses.com",
        "nickname": "Dev4",
        "first_name": "Dev4",
        "last_name": "User",
        "position": "Staff Software Design Engineer",
        "roles": "system_user",
        "locale": "en",
        "timezone": {
            "automaticTimezone": "Europe/Berlin",
            "manualTimezone": "",
            "useAutomaticTimezone": "true"
        },
        "disable_welcome_email": false,
        "last_login": 1726737170291,
        "last_status_at": 1726737825387,
        "last_post_date": 1726737235922,
        "days_active": 1,
        "total_posts": 3
    },
]
```

#### Ticket Link
None

#### Release Note
```release-note
NONE
```

2024-12-06 14:02 UTC, devinbinnie approved these changes
Thanks @hanzei :)

2024-12-13 16:26 UTC, mvitale1989 commented
The failing testcase is unrelated to this PR, and has been fixed on master branch (it would've succeeded after an update-branch).
I'll override the result of the E2E run to successful.

2024-12-13 19:07 UTC, cwarnermm commented on api/v4/source/reports.yaml
> +          description: The direction in which to accept paging values from. Will return values ahead of the cursor if "prev", and below the cursor if "next". Default is "next".
```suggestion
          description: The direction to accept paging values from. Will return values ahead of the cursor if "prev", and below the cursor if "next". Default is "next".
```

2024-12-13 19:16 UTC, ewwollesen requested changes
I tested the permission change with not having to be a system_admin and was able to confirm that so it looks good. Added one minor change suggestion to the wording of one of the `description` fields.

2024-12-13 19:18 UTC, cwarnermm commented on api/v4/source/reports.yaml
> +          description: The direction in which to accept paging values from. Will return values ahead of the cursor if "prev", and below the cursor if "next". Default is "next".
Thanks, @ewwollesen! I've applied your suggestion.

2024-12-13 19:21 UTC, ewwollesen approved these changes
Looks good to me.

2024-12-16 07:13 UTC, merged