[MM-55278]: Fixed autofocus on submenu's first element
mattermost/mattermost pull request #29547
Opened 2024-12-10 13:57 UTC by ayush-chauhan233

#### Summary

- Fixed autofocus of the first menu item in submenu using Popover to render the submenu.
- Added a sub-menu header prop to render the header ReactNode.
- Initially, the header was restricting the autofocus on the first element, Hence, refactored it with the MUI popover component.
- Updated the test case and test snapshots as well as needed.

#### Steps to reproduce  
- Tab to the ••• icon on any message
- Press DOWN with the keyboard until you get to the Remind menu item
- press RIGHT to open the submenu

#### Expected Behavior 
- Sub-menu's first element must autofocus when the sub-menu opens.

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-55278
https://mattermost.atlassian.net/browse/MM-61568

#### Screenshots

<table>
    <tr>
        <th>Before</th>
 <th>After</th>
    </tr>
    <tr>
        <td>
 <img src="https://github.com/user-attachments/assets/bccde29f-03df-4860-84a5-bc88265d55f3">
</td>
  <td>
 <img src="https://github.com/user-attachments/assets/196b4ca4-0462-4302-8764-62b258d187d8">
</td>
    </tr>
</table>

#### Release Note

```release-note
NONE
```

2024-12-10 13:57 UTC, mattermost-build commented
Hello @ayush-chauhan233,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-17 14:19 UTC, AayushChaudhary0001 reviewed
@ayush-chauhan233 While testing this PR, I faced a bug which is when a user opens the submenu, and closes it using the arrow keys multiple times, the focus state gets removed from the submenu and the user experiences a weird behaviour

Steps to reproduce:-
- Press down button till you land on Remind option fro the menu.
- Press right button to open sub-menu and then left button to close it.
- Do the above step multiple times.

The focus on the sub-menu gets removed.

2025-01-07 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-07 16:12 UTC, marianunez commented
@ayush-chauhan233 is this ready for dev review?

2025-01-08 09:21 UTC, harshilsharma63 approved these changes
Worked well! The submenu is automatically highlighted.
![Uploading Screenshot 2025-01-08 at 2.48.08 PM.png…]()

2025-01-08 09:21 UTC, harshilsharma63 commented on webapp/channels/src/components/dot_menu/post_reminder_submenu.tsx
> +            subMenuHeader={<h5 className={'dot-menu__post-reminder-menu-header'}>
Its fine here, but you should keep the tag on new line unless its a one-line tag, like how it was previously. So this would be-


```
subMenuHeader={
           <h5 className={'dot-menu__post-reminder-menu-header'}>
                {formatMessage(
                    {
                        id: 'post_info.post_reminder.sub_menu.header',
                        defaultMessage: 'Set a reminder for:',
                    },
                )}
            </h5>}
        >
```

It looks more natural.

2025-01-09 18:40 UTC, hmhealey approved these changes
Nice job! Looks good to me

2025-01-13 07:48 UTC, yasserfaraazkhan commented
/e2e-tests

2025-01-13 10:02 UTC, yasserfaraazkhan approved these changes

2025-01-13 12:56 UTC, ayush-chauhan233 commented
> E2E test has completed for commit `05ed8dbbcc148bd68c78601340bb742bd8f7ed03`. Results summary:
> 
> * Cypress: pass rate is `99.90%` (see [Automation Dashboard](https://automation-dashboard.vercel.app/cycle/12742755618_1-05ed8db-pr-onprem-ent) and commit status check `E2E Tests/test`).
> * Playwright: pass rate is `100.00%` (see commit status check `E2E Tests/test-playwright`).
> 
> The run summary artifacts are available in the corresponding [Workflow Run](https://github.com/mattermost/mattermost/actions/runs/12742755618).

The test cases mention above are passing at local for the file mentioned below. 
` tests/integration/channels/collapsed_reply_threads/replies_spec.ts`

2025-01-13 16:14 UTC, marianunez commented
> The test cases mention above are passing at local for the file mentioned below.
> ` tests/integration/channels/collapsed_reply_threads/replies_spec.ts`

@yasserfaraazkhan can you help with these flaky tests?

2025-01-14 09:28 UTC, yasserfaraazkhan commented
/update-branch

2025-01-14 17:12 UTC, yasserfaraazkhan commented
/e2e-tests

2025-01-15 04:43 UTC, yasserfaraazkhan commented
@ayush-chauhan233 the e2e have passed. Can you resolve the conflicts ? we can merge it after that.

2025-01-16 21:19 UTC, ayush-chauhan233 commented
@yasserfaraazkhan @M-ZubairAhmed I was trying to resolve the merge conflict I found two issues, I am not sure if those are intentional.
1) The outline around the menu and submenu are not visible.
2) There is no spacing between the text `Tomorrow` and `Fri, 9:00 AM` in the submenu
<table>
    <tr>
        <th>Before</th>
 <th>After (master branch)</th>
    </tr>
    <tr>
        <td>
 <img src="https://github.com/user-attachments/assets/0d7e8224-edd7-4c25-8c33-494bc46073ce">
</td>
  <td>
 <img src="https://github.com/user-attachments/assets/6bd5f0d1-cb1e-40ab-82d0-188100b8e43e">
</td>
    </tr>
</table>

Please let me know if these need to be fixed so that I can proceed with resolving the merge conflict.

2025-01-20 17:32 UTC, marianunez commented
@ayush-chauhan233 thanks for surfacing these additional issues. 

> 1. The outline around the menu and submenu are not visible.

@asaadmahmood what is the intended outline for the menu items here?

> 2. There is no spacing between the text `Tomorrow` and `Fri, 9:00 AM` in the submenu

This seems to be a regression. We do need to add the spacing back. @asaadmahmood also here what is the spacing expected?

2025-01-20 18:38 UTC, asaadmahmood commented
@marianunez 
1. We already have that in the product, I think maybe the class is not being applied.
![CleanShot 2025-01-20 at 23 35 40@2x](https://github.com/user-attachments/assets/aa5f55d7-0adb-4834-aa30-e0dfe3d2ef72)

2. Here's the margin right now.
<img width="1165" alt="CleanShot 2025-01-20 at 23 34 30@2x" src="https://github.com/user-attachments/assets/d48075f9-8c60-43ad-ae4f-5cb447dd80a4" />

2025-01-20 19:24 UTC, M-ZubairAhmed requested changes
Holding off until we fix the conflicts

2025-01-21 16:01 UTC, M-ZubairAhmed submitted a review, later dismissed

2025-01-21 16:01 UTC, M-ZubairAhmed commented on webapp/channels/src/components/menu/menu_styled.tsx
This was removed in master

2025-01-23 22:00 UTC, hmhealey commented
/e2e-tests

2025-01-24 20:12 UTC, marianunez commented
> @marianunez
> 
> 1. We already have that in the product, I think maybe the class is not being applied.
>    ![CleanShot 2025-01-20 at 23 35 40@2x](https://private-user-images.githubusercontent.com/11034289/404977970-aa5f55d7-0adb-4834-aa30-e0dfe3d2ef72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc3NDk3NTMsIm5iZiI6MTczNzc0OTQ1MywicGF0aCI6Ii8xMTAzNDI4OS80MDQ5Nzc5NzAtYWE1ZjU1ZDctMGFkYi00ODM0LWFhMzAtZTBkZmUzZDJlZjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI0VDIwMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNjkyZDU1OGNmZGIwNmJhMWFhNjVkYzEwYzI2Y2U4ZDYwMDg5MWEwMzBhYjFhMmZlODAzMWYyYmFkMGNlODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LzSRKZ6u4wB9Tqqg-rTVxLckMpQrIeW-Ia7ca5mdmH4)
> 2. Here's the margin right now.
> 
> <img alt="CleanShot 2025-01-20 at 23 34 30@2x" width="1165" src="https://private-user-images.githubusercontent.com/11034289/404978312-d48075f9-8c60-43ad-ae4f-5cb447dd80a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc3NDk3NTMsIm5iZiI6MTczNzc0OTQ1MywicGF0aCI6Ii8xMTAzNDI4OS80MDQ5NzgzMTItZDQ4MDc1ZjktOGM2MC00M2FkLWFlNGYtNWNiNDQ3ZGQ4MGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI0VDIwMTA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzODQ1M2EzYjQ0NTY4MjdmOTg0MzIyZDVkMjZiNDE5YTFiNjEyMzA5YWM2M2JhZjRiZTY1ZTIwZGE3NjRmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wdKMo7Da68I2p2-I__z6iKn9TuyJyz3UVN7UaHRpuwM">

@ayush-chauhan233 we above direction on how to adjust the issues you've noticed.

2025-01-28 06:42 UTC, M-ZubairAhmed requested changes
https://github.com/user-attachments/assets/ca2d1118-a52a-438b-bab3-54d0c2276713

Please take a look at the video when navigating with the mouse once the sub menu is open is cannot be closed until we click on the sub menu's item. Even pressed Esc doesnt seem to close the sub menu. With keyboard it works fine. This seems to be happening only in the User Account menu currently. We are blocking the events propagation in the dnd sub menu may be thats the problem there.

2025-01-29 13:08 UTC, ayush-chauhan233 commented
> CleanShot.2025-01-28.at.12.09.41.mp4 
> Please take a look at the video when navigating with the mouse once the sub menu is open is cannot be closed until we click on the sub menu's item. Even pressed Esc doesnt seem to close the sub menu. With keyboard it works fine. This seems to be happening only in the User Account menu currently. We are blocking the events propagation in the dnd sub menu may be thats the problem there.

@M-ZubairAhmed  I noticed that the issue seemed to be resolved when I removed the role of `menuitemradio`. However, I'm not entirely sure why this role was added in the first place. From what I investigated, it appears that it was intended somehow to prevent the closing of the menu and sub-menu. I'm curious, though, why this special behaviour was implemented for the DND menu item, while other menu items typically close their sub-menus when their triggering menu items are clicked. Please let me know if this is an intended behaviour and if it should be fixed.

2025-01-31 04:51 UTC, M-ZubairAhmed commented
> > CleanShot.2025-01-28.at.12.09.41.mp4
> > Please take a look at the video when navigating with the mouse once the sub menu is open is cannot be closed until we click on the sub menu's item. Even pressed Esc doesnt seem to close the sub menu. With keyboard it works fine. This seems to be happening only in the User Account menu currently. We are blocking the events propagation in the dnd sub menu may be thats the problem there.
> 
> @M-ZubairAhmed I noticed that the issue seemed to be resolved when I removed the role of `menuitemradio`. However, I'm not entirely sure why this role was added in the first place. From what I investigated, it appears that it was intended somehow to prevent the closing of the menu and sub-menu. I'm curious, though, why this special behaviour was implemented for the DND menu item, while other menu items typically close their sub-menus when their triggering menu items are clicked. Please let me know if this is an intended behaviour and if it should be fixed.

I see that it was previously set this way so that clicking the menu item “Do Not Disturb – Disables all notifications” doesn’t close the menu immediately upon selection. I think we can let go of this behavior and remove the menuitemradio from it

2025-02-02 18:13 UTC, ayush-chauhan233 commented
/update-branch

2025-02-03 06:55 UTC, M-ZubairAhmed commented
> > > CleanShot.2025-01-28.at.12.09.41.mp4
> > > Please take a look at the video when navigating with the mouse once the sub menu is open is cannot be closed until we click on the sub menu's item. Even pressed Esc doesnt seem to close the sub menu. With keyboard it works fine. This seems to be happening only in the User Account menu currently. We are blocking the events propagation in the dnd sub menu may be thats the problem there.
> > 
> > 
> > @M-ZubairAhmed I noticed that the issue seemed to be resolved when I removed the role of `menuitemradio`. However, I'm not entirely sure why this role was added in the first place. From what I investigated, it appears that it was intended somehow to prevent the closing of the menu and sub-menu. I'm curious, though, why this special behaviour was implemented for the DND menu item, while other menu items typically close their sub-menus when their triggering menu items are clicked. Please let me know if this is an intended behaviour and if it should be fixed.
> 
> I see that it was previously set this way so that clicking the menu item “Do Not Disturb – Disables all notifications” doesn’t close the menu immediately upon selection. I think we can let go of this behavior and remove the menuitemradio from it

@ayush-chauhan233 can you remove that menuitemradio in the user account menu where its used

2025-02-03 07:59 UTC, ayush-chauhan233 commented
> > > > CleanShot.2025-01-28.at.12.09.41.mp4
> > > > Please take a look at the video when navigating with the mouse once the sub menu is open is cannot be closed until we click on the sub menu's item. Even pressed Esc doesnt seem to close the sub menu. With keyboard it works fine. This seems to be happening only in the User Account menu currently. We are blocking the events propagation in the dnd sub menu may be thats the problem there.
> > > 
> > > 
> > > @M-ZubairAhmed I noticed that the issue seemed to be resolved when I removed the role of `menuitemradio`. However, I'm not entirely sure why this role was added in the first place. From what I investigated, it appears that it was intended somehow to prevent the closing of the menu and sub-menu. I'm curious, though, why this special behaviour was implemented for the DND menu item, while other menu items typically close their sub-menus when their triggering menu items are clicked. Please let me know if this is an intended behaviour and if it should be fixed.
> > 
> > 
> > I see that it was previously set this way so that clicking the menu item “Do Not Disturb – Disables all notifications” doesn’t close the menu immediately upon selection. I think we can let go of this behavior and remove the menuitemradio from it
> 
> @ayush-chauhan233 can you remove that menuitemradio in the user account menu where its used

@M-ZubairAhmed  Those changes have already been pushed please review them, and the playwright failing test cases were running successfully locally, I have pushed the updated branch, and now it should run successfully.

2025-02-03 09:26 UTC, ayush-chauhan233 commented
@M-ZubairAhmed the failing playwright test cases seem to be working locally 
![Screenshot from 2025-02-03 14-55-17](https://github.com/user-attachments/assets/981a986f-1441-4fb9-9126-57f2c3e9ab22)

2025-02-04 14:41 UTC, M-ZubairAhmed commented
> @M-ZubairAhmed @marianunez the failing playwright test cases seem to be working locally !
> 
> Same goes for cypress failing test case 

What about the failing Cypress tests

2025-02-07 15:34 UTC, hmhealey commented
Yeah, I've seen that one in quite a few PRs. I'll file a ticket to look into it

2025-02-11 06:03 UTC, M-ZubairAhmed commented
> Yeah, I've seen that one in quite a few PRs. I'll file a ticket to look into it
> 
> Edit: Also, I checked the failing Playwright tests, and they also passed locally

I see. Based on the comments above, I will override the E2E test to remove the blocking flaky E2E condition. However, please check the comment [here](https://github.com/mattermost/mattermost/pull/29547#issuecomment-2630405178), which shows all E2E passes except the flaky ones.

2025-02-11 06:04 UTC, M-ZubairAhmed approved these changes

2025-02-11 06:04 UTC, merged