[MM-61674]: Added appropriate roles to the menu component
mattermost/mattermost pull request #29545
Opened 2024-12-10 13:54 UTC by ayush-chauhan233

#### Summary

- The message priority menu does not follow the correct menu structure.
- Updated the Message priority menu structure as recommended by W3C please [refer](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/)

#### Steps to reproduce  
- Navigate to the Message priority button and select it.
- Now navigate to the Standard, Important and Urgent buttons list.
- Inspect the element.
- Notice that the list is implemented incorrectly.

#### Expected Behavior 
- Please [refer](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/)

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-61674

#### Screenshots

<table>
    <tr>
        <th>Before</th>
 <th>After</th>
    </tr>
    <tr>
        <td>
 <img src="https://github.com/user-attachments/assets/c17b23f9-a7ee-4cba-838e-c21e96f06dcf">
</td>
  <td>
 <img src="https://github.com/user-attachments/assets/089d7d88-0b0c-46fb-97cf-32ccd0a20b06">
</td>
    </tr>
</table>

#### Release Note

```release-note
NONE
```

2024-12-10 13:54 UTC, mattermost-build commented
Hello @ayush-chauhan233,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-19 10:27 UTC, AayushChaudhary0001 approved these changes
This PR has been tested for the appropriate roles added tot he menu component and all the buttons list properly aligned and implemented. Just to add that testing this issue completely is not possible on the server created, since some options are only available on enterprise version. However, on changing the conditions on local hosted server, the changes in the PR are fince, LGTM. Approved.

2025-01-07 13:40 UTC, M-ZubairAhmed requested changes

2025-01-07 13:40 UTC, M-ZubairAhmed commented on webapp/channels/src/components/post_priority/post_priority_picker_item.tsx
> +            role='menuitemcheckbox'
it should be radio not checkbox

2025-01-07 13:40 UTC, M-ZubairAhmed commented on webapp/channels/src/components/post_priority/post_priority_picker.tsx
> +                                        disabled={false}
why cant we add role inside of toggleItem instead of a wrapper

2025-01-07 15:15 UTC, marianunez commented
@M-ZubairAhmed ignore my re-request for review. I was testing something

2025-01-08 09:23 UTC, harshilsharma63 approved these changes
Looks fine other than what @M-ZubairAhmed already asked.

2025-01-09 07:08 UTC, ayush-chauhan233 commented on webapp/channels/src/components/post_priority/post_priority_picker_item.tsx
> +            role='menuitemcheckbox'
The role='menuitemcheckbox' on the Wrapper that is used as ToggleItem in the MenuGroup is for the Request acknowledgement toggle button.

![MM16674](https://github.com/user-attachments/assets/da3e9c55-e83e-4284-a12c-424dce048377)

2025-01-09 09:25 UTC, ayush-chauhan233 commented on webapp/channels/src/components/post_priority/post_priority_picker.tsx
> +                                        disabled={false}
I didn't add a prop for role here considering this component has a limited usage as a list item which is a switch(kind of checkbox). Couldn't think of its usage with different role, can you suggest me an instance ?

2025-01-20 21:54 UTC, marianunez commented
/e2e-test

2025-01-28 07:09 UTC, M-ZubairAhmed approved these changes

2025-01-28 07:10 UTC, merged