[MM-55285]: Screen reader speaking wrong item in list in Find Channels modal
mattermost/mattermost pull request #29552
Opened 2024-12-10 14:45 UTC by SaurabhSharma-884

#### Summary
Fix Screen reader speaking wrong item in list in Find Channels modal

https://mattermost.atlassian.net/browse/MM-55285

#### Steps to reproduce
- Turn on screen reader (JAWS ideally)
- in Mattermost, open the Find channels modal
- Start typing for a channel
- use the DOWN key to change focus on one of the results

#### Expected
- It should read the correct item in the list as you use the DOWN and UP keys to traverse through items in the list

#### Ticket Link

#### Screenshots

![image](https://github.com/user-attachments/assets/b581f655-499a-4f0f-952e-2a7161053776)

#### Release Note

```release-note

```

2024-12-10 14:45 UTC, mattermost-build commented
Hello @SaurabhSharma-884,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-12-10 22:32 UTC, pvev commented
@SaurabhSharma-884 you need to sign the CLA agreement.

2024-12-11 02:06 UTC, pvev approved these changes
LGTM! thanks @SaurabhSharma-884 👍

2024-12-11 02:07 UTC, pvev commented
I validated this too using Voiceover and seems to be working fine after the changes:

https://github.com/user-attachments/assets/e8c3f4f4-14b6-4095-9da0-360cac3ae9cb

2024-12-13 07:34 UTC, SaurabhSharma-884 commented
/check-cla

2024-12-16 21:29 UTC, hmhealey commented
@SaurabhSharma-884 Are these PRs ready for dev review yet? I added the "Awaiting Submitter Action" label because of the CLA, but since you've signed that now, we can remove that

2024-12-20 10:27 UTC, AayushChaudhary0001 approved these changes
This PR has been tested for the search channel modal which shows correct results on searching any desired channel, LGTM. Approved.

2024-12-30 13:49 UTC, M-ZubairAhmed commented
/update-branch

2025-01-01 08:54 UTC, M-ZubairAhmed submitted a review, later dismissed
@SaurabhSharma-884 thank you a few more e2e are failing hence the failed CI check.

2025-01-07 05:27 UTC, M-ZubairAhmed commented
/e2e-test

2025-01-07 19:17 UTC, hmhealey requested changes
Looks great! I didn't realize what the combobox role was for until I saw it used here

2025-01-07 19:17 UTC, hmhealey commented on webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
> +                    aria-owns='suggestionList'
https://www.w3.org/WAI/ARIA/apg/patterns/combobox/ has a note recommending `aria-controls` for this instead of `aria-owns`:

> In ARIA 1.0, the combobox referenced its popup with [aria-owns](https://w3c.github.io/aria/#aria-owns) instead of [aria-controls](https://w3c.github.io/aria/#aria-controls). While user agents might support comboboxes with [aria-owns](https://w3c.github.io/aria/#aria-owns) for backwards compatibility with legacy content, it is strongly recommended that authors use [aria-controls](https://w3c.github.io/aria/#aria-controls).

Would you mind changing that?

2025-01-07 19:17 UTC, hmhealey commented on webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
> +                    role='combobox'
Looking at Teams and Slack, they both use `role='textbox'` for their post textboxes, so I think we need to pass in a prop to control this. I think the `Textbox` and `SearchBar` should both have `role='textbox'`

2025-01-07 19:17 UTC, hmhealey commented on webapp/channels/src/components/suggestion/switch_channel_provider.tsx
> +        id: 'quickSwitchInput',
Why pass this in as a prop when it's hard-coded?

2025-01-07 19:17 UTC, hmhealey commented on webapp/channels/src/components/suggestion/suggestion_list.tsx
> +                    data-option-index={i}
Is this still needed? I don't see it referenced anywhere

2025-01-09 11:43 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
> +                    role='combobox'
This role here is being added in input of SuggestionList only which expands or is associated with popup element. The post textarea still uses role='textarea'. Are you suggesting to replace this role here with 'textbox' ?

2025-01-10 05:44 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/suggestion/switch_channel_provider.tsx
> +        id: 'quickSwitchInput',
Updated

2025-01-13 21:41 UTC, hmhealey commented on webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
> +                    role='combobox'
The `SuggestionBox` is also used for the post textbox and search bar as well, so I thought this role was going to interfere with the roles they have otherwise and that we'd need to remove this `role` for those. I just checked both of them in Firefox though, and they have the correct roles in it, so there's no changes that need to be made:
<img width="1728" alt="Screenshot 2025-01-13 at 4 37 39 PM" src="https://github.com/user-attachments/assets/a17b0388-9df5-4fe5-9f84-bb2763f95d96" />
<img width="1410" alt="Screenshot 2025-01-13 at 4 38 05 PM" src="https://github.com/user-attachments/assets/c959a74c-8ca6-4a61-88a1-43117ae6b1a6" />

Sorry about that!

2025-01-13 21:41 UTC, hmhealey approved these changes

2025-01-13 21:57 UTC, hmhealey commented
@SaurabhSharma-884 I'm still waiting for the Cypress E2E tests to finish ([link to those results](https://automation-dashboard.vercel.app/cycle/12756614557_1-21b4a0a-pr-onprem-ent)), but the Playwright ones have failed due to these changes. Would you mind fixing that one?
<img width="1034" alt="Screenshot 2025-01-13 at 4 56 29 PM" src="https://github.com/user-attachments/assets/37a319f9-7050-4811-b49f-4d96e95d0fb4" />

2025-01-14 05:46 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
> +                    role='combobox'
Yep, No issues :raised_hands:

2025-01-14 05:59 UTC, SaurabhSharma-884 commented
> @SaurabhSharma-884 I'm still waiting for the Cypress E2E tests to finish ([link to those results](https://automation-dashboard.vercel.app/cycle/12756614557_1-21b4a0a-pr-onprem-ent)), but the Playwright ones have failed due to these changes. Would you mind fixing that one? <img alt="Screenshot 2025-01-13 at 4 56 29 PM" width="1034" src="https://private-user-images.githubusercontent.com/3277310/402711872-37a319f9-7050-4811-b49f-4d96e95d0fb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MzQwMTQsIm5iZiI6MTczNjgzMzcxNCwicGF0aCI6Ii8zMjc3MzEwLzQwMjcxMTg3Mi0zN2EzMTlmOS03MDUwLTQ4MTEtYjQ5Zi00ZDk2ZTk1ZDBmYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMDU0ODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODcyNTQ2M2VhZDdlNGI4MzdhNWE5NzI3NWZhODM5OTEwMDQ2YTQ0ZTIzNjdkYTUyN2NiMzQ2MzI3NTdmYzA0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u8w7c1WTwGDEioflT7gKSB3Bt6lSxo0XhngVdq3dn6w">

Fixed the failing playwright E2E test

2025-01-15 05:39 UTC, SaurabhSharma-884 commented
/update-branch

2025-01-15 23:04 UTC, hmhealey commented
/e2e-test

2025-01-16 19:35 UTC, hmhealey commented
The failing E2E test is unrelated to this PR, and I filed a ticket to fix it (https://mattermost.atlassian.net/browse/MM-62611), so this is good to merge

2025-01-16 19:35 UTC, merged