[MM-55284]: Fixed adding aria-label logic in team sidebar
mattermost/mattermost pull request #29562
Opened 2024-12-11 10:34 UTC by ayush-chauhan233

#### Summary

- In the Team sidebar the screen reader announces the + button as ‘team unread link’  which is confusing.
- Updated the logic to add aria labels in the Team sidebar buttons.

#### Steps to reproduce  
- With screen reader on.
- Click on the top of the team sidebar in Mattermost to place focus on that region
- TAB until you get to the + button within the team sidebar (note: you must have access to create teams)

#### Expected Behavior 
- The screen reader should read out “Create a team” or “Other teams you can join” as the tooltip states when you hover

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-55284

#### Screenshots

<table>
    <tr>
        <th>Before</th>
 <th>After</th>
    </tr>
    <tr>
        <td>
 <img src="https://github.com/user-attachments/assets/17a39c31-e4e6-4bf6-be33-64aeba817b47">
</td>
  <td>
 <img src="https://github.com/user-attachments/assets/3457b9dc-ebe4-4450-9947-4c866cfa16cc">
</td>
    </tr>
</table>

#### Release Note

```release-note
NONE
```

2024-12-11 10:35 UTC, mattermost-build commented
Hello @ayush-chauhan233,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-13 11:15 UTC, AayushChaudhary0001 commented
@ayush-chauhan233 While testing this PR, I found an issue. While the pointer focusses on the "+" icon, the reader reads "Create a team" which is wrong in case of normal user because he might not have the permissions to create a team. Instead the reader should read "Other team you can join" for a normal user. Please refer to the screenshot below:-
![Screenshot (11)](https://github.com/user-attachments/assets/856e4e6c-b291-43cb-bdff-c4f072627d79)

2024-12-16 10:40 UTC, AayushChaudhary0001 commented
@ayush-chauhan233 It seems that the issue is fixed, but there is a spelling mistake in it. The reader reads "Others teams you can join" whereas actually it should be "Other teams you can join".

2024-12-19 10:58 UTC, AayushChaudhary0001 approved these changes
Tested the new change, LGTM. Approved.

2025-01-07 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-08 21:49 UTC, hmhealey requested changes

2025-01-08 21:49 UTC, hmhealey commented on webapp/channels/src/components/team_sidebar/team_sidebar.tsx
> +                    displayName='Other teams you can join'
These strings should be translatable since they're currently just available in English. Could you change these to use `intl.formatMessage` similar to line 249 above?

That line uses the deprecated function `Utils.localizeMessage` currently, but if you update your branch to the latest master, it'll use the proper method for translation

2025-01-14 21:02 UTC, hmhealey commented on webapp/channels/src/components/team_sidebar/team_sidebar.tsx
> +                        displayName='Create a Team'
This line also needs to be updated to use `intl.formatMessage` as well. Typically, any text in the app that's visible to the user or available to them via accessibility tools needs to be translatable

2025-01-16 19:37 UTC, hmhealey commented
/update-branch

2025-01-16 19:38 UTC, hmhealey approved these changes
Looks good to me assuming the E2E tests pass! I've also updated the branch to fix the unrelated CI issues

2025-01-16 19:53 UTC, hmhealey commented
/e2e-test

2025-01-16 21:04 UTC, hmhealey commented
/e2e-test

2025-01-20 19:23 UTC, M-ZubairAhmed approved these changes

2025-01-21 23:00 UTC, merged