[MM-22872] Fix (Bug): DM list not scrolling when you press the UP/DOWN arrow keys
mattermost/mattermost pull request #29565
Opened 2024-12-11 12:15 UTC by Victor-Nyagudi

#### Summary

This PR enables the DM list to scroll up or down when the user navigates to an option out of view.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/26117
Jira https://mattermost.atlassian.net/browse/MM-22872

#### Screenshots

<details><summary>Before</summary>

https://github.com/user-attachments/assets/2453e889-8565-45dd-891d-1e0e0984e514

</details> 

<details><summary>After</summary>

https://github.com/user-attachments/assets/53a3c03e-a4fe-4e03-8a67-53186f5ef68a

</details> 

#### QA Steps

1. Start a DM with about 8 members (or any number large enough for you to scroll through).
2. Press the ↓ key until you reach the end of the list.
3. Verify the list scrolls down so each selected item is visible.
4. Once you reach the end, press the ↑ key until you reach the beginning.
5. Verify the list scrolls up so each selected item is visible.

#### Release Note

```release-note
Fixed scrolling behavior when navigating DM list using UP/DOWN arrow keys.
```

2024-12-11 12:15 UTC, mattermost-build commented
Hello @Victor-Nyagudi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-11 12:17 UTC, Victor-Nyagudi commented
/update-branch

2024-12-13 16:02 UTC, hmhealey requested changes
Thanks for the PR! It's a bit embarrassing that this has been broken for so long when it was such a simple fix. I guess it being simple is also why it was so easy to overlook.

The scrolling on hover part is fine to leave, but thanks for mentioning it since there's a chance it would've come up during QA. I think it's worked that way since we originally added keyboard selection to this list.

Would you mind adding an E2E test for this behaviour to make sure that it doesn't break again accidentally in the future ? There's already some tests for this component in that you could add to in `e2e-tests/cypress/tests/integration/channels/messaging/dm_list_of_users_spec.js`

**Edit:** We have documentation on running and writing E2E tests [here](https://developers.mattermost.com/contribute/more-info/webapp/e2e-testing/)

2024-12-23 06:17 UTC, Victor-Nyagudi commented
\update-branch

2024-12-24 17:31 UTC, Victor-Nyagudi commented
The test's ready. 

I'm just waiting on the Zephyr test case number from the QA team.

I [asked](https://community.mattermost.com/core/pl/gau678dthtgxtrp1x75hx68hyy) about it in the QA channel on Mattermost.

2025-01-04 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-07 09:10 UTC, Victor-Nyagudi commented
@hmhealey According to the [conversation on Mattermost](https://community.mattermost.com/core/pl/afgwcq9n47gmfci8tk9xjmi76w), after merging the test-management repo PR, I should get the Zephyr test number.

I'll add that to the local e2e test, and then push the changes to this branch.

2025-01-25 02:21 UTC, saturninoabril commented
fyi, https://github.com/mattermost/mattermost-test-management/pull/198 has been merged and test case has been saved as [MM-T5669](https://github.com/mattermost/mattermost-test-management/blob/main/data/test-cases/channels/messaging/MM-T5669.md). Thanks @Victor-Nyagudi!

2025-01-26 09:37 UTC, Victor-Nyagudi commented
/update-branch

2025-01-30 21:06 UTC, hmhealey approved these changes
Thanks for adding that test. It looks great

2025-01-31 08:11 UTC, harshilsharma63 approved these changes

2025-02-05 05:26 UTC, yasserfaraazkhan approved these changes

2025-02-10 13:51 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.

2025-02-11 20:58 UTC, Victor-Nyagudi commented
/update-branch

2025-02-19 20:42 UTC, hmhealey commented
The Cypress failure doesn't repro for me locally, and the Playwright failure is caused by the submenu bug that's been resolved on master

2025-02-19 20:42 UTC, merged

2025-02-19 20:42 UTC, hmhealey commented
Thanks again for the PR, and sorry for the delay in merging it!

2025-03-14 07:44 UTC, amyblais commented
@holopin-bot @Victor-Nyagudi Mattermost Most Valued Professional (MVP)