[MM-61570]: Refactored the post priority menu and fixed the keyboard navigation issue in the menu.
mattermost/mattermost pull request #29583
Opened 2024-12-12 14:51 UTC by ayush-chauhan233

#### Summary

- Refactored the post-priority menu, removed the deprecated code, and fixed the keyboard navigation issue.
- Updated the menu component to accept a menu header as well as a menu footer.
- Updated the menu item role to `menuitemcheckbox` and `menuitemradio` and added appropriate roles to the menu.

#### Steps to reproduce  
- Navigate to the Message priority button and select it.
- Notice that after selecting the Message priority button, the keyboard focus does not move on the dialog and also does not return to the triggered element.

#### Expected behavior 
- As the menu opens it should auto-focus on the first menu item as well as all the other menu items should be keyboard accessible.

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-61570
#### Screenshots

<table>
    <tr>
        <th>Before</th>
 <th>After</th>
    </tr>
    <tr>
        <td>
 <img src="https://github.com/user-attachments/assets/9783ae50-fac9-41be-85fe-9221f579e876">
</td>
  <td>
 <img src="https://github.com/user-attachments/assets/1f642d70-79e3-4d5d-855b-932932537b16">
</td>
    </tr>
</table>

#### Release Note

```release-note
- A minor change in the message priority checkbox menu item, the description width is smaller than the previous version.
```

2024-12-12 14:51 UTC, mattermost-build commented
Hello @ayush-chauhan233,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-18 14:27 UTC, AayushChaudhary0001 approved these changes
This PR has been tested for the feature that on opening the modal, the auto-focus is on the first item and rest all the options are accessible through the keyboard, LGTM. Approved.

2024-12-31 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-09 16:44 UTC, hmhealey commented on e2e-tests/cypress/tests/integration/playbooks/channels/broadcast_spec.js
> +        cy.findByLabelText('Post extra options').should('have.attr', 'role', 'menu').and('exist');
I'm reviewing the rest of the code now, but this test failed in the last E2E run: https://automation-dashboard.vercel.app/cycle/12635348539_1-5746019-pr-onprem-ent

2025-01-09 18:21 UTC, hmhealey requested changes
During testing, I've noticed a few issues with the changes to the menu component here:
1. The "Message priority" header is off centre, and it's colour is incorrect on dark themes.
![Screenshot 2025-01-09 at 1 04 39 PM](https://github.com/user-attachments/assets/79e34c64-3a61-4470-b5bc-2805435a35e2)
2. The popover is now centred on the button that opens it instead of being to the top right corner of it.
3. Sometimes, the keyboard focus outline displays on menu items when opening those menus. I think `handleMenuButtonMouseDown` was supposed to prevent that, but that got removed so that we could auto focus the items in the menu which we do still want.
![Screenshot 2025-01-09 at 12 00 06 PM](https://github.com/user-attachments/assets/55e1d0fd-ff89-489a-a82d-6317ddf9de5a)
4. You can no longer dismiss other menus by trying to tab out of them which we want for other menus in the app.

I also don't think this approach of making the popover component uses a Menu will work because this component is more than a simple menu, and I think we want to keep that component supporting the standard case. It's similar to a regular menu, but because of the header and footer elements, the focus trapping has to behave differently for this than a regular menu.

I think you were on the right track with replacing the single `MuiMenu` component with a `MuiPopover` and an `MuiMenuList`, but I think we should go further with that by putting the `Menu` versions of those components into `Menu.Popover` and `Menu.List`. If we do that, we can hopefully revert the changes in `Menu` which are needed for the `PostPriorityPicker` but are causing problems for other menus.

How does that sound? @M-ZubairAhmed may also have thoughts since he's done most of the work on the `Menu`

2025-01-14 09:55 UTC, ayush-chauhan233 commented
> During testing, I've noticed a few issues with the changes to the menu component here:
> 
> 1. The "Message priority" header is off centre, and it's colour is incorrect on dark themes.
>    ![Screenshot 2025-01-09 at 1 04 39 PM](https://private-user-images.githubusercontent.com/3277310/401650384-79e34c64-3a61-4470-b5bc-2805435a35e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NDE3MDIsIm5iZiI6MTczNjg0MTQwMiwicGF0aCI6Ii8zMjc3MzEwLzQwMTY1MDM4NC03OWUzNGM2NC0zYTYxLTQ0NzAtYjViYy0yODA1NDM1YTM1ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMDc1NjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmZlY2IzMWFmNWQ1YjU2NGE2YmY4OTdmZGVjMDg5ZDI0MGEwOWExYWNiMjY1Njg0MTFiYjg2OGRjOTE0YWUxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mr3T2rzJrJpOby85KhJpR34Z2tDyBnfWEvO-k3huJmY)
> 2. The popover is now centred on the button that opens it instead of being to the top right corner of it.
> 3. Sometimes, the keyboard focus outline displays on menu items when opening those menus. I think `handleMenuButtonMouseDown` was supposed to prevent that, but that got removed so that we could auto focus the items in the menu which we do still want.
>    ![Screenshot 2025-01-09 at 12 00 06 PM](https://private-user-images.githubusercontent.com/3277310/401650438-55e1d0fd-ff89-489a-a82d-6317ddf9de5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NDE3MDIsIm5iZiI6MTczNjg0MTQwMiwicGF0aCI6Ii8zMjc3MzEwLzQwMTY1MDQzOC01NWUxZDBmZC1mZjg5LTQ4OWEtYTgyZC02MzE3ZGRmOWRlNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTRUMDc1NjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdiMjIxMmI3MTQwYzMzNzk5MjM5OTQ1NDM3OGUwZGViMzk4ZmZmYmU3Mjg4NTkyNmRlYjMxMTg1MmI0MzRjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AbUkC0OOP-G2U_1AeLk2w7ByF8Knl800xCwVRjP0fL8)
> 4. You can no longer dismiss other menus by trying to tab out of them which we want for other menus in the app.
> 
> I also don't think this approach of making the popover component uses a Menu will work because this component is more than a simple menu, and I think we want to keep that component supporting the standard case. It's similar to a regular menu, but because of the header and footer elements, the focus trapping has to behave differently for this than a regular menu.
> 
> I think you were on the right track with replacing the single `MuiMenu` component with a `MuiPopover` and an `MuiMenuList`, but I think we should go further with that by putting the `Menu` versions of those components into `Menu.Popover` and `Menu.List`. If we do that, we can hopefully revert the changes in `Menu` which are needed for the `PostPriorityPicker` but are causing problems for other menus.
> 
> How does that sound? @M-ZubairAhmed may also have thoughts since he's done most of the work on the `Menu`

@hmhealey Just need confirmation: do we need to create a separate `Menu.popover` component specifically for cases such as the one with `PostPriorityPicker` and revert the `Menu.Container` changes?

2025-01-17 19:03 UTC, hmhealey commented
> @hmhealey Just need confirmation: do we need to create a separate Menu.popover component specifically for cases such as the one with PostPriorityPicker and revert the Menu.Container changes?

@ayush-chauhan233 No, sorry. Now that I've thought about this more, I think I got too focused on caring that this component isn't a regular menu because I would've preferred if it was its own component, but that's likely a lot more work than it's worth at the moment. You don't need to revert all those changes since we do need most of those.

The only thing that will need to be partially reverted is the changes to how the menu handles focus because we want other menus in the app to keep following [the menu pattern described by the ARIA APG](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/). In particular, that means that pressing Tab in those menus closes the menu and returns the focus to the menu button instead of moving tab within the popover like we need for the post priority menu. The component will need a prop to change how that focus is done.

Does that make sense? The other numbered points I commented on above will need to be addressed as well, but you can ignore all the stuff after that

2025-01-24 15:07 UTC, marianunez commented
/e2e-test

2025-01-30 22:49 UTC, hmhealey requested changes
Testing this locally, the accessible parts of it closing the priority picker work well, but I've noticed that the picker no longer reverts the selected priority to the previous value in a few cases:
1. If you close the picker without pressing enter, I'd expect the initially selected priority to match the original value. [Video of the current PR behaviour](https://github.com/user-attachments/assets/b1d5daf3-4a4e-4200-b57d-06c00a3832c8)
2. After you send a post with a higher priority, the next time you open the priority picker, it'll still show the higher priority as selected.
3. If you change channels after setting the priority on a draft and not sending it, the next time you open the priority picker, it'll still show the higher priority as selected

I'm not 100% sure why this part changed from before, but I think that the `PostPriorityPicker` is staying mounted now after it's closed. Before, I think it might've been unmounted by the `PostPriorityPickerOverlay` when it was no longer visible.

Also, could you fix the merge conflicts on this? One of the other a11y PRs also made changes to the menu component, and those are conflicting

2025-02-11 15:32 UTC, marianunez commented
@ayush-chauhan233 friendly ping on this PR

2025-02-12 08:06 UTC, ayush-chauhan233 commented
/update-branch

2025-02-12 08:07 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.

2025-02-16 18:39 UTC, ayush-chauhan233 commented
> E2E test has completed for commit `80252f9cc5c75759cf83fa7a9ce23cc2e87176fc`. Results summary:
> 
> * Cypress: pass rate is `100.00%` (see [Automation Dashboard](https://automation-dashboard.vercel.app/cycle/13326711780_1-80252f9-pr-onprem-ent) and commit status check `E2E Tests/test`).
> * Playwright: pass rate is `98.44%` (see commit status check `E2E Tests/test-playwright`).
> 
> The run summary artifacts are available in the corresponding [Workflow Run](https://github.com/mattermost/mattermost/actions/runs/13326711780).

@hmhealey, Facing some issues reproducing this failing playwright test locally, seems like it runs on a licensed edition. Can you please help me with this?

2025-02-17 20:03 UTC, marianunez commented
> @hmhealey, Facing some issues reproducing this failing playwright test locally, seems like it runs on a licensed edition. Can you please help me with this?

@yasserfaraazkhan can you help on the failing tests?

2025-02-18 06:44 UTC, yasserfaraazkhan commented
@ayush-chauhan233 tests should pass now.

2025-02-18 08:53 UTC, ayush-chauhan233 commented
> @ayush-chauhan233 tests should pass now.

@yasserfaraazkhan  It seems that the test is still failing. I'm unsure why they were previously showing as 100% passed before I restarted the e2e test.

2025-02-18 09:28 UTC, yasserfaraazkhan commented
@ayush-chauhan233 try rerunning once the image is built.

2025-02-19 21:29 UTC, hmhealey approved these changes
I gave some more manual testing, and the menus all seem to behave correctly to me. That one flaky test also passes locally for me as well, so this looks good to merge

2025-02-19 21:30 UTC, merged