[MM-61592]: Updated the Theme list section in the settings modal
mattermost/mattermost pull request #29596
Opened 2024-12-13 07:08 UTC by ayush-chauhan233

#### Summary

- Updated the premade theme and custom theme radio button accordion.
- Replaced divs with buttons to ensure keyboard navigation for the premade themes.
- Updated the accordion in custom theme section and added aria-expanded and aria-controls attributes.

#### Steps to reproduce  
- Navigate to the the Display tab control using down arrow key.
- Now navigate to the Theme edit button and select it.
- Now navigate to the Custom Theme radio button using arrow keys.
- Now navigate to the Sidebar Styles button and notice that the control is not reachable by the keyboard.

#### Expected Behavior 
- The premade theme and custom theme radio button accordion must be keyboard accessible as well its content.

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-61592

#### Screenshots

<table>
    <tr>
        <th>Before</th>
 <th>After</th>
    </tr>
    <tr>
        <td>
 <img src="https://github.com/user-attachments/assets/2c1330b9-c710-4e9b-b83c-01d2f5f908c4">
</td>
  <td>
 <img src="https://github.com/user-attachments/assets/045a646e-1a05-4adc-bcf8-44ad64fa4430">
</td>
    </tr>
</table>

#### Release Note

```release-note
NONE
```

2024-12-13 07:08 UTC, mattermost-build commented
Hello @ayush-chauhan233,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2025-01-14 20:48 UTC, hmhealey requested changes

2025-01-14 20:48 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
> +                    <button
Since we're changing these to be buttons and not radio buttons under the hood, I think we need to make sure that these are still controllable like a radio group normally would be as per https://www.w3.org/WAI/ARIA/apg/patterns/radio/. In particular, you should move between them with the arrow keys and they shouldn't be tabbable.

I think it might be easier to do that though by leaving them as input elements instead of wrapping those with button elements because they already have that behaviour on master since the browser provides it.

2025-01-14 20:48 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
> +                    <button
If there's something weird with that because the listed system themes are in between the radio buttons, we could possibly consider changing the layout of the theme settings to move the selection of built-in themes below the radio group, but we'd need to talk to UX about that

2025-01-14 20:48 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
>          this.sidebarStylesHeaderRef.current?.classList.toggle('open');
I didn't realize how much of this is using old jQuery-style patterns of manipulating these manually instead of using proper React. I'm very leery that this code will be unreliable since it could lead to collapsing categories or removing ARIA attributes if React decides to re-render the component at a bad time, but as long as we can make this accessible without worrying about that, I think we can revisit this later to make this properly reactive (https://mattermost.atlassian.net/browse/MM-62569)

2025-01-14 20:48 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
> +        const isAccordionOpen = this.sidebarStylesHeaderRef.current?.classList.contains('open');
At least in Firefox, this isn't toggling the expand/collapse icons on my local instance
![Screenshot 2025-01-14 at 3 34 17 PM](https://github.com/user-attachments/assets/d39fcf4b-ae90-486d-92e5-383256b2450e)

2025-01-14 20:48 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
> +                            aria-label='Sidebar Styles'
These should be translatable by using `intl.formatMessage`. You can use the translation ID and default message from the `FormattedMessage` found below for that

2025-01-14 20:48 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
> +                            aria-label='Sidebar Styles'
Actually, you don't need the `aria-label` on these buttons because the they'll get an accessible name from the text inside them automatically. You'll have to add `aria-hidden` to the expand and collapse icons inside of each of these as well, but once you've done that and removed the `aria-label`, the name of each component will be the translated text from the `FormattedMessage` inside of it

2025-01-14 22:18 UTC, pvev requested changes
please, address the comments. Let me know if you have any questions.

2025-01-16 06:13 UTC, AayushChaudhary0001 approved these changes
This PR has been tested and the sidebar style button is now accessible through the keyboard, LGTM. Approved.

2025-01-16 11:50 UTC, ayush-chauhan233 commented on webapp/channels/src/components/user_settings/display/user_settings_theme/premade_theme_chooser/premade_theme_chooser.tsx
> +                        className={`premadeThemeButton ${activeClass}`}
I guess it is not needed, as it will get its accessible name from its inner text. Let me know if i need to add it anyways.

Screen Reader screenshot attached:  
![Screenshot (25)](https://github.com/user-attachments/assets/0f956c8a-5030-4753-976a-dc0b92888a43)

2025-01-16 22:09 UTC, ayush-chauhan233 commented on webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
> +                    <button
I replaced the radio inputs with buttons to maintain better keyboard interaction. The issue arises with the system-listed themes. Typically, a group of radio inputs can be navigated using the up/down arrow keys. However, in this case, the behaviour is more like a combination of a radio input and an accordion, where selecting a particular option opens a list of items.

When the premade listed themes are expanded, the items within the list can be accessed using the keyboard. If the focus is on the last item in the list and the user wants to move to the next radio input, the navigation becomes problematic. By default, the arrow key scrolls within the modal rather than moving the focus to the next radio input.


https://github.com/user-attachments/assets/668f0b0e-e2e1-4270-b463-6053264ae497



Here are some potential solutions:

1) Implementing focus trapping within the premade listed themes.
2) Programmatically shifting focus to the next radio input using the arrow key when the focus is currently on an opened listed item of the previous radio input.

2025-01-20 21:58 UTC, pvev commented on webapp/channels/src/components/user_settings/display/user_settings_theme/premade_theme_chooser/premade_theme_chooser.tsx
> +                        className={`premadeThemeButton ${activeClass}`}
no need, is ok if it receives it from the inner text.

2025-01-20 22:20 UTC, pvev commented on webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
> +                    <button
the focus trap could be tricky, maybe wrapping with the radiogroup role would suit better here.

2025-01-22 16:10 UTC, pvev commented
/e2e-test

2025-01-22 17:55 UTC, pvev requested changes

2025-01-23 07:08 UTC, ayush-chauhan233 commented on webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
> +                    <button
@pvev Sure I will try to implement focus trapping and will let you know if it helps reverting to real radio inputs.

2025-01-23 07:13 UTC, ayush-chauhan233 commented on webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
> +        const isAccordionOpen = this.sidebarStylesHeaderRef.current?.classList.contains('open');
@pvev, The issue is fixed which was related to the expand/collapse icon.

2025-01-24 20:29 UTC, hmhealey commented on webapp/channels/src/components/user_settings/display/user_settings_theme/user_settings_theme.tsx
> +                    <button
>  I replaced the radio inputs with buttons to maintain better keyboard interaction. The issue arises with the system-listed themes. Typically, a group of radio inputs can be navigated using the up/down arrow keys. However, in this case, the behaviour is more like a combination of a radio input and an accordion, where selecting a particular option opens a list of items.
> 
> When the premade listed themes are expanded, the items within the list can be accessed using the keyboard. If the focus is on the last item in the list and the user wants to move to the next radio input, the navigation becomes problematic. By default, the arrow key scrolls within the modal rather than moving the focus to the next radio input.

I see what you mean about this being a tricky component, but I think most of that trickiness comes from the premade theme selection being in between the two options for premade/custom themes. If we move the premade theme chooser to not be in between those options, we'll have two groups of controls:
1. A radio group for choosing between premade and custom themes
2. Either a second radio group for choosing between premade themes or the accordions for customizing your theme

<img width="1587" alt="Screenshot 2025-01-24 at 3 09 05 PM" src="https://github.com/user-attachments/assets/5a6bca98-454c-4f88-b88b-3af60918bc79" />
<img width="1587" alt="Screenshot 2025-01-24 at 3 09 18 PM" src="https://github.com/user-attachments/assets/6ad5abd1-ace1-40f2-8c8f-ebfbe3571e5e" />

If we did that, we'd just be able to use the standard keyboard interactions for radio groups for those components and the custom theme setting could be tabbed through, so all of those could use standard controls and patterns. 
I think that it'd be both easier for us to write the HTML for that and for users to navigate through it.

How does that sound?

Also, CC @asaadmahmood since this would be a minor UX change, but I don't expect it to be a problem

2025-01-27 19:01 UTC, pvev commented
/e2e-test

2025-01-30 17:00 UTC, hmhealey requested changes
I added in @asaadmahmood as a UX reviewer to confirm that the change to move the radio buttons is okay, but I think that part looks good to me.

Could you change it so that there's space between the radio buttons and the premade themes matching when the custom theme controls are visible?
|Premade|Custom|
|-|-|
![Screenshot 2025-01-30 at 11 55 22 AM](https://github.com/user-attachments/assets/dcfd2975-5eef-445d-8de5-1cc977cd1861)|![Screenshot 2025-01-30 at 11 55 25 AM](https://github.com/user-attachments/assets/0b46549e-a70e-4f57-9508-9d6438588a88)

Otherwise, this looks good to me!

2025-02-03 03:53 UTC, pvev commented
/e2e-test

2025-02-03 05:06 UTC, pvev commented
/update-branch

2025-02-04 21:11 UTC, hmhealey approved these changes

2025-02-07 15:21 UTC, pvev approved these changes
🚀

2025-02-11 15:34 UTC, marianunez commented
@asaadmahmood friendly ping on this 

https://github.com/mattermost/mattermost/pull/29596#pullrequestreview-2584498813

2025-02-14 11:19 UTC, asaadmahmood commented
@marianunez @hmhealey I feel like this may create another issue.
Since the premade themes are related to the first radio, having them appear under the second radio doesn't make sense.
If a person has the default themes toggle selected, why does he have to go below the custom theme option to select them? I am not sure if it would be intuitive for users with visual disabilities.

The main issue highlighted by this ticket was more related to:
`Now navigate to the Sidebar Styles button and notice that the control is not reachable by the keyboard.`

Why do we need to make this other change for that?

2025-02-14 22:12 UTC, marianunez commented
> @marianunez @hmhealey I feel like this may create another issue. Since the premade themes are related to the first radio, having them appear under the second radio doesn't make sense. If a person has the default themes toggle selected, why does he have to go below the custom theme option to select them? I am not sure if it would be intuitive for users with visual disabilities.

@asaadmahmood here is the context on why it was change this way. 

@hmhealey is there a way to keep the `Custom Theme` radio button below the pre-defined themes when `Theme Colors` are selected and fix the original accessibility issue? I agree that it doesn't seem right when moving through the predefined theme options

2025-02-19 14:29 UTC, ayush-chauhan233 commented
> @hmhealey @pvev @marianunez I think we should keep the radios as is, and just focus trap the focus in the premade theme's section and the custom themes section that a person can escape by just pressing tab or shift tab.
> 
> ![CleanShot 2025-02-15 at 21 05 52@2x](https://private-user-images.githubusercontent.com/11034289/413557186-15d9f4ac-b450-48f1-a93d-abf58f782ab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk5NzU0MjAsIm5iZiI6MTczOTk3NTEyMCwicGF0aCI6Ii8xMTAzNDI4OS80MTM1NTcxODYtMTVkOWY0YWMtYjQ1MC00OGYxLWE5M2QtYWJmNThmNzgyYWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE5VDE0MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Y2FjYjJiYTRmZjc3NDlmMGYxY2U4YWRlZTg4OTYxNTlhODJlMjRlYzllY2ZmZmI3NmIwNDk2MGM4MjE3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TO_rQfqZ5lBvOBy2PdQBIe_mPuh41r_wE8y_ShF58tw)


Agree, Implementing focus trapping could be a better solution, Please do let me know if I have to proceed with implementing this or not.

2025-02-19 14:43 UTC, marianunez commented
> Agree, Implementing focus trapping could be a better solution, Please do let me know if I have to proceed with implementing this or not.

Yes, let's move forward with this approach to avoid confusions when using the radio buttons and the custom theme selector. Thanks @ayush-chauhan233

2025-02-19 22:50 UTC, hmhealey commented
> @marianunez @hmhealey I feel like this may create another issue. Since the premade themes are related to the first radio, having them appear under the second radio doesn't make sense. If a person has the default themes toggle selected, why does he have to go below the custom theme option to select them? I am not sure if it would be intuitive for users with visual disabilities.
> 
> The main issue highlighted by this ticket was more related to: `Now navigate to the Sidebar Styles button and notice that the control is not reachable by the keyboard.`
> 
> Why do we need to make this other change for that?

The reason we need to make that change is because the previous design for this has the system theme selector in the middle of a radio button group. Based on the APG pattern for radio groups, you should tab once into the radio group (for system/custom theme), and then once to the controls after it. That doesn't really work though when there's other controls inside of the radio group somehow. See [this discussion above](https://github.com/mattermost/mattermost/pull/29596#discussion_r1929199788) for more info.

I think this way of arranging it makes sense since it works similarly to other settings where a radio button or toggle causes additional settings to appear below it. Perhaps the visual labelling could be improved to clarify that, but I don't think the change makes it less intuitive than the previous version

2025-02-24 09:39 UTC, ayush-chauhan233 commented
@hmhealey  Do we need ARIA attributes such as `aria-expanded` and `aria-controls` here? As we move back the themes between the radio groups and clicking those will expand their respective sections. I am unable to find any example related to this type of behaviour with the radio group so some suggestions will be really helpful. Thanks

2025-02-27 21:29 UTC, hmhealey commented
Sorry for the confusion. We've discussed this, and decided to stick with the current version you have here plus making some followup UX changes to the setting to fix some existing issues.

Thanks again for your work on this!

2025-02-27 21:29 UTC, merged