Scroll position resets when custom emojis requested #29512
mattermost/mattermost pull request #29608
Opened 2024-12-14 10:36 UTC by X1Vi

#### Summary

#### Ticket Link

#### Screenshots

2024-12-14 10:36 UTC, mattermost-build commented
Hello @X1Vi,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-12-15 06:47 UTC, X1Vi commented
/check-cla

2024-12-16 21:26 UTC, hmhealey requested changes
Thanks for picking up this PR, @X1Vi! I think there might be a slight misunderstanding here though since I don't think we want to store the scroll position of the emoji picker when it's closed an reopened but rather we just want to fix the issue with it scrolling to the top whenever more custom emojis are loaded.

I think you're on the right track though with not calling `selectFirstEmoji` in that hook though. We need to find some way to differentiate between when that hook is called because the user typed something into the filter box which should still select the first emoji from when `createCategoryAndEmojiRows` being called because more emojis have been loaded. That `useEffect` also looks very odd because we're passing `shouldRunCreateCategoryAndEmojiRows.current` as a dependency of that `useEffect` which isn't supposed to be allowed. 

Also, if it helps, this logic was added back in https://github.com/mattermost/mattermost-webapp/pull/9597, so that might explain a bit better about why this is the way it is. Unfortunately @M-ZubairAhmed is on vacattion at the moment, so we can't ask him why this is written the way that it is

2024-12-17 07:28 UTC, X1Vi commented
> Thanks for picking up this PR, @X1Vi! I think there might be a slight misunderstanding here though since I don't think we want to store the scroll position of the emoji picker when it's closed an reopened but rather we just want to fix the issue with it scrolling to the top whenever more custom emojis are loaded.
> 
> I think you're on the right track though with not calling `selectFirstEmoji` in that hook though. We need to find some way to differentiate between when that hook is called because the user typed something into the filter box which should still select the first emoji from when `createCategoryAndEmojiRows` being called because more emojis have been loaded. That `useEffect` also looks very odd because we're passing `shouldRunCreateCategoryAndEmojiRows.current` as a dependency of that `useEffect` which isn't supposed to be allowed.
> 
> Also, if it helps, this logic was added back in [mattermost/mattermost-webapp#9597](https://github.com/mattermost/mattermost-webapp/pull/9597), so that might explain a bit better about why this is the way it is. Unfortunately @M-ZubairAhmed is on vacattion at the moment, so we can't ask him why this is written the way that it is

Should I make a seprate PR instead. This functionality could be useful if desired in the future

2024-12-18 23:07 UTC, hmhealey commented
It's up to you, but I think you'd be fine making the changes on this one. If we want to add that functionality in the future, we should be able to get the old commit from this PR as long as you don't force push this branch

2024-12-23 01:51 UTC, pvev commented
@X1Vi thanks for your contribution 🎉 , in order to move forward with the review, please check the lint problems you have in this PR. You could fix most of them by running npm run fix from the webapp/channels folder. Let me know if you have any questions.

2024-12-24 05:51 UTC, harshilsharma63 commented
/e2e-test

2024-12-24 11:14 UTC, X1Vi commented
> /e2e-test

I think you can run this now .

2024-12-25 11:24 UTC, X1Vi commented
/e2e-test

2024-12-26 01:22 UTC, harshilsharma63 commented
/e2e-test

2024-12-27 05:27 UTC, X1Vi commented
@harshilsharma63 I dont think it is related to my component. 
This is the path to the component
```./webapp/channels/src/components/post_view/post_body_additional_content/post_body_additional_content.tsx
 ```

2024-12-27 05:39 UTC, harshilsharma63 commented
> @harshilsharma63 I dont think it is related to my component. This is the path to the component `./webapp/channels/src/components/post_view/post_body_additional_content/post_body_additional_content.tsx `

I'll check this out.

2024-12-27 05:48 UTC, X1Vi commented
> > @harshilsharma63 I dont think it is related to my component. This is the path to the component `./webapp/channels/src/components/post_view/post_body_additional_content/post_body_additional_content.tsx `
> 
> I'll check this out.

I am really thankful

2024-12-27 20:19 UTC, pvev commented
are those changes in package-lock.json intended?

2024-12-28 02:06 UTC, X1Vi commented
> are those changes in package-lock.json intended?

I think they are automatically generated when I install the dependencies

2025-01-03 02:40 UTC, pvev commented
> > are those changes in package-lock.json intended?
> 
> I think they are automatically generated when I install the dependencies

can you please remove those package-lock changes? we try to handle those updates to packages in separate PRs.

2025-01-03 06:11 UTC, X1Vi commented
> > > are those changes in package-lock.json intended?
> > 
> > 
> > I think they are automatically generated when I install the dependencies
> 
> can you please remove those package-lock changes? we try to handle those updates to packages in separate PRs.

done

2025-01-08 20:22 UTC, pvev commented on webapp/channels/src/components/emoji_picker/emoji_picker.tsx
> +        if (activeCategory !== 'custom') {
nit: place custom string in a constant.

2025-01-08 20:22 UTC, pvev approved these changes
LGTM! 🚀

2025-01-09 05:13 UTC, X1Vi commented
> LGTM! 🚀

Hey I see that you have approved the changes do you want me to do something else ?

2025-01-10 11:25 UTC, larkox approved these changes

2025-01-10 11:28 UTC, larkox commented
@X1Vi Now the developer review is done (even though, I would love to see if @hmhealey has any other comment), we just need to get it through QA review. For now, there is nothing left for you to do, but wait for the rest of the reviews :smile: Hopefully all is fine and we will just merge the PR.

Thank you for your patience!

2025-01-10 22:31 UTC, hmhealey approved these changes

2025-01-10 22:38 UTC, hmhealey commented
> Hey I see that you have approved the changes do you want me to do something else ?

I think these changes are good as-is since we ideally want this in before we start cutting 10.5 next week, unless @pvev feels otherwise. 

We sometimes approve a PR with minor caveats or nitpicking that the submitter should still address before it's merged, but that's usually just done for people that have the ability to merge their own PR. In this case, I think we can skip that for now though

2025-01-13 07:41 UTC, yasserfaraazkhan approved these changes

2025-01-13 09:18 UTC, merged

2025-01-13 09:18 UTC, larkox commented
@X1Vi Thank you for the contribution!

2025-01-13 09:48 UTC, amyblais commented
/cherry-pick release-10.5

2025-01-13 09:48 UTC, mattermost-build commented
Cherry pick is scheduled.

2025-01-13 09:48 UTC, amyblais commented
/cherry-pick release-9.11