WIP: MM-61707
mattermost/mattermost pull request #29606
Opened 2024-12-13 21:59 UTC by BenCookie95

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-61708

#### Release Note

```release-note
NONE
```

2025-01-08 12:14 UTC, vish9812 requested changes

2025-01-09 18:58 UTC, BenCookie95 commented on server/channels/app/authentication.go
> +func (a *App) CheckLdapUserPasswordAndAllCriteria(rctx request.CTX, user *model.User, password string, mfaToken string) (*model.User, *model.AppError) {
1. The reason I passed `user` instead of `userID` is because when a user first logs in with LDAP they won't have a userID and I didn't want to repeat the logic from `GetUserForLogin` where I'm reaching out to the LDAP server to get the LDAP user.
2. I can't remember why I changed that, will change it back

2025-01-09 18:59 UTC, BenCookie95 commented on server/public/model/report.go
> +	u.ClearNonProfileFields(true)
Yeah I tested and the report still excludes NotifyProps and FailedAttempts.

2025-01-10 07:57 UTC, vish9812 commented on server/channels/app/authentication.go
> +func (a *App) CheckLdapUserPasswordAndAllCriteria(rctx request.CTX, user *model.User, password string, mfaToken string) (*model.User, *model.AppError) {
Since the consumer of this function is already has user object, wouldn't they simply pass the `user.Id` instead of user?
And then in this function, you already check for empty `user.Id`.

2025-01-10 08:05 UTC, vish9812 commented on server/public/model/report.go
> +	u.ClearNonProfileFields(true)
I suppose then it's being reset somewhere else in the code. Because passing `true` skips the _reset_ check. Anyway, if it works, then all good.

2025-01-10 16:06 UTC, BenCookie95 commented on server/channels/app/authentication.go
> +func (a *App) CheckLdapUserPasswordAndAllCriteria(rctx request.CTX, user *model.User, password string, mfaToken string) (*model.User, *model.AppError) {
I need the `user.AuthData` to determine the `ldapID` in this method, if I pass the `user.Id` I will also need to pass the `user.Authdata` because first time ldapUsers have incomplete user objects. So yeah I can remove the user object from the parameters and add a user.Id and user.AuthData. Passing the user object would have also caused concurrency issues for first time ldap users as well anyway. Thanks

2025-01-14 08:01 UTC, vish9812 approved these changes
LGTM 🚀

2025-01-29 16:03 UTC, esarafianou requested changes
Minor changes, but looks good!

2025-01-29 16:03 UTC, esarafianou commented on webapp/channels/src/components/admin_console/admin_definition.tsx
> +                                    help_text: defineMessage({id: 'admin.ldap.maximumLoginAttemptsDesc', defaultMessage: 'The maximum number of login attempts before the account is locked. You can un
```suggestion
                                    help_text: defineMessage({id: 'admin.ldap.maximumLoginAttemptsDesc', defaultMessage: 'The maximum number of login attempts before the Mattermost account is locked. You can unlock the account in system console on the users page.'}),
```

2025-01-29 16:28 UTC, BenCookie95 commented on server/channels/api4/user.go
> +	auditRec.AddEventPriorState(user)
Yeah the whole user object, I made it the same as the other audit records

2025-01-29 17:18 UTC, BenCookie95 commented on server/channels/app/authentication.go
> +				return nil, model.NewAppError("CheckPasswordAndAllCriteria", "app.user.update_failed_pwd_attempts.app_error", nil, "", http.StatusInternalServerError).Wrap(passErr)
The field is FailedAttempts so we count failed MFA attempts too. Email/password login is the same

2025-01-30 11:13 UTC, esarafianou approved these changes

2025-01-30 13:23 UTC, hanzei requested changes
Great work @BenCookie95 :+1:

2025-01-30 13:23 UTC, hanzei commented on server/channels/app/authentication.go
> +	}
That call adds an additional round trip to the LDAP server. Can we avoid that?

2025-01-30 13:23 UTC, hanzei commented on server/channels/app/authentication.go
> +		}
Why are we fetching the user again here? If the user exists in MM, `GetUserForLogin` did find it. If it's a fresh user, this will fail, right?

2025-01-30 13:23 UTC, hanzei commented on server/channels/app/authentication.go
>  		}
Should we do that only if `"ent.ldap.do_login.invalid_password.app_error"` got returned?

2025-01-30 13:23 UTC, hanzei commented on server/channels/app/authentication_test.go
> +	defer mockCtrl.Finish()
That seems wrong. Are we even using the mock controller?

2025-01-30 13:23 UTC, hanzei commented on webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx
> +        }
as mentioned above, I'm not sure if we need to be that restrictive.

2025-01-30 13:23 UTC, hanzei commented on server/channels/app/authentication.go
> +	defer a.ch.ldapLoginAttemptsMut.Unlock()
I'm aware that this mirrors the password/email implementation. Still, I wonder about the impact to performance. Especially, because this method involves at least one roundtrip to the LDAP server, which might take some time.

What happens if all 100k users want to log in at the same time due to a SEV0?

2025-01-30 15:37 UTC, BenCookie95 commented on server/channels/api4/user.go
> +	}
We have it in a few places where you can only update a system admin if you are also a system admin. I think it makes sense in this case

2025-01-30 16:49 UTC, BenCookie95 commented on server/channels/app/authentication.go
> +	}
Yeah I didn't have this originally, it's being used to ensure we have the correct value for `MaxAttempts` after we acquire the lock. I'll remove this call and just get the updated `MaxAttempts` value for a user

2025-01-30 16:49 UTC, BenCookie95 commented on server/channels/app/authentication.go
> +	defer a.ch.ldapLoginAttemptsMut.Unlock()
Yeah unfortunately this concurrency issue is tricky. 

`pluginapi` has this neat way of using the `pluginkeyvaluestore` for cluster aware dynamic mutexes where you can use the userID as a dynamic key in order to lock the code path for specific users. 

I'm curious why we didn't think about a map of mutexes, where the userID is the key, in the first implementation. While it's not cluster aware it would allow different users to acquire locks at the same time. That is probably the solution but it's quite a bit of work because we'd also have to implement a job to cleanup the map periodically. It's also something that would require a lot of testing. The scope of this bug fix is already quite large.

@agnivade are you able to weigh in here, did we consider the implication of a mutex lock on a Sev0 when using email login? This method will have at least one round trip to the LDAP server and first time users will also initiate a `FirstLoginSync` with the ldap server.

2025-01-31 20:33 UTC, BenCookie95 commented on server/channels/app/authentication.go
> +		}
Added a check for this so we only do this for new users.

2025-01-31 20:46 UTC, BenCookie95 commented on server/public/model/report.go
> +	u.ClearNonProfileFields(true)
https://github.com/mattermost/mattermost/blob/MM-61707/server/channels/jobs/export_users_to_csv/export_users_to_csv.go#L122 Makes a call to `ToReport()` [here](https://github.com/mattermost/mattermost/blob/MM-61707/server/public/model/report.go#L86). Those are the fields that get exported. Definitely confusing and probably needs to be looked at but not in this PR.

2025-02-03 16:40 UTC, agnivade commented on server/channels/app/authentication.go
> +	defer a.ch.ldapLoginAttemptsMut.Unlock()
This is a tricky thing to do it correctly balancing performance and simplicity. Using an app level mutex was the simplest and cleanest approach to me. The alternative would be to:
- Expose transaction semantics outside the store layer to the app layer (Lot of work)
- Move some logic from app layer to store layer (Ugly)

> I'm curious why we didn't think about a map of mutexes, where the userID is the key, in the first implementation.

Always think of the simplest approach first :) A sharded mutex sounds elegant in theory, but it's quite difficult to implement in practice. See platform/service/lru_striped.go for example. You have to be very careful not to introduce "false sharing", otherwise you could end up with worse performance.

> What happens if all 100k users want to log in at the same time due to a SEV0?

We actually have some data on this from actual customer SEV0s. In reality, all 100K users don't log in all at the same time. More like 2-3 users/sec. This is less than what we load-test with currently. And given that we haven't faced any major issues, this mutex in particular is unlikely to cause issues.

But what _could_ cause issues is the load generated on the LDAP server. In a previous convo, I highlight how spawning a new connection with the LDAP server for every single method is not very efficient for "thundering herd" situations like this. I think that is a bigger problem to solve than this mutex problem.

Let me cc @cpoile and @agarciamontoro for visibility.

2025-02-06 15:44 UTC, hanzei commented on server/channels/api4/user.go
> +	}
Fair point on the consistency :+1:

2025-02-06 15:47 UTC, hanzei commented on server/channels/api4/user.go
> +	}
I don't see the point in blocking an admin from getting the failed attempts. The purpose of the API endpoint is to do that - reset the count. There might be 3th party integrations that call the API before checking the count. 

2/5 we should remove the `<` check for both email and LDAP users.

2025-02-06 16:05 UTC, hanzei reviewed
A minor comments are left. Once they are resolved, the PR is good to go.

2025-02-06 16:05 UTC, hanzei commented on server/channels/app/authentication.go
> +		// If this is a new ldap user we need to get the user from the database because DoLogin will have created the user
Should we also add an example via the comment to make clear that this is an edge case?

2025-02-06 16:05 UTC, hanzei commented on server/channels/app/authentication.go
> +	}
Should we only do this if `ldapUser.FailedAttempts > 0`?

2025-02-06 16:51 UTC, hanzei commented on server/channels/app/authentication.go
> +	defer a.ch.ldapLoginAttemptsMut.Unlock()
@agnivade  Out of curiosity: The load test uses email/password, right? Is the point that email/password already uses a mutex, and hence, we can do the same for LDAP without an issue? Is it still true if `checkLdapUserPasswordAndAllCriteria` takes longer to return due to the round trip to the LDAP server?

2025-02-10 07:33 UTC, agnivade commented on server/channels/app/authentication.go
> +	defer a.ch.ldapLoginAttemptsMut.Unlock()
>  Is the point that email/password already uses a mutex, and hence, we can do the same for LDAP without an issue? 

Correct.

> Is it still true if checkLdapUserPasswordAndAllCriteria takes longer to return due to the round trip to the LDAP server?

I believe so. Assuming the roundtrip duration adds a constant delay on average, then the latency a single user faces will be equal to this delay + mutex contention. And given that mutex contention is not a factor, then the overall delay will still be the same.

But again, this also relates to the fact that if a large number of connections are opened to the LDAP server all at once, then some requests will get hampered more than others. In this case, actually the mutex sort of helps by restricting the concurrency of the action. But in the long-term, having a connection pool will help a lot in reducing the latency, because the TCP connection overhead will be gone.

So, I see 2 related issues. But using mutex + connection pool is still the right solution to me balancing simplicity and performance.

2025-02-26 21:45 UTC, DHaussermann approved these changes
Tested and passed
I have provided a list of tests in the Jira ticket

Huge thanks for the help and guidance on this one @BenCookie95

2025-02-28 14:53 UTC, esarafianou approved these changes
Thanks Ben! 🎉

2025-03-12 22:22 UTC, merged

2025-03-13 18:23 UTC, cwarnermm commented
@BenCookie95 - Can you help identify any product documentation updates needed for this PR, please?

2025-03-17 10:01 UTC, amyblais commented
@BenCookie95 Can you help cherry-pick this to ``release-10.6``, ``release-10.5``, ``release-10.4`` and ``release-9.11`` branches? The enterprise PR might need manual cherry-pick PRs.