Add 'metrics' tag to `/api/v4/client_perf` endpoint
mattermost/mattermost pull request #29612
Opened 2024-12-15 14:47 UTC by unode

#### Summary

All [YAML API specification files](https://github.com/mattermost/mattermost/tree/master/api/v4/source) include a `tags` attribute that is used by [`python-mattermost-autodriver`](https://github.com/embl-bio-it/python-mattermost-autodriver), that I maintain, to generate one python file per collection of tagged endpoints.

The `metrics.yaml` file that introduced `/api/v4/client_perf` in commit https://github.com/mattermost/mattermost/commit/c74f830b763bbc144ade921729972e4832deb9d4 (@hmhealey) is currently missing the `tags` attribute and makes the approach followed by [`python-mattermost-autodriver`](https://github.com/embl-bio-it/python-mattermost-autodriver) fail for this endpoint.

The present PR adds such tag.
The tag is derived from the filename that contains the endpoint (i.e.  `metrics`)

#### Release Note

```
Add 'metrics' tag to `client_perf` endpoint
```

2024-12-15 14:47 UTC, mattermost-build commented
Hello @unode,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-16 21:45 UTC, hmhealey requested changes
Thanks for the PR, @unode! I never paid attention to that `tags` field before, but I think I understand it now. Just to make sure I understand what you're seeing, is the autodriver just failing because there's no tags on this endpoint or because it's missing that tag specifically?

I've also noticed that this endpoint is actually missing from https://api.mattermost.com which I assume is because of the missing tag, but I think we'd also need to add the new tag to the `tags` and `x-tagGroups` sections of `api/v4/source/introduction.yaml` as well to make it show up. Would you mind adding those as well? Hopefully that should make it show up on the API reference site as well

2024-12-18 15:31 UTC, unode commented
@hmhealey added. Wasn't sure what to include as description but hopefully it's still generic enough for future uses.

I also noticed that not all tags under `x-tagGroups` are present under `tags` with a `name` and `description` (e.g. `usage`, `permissions`, ...). Possibly something to address elsewhere?

2024-12-18 15:37 UTC, unode commented
As to your first question, the code in `python-mattermost-autodriver` requires the `tags` attribute to identify which file the endpoint should be added into.

For instance, `/api/v4/users/{user_id}/convert_to_bot` is tagged with both `users` and `bots` so the endpoint function call is found in both the [`users.py`](https://github.com/embl-bio-it/python-mattermost-autodriver/blob/2a505396d7f202d6c02f347ae3224fbbb0c2c5bb/src/mattermostautodriver/endpoints/users.py#L409) and [`bots.py`](https://github.com/embl-bio-it/python-mattermost-autodriver/blob/2a505396d7f202d6c02f347ae3224fbbb0c2c5bb/src/mattermostautodriver/endpoints/bots.py#L6) endpoint files.

2024-12-29 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-07 00:29 UTC, unode commented
@hmhealey coming out of the winter break, is there any further action needed from my side?

2025-01-07 18:47 UTC, hmhealey approved these changes

2025-01-13 11:47 UTC, hanzei commented
@unode Would you please merge `master` into your branch and resolve the conflict? Thanks!

2025-01-14 09:24 UTC, merged