[MM-62142] Avoid SELECT * in status_store.go
mattermost/mattermost pull request #29610
Opened 2024-12-14 20:42 UTC by Aryakoste

#### Summary

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29550
Jira https://mattermost.atlassian.net/browse/MM-62142
#### Screenshots

#### Release Note

```release-note
NONE
```

2024-12-14 20:42 UTC, mattermost-build commented
Hello @Aryakoste,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-17 16:25 UTC, lieut-data requested changes
Thanks, @Aryakoste! In addition to the comments below, there's other `Select *` instances in this file, e.g. see `updateExpiredStatuses`. Can you help update those?

2024-12-19 13:58 UTC, lieut-data commented on server/channels/store/sqlstore/status_store.go
> +		if err = rows.Scan(&status.UserId, &status.Status, &status.Manual, &status.LastActivityAt, &status.DNDEndTime, &status.PrevStatus); err != nil {
Double checked that this should be fine, and actually closes an unintended gap in the store!

2024-12-22 18:39 UTC, Aryakoste commented
@lieut-data Changes done

2024-12-23 13:49 UTC, lieut-data approved these changes

2025-01-03 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-09 12:30 UTC, lieut-data commented
/e2e-run

2025-01-10 15:23 UTC, lieut-data commented
/update-branch

2025-01-21 03:30 UTC, lieut-data commented
Hey @mgdelacroix, are you available to take a look at this review?

2025-01-21 18:40 UTC, mgdelacroix approved these changes
LGTM! Thanks @Aryakoste :sparkles:

2025-01-22 15:59 UTC, merged