Permanent deletion of Direct and Group channels
mattermost/mattermost pull request #29611
Opened 2024-12-15 11:07 UTC by Alenoda

#### Summary
Allows permanent deletion of Direct and Group channels. Soft deletion remains disallowed. Users require PermissionDeletePrivateChannel to delete.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/27489
Jira https://mattermost.atlassian.net/browse/MM-59260

#### Release Note
```release-note
Allows permanent deletion of Direct and Group channels. Soft deletion remains disallowed. Users require PermissionDeletePrivateChannel to delete.
```

2024-12-15 11:08 UTC, mattermost-build commented
Hello @Alenoda,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-23 04:41 UTC, agnivade requested changes
This should be documented in api/v4/source/channels.yaml as well.

2024-12-23 04:42 UTC, agnivade commented
And also please add a test case to check for the change in behavior.

Adding @isacikgoz as well because he has been dealing with import/export and wondering if that has any impact here.

2025-01-03 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-06-06 06:23 UTC, hanzei commented
Closing this inactive PR

2025-06-06 06:23 UTC, closed without merging