[MM-29441] Fix errcheck issues in web_hub.go
mattermost/mattermost pull request #29614
Opened 2024-12-15 17:08 UTC by YahyaHaq

**Summary**
Fix errcheck issues in server/channels/app/platform/web_hub.go

Ticket Link
https://github.com/mattermost/mattermost/issues/29441

2024-12-15 17:08 UTC, mattermost-build commented
Hello @YahyaHaq,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-12-15 17:18 UTC, YahyaHaq commented
/check-cla

2024-12-17 08:43 UTC, hanzei requested changes
Thanks for the PR :+1:

2024-12-17 08:43 UTC, hanzei commented on server/channels/app/platform/web_hub.go
> +		ps.logger.Error("Unable to write userID to hash", mlog.Err(err))
Let's also log the userID

2024-12-17 08:45 UTC, hanzei commented
/release-note-none

2024-12-20 18:29 UTC, YahyaHaq commented on server/channels/app/platform/web_hub.go
> +		ps.logger.Error("Unable to write userID to hash", mlog.Err(err))
Sounds good

2024-12-21 05:19 UTC, YahyaHaq commented on server/channels/app/platform/web_hub.go
> +		ps.logger.Error("Unable to write userID to hash", mlog.Err(err))
@hanzei done

2024-12-21 19:11 UTC, hanzei approved these changes
LGTM :+1:

2024-12-23 04:47 UTC, agnivade approved these changes
FYI, this method actually never returns an error. It is just there to satisfy the interface.

But any ways, it's good to keep things consistent.

2024-12-23 04:47 UTC, agnivade commented
/e2e-test

2024-12-23 09:39 UTC, agnivade commented
@mvitale1989 - Looks like a flaky e2e test.

2024-12-23 09:39 UTC, merged

2024-12-23 12:15 UTC, mvitale1989 commented
> @mvitale1989 - Looks like a flaky e2e test.

It indeed looks that way, i'll look into it. Thanks for raising!