[MM-61577]: Ensure all interactive functionality is operable with the keyboard in emoji picker
mattermost/mattermost pull request #29629
Opened 2024-12-17 13:29 UTC by SaurabhSharma-884

#### Summary
Fix the interactive controls that cannot be navigated to and operated with the keyboard alone in the Emoji picker modal

#### Steps to reproduce  

- Press Tab repeatedly to navigate through the Emoji button controls in the page.
- If the control can be focused, attempt to interact with the control using Enter, Space, Up/Down Arrow, and any other
applicable keystrokes.
- Notice that the control cannot be focused or that the control cannot be interacted with using the keyboard alone.

 #### Expected Behaviour
- The button should be focusable and operable by the keyboard.
- Element can be triggered when using the SPACE bar or ENTER key. 
- Element should have accessible name

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-61577

#### Screenshots

![Screenshot (5)](https://github.com/user-attachments/assets/e0f3e522-6d6a-4c3d-bbd1-e950825f54cb)
![image](https://github.com/user-attachments/assets/01127916-cc4a-4266-9c27-c0654eec9123)

#### Release Note

```release-note

```

2024-12-17 13:29 UTC, mattermost-build commented
Hello @SaurabhSharma-884,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-18 19:08 UTC, marianunez commented
@SaurabhSharma-884 is this ready for dev review ? Just double checking as I see that I am assigned but doesn't have the `Dev Review` label

2024-12-23 11:39 UTC, AayushChaudhary0001 reviewed
This PR has been tested for the changes and I have found an issue that the elements(emojis) are not triggered using the SPACE key. Although, they are triggered through the Enter key, but the space key is taken as an input in the search bar of emoji.

2024-12-23 12:51 UTC, harshilsharma63 commented
/e2e-test

2024-12-24 04:53 UTC, harshilsharma63 commented
@SaurabhSharma-884 there are some failing end-to-end tests regarding emoji. If you click the `Detail` link in front of `E2E Tests/test` CI step, you'll be able to see the detail.

2024-12-24 04:56 UTC, harshilsharma63 commented
> This PR has been tested for the changes and I have found an issue that the elements(emojis) are not triggered using the SPACE key. Although, they are triggered through the Enter key, but the space key is taken as an input in the search bar of emoji.

I can reproduce this bug as well, on the cloud test server as well as locally. @SaurabhSharma-884 please fix this. Once this is fixed, please tag me and I'll review this.

2024-12-24 04:58 UTC, harshilsharma63 requested changes
Changes look good. Just need to fix the failing e2e tests and the part about being able to select an emoji by pressing `space` doesn't work.

2024-12-24 04:59 UTC, harshilsharma63 commented
@SaurabhSharma-884 regarding e2e tests, you will be able to run them by having the Mattermost server running, and in a second terminal navigating to `e2e-tests/cypress` and running `npm run cypress:open`. LMK if you need any kind of help with this.

2024-12-27 08:06 UTC, SaurabhSharma-884 commented
> This PR has been tested for the changes and I have found an issue that the elements(emojis) are not triggered using the SPACE key. Although, they are triggered through the Enter key, but the space key is taken as an input in the search bar of emoji.

Fixed. Please re-review

2024-12-30 13:50 UTC, M-ZubairAhmed commented
/update-branch

2025-01-01 08:54 UTC, M-ZubairAhmed commented
/e2e-test

2025-01-01 08:55 UTC, M-ZubairAhmed commented
> > @SaurabhSharma-884 regarding e2e tests, you will be able to run them by having the Mattermost server running, and in a second terminal navigating to `e2e-tests/cypress` and running `npm run cypress:open`. LMK if you need any kind of help with this.
> 
> I tried running the e2e tests locally but i encounter an issue regarding the features that are only available in enterprise edition. Some of the APIs fail and the tests stop there itself. Can you help me out with this.

I have ran the e2e test here itself, you can check just the failing ones directly from the dashboard

2025-01-01 08:59 UTC, M-ZubairAhmed requested changes

2025-01-01 08:59 UTC, M-ZubairAhmed commented on webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
> +        case ' ': {
why do we need this case and why it execute onEnter?

2025-01-01 08:59 UTC, M-ZubairAhmed commented on webapp/channels/src/components/emoji_picker/components/emoji_picker_item.tsx
> +                alt={`${emoji.name.toLocaleLowerCase()} emoji image`}
as removed above we can use the emojiName variable instead here, because emoji might miss name or shortname

2025-01-02 11:42 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
> +        case ' ': {
Added that to make the emoji trigger on both `ENTER` and `SPACE` as mentioned in
Issue: https://mattermost.atlassian.net/browse/MM-61577

2025-01-02 11:50 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/emoji_picker/components/emoji_picker_item.tsx
> +                alt={`${emoji.name.toLocaleLowerCase()} emoji image`}
`emojiName` will anyways default to `emoji.name` if `short_name` is missing, so removed an extra step here. 
Moreover, i think `emoji.name` will always exist in both system and custom emojis. Let me know if i am missing something here.

2025-01-07 05:22 UTC, M-ZubairAhmed commented
/e2e-test

2025-01-07 05:23 UTC, M-ZubairAhmed commented
@SaurabhSharma-884 feel free to re-request review, so we can notification to re check the PR :)

2025-01-07 05:30 UTC, M-ZubairAhmed commented on webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
> +        case ' ': {
We can check explicitly for Enter and Space keys rather than a blank string

2025-01-07 13:09 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
> +        case ' ': {
the `event.key` value compared by switch case for space key is " " (ref: https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values). 

We need to change `event.key` -> `event.code` if we want to use case 'Space' here.

2025-01-07 13:12 UTC, SaurabhSharma-884 commented
Fixed E2E tests.Please review @M-ZubairAhmed @harshilsharma63

2025-01-08 09:12 UTC, harshilsharma63 approved these changes
Looks good!

2025-01-16 19:12 UTC, hmhealey commented
Dismissing the review request for me since I've got a ton of other PRs awaiting review and because Harshil and @M-ZubairAhmed are both on this one already as reviewers

2025-01-20 10:04 UTC, AayushChaudhary0001 approved these changes
The changes are working fine, so approving this PR.

2025-01-20 19:21 UTC, M-ZubairAhmed commented
@hmhealey Heads up this will conflict directly with you emoji picker PR. Would it be ok to wait or we can let it in

2025-01-21 22:59 UTC, hmhealey commented
> @hmhealey Heads up this will conflict directly with you emoji picker PR. Would it be ok to wait or we can let it in

Thanks for the heads up! It might conflict a bit because of my one change to fix the placeholder in `EmojiPickerSearch`, but I don't think it'll be bad because my other changes are outside of the emoji picker itself (in `EmojiPickerTabs` and `EmojiPickerOverlay`) while the changes to this PR are mostly inside of the emoji picker. I think it'd be fine to let this one in first once it's done reviews

2025-01-28 07:33 UTC, M-ZubairAhmed requested changes

2025-01-28 07:33 UTC, M-ZubairAhmed commented on webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
> +        case ' ': {
lets add this comment here and can you check if there is somewhere a constant for space key

2025-01-31 04:36 UTC, M-ZubairAhmed approved these changes

2025-01-31 04:36 UTC, M-ZubairAhmed commented
/update-branch

2025-02-02 14:12 UTC, ayush-chauhan233 commented
/update-branch

2025-02-02 14:12 UTC, mattermost-build commented
Looks like you don't have permissions to trigger this command.
 Only available for the PR submitter and org members

2025-02-03 06:56 UTC, merged