Adds the main Property System Architecture components
mattermost/mattermost pull request #29644
Opened 2024-12-19 14:09 UTC by mgdelacroix

#### Summary
This change adds the necessary migrations for the Property Groups, Fields and Values tables to be created, the store layer and a Property Service that can be used from the app layer.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-62165
https://mattermost.atlassian.net/browse/MM-62166
https://mattermost.atlassian.net/browse/MM-62167

#### Release Note
```release-note
* Adds the migrations, store layer and service for the Property System Architecture
```

2025-01-09 07:10 UTC, amyblais commented
@mgdelacroix Kind note that v10.5 feature complete deadline is scheduled for Monday, Jan 13th.

2025-01-09 17:47 UTC, JulienTant requested changes
Thank you @mgdelacroix! I left a few comments, I'm not sure what should be considered in the scope of the POC, so I'm marking this as Request changes but ultimately there's nothing majorly blocking.

2025-01-09 17:47 UTC, JulienTant commented on server/public/model/property_group.go
> +}
Do we need a `IsValid()` method that checks for the name?

2025-01-09 17:47 UTC, JulienTant commented on server/public/model/property_field.go
> +	if pf.Type == "" {
Should we make sure `Type` is one of the known/supported ones?

2025-01-09 17:47 UTC, JulienTant commented on server/public/model/property_value.go
> +	Value      string `json:"value"`
Given that the `value` will be fairly free in the future (string, array, I also suggested a `number` type), would it be worth it to start right away with a `json.RawMessage` type for Value? Or are we gonna convert all values to "string" in the frontend and parse them based on the field type?

So instead of sending a `multiuser` as `[id1,id2,id3]`, we would stringify it as a CSV and do some parsing on the frontend?

Might be out of target for the POC, just thinking out loud.

2025-01-09 17:47 UTC, JulienTant commented on server/channels/db/migrations/postgres/000130_add_property_fields.up.sql
> +    CREATE TYPE property_field_type AS ENUM (
Have we considered how plugins could extend the property field types in the future? I'm afraid that enforcing this as a DB level might prevent us to allow plugins to register their own "property field types" on the fly.

2025-01-09 17:47 UTC, JulienTant commented on server/channels/store/sqlstore/property_field_store.go
> +		if err := field.IsValid(); err != nil {
I'm wondering if using `err :=` will shadow the `err` declared in the function definition (`(_ []*model.PropertyField, err error)`) and ultimately impact what `defer finalizeTransactionX(transaction, &err)` does

2025-01-10 05:18 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +	rows, err := s.GetReplica().Query(queryString, args...)
Any reason we cannot do:

```
fields := []*model.PropertyField{}
err := s.GetReplica().Select(&fields, queryString, args...)
```
?

Then we don't really need `propertyFieldFromRows` which seems redundant.

If this is about `attrsJSON` and unmarshaling to `field.Attrs`, then we can simply define a custom type with `Value()` and `Scan()` methods for that. sqlx will automatically call those methods to parse out values from and to the DB. See: `func (sa StringArray) Value() (driver.Value, error) {` and `func (sa *StringArray) Scan(value any) error {` in model/utils.go

As a further step, you can even do `s.GetReplica().SelectBuilder()` and pass the builder directly without having to do a `.ToSql` and checking the error output. `(Select/Get)Builder` will do both for you.

2025-01-10 05:24 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +	if _, err := s.GetMaster().Exec(queryString, args...); err != nil {
Tip: we can use `ExecBuilder` and avoid having to do `.ToSql`

2025-01-10 05:26 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +		return nil, errors.New("property_field_get_many_missmatch_results")
`property_field_get_many_missmatch_results` barely has any context. Let's try to have a more user friendly error: `Number of ids got: %d is fewer than number of ids passed: %d`.

2025-01-10 05:27 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +	if opts.PerPage < 0 {
Even 0 is wrong here right?

2025-01-10 05:33 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +		Limit(uint64(opts.PerPage))
Instead of having an offset/limit model, could we pivot to key-set based pagination, where we pass the fieldID as the cursor and say "give me next 10 items after this fieldID"? It gets simple if we don't have to order by `CreateAt` . Then we can just order by ID. But if it's a requirement to order by `CreateAt`, then we can follow a sample implementation here: `(s *SqlPostStore) getPostWithCollapsedThreads`.

2025-01-10 05:36 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +		query = query.Where(sq.Eq{"TargetType": opts.TargetType})
Note that you only have a unique index on `(GroupID, TargetID, Name)`. This means queries to filter by just DeleteAt or TargetType, or even just TargetID won't use any index. Should we add an index for those? Or are we confident that there won't be too many SQL queries using those fields?

2025-01-10 05:40 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +		queryString, args, err := s.getQueryBuilder().
This could get expensive later, so maybe worth highlighting now. If you pass too many fields, then it becomes a long transaction. With a little bit of work, you can convert this into a single `UPDATE` with `CASE` to update multiple rows in a single statement. I will leave it to you.

2025-01-10 05:41 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +			return nil, errors.Wrap(err, "property_field_update_exec")
Let's use a more user friendly string: `Failed to update property field for id: %s`

2025-01-10 05:41 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +		return errors.Wrap(err, "property_field_delete_exec")
Same as earlier. Use a more user-friendly string and pass the id.

2025-01-10 05:43 UTC, agnivade commented on server/channels/store/sqlstore/property_group_store.go
> +	}
This is not atomic. Imagine 2 concurrent Register requests. One will pass, one will fail. We need to use an `INSERT .. ON CONFLICT` clause for this. See `(ls SqlLicenseStore) Save`.

2025-01-10 05:44 UTC, agnivade commented on server/channels/store/sqlstore/property_value_store.go
> +var propertyValueColumns = []string{
Same comment as the propertyField table.

2025-01-10 05:45 UTC, agnivade commented on server/channels/store/sqlstore/property_value_store.go
> +	if len(values) < len(ids) {
Mostly same comments as the earlier table. On error formatting, cursor-based pagination etc.

2025-01-10 09:53 UTC, mgdelacroix commented on server/public/model/property_value.go
> +	Value      string `json:"value"`
In other projects like boards we've used the string and parsing approach, but I like the idea of using generics for this. I'll explore it in a follow-up PR

2025-01-10 10:39 UTC, mgdelacroix commented on server/public/model/property_group.go
> +}
As the property group store accepts a `name string` instead of a group object, we're performing the `name == ""` check directly there

2025-01-10 10:59 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +		if err := field.IsValid(); err != nil {
The returned value is the explicit one instead of the `err`, but happy to make this more explicit to avoid confusion

2025-01-10 11:00 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +		if err := field.IsValid(); err != nil {
PTAL b3f4648131

2025-01-10 11:00 UTC, mgdelacroix commented on server/public/model/property_field.go
> +	if pf.Type == "" {
Fixed, PTAL 399e8fdbc9

2025-01-10 11:07 UTC, mgdelacroix commented on server/channels/db/migrations/mysql/000131_add_property_values.up.sql
> +	GroupID varchar(26) NOT NULL,
GroupID makes it easy to fetch values for a given feature ("give me all Custom Profile Attributes values for a user" translates into GroupID=CustomProfileAttributesID & TargetID=userID) and FieldID links a given value with its field

2025-01-10 11:12 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +	rows, err := s.GetReplica().Query(queryString, args...)
Yep, the reason was the use of JSON, but I didn't have time to check how this was done during the initial implementation. Will fix in a follow-up PR

2025-01-10 11:26 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +		Limit(uint64(opts.PerPage))
Makes sense, will send a follow-up PR updating the pagination model

2025-01-10 11:26 UTC, Willyfrog approved these changes
minor nitpicks, but LGTM

2025-01-10 11:26 UTC, Willyfrog commented on server/channels/db/migrations/postgres/000129_add_property_groups.up.sql
> +);
nitpick: we don't allow for deleting/modifying groups?

I don't think it is needed for this phase, but something to consider

2025-01-10 11:26 UTC, Willyfrog commented on server/channels/store/sqlstore/property_value_store.go
> +func (s *SqlPropertyValueStore) Get(id string) (*model.PropertyValue, error) {
nitpick: I wonder if `Get` should rely on `GetMany` to simplify code.

2025-01-10 11:31 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +		queryString, args, err := s.getQueryBuilder().
I think it makes sense, will make the changes in a follow-up PR

2025-01-10 12:14 UTC, mgdelacroix commented on server/public/model/property_field.go
> +	if pf.Name == "" {
Centralizing the conversation in this thread. Love the idea, PTAL fdf311b45c for property fields and eeea340fd4 for property values. Way clearner this way

2025-01-10 12:15 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +var propertyFieldColumns = []string{
Fixed, PTAL fdaadc04eb

2025-01-10 12:16 UTC, mgdelacroix commented on server/channels/db/migrations/postgres/000130_add_property_fields.up.sql
> +	DeleteAt bigint
Fixed, PTAL 46793c34e6

2025-01-10 12:16 UTC, mgdelacroix commented on server/channels/db/migrations/postgres/000131_add_property_values.up.sql
> +	DeleteAt bigint
Same, PTAL 46793c34e6

2025-01-10 12:16 UTC, mgdelacroix commented on server/channels/db/migrations/mysql/000129_add_property_groups.up.sql
> +CREATE TABLE IF NOT EXISTS PropertyGroups (
We had a bad experience in Boards with a big migration file and I grew attached to small ones, but in this case it doesn't make sense as it is fully idempotent. Fixed in f0f08479b2

2025-01-10 12:17 UTC, mgdelacroix commented on server/public/model/property_field.go
> +	if pf.CreateAt == 0 {
Closing all these small ones in favor of https://github.com/mattermost/mattermost/pull/29644#discussion_r1909835360, please reopen if necessary

2025-01-10 12:28 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +			return nil, errors.Wrap(err, "property_field_update_exec")
Fixed in 75c75982d1

2025-01-10 12:28 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +		return nil, errors.New("property_field_get_many_missmatch_results")
Makes sense, fixed in 75c75982d1

2025-01-10 12:32 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +	if opts.PerPage < 0 {
Fixed in 7770e6ed43

2025-01-10 12:37 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +		query = query.Where(sq.Eq{"TargetType": opts.TargetType})
Features should use searches that are narrowed down to a specific group at least, if not a group and a target. We can enforce this by changing the signature of the service search method to receive those fields explicitly and add them to the options for good measure, and add more indexes if we start having the need to run different queries that escape this restriction.

What do you think?

2025-01-10 12:53 UTC, mgdelacroix commented on server/channels/db/migrations/postgres/000129_add_property_groups.up.sql
> +);
Not at this phase of the feature, we'd have to define the expectations on what should happen when deleting a group, what features would require that, etc.

2025-01-10 12:57 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_value_store.go
> +func (s *SqlPropertyValueStore) Get(id string) (*model.PropertyValue, error) {
We'd have to do some error checking to convert missmatched results into `sql.ErrNoRows`, so we don't remove that much code. 1/5 tho

2025-01-10 12:59 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_value_store.go
> +var propertyValueColumns = []string{
Fixed in https://github.com/mattermost/mattermost/commit/fdaadc04ebe7631e37cb627377abe3858c4ea623, PTAL

2025-01-10 12:59 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +		return errors.Wrap(err, "property_field_delete_exec")
Fixed in https://github.com/mattermost/mattermost/commit/4205b3481705802746e01f134c02ee8011d26721, PTAL

2025-01-10 13:18 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_group_store.go
> +	}
Fixed, PTAL f48d8a126d

2025-01-10 14:38 UTC, agnivade commented on server/channels/store/sqlstore/property_field_store.go
> +		query = query.Where(sq.Eq{"TargetType": opts.TargetType})
Ok. Changing the signature of those search methods to use those fields explicitly sounds like a good idea. :+1:

2025-01-10 14:54 UTC, agnivade reviewed
Looks good Miguel. There's just one small bug in the translation field. Good to go from my side once that's fixed.

2025-01-10 14:54 UTC, agnivade commented on server/channels/store/sqlstore/property_group_store.go
> +	existingGroup, err := s.Get(name)
Once we have the `ON CONFLICT` clause, then we don't really need this. Because we are already doing:

```
if rowsAffected == 0 {
		return s.Get(name)
	}
```
later. So this can be removed.

2025-01-10 14:54 UTC, agnivade commented on server/public/model/property_field.go
> +		return NewAppError("PropertyField.IsValid", "model.property_field.is_valid.update_at.app_error", map[string]any{"FieldName": "update_at", "Reason": "value cannot be zero"}, "id="+pf.ID, http.Status
Same as before.

2025-01-10 15:34 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_group_store.go
> +	existingGroup, err := s.Get(name)
Right, good catch, removed here 4a54403d0a

2025-01-10 15:36 UTC, mgdelacroix commented on server/public/model/property_field.go
> +		return NewAppError("PropertyField.IsValid", "model.property_field.is_valid.create_at.app_error", map[string]any{"FieldName": "create_at", "Reason": "value cannot be zero"}, "id="+pf.ID, http.Status
Yep, missed removing those two although I did add the details map, fixed here 45eaff136f

2025-01-10 22:01 UTC, JulienTant commented on server/channels/db/migrations/postgres/000130_add_property_fields.up.sql
> +    CREATE TYPE property_field_type AS ENUM (
Sounds good to me, just wanted to make sure it's been considered! Resolving this

2025-01-10 22:02 UTC, JulienTant approved these changes
Thanks @mgdelacroix!

2025-01-11 11:52 UTC, agnivade approved these changes
LGTM!

2025-01-13 08:52 UTC, mgdelacroix commented
/update-branch

2025-01-13 10:53 UTC, mgdelacroix commented
/e2e-test

2025-01-13 11:41 UTC, merged

2025-01-13 11:46 UTC, amyblais commented
/cherry-pick release-10.5

2025-01-13 11:46 UTC, mattermost-build commented
Cherry pick is scheduled.

2025-01-13 11:51 UTC, amyblais commented
@mgdelacroix Can you help fill in details from this doc https://docs.google.com/document/d/18lD7N32oyMtYjFrJKwsNv8yn6Fe5QtF-eMm8nn0O8tk/edit?tab=t.0#heading=h.1ozc9hcotgot to add more details to the release notes?

2025-01-24 15:17 UTC, esarafianou reviewed
@mgdelacroix a late review. Just a few comments that are not security related and definitely not a blocker.

2025-01-24 15:17 UTC, esarafianou commented on server/channels/store/sqlstore/property_value_store.go
> +	value.PreSave()
Same comment as in the property fields

2025-01-24 15:17 UTC, esarafianou commented on server/channels/app/properties/property_group.go
> +}
Shouldn't we at least have a delete option? What happens if I register a property group with e.g. a typo?

2025-03-07 16:23 UTC, mgdelacroix commented on server/public/model/property_group.go
> +		pg.ID = NewId()
Property groups are currently not tracking timestamps, as they're only used to group fields and values and not expected to be dynamic.

2025-03-07 16:28 UTC, mgdelacroix commented on server/channels/store/sqlstore/property_field_store.go
> +	field.PreSave()
It is a common pattern in our store on creation methods to first check the existence of an ID and return an error if present (probably to signal to the client that they're passing an ID on a creation payload, so potentially using the wrong endpoint, or to the implementer that they need to use `Update` instead of `Create` for existing fields), then we create the ID with `PreSave` and last we use an `IsValid` function that checks that the model is fully ready to be persisted.

2025-03-07 16:31 UTC, mgdelacroix commented on server/public/model/property_group.go
> +	if pg.ID == "" {
Same explanation than https://github.com/mattermost/mattermost/pull/29644#discussion_r1985359495, or at least that's what I understand from the code after seeing this applied for other entities like `user` or `channel`