[MM-61599]: Remove tabIndex from non-interactive elements
mattermost/mattermost pull request #29659
Opened 2024-12-20 04:36 UTC by SaurabhSharma-884

#### Summary

The PR ensures focus order of interactive elements on the page is logical and focus is not moved to non-interactive elements of the page. 

#### Steps to reproduce  
- Navigate to the page using tab key until reaches the entire section of the At 8:08 PM Monday, September 23, Someone wrote, user joined the team text.
- Notice that non-interactive elements receive focus.

#### Ticket Link

Fixes: https://mattermost.atlassian.net/browse/MM-61599

#### Screenshots

[Screencast from 2024-12-16 18-04-35.webm](https://github.com/user-attachments/assets/583b5396-545c-4de5-8ea5-9445aca68127)

#### Release Note

```release-note

```

2024-12-20 04:36 UTC, mattermost-build commented
Hello @SaurabhSharma-884,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-31 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-02 10:46 UTC, AayushChaudhary0001 approved these changes
This PR has been tested for the changes and the non-interactive element(text here) is not getting focussed anymore, LGTM. Approved

2025-01-03 03:45 UTC, harshilsharma63 approved these changes

2025-01-07 05:21 UTC, M-ZubairAhmed requested changes
few a11y e2e tests are failing

2025-01-10 06:13 UTC, SaurabhSharma-884 commented
/update-branch

2025-01-15 12:13 UTC, SaurabhSharma-884 commented
/update-branch

2025-01-17 13:27 UTC, M-ZubairAhmed commented
@SaurabhSharma-884 can you check failing e2e

2025-01-17 14:20 UTC, SaurabhSharma-884 commented
> @SaurabhSharma-884 can you check failing e2e

Checked. Result shows 3 failing tests but those are passing on my local

2025-01-21 05:35 UTC, SaurabhSharma-884 commented
/update-branch

2025-01-28 07:34 UTC, M-ZubairAhmed requested changes
Can you check CI

2025-01-30 12:07 UTC, ayush-chauhan233 commented
@M-ZubairAhmed The failing test case is running successfully on local 
![Screenshot from 2025-01-30 17-35-43](https://github.com/user-attachments/assets/f15d2c8a-2d70-4dc2-bb74-e46b4a69a1fe)

2025-01-30 18:18 UTC, marianunez commented
> @M-ZubairAhmed The failing test case is running successfully on local ![Screenshot from 2025-01-30 17-35-43](https://private-user-images.githubusercontent.com/180265069/408113520-f15d2c8a-2d70-4dc2-bb74-e46b4a69a1fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgyNjEyNzcsIm5iZiI6MTczODI2MDk3NywicGF0aCI6Ii8xODAyNjUwNjkvNDA4MTEzNTIwLWYxNWQyYzhhLTJkNzAtNGRjMi1iYjc0LWU0NmI0YTY5YTFmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEzMFQxODE2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTcwNDI4NjdjNWNiODdmYTVkNDg2YmRiOTE2YzVlNjQ3ZjM0ZjFiODM0ZGQzNzU3YzVmMDc5OWJhZmJiMzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0OvEKh5qg3Ikc5ehGSbFbbYJ8qAvATNheVEVpFM0C5k)

@yasserfaraazkhan is this a know flaky test? 
`1. tests/integration/channels/messaging/message_reaction_gm_spec.js`

2025-01-31 05:35 UTC, M-ZubairAhmed approved these changes

2025-01-31 15:57 UTC, yasserfaraazkhan commented
> @yasserfaraazkhan is this a know flaky test? `1. tests/integration/channels/messaging/message_reaction_gm_spec.js`

@marianunez 
This test it fixed. It was failing as the `tab` focus was not on expected element.

2025-01-31 16:24 UTC, merged