Custom profile attributes field endpoints
mattermost/mattermost pull request #29662
Opened 2024-12-20 15:29 UTC by mgdelacroix

#### Summary
Adds the Custom Profile Attribute fields store, app and API endpoints.

#### Release Note
```release-note
* Adds the Custom Profile Attribute fields store, app and API endpoints.
```

2025-01-02 18:17 UTC, sbishel commented
/update-branch

2025-01-02 20:46 UTC, sbishel commented
/update-branch

2025-01-02 20:46 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.

2025-01-10 13:17 UTC, agarciamontoro requested changes
Very thorough work, thank you! I've made a first pass for:
- `server/channels/api4`
- `server/channels/web`
- `public/model/client4.go`
- `public/model/custom_profile_attributes.go`
- `public/model/feature_flags.go`

One important thing to note is that we would need to add coverage for the new endpoints to the load-test tool eventually. I can help you with that if needed. I see this is behind a feature flag for now, so we have some time.

2025-01-10 13:17 UTC, agarciamontoro commented on server/public/model/client4.go
> +	r, err := c.DoAPIGet(ctx, c.userRoute(userID)+c.customProfileAttributesRoute(), "")
Nit: Should we add another `userCustomerProfileAttributesRoute(userID)` function for this?

2025-01-10 13:17 UTC, agarciamontoro commented on server/channels/api4/custom_profile_attributes_test.go
> +		th.LoginBasic2()
This login is needed for both tests here, right? Should we move it outside of the `t.Run`s? Or repeat it in the second one?

2025-01-10 13:17 UTC, agarciamontoro commented on server/channels/api4/custom_profile_attributes_test.go
> +	})
Not sure what the difference is between these two tests. The first one says `create`, but it's also patching.

2025-01-10 14:35 UTC, mgdelacroix commented on server/channels/api4/custom_profile_attributes.go
> +	}
The response was missing the results. Fixed and tested in 1b67d20444, PTAL

2025-01-10 14:36 UTC, mgdelacroix commented on server/channels/api4/custom_profile_attributes.go
> +	}
Fixed in c5703748a3

2025-01-10 16:12 UTC, agarciamontoro commented on server/channels/api4/custom_profile_attributes.go
> +	}
Neat, thank you

2025-01-10 17:17 UTC, JulienTant requested changes
I didn't do an actual full review because the PR is not marked as ready but I thought I'd cover some basics before sending to the security team, so I only looked at the entry point (api*/ routes) for permissions and input validation.

Permissions seem to be well covered, I imagine that as far as the POC is concerned we don't wanna add dedicated permissions.

We need to add some input validation and sanitization.

I'll do a complete when the PR is ready!

2025-01-10 17:17 UTC, JulienTant commented on server/channels/api4/custom_profile_attributes.go
> +
Missing input sanitization/validation

2025-01-10 17:17 UTC, JulienTant commented on server/channels/api4/custom_profile_attributes.go
> +
Missing input sanitization/validation

2025-01-10 17:17 UTC, JulienTant commented on server/channels/api4/custom_profile_attributes.go
> +		patchedValue, appErr := c.App.PatchCPAValue(userID, fieldID, value)
Missing input sanitization/validation

2025-01-10 17:17 UTC, JulienTant commented on server/channels/api4/custom_profile_attributes.go
> +	if !c.App.SessionHasPermissionToUser(*c.AppContext.Session(), userID) {
You love to see this!!

2025-01-13 11:01 UTC, mgdelacroix commented on server/channels/api4/custom_profile_attributes.go
> +
Fixed, PTAL daa1b91399

2025-01-13 11:01 UTC, mgdelacroix commented on server/channels/api4/custom_profile_attributes.go
> +
PTAL daa1b91399

2025-01-13 11:02 UTC, mgdelacroix commented on server/channels/api4/custom_profile_attributes.go
> +		patchedValue, appErr := c.App.PatchCPAValue(userID, fieldID, value)
PTAL daa1b91399

2025-01-13 11:03 UTC, mgdelacroix commented on server/channels/api4/custom_profile_attributes_test.go
> +		th.LoginBasic2()
Good catch! PTAL 294e0eeb90

2025-01-13 11:09 UTC, mgdelacroix commented on server/channels/api4/custom_profile_attributes_test.go
> +	})
The same endpoint is used to perform multiple actions, in this case, if a field doesn't exist it will create it, and later the same endpoint call will apply a patch to the existing field. [This is the related logic](https://github.com/mattermost/mattermost/pull/29662/files#diff-74f3c860c5673d7da3357ad9454a53f2019e57ec7faeb378241994bad6e325e4R217-R235)

2025-01-13 11:59 UTC, mgdelacroix commented
@agarciamontoro @JulienTant thanks a ton for the first passes on the PR! The PSA one has been merged, so you should see the LoC count for this one reduced by 2/3. I've moved it out of draft as it is ready for a final review, PTAL when you have the time :)

2025-01-13 13:31 UTC, agarciamontoro requested changes
Thanks, @mgdelacroix! Just a few nits below, nothing really important.

2025-01-13 13:31 UTC, agarciamontoro commented on server/channels/app/custom_profile_attributes.go
> +		PerPage:        999999,
Same here

2025-01-13 13:31 UTC, agarciamontoro commented on server/channels/app/custom_profile_attributes_test.go
> +	}
Consistency nit: we call `cpaGroupID()` here, but in the previous test we directly call `RegisterPropertyGroup`. Should we do it the same way in both tests?

2025-01-13 13:31 UTC, agarciamontoro commented on server/channels/app/custom_profile_attributes_test.go
> +		for i := 1; i < CustomProfileAttributesFieldLimit-1; i++ {
This index is like this because we've created two fields in the tests above, right? Should we try and start from scratch in all tests? So that they don't depend on each other?

2025-01-13 13:31 UTC, agarciamontoro commented on server/channels/app/custom_profile_attributes_test.go
> +}
Same here, I feel like tests depending on each other are a bit dangerous. Not urgent for this PR, though, if time is a constraint.

2025-01-13 13:31 UTC, agarciamontoro commented on server/channels/app/custom_profile_attributes_test.go
> +		require.Empty(t, updatedField.TargetType, "CPA should not allot to patch the field's target type")
Typos here
```suggestion
		require.Empty(t, updatedField.TargetID, "CPA should not allow to patch the field's target ID")
		require.Empty(t, updatedField.TargetType, "CPA should not allow to patch the field's target type")
```

2025-01-13 13:31 UTC, agarciamontoro commented on server/channels/app/custom_profile_attributes_test.go
> +	})
This I really like! A test being included inside another one, the dependency is clear.

2025-01-13 13:57 UTC, mgdelacroix commented on server/channels/app/custom_profile_attributes.go
> +	}
Right! PTAL 48903f70ef

2025-01-13 14:15 UTC, mgdelacroix commented on server/channels/app/custom_profile_attributes_test.go
> +	}
Standardized `groupID` access on 93f2dd5f1f, PTAL

2025-01-13 14:19 UTC, mgdelacroix commented on server/channels/app/custom_profile_attributes_test.go
> +		for i := 1; i < CustomProfileAttributesFieldLimit-1; i++ {
Fixed this comment and the next on be7fc44856, PTAL

2025-01-13 14:20 UTC, mgdelacroix commented on server/channels/app/custom_profile_attributes_test.go
> +}
Closing this one to centralize the conversation on the previous comment

2025-01-13 14:20 UTC, mgdelacroix commented on server/channels/app/custom_profile_attributes_test.go
> +	})
Heh, funnily enough, tackled your previous comment through nesting as well, glad it is clear that way :)

2025-01-13 15:19 UTC, mgdelacroix commented
/e2e-test

2025-01-13 15:33 UTC, agarciamontoro approved these changes
Looking great, thank you!

2025-01-13 16:39 UTC, calebroseland approved these changes

2025-01-13 17:00 UTC, JulienTant approved these changes
I'll go ahead and approve because my remark is not critical, but I think that would be a nice DX improvement by preventing devs in the future to call the `getProperties*` methods and then forget to check the group ID.
Thanks @mgdelacroix!

2025-01-13 17:12 UTC, merged

2025-01-13 17:12 UTC, mattermost-build commented
Cherry pick is scheduled.

2025-01-13 17:12 UTC, mattermost-build commented
Error trying doing the automated Cherry picking. Please do this manually

```
+++ Updating remotes...
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
From github.com:mattermost/mattermost
   6f981b77fb..289568350e  MM-60407     -> upstream/MM-60407
   3e4c6f7bc9..eee11c2454  MM-61966     -> upstream/MM-61966
   e53dbf29c4..bf664b9f1b  MM-62170-CPA-User-Settings -> upstream/MM-62170-CPA-User-Settings
 * [new branch]            WeblateFix   -> upstream/WeblateFix
   0950e060fb..fb0109b73e  fix-manage-playbook-members-language -> upstream/fix-manage-playbook-members-language
   c6984941f1..ca34c6a03f  master       -> upstream/master
   f3ef643ef0..610704cc3f  release-10.5 -> upstream/release-10.5
 * [new branch]            sync-weblate -> upstream/sync-weblate
Fetching upstream
hostfile_replace_entries: mkstemp: Read-only file system
update_known_hosts: hostfile_replace_entries failed for /app/.ssh/known_hosts: Read-only file system
+++ Updating remotes done...
+++ Creating local branch automated-cherry-pick-of-mattermost-#29662-upstream-release-10.5-1736788362
Switched to a new branch 'automated-cherry-pick-of-mattermost-#29662-upstream-release-10.5-1736788362'
Branch 'automated-cherry-pick-of-mattermost-#29662-upstream-release-10.5-1736788362' set up to track remote branch 'release-10.5' from 'upstream'.

+++ About to attempt cherry pick of PR #29662 with merge commit ca34c6a03f2f2f9ae392498e998a6aaee7fe4d13.

Auto-merging api/v4/source/introduction.yaml
CONFLICT (content): Merge conflict in api/v4/source/introduction.yaml
CONFLICT (modify/delete): server/channels/store/sqlstore/property_field_store.go deleted in HEAD and modified in ca34c6a03f (Custom profile attributes field endpoints (#29662)).  Version ca34c6a03f (Custom profile attributes field endpoints (#29662)) of server/channels/store/sqlstore/property_field_store.go left in tree.
Auto-merging server/i18n/en.json
CONFLICT (modify/delete): server/public/model/property_field.go deleted in HEAD and modified in ca34c6a03f (Custom profile attributes field endpoints (#29662)).  Version ca34c6a03f (Custom profile attributes field endpoints (#29662)) of server/public/model/property_field.go left in tree.
error: could not apply ca34c6a03f... Custom profile attributes field endpoints (#29662)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

+++ Conflicts detected:

UU api/v4/source/introduction.yaml
Aborting.

+++ Aborting in-progress git cherry-pick.

+++ Returning you to the master branch and cleaning up.

```

2025-01-13 17:19 UTC, mgdelacroix commented on server/channels/app/custom_profile_attributes.go
> +	field, err := a.Srv().propertyService.GetPropertyField(fieldID)
Thanks for pointing this out! I have a follow-up PR on the service API shape to try and make it more natural to use the indexes we have, so I'll work on this too as part of those changes :)

2025-01-14 07:26 UTC, amyblais commented
@mgdelacroix If this is scheduled for v10.5, can you help open a manual cherry-pick PR? The automated cherry-pick failed.

2025-01-14 12:57 UTC, mgdelacroix commented
@amyblais cherry pick done at https://github.com/mattermost/mattermost/pull/29849

2025-01-27 11:20 UTC, esarafianou reviewed
@mgdelacroix some minor comments but nothing blocking

2025-01-27 11:20 UTC, esarafianou commented on server/channels/api4/custom_profile_attributes.go
> +		api.BaseRoutes.CustomProfileAttributesValues.Handle("", api.APISessionRequired(patchCPAValues)).Methods(http.MethodPatch)
Is the goal to add in the future restrictions on whether a value can be patched by a user? e.g. customers may want CPA to come from their IdP and disallow users to update them similar to how we currently handle first/last name and email.

2025-03-07 16:44 UTC, mgdelacroix commented on server/channels/api4/custom_profile_attributes.go
> +		api.BaseRoutes.CustomProfileAttributesValues.Handle("", api.APISessionRequired(patchCPAValues)).Methods(http.MethodPatch)
Yes! We're planning to forbid patching a value for a field that is being synced with an external source of truth (say LDAP/SAML), but we've discussed the possibility of making this an option on certain fields, so only admins can set values for other users

2025-03-07 16:48 UTC, mgdelacroix commented on server/channels/app/custom_profile_attributes.go
> +	fields, err := a.Srv().propertyService.SearchPropertyValues(opts)
Indeed 😅 this was fixed on a follow up PR