fix(pluginapi/store): init master db if no replica
mattermost/mattermost pull request #29674
Opened 2024-12-22 10:23 UTC by ebuildy

#### Summary

GetReplicaDB return nil because masterDB is not initialized, the fix initialize the masterDB (this is skipped if masterDB is already initialized).

```go
dbDriver, err := p.pluginAPIClient.Store.GetReplicaDB()
```

--> dbDriver is nil

```go
p.pluginAPIClient.Store.GetMasterDB()
dbDriver, err := p.pluginAPIClient.Store.GetReplicaDB()
```

OK!

#### Ticket Link

#### Screenshots

#### Release Note

```release-note
* Fix pluginapi.store.GetReplicaDB return nil if masterDB is not initialized
```

2024-12-22 10:23 UTC, mattermost-build commented
Hello @ebuildy,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-12-24 13:36 UTC, lieut-data approved these changes
Ooh, nice catch @ebuildy! Thanks :)

2024-12-30 15:47 UTC, agnivade requested changes
Nice one! Could we add a test for this?

2024-12-30 17:38 UTC, ebuildy commented
Actually there is a test already, but as "get master DB" was called before "get replica DB" ..... I have just switched it.

2025-01-01 07:32 UTC, agnivade commented on server/public/pluginapi/store_test.go
>  		store := pluginapi.NewClient(api, driver).Store
Can we have 2 separate sub-tests with different instances of store? One should call `GetMasterDB` first, the other should call `GetReplicaDB` first. The current changes trade off one code path for another.

2025-01-01 21:09 UTC, ebuildy commented on server/public/pluginapi/store_test.go
>  		store := pluginapi.NewClient(api, driver).Store
Done! added "master db fallback without get master first" test

2025-01-02 02:40 UTC, agnivade approved these changes
Thanks!

2025-01-02 02:40 UTC, agnivade commented
/e2e-test

2025-01-02 04:37 UTC, agnivade commented
/e2e-test

2025-01-02 08:21 UTC, merged