[MM-19267] Add OnPluginStatusesChanged plugin hook and GetPluginStatuses plugin API method
mattermost/mattermost pull request #29673
Opened 2024-12-21 13:39 UTC by willypuzzle

#### Summary
This Update adds `OnPluginStatusesChanged `plugin hook. It is called when `App.notifyPluginStatusesChanged` is called. Some refactoring  and breaking changes are made necessary because they need the request.CTX have to be provided.

This update introduces a new API method, `GetPluginStatuses`, which returns the statuses of all plugins on the server. The implementation has been added to several files including `api.go`, `api_timer_layer_generated.go` and `client_rpc_generated.go`. Additionally, a mock function for testing this new API method has been provided in plugintest/api.go. Minor changes have also been made to the `InstallPlugin `mock function parameters in `plugintest/api.go` for better consistency.

A new function, `GetPluginStatuses()`, has been added to the `PluginAPI`. This function returns the status of all plugins currently running on the server.

#### Ticket Link
https://github.com/mattermost/mattermost/issues/13945

#### Release Note
```release-note
Some breaking changes have been introduced
- `InstallPlugin` of `AppIface` method signature modified: `InstallPlugin(pluginFile io.ReadSeeker, replace bool, r *http.Request)`
- `RemovePlugin` of `Channels` method signature modified: `RemovePlugin(id string, r *http.Request)`
- IMPORTANT: `InstallPlugin` of `plugin.API` method signature modified: `InstallPlugin(file io.Reader, replace bool, r *http.Request)`
- `Install` of `PluginService` method signature modified: `Install(file io.Reader, replace bool, r *http.Request)`
- `CompleteOnboarding` of `AppIface` method signature modified: `CompleteOnboarding(c request.CTX, request *model.CompleteOnboardingRequest, r *http.Request)`
- added `app AppIface` member to `Channels` struct
- `InstallMarketplacePlugin` of `Channels` method signature modified: `InstallMarketplacePlugin(request *model.InstallMarketplacePluginRequest, r *http.Request)`
- `InstallPluginFromURL` of `PluginService` method signature modified: `InstallPluginFromURL(downloadURL string, replace bool, r *http.Request)`
```

2024-12-21 13:39 UTC, mattermost-build commented
Hello @willypuzzle,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2025-01-01 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-25 01:02 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-27 14:49 UTC, lieut-data requested changes
Hi @willypuzzle! Apologies for the delay in reviewing -- I had meant to share this feedback earlier, but I'm surprised by how many files are signatures are being changed to support this method.

Commented inline, but something seems "wrong" to require `http.Request` as part of `RemovePlugin` and `InstallPlugin`.

What's the problem being solved by adding those arguments, and perhaps we chat through alternate solutions.

2025-01-27 14:49 UTC, lieut-data commented on server/public/plugin/api.go
> +	RemovePlugin(id string, r *http.Request) *model.AppError
@willypuzzle, I can't see a reason for why `RemovePlugin` and `InstallPlugin` require a `*http.Request`. These are methods that are designed to be used outside of an HTTP request, so something seems amiss here.

2025-01-27 14:58 UTC, willypuzzle commented on server/channels/api4/plugin.go
> +func installPlugin(c *Context, w http.ResponseWriter, plugin io.ReadSeeker, force bool, r *http.Request) {
Yes, sure!

2025-01-27 15:02 UTC, willypuzzle commented on server/public/plugin/api.go
> +	RemovePlugin(id string, r *http.Request) *model.AppError
yes, I could not pass the `http.Request` in these calls but this implies that the context passed in `OnPluginStatusesChanged` will bell always null, when such methods are called.

2025-01-30 10:28 UTC, willypuzzle commented on server/public/plugin/api.go
> +	RemovePlugin(id string, r *http.Request) *model.AppError
@lieut-data so, what should I do? passing nothing and allowing null context in any case?

2025-01-30 14:52 UTC, lieut-data commented on server/public/plugin/api.go
> +	RemovePlugin(id string, r *http.Request) *model.AppError
I'd have to double check, but I think the pattern would be to create an empty context. Are there some fields that we can fill in for the context while leaving the others empty (because they didn't come from an `http.Request` in the first place?)

2025-01-30 15:23 UTC, willypuzzle commented on server/public/plugin/api.go
> +	RemovePlugin(id string, r *http.Request) *model.AppError
Unfortunately not, are all http based information https://github.com/mattermost/mattermost/blob/master/server/channels/app/context.go#L17-L25

2025-01-30 15:52 UTC, lieut-data commented on server/public/plugin/api.go
> +	RemovePlugin(id string, r *http.Request) *model.AppError
Then just an empty context should suffice: we do this elsewhere with hooks, for example:

https://github.com/mattermost/mattermost/blob/369b9fa96b4663de470b7c210da34caca7992783/server/channels/app/cluster_handlers.go#L51-L54

2025-01-30 22:14 UTC, willypuzzle commented
@lieut-data I apply your suggestions, I hope everything is good now.

2025-02-03 13:14 UTC, lieut-data commented
Thanks, @willypuzzle! Will take a look :)

2025-02-08 17:14 UTC, willypuzzle commented
@lieut-data sorry if I ping you but I care about this PR :)

2025-02-10 14:02 UTC, lieut-data commented
Apologies, @willypuzzle! This one slipped off my radar once I "requested changes" -- I've re-requested a review from myself to help move it forward :)

2025-02-14 11:50 UTC, willypuzzle commented
@lieut-data up

2025-02-17 14:16 UTC, lieut-data reviewed
Hey @willypuzzle! I've been mulling over a few of the propose changes around `app` and what looks like "dual contexts", and I think something is "wrong" here, but I'll need some more time to dig deeper into what's broken with our context architecture here.

Commenting so this stays on my radar, with a few details below.

2025-02-17 14:16 UTC, lieut-data commented on server/channels/app/channels.go
> +	app               *App
The fact that we have to add `app` to the `Channels` struct feels wrong here. I'm trying to figure out what to propose changing.

2025-02-17 14:16 UTC, lieut-data commented on server/channels/app/onboarding.go
> +func (a *App) CompleteOnboarding(c request.CTX, request *model.CompleteOnboardingRequest, r *http.Request) *model.AppError {
Another potential problem here (not necessarily yours, but symptomatic of something bigger): we should haven't to pass a `request.CTX` and `*http.Request` so we can build /another/ context object for plugins. Something is off here and I need to figure out what to recommend.

2025-05-21 17:17 UTC, lieut-data commented
@willypuzzle, I apologize that this has sat so long. I had hoped this would be an easy change, but I see how our use of request contexts has regrettably muddied things, and I don't have an immediate suggestion for how to "fix" it.

I'd love to come back to this and help figure out next steps, but I know that's not going to happen in the short term, so I'll close this out for now. Thanks for being willing to engage on the proposal!

2025-05-21 17:17 UTC, closed without merging