MM-62145 Migrate SELECT * Queries in system_store.go
mattermost/mattermost pull request #29688
Opened 2024-12-24 07:54 UTC by gitshubham45

#### Summary

This PR addresses backward compatibility concerns introduced by potential SELECT * queries in the system_store.go file.

- Replaces hard-coded SELECT * queries with the SQL builder pattern.

- This ensures explicit selection of columns and avoids issues with schema changes on older servers.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/29681
Jira  https://mattermost.atlassian.net/browse/MM-62145

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-12-24 07:54 UTC, mattermost-build commented
Hello @gitshubham45,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2024-12-24 14:26 UTC, lieut-data requested changes
Thanks for this, @gitshubham45! This is "Step 1" of the ask: to rewrite using the query builder. Can you help complete "Step 2", namely: "Step 2: Migrate any instances of SELECT * into explicitly enumerating the needed columns"?

2024-12-25 13:23 UTC, gitshubham45 commented
@lieut-data Only instance involving multiple columns is this one.
`query := s.getQueryBuilder(). Insert("Systems"). Columns("Name", "Value"). Values(system.Name, system.Value)`
but in the issue it is mentioned only to change Select *. Do I need to change this also ?

2024-12-26 01:15 UTC, harshilsharma63 commented
/check-cla

2024-12-26 04:19 UTC, harshilsharma63 commented
/e2e-tests

2025-01-03 03:38 UTC, harshilsharma63 requested changes

2025-01-03 03:38 UTC, harshilsharma63 commented on server/channels/store/sqlstore/system_store.go
> +	systemInsertQuery sq.InsertBuilder
You are over-complicating this. Just create a function that returns an array of columns names and call that function instead of using select *, See function `bookmarkWithFileInfoSliceColumns for reference.

2025-01-08 19:51 UTC, lieut-data commented
Thanks for the effort here, @gitshubham45! I think this PR isn't going in the right direction, so I'm going to close it out for now, but happy to continue the conversation in the issue.

2025-01-08 19:51 UTC, closed without merging