[MA-26]: Fix ARIA roles, states, and properties are valid in user profile image and @user buttons
mattermost/mattermost pull request #29692
Opened 2024-12-24 14:46 UTC by SaurabhSharma-884

#### Summary

This PR ensure ARIA roles, states, and properties are valid in user profile image and @user buttons.

#### Steps to reproduce  

- Navigate to the user profile image button.
- Inspect the element.Notice that the aria-expanded and aria-haspopup attributes implemented for the <span>tag is invalid.

#### Ticket Link

Fixes: https://mattermost.atlassian.net/browse/MM-61598

#### Screenshots

![Screenshot from 2024-12-16 14-35-49](https://github.com/user-attachments/assets/87415900-c8a5-476b-accf-d80678730da5)
![Screenshot from 2024-12-16 14-36-01](https://github.com/user-attachments/assets/01da7318-0a02-450a-bb03-bb2fb5e928a0)

#### Release Note

```release-note
NONE
```

2024-12-24 14:46 UTC, mattermost-build commented
Hello @SaurabhSharma-884,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2025-01-02 09:49 UTC, AayushChaudhary0001 commented
@SaurabhSharma-884 Can you please update the description of this PR properly? This is not very clear.

2025-01-19 01:04 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-01-20 10:21 UTC, AayushChaudhary0001 approved these changes
This PR has been tested and the aria-expanded and aria-popover has been implemented for the tags, LGTM. Approved.

2025-01-20 17:15 UTC, marianunez commented
/e2e-test

2025-01-20 19:01 UTC, M-ZubairAhmed requested changes

2025-01-20 19:01 UTC, M-ZubairAhmed commented on webapp/channels/src/components/post/post_component.tsx
> -                    role='application'
why are we loosing this role in these snapshots?

2025-01-20 19:01 UTC, M-ZubairAhmed commented on webapp/channels/src/components/at_mention/at_mention.tsx
>                      <a
this is a bit problematic since now we have button and its child as a link

2025-01-20 19:35 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/at_mention/at_mention.tsx
>                      <a
An anchor tag without `href` is not actually a link (and it is valid HTML as well). Ref: https://www.w3.org/TR/2011/WD-html5-20110525/text-level-semantics.html#the-a-element

 So, it won't be a problem to use it like this. We can still remove anchor tag and use another HTML tag instead.

2025-01-20 19:42 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/post/post_component.tsx
> -                    role='application'
Just to clarify, this file isn't a snapshot. The role application was removed as recommended in the issue here: https://mattermost.atlassian.net/browse/MM-61598

 Could you let me know if there's something specific you’d like me to address here?

2025-01-22 01:28 UTC, pvev requested changes
In general looks good, the only concern I share with @M-ZubairAhmed comment is about having the two nested interactive elements, even if it is "valid" HTML. Please, explore other option for this. If what you find is too complex, implies lots of changes or the solution will be error prone, we can consider going with the nested interactive elements.

2025-01-22 01:28 UTC, pvev commented on webapp/channels/src/components/at_mention/at_mention.tsx
>                      <a
an <a> tag without an href is valid HTML, however, it is not semantically appropriate. Also, it can confuse users and also potentialy confuse assistive technologies. Screen readers may announce it as a link. Isn't other way to handle this?

2025-01-22 06:30 UTC, SaurabhSharma-884 commented on webapp/channels/src/components/at_mention/at_mention.tsx
>                      <a
Sure, used span tag instead. Added few styles as well to match the previous UI.

2025-01-22 23:45 UTC, pvev commented
/e2e-test

2025-01-22 23:47 UTC, pvev approved these changes
LGTM! Great work here. One last comment about a color, please address it 🚀 🎉

2025-01-22 23:47 UTC, pvev commented on webapp/channels/src/sass/components/_mentions.scss
> +    color:rgb(56, 111, 229)
question, which color is this one? where did you get it from? can you please use one of the colors we have as a variable value for supporting the theming?

2025-01-28 07:06 UTC, M-ZubairAhmed requested changes
@pvev ask regarding the color and a nit thats all

2025-01-28 07:06 UTC, M-ZubairAhmed commented on webapp/channels/src/sass/components/_mentions.scss
> +.mention-link:focus {
please move the above nesting inside of mention-link

2025-01-30 06:29 UTC, ayush-chauhan233 commented
/update-branch

2025-01-30 06:29 UTC, mattermost-build commented
Looks like you don't have permissions to trigger this command.
 Only available for the PR submitter and org members

2025-01-31 04:32 UTC, M-ZubairAhmed approved these changes
Just a nit

2025-01-31 04:32 UTC, M-ZubairAhmed commented on webapp/channels/src/sass/components/_mentions.scss
> +    :focus {
```suggestion
    &:hover,
    &:focus {
```

2025-02-02 18:50 UTC, merged