Restore post api integration
mattermost/mattermost pull request #29719
Opened 2024-12-31 09:14 UTC by harshilsharma63

#### Summary
Used the new restore post API for restoring post versions.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-62015

#### Release Note
```release-note
none
```

2024-12-31 11:42 UTC, M-ZubairAhmed requested changes

2024-12-31 11:42 UTC, M-ZubairAhmed commented on webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
> +            dispatch(logError(error));
we are logError(ing) two time if its time limit

2024-12-31 11:42 UTC, M-ZubairAhmed commented on webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
> +                role={'button'}
explicitly is this needed?

2024-12-31 11:42 UTC, M-ZubairAhmed commented on webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
>                                  className='edit-post-history__icon__button toggleCollapseButton'
why can we just use the standard button classes from `webapp/channels/src/sass/components/_buttons.scss`

2024-12-31 11:42 UTC, M-ZubairAhmed commented on webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
>                  className='edit-post-history__icon__button restore-icon'
same using standard class

2025-01-02 00:28 UTC, harshilsharma63 commented on webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
> +            dispatch(logError(error));
The first one makes the error appear on top bar for the user, is second one is a generic catch all. I've moved it into he `else` to avoid confusion.

2025-01-02 00:28 UTC, harshilsharma63 commented on webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
> +                role={'button'}
Not needed, removed.

2025-01-02 00:29 UTC, harshilsharma63 commented on webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
>                                  className='edit-post-history__icon__button toggleCollapseButton'
They don't match the style. This isn't a new button I'm creating, I'm migrating from IconButton to native button to avoid using styled components so I could migrate its test from enzyme to react testing library.

2025-01-02 00:29 UTC, harshilsharma63 commented on webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
>                  className='edit-post-history__icon__button restore-icon'
Styles don't match.

2025-01-06 04:43 UTC, M-ZubairAhmed approved these changes

2025-01-06 05:22 UTC, merged