[MM-61619]: Added aria-live property for message sent status
mattermost/mattermost pull request #29720
Opened 2024-12-31 12:34 UTC by ayush-chauhan233

#### Summary

- Added aria-live property to the message status element.
- Programmatically triggering the `Message Sent` prompt.

#### Steps to reproduce  
- Navigate to the write to town square edit field and type 'tester'.
- Now navigate to the Send a message button and select it.
- Notice that after selecting the Send a message button, the screen reader not announcing any status message.

#### Expected Behavior 
- When the message is successfully sent a screen should announce the status of sent message.

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-61619

#### Screenshots

<table>
    <tr>
        <th>Before</th>
 <th>After</th>
    </tr>
    <tr>
        <td>
 <img src="https://github.com/user-attachments/assets/4122f9bc-c2cc-4a76-b3eb-b0044ef32d78">
</td>
  <td>
 <img src="https://github.com/user-attachments/assets/df3efa9b-1416-4175-afff-792dc6ffb4e9">
</td>
    </tr>
</table>

#### Release Note

```release-note
NONE
```

2024-12-31 12:34 UTC, mattermost-build commented
Hello @ayush-chauhan233,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2025-01-06 13:00 UTC, AayushChaudhary0001 approved these changes
This PR has been tested for the code changes and the screen reader reads the message sent by the user, LGTM. Approved.

2025-01-14 04:24 UTC, harshilsharma63 requested changes

2025-01-14 04:24 UTC, harshilsharma63 commented on webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
> +    const onSubmit = useCallback((submittingDraft?: PostDraft, schedulingInfo?: SchedulingInfo, options?: CreatePostOptions) => {
can you rename this to something like `handleSubmitWithErrorHandling`? Because we already have `handleSubmit` and `handleSubmitWrapper`, which is already a bit confusing, and now we have `onSubmit` as well, it will definitely create some confusion in the future.

2025-01-14 04:24 UTC, harshilsharma63 commented on webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Unintended change.

2025-01-14 04:26 UTC, harshilsharma63 commented
@ayush-chauhan233 can you please update this branch with `master` as this PR was merged yesterday - https://github.com/mattermost/mattermost/pull/29769 containing some advanced text editor changes.

2025-01-14 04:27 UTC, harshilsharma63 commented
/e2e-test

2025-01-16 19:48 UTC, devinbinnie requested changes
Just one quick change to make

2025-01-16 19:48 UTC, devinbinnie commented on webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
> +    const handleDraftChange = useCallback((draftToChange: PostDraft, options: { instant?: boolean; show?: boolean } = {instant: false, show: false}) => {
Nit: don't need the extra spacing here.

2025-01-20 04:41 UTC, harshilsharma63 approved these changes

2025-01-20 04:42 UTC, harshilsharma63 commented
Changes look good. Need to fix some lint error and merge conflict.

2025-01-20 21:34 UTC, marianunez commented
/e2e-test

2025-01-21 15:54 UTC, devinbinnie approved these changes

2025-01-21 15:55 UTC, merged