[MM-61656]: Updated the input grouping in notification setting tab
mattermost/mattermost pull request #29724
Opened 2024-12-31 12:50 UTC by ayush-chauhan233

#### Summary

- Wrapped the checkbox input with the fieldset tag.
- Added legend tag for assistive technology to announce the information for grouping.

#### Steps to reproduce  
- Navigate to the Keywords that trigger notifications edit button and select it.
- Now navigate to the Your non case-sensitive username "admin" checkbox.
- Notice that the components are not grouped together.

#### Expected Behavior 
- Related form control should be grouped together so that screen reader can announce it as a group.

#### Ticket Link

Jira https://mattermost.atlassian.net/browse/MM-61656

#### Screenshots

#### Release Note

```release-note
NONE
```

2024-12-31 12:50 UTC, mattermost-build commented
Hello @ayush-chauhan233,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2025-01-13 10:41 UTC, AayushChaudhary0001 approved these changes
This PR has been tested and the code changes makes the screen reader to read the related form control collectively as a group, LGTM. Approved.

2025-01-14 21:10 UTC, hmhealey approved these changes
Looks good to me!

2025-01-20 19:18 UTC, M-ZubairAhmed requested changes

2025-01-20 19:18 UTC, M-ZubairAhmed commented on webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
> +                    inputs={
Fix should probably not be here but in the SettingItemMax because i believe we could have more places where this would be needed

2025-01-21 13:01 UTC, ayush-chauhan233 commented on webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
> +                    inputs={
On investigating the usage of this component across the codebase, I found a similar approach to adding `fieldset` (like in `join_leave_section.tsx`, `performance_debugging_section.tsx` etc.). Moving this inside `SettingItemMax` would require many changes across multiple files and their test cases which will probably go beyond the scope of this issue ticket.

2025-01-24 17:22 UTC, hmhealey commented on webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
> +                    inputs={
Let's leave this as-is. Ideally, we should do this better, but I don't think we need to do that now

2025-01-27 09:48 UTC, ayush-chauhan233 commented
/update-branch

2025-01-28 07:14 UTC, M-ZubairAhmed approved these changes

2025-01-28 07:15 UTC, merged